### ISSUE TITLE
Support for private models? 

### ISSUE THREAD

**Issue by hbredin** [huggingface/huggingface_hub#10]
Looks like `hf_hub_url` and/or `cached_download` do not (yet ?) support authentication for private models.

What is the recommended way of downloading private models?

**Comment by julien-c** [comment]
You can use the `use_auth_token` in `cached_download()` and set it to True to use your local huggingface token (or you can also pass the string directly)

`hf_hub_url` is the same as it's just a url which is the same for private models.

**Comment by hbredin** [comment]
Thanks. Cross-reference from pyannote.audio repo and closing.
