### ISSUE TITLE
`metadata_update` fails when README.md has no text content (but it has metadata)

### ISSUE THREAD

**Issue by cakiki** [huggingface/huggingface_hub#1010]
### Describe the bug

`metadata_update` fails when there is no newline after the YAML header.

I had a README.md file with the following 3 lines:

```yaml
---
license: cc-by-sa-4.0
---
```

calling `metadata_update("cakiki/abc", {"tag": "test"}, repo_type="dataset", overwrite=True)` throws `TypeError: argument of type 'NoneType' is not iterable`.

I had to add a new line, i.e. content to the README for this to work.

### Logs

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_117739/230484724.py in <module>
----> 1 metadata_update("cakiki/abc", {"tag": "test"}, repo_type="dataset", overwrite=True)

/media/ssd/BIGSCIENCE/env/lib/python3.7/site-packages/huggingface_hub/repocard.py in metadata_update(repo_id, metadata, repo_type, overwrite, token, commit_message, commit_description, revision, create_pr)
    199             # update all fields except model index
    200             else:
--> 201                 if key in existing_metadata and not overwrite:
    202                     if existing_metadata[key] != metadata[key]:
    203                         raise ValueError(

TypeError: argument of type 'NoneType' is not iterable
```

### System Info

```shell
- `transformers` version: 4.21.1
- Platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.9.0.dev0
- PyTorch version (GPU?): 1.11.0+cu102 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
```

**Comment by osanseviero** [comment]
cc @Wauplin @lvwerra

**Comment by osanseviero** [comment]
I think this is an issue with the [regex](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/repocard.py#L24) we use to detect the metadata which expects a newline but I haven't looked into it

**Comment by Wauplin** [comment]
Yep indeed. Thanks for reporting this one as well.

**Comment by Wauplin** [comment]
Let's wait for this PR https://github.com/huggingface/huggingface_hub/pull/940 to be merged first. It refactors quite a bit how modelcards are handled.

**Comment by nateraw** [comment]
Thank you for reporting this!! I will fix this once we merge the aforementioned PR, which should be very soon.

**Comment by Wauplin** [comment]
Seems that @nateraw already fixed it without knowing :D 
I created a PR to add a regression test but that's it. Please let me know if I missed something.

**Comment by Wauplin** [comment]
Oops, closed it automatically with the PR. Please open it again if necessary @cakiki
