### ISSUE TITLE
Add a git tag to a repository

### ISSUE THREAD

**Issue by lhoestq** [huggingface/huggingface_hub#1014]
Is there a way in `huggingface_hub` to add a git tag at a specific revision without cloning the repo locally ?

This would be useful to allow users to specify a git tag when they do `push_to_hub` for a model or dataset, so that they can reload it later at that resivion.

**Comment by Wauplin** [comment]
Hi @lhoestq, it is currently not possible to tag a commit in `create_commit` using the HF API (therefore not in `push_to_hub` either).

@Pierrci @SBrandeis is this something the commit endpoint can do on the Hub ?
(also, is [this table](https://huggingface.co/docs/hub/api#endpoints-table) supposed to be exhaustive ? do we have an internal endpoints table ?)

**Comment by Pierrci** [comment]
> also, is [this table](https://huggingface.co/docs/hub/api#endpoints-table) supposed to be exhaustive ? do we have an internal endpoints table ?

I don't think it is - the internal endpoint table is https://github.com/huggingface/moon-landing/blob/main/server/server.ts 🙃

**Comment by julien-c** [comment]
if we do this, API-design-wise i don't know whether it should be an extra param to `create_commit`, or a dedicated `create_tag(commit="...")` method

**Comment by Wauplin** [comment]
A tag endpoint [has been added to the Hub](https://github.com/huggingface/moon-landing/pull/3846) (internal link) ! :tada: 

So we can now implement it in `huggingface_hub` as well. Preferred solution is to have a separate method for this (e.g. `create_tag(commit="...")`).

**Comment by coyotte508** [comment]
Also helpful for cases like this: https://huggingface.slack.com/archives/C034A8MG0JK/p1663775251718419 :)
