### ISSUE TITLE
Replace empty subfolder with None in hf_hub_download

### ISSUE THREAD

**Issue by thomwolf** [huggingface/huggingface_hub#1016]
Right now, calling `hf_hub_download` with an empty string as `subfolder` will fail because it add a double backslash to the url. If would be good to replace an empty subfolder with `None` by default.

I'm using huggingface-hub 0.8.1

**Comment by Wauplin** [comment]
Thanks for reporting @thomwolf. I fixed it in https://github.com/huggingface/huggingface_hub/pull/1021.
