### ISSUE TITLE
Activity view shows likes for private datasets

### ISSUE THREAD

**Issue by cakiki** [huggingface/huggingface_hub#1017]
### Describe the bug

I made a dataset private and the amount of likes it had when it was public was still visible in the "Activity" view on my homepage, even though that information disappears on the dataset page itself.

This isn't really a bug, but rather a UI mismatch between the two views.

![image](https://user-images.githubusercontent.com/3664563/186918805-b211ef0c-390e-4031-a873-c4fd43d3b83a.png)

### System Info

```shell
hf.co
```

**Comment by Wauplin** [comment]
Hi @cakiki thanks for reporting. I created an issue to track it on our internal repo that handles the front-end. I'm closing this one.

(ref: https://github.com/huggingface/moon-landing/issues/3727).

**Comment by osanseviero** [comment]
For next times we have a public repo where we welcome all feedback about the website, https://github.com/huggingface/hub-docs. @cakiki feel free to open issues there and @Wauplin feel free to transfer the issues from this repo to `hub-docs`

**Comment by cakiki** [comment]
Ah, good to know! Thank you :smile_cat:

**Comment by Wauplin** [comment]
Didn't know about that, thanks for the clarification @osanseviero !
