### ISSUE TITLE
Connection Error under Proxy

### ISSUE THREAD

**Issue by MrZhengXin** [huggingface/huggingface_hub#1020]
https://github.com/huggingface/huggingface_hub/blob/48ddc62cbed37d2101b8dce2a34951c404629cd5/src/huggingface_hub/file_download.py#L464

This line of code only consider ConnectTimeout, and fails to address the connection timeout when proxy is used. Also, variable "max_retries" is set to 0 by default and huggingface transformers have not yet properly set this parameter yet.

> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
>     self._prepare_proxy(conn)
>   File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 996, in _prepare_proxy
>     conn.connect()
>   File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 424, in connect
>     tls_in_tls=tls_in_tls,
>   File "/usr/local/lib/python3.7/dist-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
>     sock, context, tls_in_tls, server_hostname=server_hostname
>   File "/usr/local/lib/python3.7/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
>     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
>   File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
>     session=session
>   File "/usr/lib/python3.7/ssl.py", line 853, in _create
>     self.do_handshake()
>   File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
>     self._sslobj.do_handshake()
> socket.timeout: _ssl.c:1039: The handshake operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 499, in send
>     timeout=timeout,
>   File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 788, in urlopen
>     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
>   File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 592, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /google/t5-v1_1-large/resolve/main/tokenizer_config.json (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/tiger/.local/lib/python3.7/site-packages/transformers-4.22.0.dev0-py3.7.egg/transformers/models/auto/tokenization_auto.py", line 541, in from_pretrained
>     tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
>   File "/home/tiger/.local/lib/python3.7/site-packages/transformers-4.22.0.dev0-py3.7.egg/transformers/models/auto/tokenization_auto.py", line 405, in get_tokenizer_config
>     _commit_hash=commit_hash,
>   File "/home/tiger/.local/lib/python3.7/site-packages/transformers-4.22.0.dev0-py3.7.egg/transformers/utils/hub.py", line 391, in cached_file
>     local_files_only=local_files_only,
>   File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/file_download.py", line 1096, in hf_hub_download
>     timeout=etag_timeout,
>   File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/file_download.py", line 429, in _request_wrapper
>     **params,
>   File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/file_download.py", line 461, in _request_wrapper
>     method=method.upper(), url=url, timeout=timeout, verify=False, **params
>   File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 59, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 587, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 701, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 559, in send
>     raise ProxyError(e, request=request)
> requests.exceptions.ProxyError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /google/t5-v1_1-large/resolve/main/tokenizer_config.json (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))

**Comment by Wauplin** [comment]
> This line of code only consider ConnectTimeout, and fails to address the connection timeout when proxy is used.

Haven't reproduced the error but seems legit indeed. Would you like to create a PR to address it ?

> Also, variable "max_retries" is set to 0 by default and huggingface transformers have not yet properly set this parameter yet.

`max_retries` is set to 0 because `huggingface_hub` is meant to be a generic library that is used in other libraries. Therefore we  prefer to disable by default the "backoff" feature and let subsequent libraries enable it if they find it useful. I would advice to create an issue on https://github.com/huggingface/transformers instead.

**Comment by MrZhengXin** [comment]
Hi~@Waupulin, thanks for your advice, and I have just created a simple PR.

**Comment by Wauplin** [comment]
Thank you, will review it :)

**Comment by Wauplin** [comment]
Closed.
