### ISSUE TITLE
Add template kwargs for dataset card

### ISSUE THREAD

**Issue by nateraw** [huggingface/huggingface_hub#1030]
**Is your feature request related to a problem? Please describe.**

Currently the [dataset card template](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/templates/datasetcard_template.md) is missing a lot of template kwargs that might be useful. 

**Describe the solution you'd like**

We should add them basically wherever there is a "[More Information Needed]". If not provided, we default to "[More Information Needed]".

**Describe alternatives you've considered**
...

**Additional context**
The model card template has a bunch of template kwargs you can use, so we want to mirror that functionality for dataset cards.

**Comment by Wauplin** [comment]
Fixed by @nateraw in https://github.com/huggingface/huggingface_hub/pull/1068.
