### ISSUE TITLE
`notebook_login` showing unavoidable warning on Google Colab

### ISSUE THREAD

**Issue by apolinario** [huggingface/huggingface_hub#1043]
### Describe the bug

When a user logs in using 
```
from huggingface_hub import notebook_login
notebook_login()
``` 
in a Google Colab, even when everything goes right, the user sees this warning which they have no control over
![image](https://user-images.githubusercontent.com/788417/189395295-70470fa1-82f3-4c26-81e0-bd204277a082.png)

I think that this could be suppressed on Colab

### System Info

```shell
Google Colab on `huggingface_hub == 0.9.1`
```

**Comment by Wauplin** [comment]
Yep good catch. I find it annoying even on local machine :grin:

**Comment by apolinario** [comment]
I also find it a bit annoying locally - but I thought maybe it was indeed some setting up I could do on my machine to fix - but on colab I thought the user has no control over it

**Comment by osanseviero** [comment]
Note that the warning goes away after doing

```python
notebook_login()
!git config --global credential.helper store
```

if you want it to go away, as per the error message, but I agree it's annoying in Colab so maybe suppressing it would be good

**Comment by LysandreJik** [comment]
If the user doesn't do it, then it's possible that they'll face issues when cloning with `git`.

It's unlikely as the use-cases are rare, so it's fine for me if we remove it, but the warning isn't here just to be here :smiley:.

**Comment by julien-c** [comment]
personally i would advocate removing all the credential-storage related things as it was never really an elegant solution

**Comment by Wauplin** [comment]
So 2 things here:

1. Showing the warning in a google colab is not super useful as I assume 99% of the users don't care about the git credential store (please correct me if I'm wrong). What I suggest is to update `huggingface_hub` to [check if we are in a google colab](https://stackoverflow.com/a/53586419) and if yes, run `git config --global credential.helper store` in the background and disable the warning. It would be a very specific fix but I feel google colab is used a lot to promote our work.

2. As @julien-c mentioned, we could do better than using the git credential store. Let's create a separate issue to address it: https://github.com/huggingface/huggingface_hub/issues/1051

If that's fine with everyone, I'll address 1. before next release. Point 2. has slightly less priority in my opinion.

**Comment by Wauplin** [comment]
@apolinario closing this issue (addressed by https://github.com/huggingface/huggingface_hub/pull/1053)
