### ISSUE TITLE
Automatically create HF PRs

### ISSUE THREAD

**Issue by lbourdois** [huggingface/huggingface_hub#1044]
Hi!

I was having a discussion with @mishig25  where I asked him if it was possible to add a "Community" button in the organization cards?
I was using the example of the organisation https://huggingface.co/masakhane to show the interest of the point.
They have 133 models in French but they are not currently tagged. Adding them would increase the number of French models available by 15%. I don't necessarily want to open 133 PRs manually (345 if we want to tag all the models in the organization). The purpose of placing the "Community" button would be to open a discussion to ask authors to do so. 

Mishig told me that it would take time if the Hugging Face team did it.
Instead I could be able to open several PRs programatically using the python huggingface_hub client but that I had to ask for more precision by opening this issue and advised me to tag @Wauplin.

So here I am, and my question is: is there a place that describes how to make HF PRs automatically?

I could not find information in the documentation because the PR & Discussions part is not yet available: [https://huggingface.co/docs/huggingface_hub/how-to-discussions-and-pull-requests](https://t.co/WLgrJGOcD9)

Thank you in advance :)

**Comment by osanseviero** [comment]
Hi there! You can pip install from GitHub directly to get some nice utilities we have for dataset cards that are not in the latest release yet. You can check out the docs at https://huggingface.co/docs/huggingface_hub/main/en/how-to-model-cards. The card objects have a `create_pr` param you can use to open PRs

```python
card.push_to_hub(repo_id, create_pr=True)
```

**Comment by lbourdois** [comment]
Thank you very much, it works! 🚀

I hope for the authors that we can merge several pull requests at once because 345 to validate will be a long time 👀

I just want to mention that I get an error `PermissionError: [Errno 13] Permission denied` for the models "masakhane/afrimbart_bam_fr_news" and "masakhane/afrimt5_fr_bam_news" when I tried to load the card with the `ModelCard.load` function and therefore had to do a manual PR for these two models.
I don't know if it's a bug or not.

I am closing this PR.

**Comment by Wauplin** [comment]
@osanseviero thanks for answering so quickly :)

@lbourdois FYI, it is indeed possible to merge PRs programmatically. If you are in touch with the authors don't hesitate to tell them. There are a [get_repo_discussions](https://huggingface.co/docs/huggingface_hub/v0.9.1/en/package_reference/hf_api#huggingface_hub.HfApi.get_repo_discussions) and a [merge_pull_request](https://huggingface.co/docs/huggingface_hub/v0.9.1/en/package_reference/hf_api#huggingface_hub.HfApi.merge_pull_request) method.

```py
# get discussions
discussions  = get_repo_discussions(repo_id)

# select the PR
for discussion in discussions:
    discussion.title # "Upload README.md with huggingface_hub"
    discussion.status # merge, draft, open, closed
    discussion.num # the id you need to merge
    ...

merge_pull_request(repo_id, discussion_num) # <- merge it 
```

**Comment by julien-c** [comment]
(if Masakhane team members want some help in merging 345 different PRs we can also help them to do it programmatically, or do it ourselves – just ping us!)
