### ISSUE TITLE
Allow to retrieve discussions/PRs using list_models

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#1071]
It would be nice to have a `discussions=True` parameter in `list_models` and other listing methods, to also add the discussions related information in the response. At the moment, one needs to do `list_models` + `get_repo_discussions` for each, but that involves quite a bit of work.

@julien-c argument on keeping as they are was

> config and cardData are properties of the model in the data backend, whereas discussions are another object completely

From my side, I don't think that's a distinction that users should know/internalize, and I would find making `list_models` more powerful a better approach from a user perspective

(internal [discussion](https://huggingface.slack.com/archives/C02V5EA0A95/p1663596596913389))

WDYT @julien-c @Pierrci @Wauplin

**Comment by julien-c** [comment]
an API always reflect a bit the underlying data model, IMO

I'd be in favor of keeping the server API unchanged, but coding a helper in `huggingface_hub` could be an option (I thought you were suggesting changing the server API)

**Comment by Wauplin** [comment]
Coding the helper in `huggingface_hub` directly is a bit clunky in my opinion. If the helper is just a for loop to get the discussions repo after repo, we end up with potentially thousands of calls to the API and a very long execution time 

```py
models = list_models()
for model in models:
    model.discussions = list(get_repo_discussions(model.id))
```
Even if we parallelize the calls, it still seems very unefficient.

**Comment by Wauplin** [comment]
Something we can do is to add a `discussions: bool=True` parameter to `model_info(...)` when we get information from a single model but I don't think that is what you want @osanseviero, right ?

**Comment by julien-c** [comment]
> Even if we parallelize the calls, it still seems very unefficient.

if it's inefficient in `huggingface_hub` it will similarly be inefficient on the backend =)

**Comment by Wauplin** [comment]
> if it's inefficient in huggingface_hub it will similarly be inefficient on the backend =)

Yep, so having a helper in `huggingface_hub` is not really helpful in the end.

@osanseviero are you interested in having all the discussions for all the repos or a proxy like "number of discussions per repo" could be enough ? (and not even sure the backend can do that more efficiently than retrieving all the discussions)

**Comment by osanseviero** [comment]
> Something we can do is to add a discussions: bool=True parameter to model_info(...) when we get information from a single model but I don't think that is what you want @osanseviero, right ?

No, my idea would be to programmatically get all the discussions from an organization of hundreds of repos, or even from all the Hub (but my use case is exploratory analysis, so maybe too specific/power-feature)

> @osanseviero are you interested in having all the discussions for all the repos or a proxy like "number of discussions per repo" could be enough ? (and not even sure the backend can do that more efficiently than retrieving all the discussions)

Ideally all, as what I'm interested in is in knowing # of open/closed discussions/PRs across repos.

I've been thinking more on this and maybe it's too much of a power feature at the moment, so I would feel ok to freeze this for now.

**Comment by Wauplin** [comment]
Idk if that's possible, but is an internal DB access to do analytics already exists/is planned ? IMO that would be more the way to go for exploratory analysis both to avoid unnecessary features in the Hub API/`huggingface_hub` and to avoid overloading the prod database with thousands of requests at once. (cc @Pierrci @julien-c)

**Comment by Wauplin** [comment]
I'm closing this issue as "won't fix". As discussed in this issue, implementing this would be very inefficient ("n+1 calls") no matter if we implement it server-side or as an helper in `huggingface_hub`.  It also feels like a quite niche feature request
