### ISSUE TITLE
after install huggingface_hub with pip, the huggingface_cli command not found

### ISSUE THREAD

**Issue by xiongma** [huggingface/huggingface_hub#1079]
### Describe the bug

after install huggingface_hub with pip, the huggingface_cli command not found

### System Info

```shell
os: MAC OS 11.6.8
```

**Comment by xiongma** [comment]
![image](https://user-images.githubusercontent.com/30991932/192191155-f42a901b-6e22-4322-948e-90e5f47b14a3.png)

**Comment by xiongma** [comment]
![image](https://user-images.githubusercontent.com/30991932/192191262-e2c7b46c-6bea-47ad-87f5-1098283523c6.png)

**Comment by julien-c** [comment]
can you paste the output of `which pip` and `which python`?

**Comment by xiongma** [comment]
![image](https://user-images.githubusercontent.com/30991932/192248107-ca161bab-acbe-4c54-bdcb-24b1de7bd165.png)
@julien-c

**Comment by xiongma** [comment]
![image](https://user-images.githubusercontent.com/30991932/192413192-5b27d05f-4d90-4fdb-abee-bbff0a488fa9.png)
@Wauplin

**Comment by Wauplin** [comment]
@xiongma hmm, it seems that `huggingface_hub` is correctly installed so the problem might be with your `$PATH` variable.
Could you try the solution proposed here: https://stackoverflow.com/a/62151306 ?

e.g. updating your `$PATH` like this:
```sh
# Taken from https://stackoverflow.com/a/62151306
echo "export PATH=\"`python3 -m site --user-base`/bin:\$PATH\"" >> ~/.bashrc
source ~/.bashrc
```
(depending on your setup, you might want to update your `.bashrc` or `.zshrc` or any config file you use)

**Comment by xiongma** [comment]
thanks, it works

**Comment by Lucasnovitch** [comment]
Hi, 
I tried your solution and now everything got destroyed... I had the same problem as @xiongma but now even the 'pip' command isn't working...

I am not very good with command box is it possible to help me ?
 
![image](https://user-images.githubusercontent.com/122399657/212409942-2c3f5171-1b60-41a2-940f-5255d895ff4f.png)

**Comment by liudonghua123** [comment]
I installed the latest huggingface_hub package, the cli tool `huggingface_cli` seems changed to `hf`. And the command options like `--resume-download`, `--local-dir-use-symlinks` have changed or removed. But from the doc https://huggingface.co/docs/huggingface_hub/en/guides/cli, I couldn't find any clues.

```
# pip uninstall huggingface_hub
Found existing installation: huggingface_hub 1.1.4
Uninstalling huggingface_hub-1.1.4:
  Would remove:
    /usr/local/bin/hf
    /usr/local/bin/tiny-agents
    /usr/local/lib/python3.12/dist-packages/huggingface_hub-1.1.4.dist-info/*
    /usr/local/lib/python3.12/dist-packages/huggingface_hub/*
Proceed (Y/n)? n
# hf download --help
Usage: hf download [OPTIONS] REPO_ID [FILENAMES]...

  Download files from the Hub.

Arguments:
  REPO_ID         The ID of the repo (e.g. `username/repo-name`).  \[required]
  [FILENAMES]...  Files to download (e.g. `config.json`,
                  `data/metadata.jsonl`).

Options:
  --repo-type [model|dataset|space]
                                  The type of repository (model, dataset, or
                                  space).  \[default: model]
  --revision TEXT                 Git revision id which can be a branch name,
                                  a tag, or a commit hash.
  --include TEXT                  Glob patterns to include from files to
                                  download. eg: *.json
  --exclude TEXT                  Glob patterns to exclude from files to
                                  download.
  --cache-dir TEXT                Directory where to save files.
  --local-dir TEXT                If set, the downloaded file will be placed
                                  under this directory. Check out https://hugg
                                  ingface.co/docs/huggingface_hub/guides/downl
                                  oad#download-files-to-local-folder for more
                                  details.
  --force-download / --no-force-download
                                  If True, the files will be downloaded even
                                  if they are already cached.  \[default: no-
                                  force-download]
  --dry-run / --no-dry-run        If True, perform a dry run without actually
                                  downloading the file.  \[default: no-dry-
                                  run]
  --token TEXT                    A User Access Token generated from
                                  https://huggingface.co/settings/tokens.
  --quiet / --no-quiet            If True, progress bars are disabled and only
                                  the path to the download files is printed.
                                  \[default: no-quiet]
  --max-workers INTEGER           Maximum number of workers to use for
                                  downloading files. Default is 8.  \[default:
                                  8]
  --help
```

**Comment by Wauplin** [comment]
Yes indeed @liudonghua123. This is the case since the v1.0 release (see [announcement](https://github.com/huggingface/huggingface_hub/releases/tag/v1.0.0)). We did introduce some breaking changes to the API. You can check https://huggingface.co/docs/huggingface_hub/package_reference/cli as reference for the new format.
