### ISSUE TITLE
Add `endpoint` param to `hf_hub_url`

### ISSUE THREAD

**Issue by mariosasko** [huggingface/huggingface_hub#1082]
As discussed in https://github.com/huggingface/hffs/pull/1, it would be nice to add the `endpoint` param to `hf_hub_url` to support passing custom endpoints (useful for private Hub users)

**Comment by osanseviero** [comment]
One can set the `HF_ENDPOINT` environment variable to change the endpoint, which was added with private Hub use cases in mind

https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/constants.py#L42

**Comment by Wauplin** [comment]
Thanks @mariosasko for opening the ticket and thanks @osanseviero for providing a solution :)
Environment variable is a good way to solve that but let's keep this issue open. Wouldn't hurt to have 2 ways of settings the endpoint.

**Comment by julien-c** [comment]
in `hffs` context, what's the use case for setting an `endpoint`?

**Comment by mariosasko** [comment]
@julien-c For easier testing (see https://github.com/huggingface/hffs/pull/1#discussion_r933283730)

I can remove the `endpoint` param for now and use the env variable instead, but then we need to use patching, which makes the tests more complex (I assume `HfApi` has this param for the same reason).

**Comment by severo** [comment]
fyi, we have code in datasets-server that depend on this

https://github.com/huggingface/datasets-server/pull/1296/files#diff-706957870370898392d2283826314dc06e70e585c298f3d63154669dfc23cbc3R417
