### ISSUE TITLE
Add a `token` attribute to `HfApi`

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1104]
Mentioned multiple times, last time in https://github.com/huggingface/huggingface_hub/issues/1094#issuecomment-1263349065.

The idea is to be able to set a `token` in the constructor of `HfApi` client object. This would avoid to pass the token to each method 1 by 1.  This proposition is different than using `notebook_login` or `huggingface-cli login` as the token should not be persisted on disk.

**Comment by LysandreJik** [comment]
I think we discussed this somewhere with @adrinjalali in the past but I can't find the thread. I like the idea!

**Comment by osanseviero** [comment]
I think it was brought up in https://github.com/huggingface/huggingface_hub/issues/1094#issuecomment-1263349065

**Comment by LysandreJik** [comment]
Ah indeed! There must be another thread from ~6 months ago with a discussion about it as well :)

**Comment by adrinjalali** [comment]
I think @LysandreJik is referring to this one: https://github.com/huggingface/huggingface_hub/issues/796, which is almost a duplicate issue.
