### ISSUE TITLE
Overridable download progress display

### ISSUE THREAD

**Issue by nerochiaro** [huggingface/huggingface_hub#1110]
**Is your feature request related to a problem? Please describe.**
I am writing an application using huggingface libraries and would like to display the progress of downloads in the UI.
At the moment `huggingface_hub.snapshot_download` displays progress using `tqdm.auto` (wrapped by `huggingface_hub.utils.tqdm`) and there is no way to override this.

**Describe the solution you'd like**
Ideally, I would be able to somehow be allowed to specify an optional callback function that would get called for each download whenever new data is received. 
The function would be passed the file name, the total size and the size of the data downloaded so far.

**Describe alternatives you've considered**
An alternative would be to be able to pass to `snapshot_download` a class that is derived from `tqdm` (or that mimics the `tqdm` API) to use. This way `snapshot_download` does not need to be internally changed much, it just needs to instantiate from the passed class (if any) instead of using `tqdm`

**Comment by Wauplin** [comment]
Hi @nerochiaro , sorry for the (very) late reply. I just opened a PR that should solve your issue. The idea is to pass a custom class inherited from `tqdm` (or that mimics the interface). This custom class is then used in `thread_map` to track the progress of the download.

Note that the custom `tqdm_class` is not passed to each individual `hf_hub_download`. 

What do you think about it @nerochiaro ?

**Comment by nerochiaro** [comment]
Looks good, seems like it would work for my purpose, thought I haven't been
able to try it yet.
Also I think the multi thread download is going to be really helpful.
I will try it out as soon as possible, but in the meantime I added a
suggestion for a small quality of life improvement to the PR.
