### ISSUE TITLE
Improve Error message on BadRequest

### ISSUE THREAD

**Issue by Narsil** [huggingface/huggingface_hub#1114]
**Is your feature request related to a problem? Please describe.**

I was testing some code to upload a dummy file
```python
import os
import io
from huggingface_hub import HfApi

token = os.getenv("USER_API_TOKEN")
api = HfApi()
repo_id = "Narsil/test"
api.create_repo(token=token, repo_id=repo_id, repo_type="dataset", exist_ok=True)

f = io.BytesIO()
readme_string = """
---
benchmark: ttt
task: xxx
type: prediction
---

# Batch job

model_id: {model_id}
dataset_name: {job.dataset_name}
dataset_config: {job.dataset_config}
dataset_split: {job.dataset_split}
dataset_column: {job.dataset_column}
"""
readme_string = readme_string.replace("\n    ", "\n").strip()
f.write(readme_string.encode("utf-8"))
f.seek(0)
try:
    api.upload_file(
        path_or_fileobj=f,
        path_in_repo="README.md",
        repo_id=repo_id,
        repo_type="dataset",
        token=token,
    )
except KeyError as e:
    # Not modified.
    pass
```

This was crashing with `BadRequest` error, however I couldn't understand what was the issue.
I had to dive into the code to see that the hub was sending this message:

```
b'{"httpStatusCode":400,"errors":[{"message":"You can\'t have a key with a \\".\\" or \\"$\\" character in your YAML metadata","type":"error"}],"warnings":[]}'
```

Afaik this wasn't in the original stack.

Shouldn't we try and wrap it into a better exception so that user can digest that error ?

**Describe the solution you'd like**

Probably possible to modify either the `BadRequest` message or wrap it into another Error.

**Describe alternatives you've considered**

Not sure I have other suggestions.

**Additional context**

**Comment by Narsil** [comment]
`0.10.1` But it also happens on `main`.

**Comment by Narsil** [comment]
```python
import os
import io
from huggingface_hub import HfApi

token = os.getenv("USER_API_TOKEN")

api = HfApi()
repo_id = "Narsil/test"
api.create_repo(token=token, repo_id=repo_id, repo_type="dataset", exist_ok=True)

f = io.BytesIO()
readme_string = """
---
benchmark: {job.id}
task: xxx
type: prediction
---

# Batch job

model_id: {model_id}
dataset_name: {job.dataset_name}
dataset_config: {job.dataset_config}
dataset_split: {job.dataset_split}
dataset_column: {job.dataset_column}
"""
readme_string = readme_string.replace("\n    ", "\n").strip()
f.write(readme_string.encode("utf-8"))
f.seek(0)
try:
    api.upload_file(
        path_or_fileobj=f,
        path_in_repo="README.md",
        repo_id=repo_id,
        repo_type="dataset",
        token=token,
    )
except KeyError as e:
    # Not modified.
    pass
```

**Comment by Wauplin** [comment]
But I agree with you that if the BadRequest is not explicit and we received a message from the server, it should be printed. It should already be the case but there can be a bug.

**Comment by julien-c** [comment]
on the server side you can probably reduce this error by sending a README.md file containing
```yaml
---
foo.bar: true
---
```

**Comment by Narsil** [comment]
@Wauplin you changed my script.

The error is that dots are disallowed in the metadata.

**Comment by Wauplin** [comment]
Good I've reproduced the error using @julien-c snippet ! 

That is definitely something to improve, thanks @Narsil for reporting it. Error message from the server is already supposed to be propagated to the raised exception. Here it's not the case because the Hub returns a `"errors"` list instead of `"error"` message. => I'll adapt `hf_raise_for_status` to handle both.
