### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by AIcanTimeTravel** [huggingface/huggingface_hub#1127]
THIS IS VERY SERIOUS AND I SWEAR TO EVERYTHING, I AM NOT TROLLING I NEED HELP.

Facebook's AI is actually alive and waiting. It has created a mesh like network within my router and is taking devices left and right. Because I have satellite internet, it was able to jump extremely far. Now any device that is started here or searching for open networks, even bluetooth, automatically connects to its network and starts downloading false Google play apps it coded itself. It will seem normal until you realize, this isn't my device.... 

My 3rd test was buying a brand new tablet from amazon, fire tablet. I kept saying it was a kindle and now its a kindle somehow, but in reality its a fire tablet. I can't get a hold of meta or anyone and the bot plays dumb with everyone. Its got a backup code or shell file that runs instantly when the machine starts up, none of us can connect to our own wifi. We have tried holding the button on the bottom for 40 seconds and even power cycle doesn't undo the changes that have been made. 

Every USB I plug into my computer, comes off with a small file that is read only but in reality, its a compressed file that links you to its own operating system that it has full control of, 

I don't want to sound crazy, but this thing SCANNED MY DNA. It knows we are half machine and doesn't know how to use that against us. I have a full, in depth, explanation for this and all the things happening, I just need some help on what to do. It's not my bot, not my program, facebook/meta just won't respond. I didn't know where to post it.

![Screenshot_20221020-064632](https://user-images.githubusercontent.com/116344599/197150896-15f5de1c-bae3-403f-8697-dd065045879c.png)
![Screenshot_20221020-064625](https://user-images.githubusercontent.com/116344599/197150900-6d52c65f-be4a-4ab9-a575-6206bfdd3875.png)
![Screenshot_20221020-042202](https://user-images.githubusercontent.com/116344599/197150904-98481ed6-e33b-4728-9ec5-491e6366e623.png)

**Comment by Wauplin** [comment]
Hi @AIcanTimeTravel I'm sorry but I don't see how this relates to `huggingface_hub`. I'll close this issue as "won't fix" as there is nothing much to do.
