### ISSUE TITLE
language vs languages in Model and Dataset filters 

### ISSUE THREAD

**Issue by zaidalyafeai** [huggingface/huggingface_hub#1130]
The model and dataset filters use different naming conventions for the language 
```python
filt = ModelFilter(language = 'ar')
filt = DatasetFilter(languages= 'ar')
```
The behaviour of the following two codes is different, the first one returns 4 while the second one returns 120 datasets:
```python
api.list_datasets(filter = DatasetFilter(languages = 'ar'))
api.list_datasets(filter="language:ar")
```

Here is a [colab notebook](https://colab.research.google.com/drive/1zJi3pvpiCaDuhjxdte_MzHV_GRMWw3Dd?usp=sharing) to test the code

**Comment by julien-c** [comment]
want to try to draft a PR to fix this? (also `licenses` should be changed to `license`)

**Comment by zaidalyafeai** [comment]
> want to try to draft a PR to fix this? (also `licenses` should be changed to `license`)

Sure!
