### ISSUE TITLE
HfApi method to fetch "liked" models by current user

### ISSUE THREAD

**Issue by creatorrr** [huggingface/huggingface_hub#1137]
**Is your feature request related to a problem? Please describe.**

The huggingface dashboard seems to only list the last 20 "liked" models and datasets for my account. I use the "like" button extensively for bookmarking models but recently realized I can only view a limited number. Adding an api method would also help for analysing a user's interests. 

**Describe the solution you'd like**

Something like this perhaps?

```python
HfApi.get_liked(
  username: Optional[str] = None,
  auth_token: Optional[str] = None,
  entity_type: "all" | "model" | "space" | "dataset" = "all", 
  max_items: int = 100
) -> List[ModelInfo|SpaceInfo|DatasetInfo]
```

**Comment by Wauplin** [comment]
Hi @creatorrr , thanks for creating an issue for this. It is currently not possible to do that from `huggingface_hub` as you spotted. @osanseviero just created an internal server-side issue.

As for the API design if/when we integrate this to the Hub, I'd be in favor of extending the [`list_models`](https://huggingface.co/docs/huggingface_hub/v0.10.1/en/package_reference/hf_api#huggingface_hub.HfApi.list_models), [`list_datasets`](https://huggingface.co/docs/huggingface_hub/v0.10.1/en/package_reference/hf_api#huggingface_hub.HfApi.list_datasets) and [`list_spaces`](https://huggingface.co/docs/huggingface_hub/v0.10.1/en/package_reference/hf_api#huggingface_hub.HfApi.list_spaces) methods. We can add a ~`is_liked` boolean argument (defaults to `False`)  that does the filtering.

**Comment by julien-c** [comment]
@creatorrr that's a good feature (and good to know you're using likes extensively), we'll prioritiez

**Comment by creatorrr** [comment]
@Wauplin makes sense. If an API endpoint does become available, please let me know @osanseviero ! I would be happy to use that in the meantime.

**Comment by creatorrr** [comment]
Any update on an API endpoint, @osanseviero ? Hate to bother again, would be great if there was a public trello or something. :grimacing:

**Comment by julien-c** [comment]
yes our backlog is LIFO =)

more seriously: coming soon!

**Comment by Wauplin** [comment]
Looks like it was a good idea to post a reminder @camenduru ! :stuck_out_tongue: :rocket: => https://github.com/huggingface/huggingface_hub/pull/1254

**Comment by creatorrr** [comment]
Thank you guys! Really appreciate this :)

**Comment by Wauplin** [comment]
@creatorrr @camenduru It's merged ! Feel free to use it from `main` branch :)

```py
# !pip install git+https://github.com/huggingface/huggingface_hub.git@main

from huggingface_hub import HfApi

api = HfApi()
api.like("bigcode/the-stack", repo_type="dataset")

likes = api.list_liked_repos()
likes.datasets
# ['bigcode/the-stack', ...]
```

**Comment by camenduru** [comment]
thanks @Wauplin ❤
