### ISSUE TITLE
Permission on local cached files should be configurable

### ISSUE THREAD

**Issue by antoche** [huggingface/huggingface_hub#1141]
**Is your feature request related to a problem? Please describe.**
If multiple users attempt to share the same models cache (e.g., on a company internal shared file system), anytime model files are downloaded, their permissions are 0600 (on linux) regardless of the umask. This is because file_download is using `tempfile.NamedTemporaryFile` (see https://github.com/huggingface/huggingface_hub/blob/60077db55b81f2add3fd3bf774d7dc0f7acc4857/src/huggingface_hub/file_download.py#L727 and https://stackoverflow.com/questions/10541760/can-i-set-the-umask-for-tempfile-namedtemporaryfile-in-python), so only the user who downloaded them can read those files. As a result, users can't share a local cache, which is a waste of resources and time for users.

**Describe the solution you'd like**
huggingface_hub should `chmod` the downloaded files (for example, using the current `os.umask`, or using a new configuration option) after the file is downloaded and before it is renamed so it can be shared across users.

**Describe alternatives you've considered**
Separate caches per user is a workaround but is a massive waste of disk space and time. Each user would have to wait for new downloads even if the files have been downloaded by another user already.

**Additional context**
Trying to use the HuggingFace diffusers/transformers library in an enterprise context.

**Comment by Wauplin** [comment]
Hi @antoche , thanks for opening this issue. This seems a very legit use case to me. So what we could do is to `chmod` the temporary file just before moving it to the cache [here](https://github.com/huggingface/huggingface_hub/blob/60077db55b81f2add3fd3bf774d7dc0f7acc4857/src/huggingface_hub/file_download.py#L745) and [here](https://github.com/huggingface/huggingface_hub/blob/60077db55b81f2add3fd3bf774d7dc0f7acc4857/src/huggingface_hub/file_download.py#L1244). 
I would set the file permissions to match the same as the cache directory itself. Something like: (not tested)

```py
import os
import stat

cache_dir_mode = os.stat(cache_dir).st_mode
# https://docs.python.org/3/library/stat.html#stat.S_IMODE
os.chmod(temp_file.name, stat.S_IMODE(cache_dir_mode))
```

Would you like to try that and open a PR for it ?

**Comment by antoche** [comment]
That sounds like a sensible solution. I'd love to contribute but I have quite a few hurdles in my way due to corporate security&legal limitations. I already have another change in the wings related to proxy/certificate settings that I'm trying get over the fence to you, I'm not sure when I'll get that done. I'll add this one on my plate, but if anyone else has some time to address it, feel free to go ahead.

**Comment by Wauplin** [comment]
Ok thanks for letting us know @antoche. Not sure yet how we will prioritize this so when and if you have time, feel free to go ahead. If I start to work on it, I'll assigned the issue to myself to let you know.

**Comment by stas00** [comment]
@Wauplin, sent me here from a similar Issue I have just filed https://github.com/huggingface/huggingface_hub/issues/1215

In group environment usually users must set `umask` to support shared files. So you could refer to that setting to know which perms to set.

In my issue I also linked to https://github.com/huggingface/datasets/pull/2157 where `datasets` deals with a similar issue if it helps.

**Comment by antoche** [comment]
Hi, just confirming that we've switched to v0.11.1 and this works just as expected and is fixing a lot of headaches for me, thanks a lot!

**Comment by sgavela** [comment]
Hi! Any updates on this issue? Is there an easy way such a configuration option for sharing the cache across users without doing chmod each time a user loads a new dataset or just having separate caches? Thank you!

**Comment by Wauplin** [comment]
> Hi! Any updates on this issue? Is there an easy way such a configuration option for sharing the cache across users without doing chmod each time a user loads a new dataset or just having separate caches? Thank you!

As far as I remember, we considered this issue as completed by https://github.com/huggingface/huggingface_hub/pull/1220. What we now do is to set the user permission of the cached files to the same permission of the cache folder itself. Do you currently have issues with it? If yes, I would prefer to open a new issue describing your problem (and why it is not solved by this one).
