### ISSUE TITLE
Make it easier to modify the model card content

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#1144]
Modifying `card.text` does not modify `card.content`, which is what is pushed to the Hub.

```
card = ModelCard.load('akdeniz27/roberta-large-cuad')
card.text = """
This is the new model card
"""
card.content = str(card)
```

It would work, but it has the last unintuitive step of modifying `content. Ideally, when `text` is modified, the `content` should also be modified.

cc @nateraw

**Comment by osanseviero** [comment]
@nateraw should I assign this issue to you?

**Comment by Wauplin** [comment]
[Related thread](https://huggingface.slack.com/archives/C025H22A3ND/p1667260413472069) (internal slack discussion).

A good way mentioned to solve this is to use a `@property` for the `content` field.

**Comment by merveenoyan** [comment]
in skops, we had an intermediate object to handle this and we rendered during saving separately. (but @BenjaminBossan is refactoring again 😂)
