### ISSUE TITLE
At least some boolean arguments in query functions are not working correctly

### ISSUE THREAD

**Issue by buhrmann** [huggingface/huggingface_hub#1146]
### Describe the bug

Functions like `list_models` have boolean arguments supposedly determining whether or not to include certain data in the results, e.g. `full`, `cardData`, or `fetch_config`. The mix of camel case and snake case aside, being type hinted as boolean, one would expect this to toggle the respective feature using `True`/`False`. Instead, one has to pass `None` instead of `False` to disable it.

This smells of a possible misunderstanding of what `cardData: typing.Optional[bool] = None` means, in that `typing.Optional` doesn't in fact make the argument optional, it simply allows `None` being explicitly passed as a value. It is made optional simply by providing a default value, and so I suspect that a better way to define these signatures is simply using `cardData: bool = False`. 

### Reproduction

Setting `cardData=False` doesn't turn this option off (only setting it to None does):

```python
list_models(author="huggingface", cardData=False)[0]
```

```
ModelInfo: {
	modelId: huggingface/CodeBERTa-small-v1
	sha: None
	lastModified: None
	tags: []
	pipeline_tag: fill-mask
	siblings: None
	private: False
	author: None
	config: None
	_id: 621ffdc136468d709f17bd02
	id: huggingface/CodeBERTa-small-v1
	cardData: {'language': 'code', 'thumbnail': 'https://cdn-media.huggingface.co/CodeBERTa/CodeBERTa.png', 'datasets': ['code_search_net']}
}
```

Setting `fetch_config=False` doesn't turn this option off (only setting it to None does):

```python
list_models(author="huggingface", fetch_config=False)[0]
```
```
ModelInfo: {
	modelId: huggingface/CodeBERTa-small-v1
	sha: None
	lastModified: None
	tags: []
	pipeline_tag: fill-mask
	siblings: None
	private: False
	author: None
	config: {'architectures': ['RobertaForMaskedLM'], 'model_type': 'roberta'}
	_id: 621ffdc136468d709f17bd02
	id: huggingface/CodeBERTa-small-v1
}
```

### System Info

```shell
huggingface_hub=0.10.1
```

**Comment by Wauplin** [comment]
Hi @buhrmann thanks for reporting ! That is definitely a bug and it seems to come from a server-side issue.

About the `Optional[bool]` / `bool`, I get your point. The slight difference between `fetch_config=None` and `fetch_config=False` is that in the first case the default behavior is decided by the server as in the second case it is hard-coded in the lib. This rule could be revisited but at least that's the short explanation about it.
