### ISSUE TITLE
Ability to get file size for `RepoFile`

### ISSUE THREAD

**Issue by Narsil** [huggingface/huggingface_hub#1158]
**Is your feature request related to a problem? Please describe.**

I'm trying to do some operations on my repository and I want to skip the super large models.
When I do `list(api.list_models(..))` I receive the model information I asked for, but I do not get the 
file size of `pytorch_model.bin` of the relevant models. So I cannot filter them out.

**Describe the solution you'd like**
something like `model_info.sibling[n].get_file_size()` or assimilated, which would fetch the file size when asked for it for those lfs files
would be super convenient.

**Describe alternatives you've considered**
Currently I'm writing my own HEAD requests to get that information.

I could do `model_info(m for m in list_models(...), files_metadata)` but it might be too strainful on the hub.

**Additional context**
@XciD Anything constraints on gitaly to implement those ?
@Wauplin

**Comment by Wauplin** [comment]
For the record, there is a [get_hf_hub_metadata](https://huggingface.co/docs/huggingface_hub/main/en/package_reference/file_download#huggingface_hub.get_hf_file_metadata) that can make the HEAD request for you. It returns a [HfFileMetadata](https://huggingface.co/docs/huggingface_hub/main/en/package_reference/file_download#huggingface_hub.HfFileMetadata) object that currently has only `commit_hash`, `etag` and `location`. It's a bit a shame (my bad) that we do not parse the `X-Linked-Size` header as well. This feature request could be added here.

```py
from huggingface_hub import get_hf_file_metadata, hf_hub_url

url = hf_hub_url(repo_id="gpt2", filename="pytorch_model.bin")
metadata = get_hf_file_metadata(url)
# metadata.commit_hash
# metadata.etag
# metadata.location
```

Note: `RepoFile` and `HfFileMetadata` are currently two unrelated objects in the implementation.

**Comment by julien-c** [comment]
Note that https://huggingface.co/api/models/bert-base-cased?blobs=true (note the ?blobs=true) will already give you the sizes of the files inside a repo already

**Comment by Wauplin** [comment]
> Note that https://huggingface.co/api/models/bert-base-cased?blobs=true (note the ?blobs=true) will already give you the sizes of the files inside a repo already

Yes indeed, that's what `(model_info(m.modelId, files_metadata=True) for m in list_models(...))` would do. I think here Narsil wanted a way to check the size of a specific file instead of requesting the metadata from all files of the repo (to reduce the moon-landing <> gitaly requests).

**Comment by BramVanroy** [comment]
> Note that https://huggingface.co/api/models/bert-base-cased?blobs=true (note the ?blobs=true) will already give you the sizes of the files inside a repo already

Came here after hitting my head against a wall: the siblings from repo_info had a None `size` attribute, just like `lfs`. But using your approach does correctly yield the expected sizes. Not sure implementation-wise what goes wrong (my dataset repo contains duckdb files).
