### ISSUE TITLE
Send delete operations before add operations in `create_commit`

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1162]
Originally from @severo [on slack](https://huggingface.slack.com/archives/C0311GZ7R6K/p1667594293037349?thread_ts=1667575477.939639&cid=C0311GZ7R6K) (internal link).

> the delete operations are always located as the last operations, thus the files that have been created are deleted afterwards. I’m wondering if it should not be otherwise: first delete, then create.

From @coyotte508 :

> since create = update, you could otherwise not delete files you update? (but I agree that putting delete operations before create operations makes sense)

**Comment by coyotte508** [comment]
With the `jsonlines` content-type the hub should pass operations to gitaly in the same order it receives them but I'm not sure how gitaly will react to having multiple operations on the same file.

**Comment by Wauplin** [comment]
> With the jsonlines content-type the hub should pass operations to gitaly in the same order it receives them

That seems to be the correct way of doing it indeed. Not sure yet how I will implement it :D 

 > I'm not sure how gitaly will react to having multiple operations on the same file
 
 The least I can do is to raise a warning when a user do so. At the moment it is also possible to send two "Add" operations on the same file which doesn't make much sense.
