### ISSUE TITLE
Import `constants` module instead of importing constant values directly

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1172]
Best described by @albertvillanova in https://github.com/huggingface/datasets/pull/5196#discussion_r1016675174 and https://github.com/huggingface/datasets/pull/5196#discussion_r1017511194.

Basically, change from
```py
from huggingface_hub.constants import CONSTANT_VALUE

CONSTANT_VALUE
(...)
```

to

```py
from huggingface_hub import constants

constants.CONSTANT_VALUE
(...)
```

everywhere.

:warning: This will most probable brake some monkey-patching in downstream libraries. Let's be careful about how to perform such a change. E.g. let's do it and make some tests before merging.

**Comment by dankornas** [comment]
Hi, is this issue still available to work on? If yes, I would like to give it a shot. I have been eager to contribute to HuggingFace, and this would be a nice start.

**Comment by Wauplin** [comment]
Hi @dankornas, thanks for proposing to contribute on this one! It is open for contributions yes :) Maybe as a start you can work on a first PR that makes the change only in a few modules (instead of the entire codebase at once) so that we can iterate on it. What do you think? If you have any questions, please let me know! 

Thanks in advance 🤗

**Comment by dankornas** [comment]
Hey @Wauplin, sounds good to me! Based on the comments that you provided in your first comment, I think I have a pretty good idea of what we want to do here. So, I will start playing around with this whenever I can and once I have something or if I have any questions, I'll be sure to get back to you :)

**Comment by Wauplin** [comment]
Good, sounds like we have a plan then :) Feel free to ping me whenever!

**Comment by WizKnight** [comment]
Hey @Wauplin , the task was completed to update constants in `hf_api.py`, can I work on other files as well or first wait for it to get reviewed and merged

**Comment by Wauplin** [comment]
I think it's best to definitively complete the first PR first, which should happen very soon!

**Comment by Wauplin** [comment]
Hi @WizKnight , I just merged https://github.com/huggingface/huggingface_hub/pull/2453! Thanks for the contributions :hugs: Would you like to open a follow-up PR to address all other constants occurrences? :)

**Comment by Wauplin** [comment]
Hi @WizKnight, I'm very sorry, I closed https://github.com/huggingface/huggingface_hub/pull/2453 too quickly. My fault on that.

What I meant in https://github.com/huggingface/huggingface_hub/pull/2453#discussion_r1721841938 is that we should keep all the imports for backward compatibility BUT we should still use `constants. ...` in the module (for example, keeping `from .constants import REPO_TYPES_MAPPING`, adding `from . import constants` and use `constants.REPO_TYPES_MAPPING` in the code). So most of the things in commit https://github.com/huggingface/huggingface_hub/pull/2453/commits/5bb271c18b3d4e7473d517475472b1f9debe7e1f can be reverted. Very sorry about the misunderstanding. Could you open a new PR for that since I merged the previous one? Thanks a lot!

**Comment by WizKnight** [comment]
> Hi @WizKnight, I'm very sorry, I closed #2453 too quickly. My fault on that.
> 
> What I meant in [#2453 (comment)](https://github.com/huggingface/huggingface_hub/pull/2453#discussion_r1721841938) is that we should keep all the imports for backward compatibility BUT we should still use `constants. ...` in the module (for example, keeping `from .constants import REPO_TYPES_MAPPING`, adding `from . import constants` and use `constants.REPO_TYPES_MAPPING` in the code). So most of the things in commit [5bb271c](https://github.com/huggingface/huggingface_hub/commit/5bb271c18b3d4e7473d517475472b1f9debe7e1f) can be reverted. Very sorry about the misunderstanding. Could you open a new PR for that since I merged the previous one? Thanks a lot!

Okay, I'll open a new PR and will keep this with backward compatibility `from .constants import REPO_TYPES_MAPPING`, and add `from . import constants` and use `constants.REPO_TYPES_MAPPING' in the code.

Right??

**Comment by Wauplin** [comment]
>  and use constants.REPO_TYPES_MAPPING in the code.

And use all other constants as `constants.MY_CONSTANT` as well. Right yes!

**Comment by Wauplin** [comment]
Closing this issue as completed by https://github.com/huggingface/huggingface_hub/pull/2489. Thanks @WizKnight!
