### ISSUE TITLE
Expose a modified `requests` module to wrap `build_hf_headers` and `hf_raise_for_status` 

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1194]
We could have `huggingface_hub.requests.post(...)` (and `.head`, `.get`, `.delete`, ...), all returning a `HfResponse` that inherits from `requests.Response`.

`huggingface_hub.requests.post(...)` could also take as input a `token` argument.

First mentioned in [this discussion](https://huggingface.co/spaces/osanseviero/repo_duplicator/discussions/3) cc @julien-c

**Comment by julien-c** [comment]
maybe overkill though – your solution in https://huggingface.co/spaces/osanseviero/repo_duplicator/discussions/3 is good enough IMO

**Comment by Wauplin** [comment]
For the record and for users landing on this issue, here is the current workaround. It is officially supported (e.g. you can expect long-term support):

```py
from huggingface_hub.utils import build_hf_headers, hf_raise_for_status

r = requests.post(
    f"{ENDPOINT}/api/{repo_type}s/{source_repo}/duplicate",
    headers=build_hf_headers(token=token),
    json={"repository": dst_repo},
)
hf_raise_for_status(r)
```

**Comment by Wauplin** [comment]
Closing as wontfix => solution described in https://github.com/huggingface/huggingface_hub/issues/1194#issuecomment-1318447821 is good enough.
