### ISSUE TITLE
Programmatically accept gated repo 

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1198]
Mentioned multiple times already. Last time in https://github.com/huggingface/diffusers/issues/1239. Also [on slack](https://huggingface.slack.com/archives/C03UQJENJTV/p1668585070021629?thread_ts=1668548492.210079&cid=C03UQJENJTV) (internal link).

It would be good to have an API to read and accept license for a gated repo.
This requires 2 endpoints from the Hub:
1. Get the license message (e.g. extra_gated_prompt) + which fields to prompt (e.g. extra_gated_fields) => **TODO in moon-landing**
2. Accept the license with required fields => already exists

(cc @anton-l @patrickvonplaten from `diffusers`, cc @julien-c @Pierrci from `moon-landing`)

**Comment by julien-c** [comment]
not super prio IMO given:
- you still need to create a user account on the website, and log in to the website at least once (at least to create a user access token)
- it's going to be an interactive prompt given we need to show you the gating message/license and you need to press "confirm"

Besides, some prominent diffusion model repos have removed their gating recently

I was thinking, maybe a quick improvement is to display a link to the repo page where one can accept, but it's probably already in there actually no?

**Comment by Wauplin** [comment]
For the record, the error message from trying to access a gated repo is already quite explicit:

```text
huggingface_hub.utils._errors.HfHubHTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/models/ardent-figment/gated-model (Request ID: 8c_6mRGLI3wJlma-pacqZ)

Access to model ardent-figment/gated-model is restricted and you are not in the authorized list. Visit https://huggingface.co/ardent-figment/gated-model to ask for access.
```

**Comment by julien-c** [comment]
yep cool. I guess in _interactive mode_ you could even open the browser directly or something, but maybe overkill

**Comment by Wauplin** [comment]
> I guess in interactive mode you could even open the browser directly or something, but maybe overkill

Yeah, why not. It is straightforward to detect if we run in a google colab and if yes, open a new tab. Seems very specific to colab users but I feel they represent a majority of the users having an issue with gated repos (right @patrickvonplaten @anton-l ?)

Outside of the google colab use case, I'd be more reluctant as we can't know for sure if we want to use `webbrowser` (open tab from machine running the python code) or a javascript `windows.open(...)` (open tab from machine running the frontend).

**Comment by osanseviero** [comment]
Imo this is a very niche use case which might not get much usage except for very specific popular gated repos (e.g. Stable Diffusion), but otherwise I don't expect this to be used much, and might be more of a pain to maintain. The explicit error message is quite nice mo.

**Comment by Wauplin** [comment]
Let's just do nothing and keep it as it is then 🙂
Should I close the issue as "won't do" ?

**Comment by osanseviero** [comment]
Up to you! We can also leave open and see if more community members are interested in this; we can re-evaluate if we see more demand for it

**Comment by Wauplin** [comment]
I'll leave it open and tagged as "wontfix" then. Will be reevaluated if we get more interest in it.

**Comment by charlesfrye** [comment]
Hi! Many thanks for making an awesome community and libraries.

I'm developing tutorial content around Dreambooth and have noticed many or even most people get stuck on the license, even after making HF accounts+tokens, despite explicit instructions. One person expressed that they did not expect the license to be blocking. It'd be great to be able to programmatically handle license review and acceptance to remove this roadblock.

We don't get the informative error message mentioned above. The script we're using, [`train_dreambooth.py` from the `diffusers` examples](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth.py), doesn't load the model directly -- it loads the individual components, so perhaps the error path is different.

We instead get a red herring error message, like:
```python
OSError: Can't load tokenizer for 'CompVis/stable-diffusion-v1-3'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 
'CompVis/stable-diffusion-v1-3' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer
```

**Comment by julien-c** [comment]
i think the repo owners are discussing about removing the gating mechanism from those particular model repos so it should solve 90% of the issues

I agree though that we should check (and guarantee) that a correct error message is printed out in downstream libraries.

For me this is the main thing to solve

**Comment by sgugger** [comment]
@Wauplin To print a better exception, we would need a specific exception type from hf_hub that we can catch (to distinguish it from conection errors) ideally.

**Comment by Wauplin** [comment]
I made a [PR in moon-landing](https://github.com/huggingface/moon-landing/pull/4627) (internal link) so that we can know when we get an error because of a gated repo (other than parsing the response payload). Let's settle this  server-side and then I'll adapt in `huggingface_hub`.

**Comment by Wauplin** [comment]
@sgugger `GatedRepoError` is now implemented in `huggingface_hub`. Feel free to use it starting from next release :)

**Comment by samuel100** [comment]
@Wauplin Is it possible to revive this feature ask? I have a scenario where I want to download ~225 datasets all of which require to accept T&Cs (which are automatically accepted by the provider). Currently, I'd need to go into the browser and accept 225 T&Cs before I could download. I'd rather do this programmatically rather than (laboriously) clicking 225 buttons. This might need a new method like `request_access(path)`.

**Comment by Wauplin** [comment]
@samuel100 if the repos you are trying to access are gated without any form, you can programmatically accept them using the (undocumented) API like this:

```py
import requests

from huggingface_hub.utils import build_hf_headers

headers = build_hf_headers()
# or directly `headers = {"authorization": "Bearer hf_xxx"}`

repo_id = "severo/test_gated"
repo_type = "dataset"
url = f"https://huggingface.co/{repo_type}s/{repo_id}/ask-access"

response = requests.post(url, headers=headers)
response.raise_for_status()
```


Not sure we will integrate it in `huggingface_hub` anytime soon so in the meantime you can use this.
If the gated repo as a form, the body of the POST request must contains the values (not sure exactly about the format but you should be able to see it from the developer console in your browser).

Hope this helps in the meantime! :hugs:
