### ISSUE TITLE
Improve error message when push to hub fails because it is not a git repo

### ISSUE THREAD

**Issue by payoto** [huggingface/huggingface_hub#1204]
**Is your feature request related to a problem? Please describe.**

I can't figure out which folder I need to modify to get a `push_to_hub` to work. I would like to improve the already excellent error message:

```python
/usr/lib/python3.8/site-packages/huggingface_hub/repository.py in clone_from(self, repo_url, token)
    760                 # Check if the folder is the root of a git repository
    761                 if not is_git_repo(self.local_dir):
--> 762                     raise EnvironmentError(
    763                         "Tried to clone a repository in a non-empty folder that isn't a"
    764                         " git repository. If you really want to do this, do it"

OSError: Tried to clone a repository in a non-empty folder that isn't a git repository. If you really want to do this, do it manually:
git init && git remote add origin && git pull origin main
 or clone repo to a new folder and move your existing files there afterwards.
OSError: Tried to clone a repository in a non-empty folder that isn't a git repository. If you really want to do this, do it manually:
git init && git remote add origin && git pull origin main
 or clone repo to a new folder and move your existing files there afterwards.
```

**Describe the solution you'd like**

I would like the `self.local_dir` variable to be interpolated into the error message: 

```
"Tried to clone a repository in a non-empty folder that isn't a"
f" git repository ('{self.local_dir}'). If you really want to do this, do it"
```

**Describe alternatives you've considered**

None

**Additional context**

 None

**Comment by payoto** [comment]
Happy to implement the suggested fix

**Comment by Wauplin** [comment]
Hi @payoto, I'm completely fine with the idea as it would for sure improve user experience. Feel free to implement it and thank you in advance! :)

**Comment by Wauplin** [comment]
Out of curiosity, in which context are you using the `Repository` class in your projects ? Question is unrelated to the issue, it's just to get to know more about the usage of this module.

**Comment by payoto** [comment]
Great, I'll do that then.

It's used as part of the optimum Graphcore library (the implementation of optimum for Graphcore's IPU). The error shows up during a call to `push_to_hub`. I've been running quite a lot of models and tinkering with moving/sharing caches between containers and I suspect a `.git` folder got lost in the process.

**Comment by Wauplin** [comment]
Ok, thanks for the input :)
I approved the PR. Have a nice weekend.
