### ISSUE TITLE
[advice] use github to replace gitlab in pre-commit-config

### ISSUE THREAD

**Issue by Freed-Wu** [huggingface/huggingface_hub#1206]
<https://github.com/huggingface/huggingface_hub/blob/main/.pre-commit-config.yaml#L15>

github also has flake8 <https://github.com/pycqa/flake8>. Why not use github for all pre-commit hooks?

**Comment by Wauplin** [comment]
Seems reasonable. To real reason here except "it has been done like this".

**Comment by severo** [comment]
https://flake8.pycqa.org/en/latest/internal/contributing.html#contributing-code

> Flake8 development happens on [GitHub](https://github.com/pycqa/flake8). Code contributions should be submitted there.
