### ISSUE TITLE
Dataset metadata lost when loading evaluations with `ModelCard.load()`

### ISSUE THREAD

**Issue by lewtun** [huggingface/huggingface_hub#1208]
### Describe the bug

When loading evaluation metadata with the `ModelCard` API, it seems some important information like `dataset_config` and `dataset_split` is lost.

For example, [this model card](https://huggingface.co/philschmid/bart-large-cnn-samsum) has [evaluations](https://huggingface.co/philschmid/bart-large-cnn-samsum/blob/main/README.md#L50-L51) where both the dataset config and split are specified. 

However, when loading the metadata with `ModelCard.load()`, these fields are absent since the metadata appears to be grouped under a single (task, dataset) and this optional information isn't collected. See below for a reproducible example.

### Reproduction

Here's one way to see the problem:

```python
from huggingface_hub import ModelCard

card = ModelCard.load("philschmid/bart-large-cnn-samsum")
# Expect to see dataset config/test fields here
card.data
```

Alternatively, we can run a check on the evaluation data itself:

```python
from huggingface_hub import ModelCard

card = ModelCard.load("philschmid/bart-large-cnn-samsum")
metadata = card.data.to_dict()
eval_results = model_index_to_eval_results(metadata["model-index"])[1]
assert any(eval_result.dataset_config is not None for eval_result in eval_results) is True, "at least one config should exist"
```

### System info

```shell
- huggingface_hub version: 0.11.0
- Platform: Linux-4.19.0-22-cloud-amd64-x86_64-with-glibc2.10
- Python version: 3.8.13
- Running in iPython ?: Yes
- iPython shell: ZMQInteractiveShell
- Running in notebook ?: Yes
- Running in Google Colab ?: No
- Token path ?: /home/lewis_huggingface_co/.huggingface/token
- Has saved token ?: True
- Who am I ?: lewtun
- Configured git credential helpers: store
- FastAI: N/A
- Tensorflow: N/A
- Torch: 1.11.0
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
```

**Comment by Wauplin** [comment]
Fixed in https://github.com/huggingface/huggingface_hub/pull/1214 by @lewtun !
