### ISSUE TITLE
Easy check repository and branch

### ISSUE THREAD

**Issue by camenduru** [huggingface/huggingface_hub#1213]
```py
    try:
        repo_exists = True
        r_info = model_info(model_to, token=token)
    except RepositoryNotFoundError:
        repo_exists = False
    finally:
        if repo_exists:
            print(r_info)
        else:
            create_repo(model_to, private=True, token=token)
    try:
        branch_exists = True
        b_info = model_info(model_to, revision=branch, token=token)
    except RevisionNotFoundError:
        branch_exists = False
    finally:
        if branch_exists:
            print(b_info)
        else:
            create_branch(model_to, branch=branch, token=token)
```

can we turn this into like 

```py
    if not HfApi().is_repository_exists(model_to):
        create_repo(model_to, private=True, token=token)
    if not HfApi().is_branch_exists(model_to, branch):
        create_branch(model_to, branch=branch, token=token)
```

also sometimes branch sometimes revision 😋
code from: https://huggingface.co/spaces/camenduru/converter/blob/main/app.py
thanks for the new create_branch() ❤

**Comment by Wauplin** [comment]
Hi @camenduru :wave: 
3 things here:
1. It is possible to pass `exists_ok=True` to `HfApi().create_repo`. This way no need for a `is_repository_exists()` helper that would be quite unsafe if the repo is concurrently created between `is_repository_exists` and `create_repo`. See [documentation](https://huggingface.co/docs/huggingface_hub/v0.11.0/en/package_reference/hf_api#huggingface_hub.HfApi.create_repo).
2. We should definitely add a `exists_ok: bool = False,` argument to both `create_branch` and `create_tag` to solve what you described. Implementation would be to try/catch the `hf_raise_for_status` line and if `exists_ok=True` then do not raise issue (in case of HTTP 409 Conflict I mean). Would you like to implement it ? I can help if you need help.
3. `branch` and `revision` have different meaning. `branch` refers to a git branch. A `revision` is more generic. It can be a branch name, a tag, a ref (`refs/pr/1`) or even a commit hash (`99ac57` or `99ac57b5f8e7cf9ed6a4cfe840e3cd246d4f997a`). So yeah, we need different naming here :)
