### ISSUE TITLE
hf_hub_download always writes to disk when revision is not a complete commit hash

### ISSUE THREAD

**Issue by mhham** [huggingface/huggingface_hub#1216]
Due to the behavior of `_cache_commit_hash_for_specific_revision` (https://github.com/huggingface/huggingface_hub/blob/99ac57b5f8e7cf9ed6a4cfe840e3cd246d4f997a/src/huggingface_hub/file_download.py#L842), if the revision is not a complete commit hash, `hf_hub_download` will always write the commit hash to the refs folder, even if the file already exists.

This can be problematic if the user loading the pretrained model does not have write access to the transformers cache directory.

I suggest first checking if the refs file containing the commit hash exists and has the same commit hash, before trying to write it.

# To reproduce

1. Download a pretrained model 

```python
import transformers
model = transformers.DistilBertModel.from_pretrained("distilbert-base-uncased")
```

2. Change the HF_HOME directory permissions to remove write permission
3. Try to load the same model

```python
import transformers
model = transformers.DistilBertModel.from_pretrained("distilbert-base-uncased")
```

-> Should break with a permission error

**Comment by Wauplin** [comment]
@mhham Thanks for reporting. I made a PR (https://github.com/huggingface/huggingface_hub/pull/1219) to fix this. 

Another (immediate) solution is to set `HF_HUB_OFFLINE` environment variable to true. The user that has read-only access to the cache will not try to fetch latest version from the Hub (and therefore not trigger PermissionError).

**Comment by mhham** [comment]
Thanks for the quick fix @Wauplin , and the workaround !
