### ISSUE TITLE
Ability to version with training script to model repository

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/huggingface_hub#1231]
I was chatting with folks and got this idea that it would be good to version model with its' own training script for better reproducibility. This can simply be done if training script includes push to hub and if we could give user ability to add the file indicated in `__file__` to  the repository everything's saved in and is about to be pushed to remote. AFAIK this is not done. WDYT?  @osanseviero @nateraw  @Wauplin

**Comment by Wauplin** [comment]
Please correct me but I feel this is more specific to the training library that is used than to `huggingface_hub` itself.
`hfh` provides all the utils to upload files to the Hub, including the folder containing all the training scripts for example. But in the description you wrote, I am not sure to understand where you would like to see this option in `huggingface_hub`. Could you elaborate on this please ? :)

**Comment by merveenoyan** [comment]
@Wauplin imagine you have a training script where you're calling `push_to_hub_keras`. This function starts a repository, saves the model there, and pushes it to Hub. What I'm saying is, we could add an argument where this function also adds training script to the target repository model was saved in.

**Comment by Wauplin** [comment]
Most flexible way I see is to provide a list of operation to add in the same commit as the push. That might be a bit low-level but at least it's flexible.

On the other side we could provide just a path (or list of paths) to a file/folder and upload everything. What I'm afraid of with this strategy is that a previously uploaded script could be hanging in the repo without being deleted (if training script name changed).

**Comment by osanseviero** [comment]
This seems like a very niche case, and I think we generally don't want people to push too much for their training scripts on the Hub. Not sure if it's worth adding this to the Keras callback as the usage is relatively low. 

cc @julien-c @gary149

**Comment by nateraw** [comment]
I think this is a really interesting idea!! 👀 

Probably best if it lives outside of this lib though, as that way you could build some other nice things around it (environment, etc.) without adding too much niche code here.

**Comment by Wauplin** [comment]
Worth mentioning that to build something outside of `huggingface_hub`, one can still use the `save_pretrained_keras` and reimplement a more flexible `push_to_hub_keras` based on it.

**Comment by Wauplin** [comment]
@merveenoyan based on the discussion is it fine if I close this issue as "won't fix" ? Please let me know if you are working on such a tool :) (maybe on this issue so that everyone knows)
