### ISSUE TITLE
Opt-in for downloading without symlinks

### ISSUE THREAD

**Issue by pcuenca** [huggingface/huggingface_hub#1240]
This is possibly a niche use case.

I recently found that some libraries (`coremltools`, in this case) don't play nice with symlinks even on Unix platforms 😲. This led me to replace this one-liner, which was intended for user communication:

```Python
from huggingface_hub import snapshot_download

repo_id = "apple/coreml-stable-diffusion-v1-4"
variant = "original/packages"

downloaded = snapshot_download(repo_id, allow_patterns=f"{variant}/*")
```

With this one (taken from [the blog post](https://huggingface.co/blog/diffusers-coreml#download-the-model-checkpoints)):

```Python
from huggingface_hub import snapshot_download
from huggingface_hub.file_download import repo_folder_name
from pathlib import Path
import shutil

repo_id = "apple/coreml-stable-diffusion-v1-4"
variant = "original/packages"

def download_model(repo_id, variant, output_dir):
    destination = Path(output_dir) / (repo_id.split("/")[-1] + "_" + variant.replace("/", "_"))
    if destination.exists():
        raise Exception(f"Model already exists at {destination}")
    
    # Download and copy without symlinks
    downloaded = snapshot_download(repo_id, allow_patterns=f"{variant}/*", cache_dir=output_dir)
    downloaded_bundle = Path(downloaded) / variant
    shutil.copytree(downloaded_bundle, destination)

    # Remove all downloaded files
    cache_folder = Path(output_dir) / repo_folder_name(repo_id=repo_id, repo_type="model")
    shutil.rmtree(cache_folder)
    return destination

model_path = download_model(repo_id, variant, output_dir="./models")
print(f"Model downloaded at {model_path}")
```

It's not the end of the world, but in this case I _really_ wanted to stress how easy it was to download Core ML checkpoints from the hub and use them downstream for whatever purpose.

If this is something that only affects `coremltools`, then it's not worthwhile doing anything (I'll open a PR there when I look into the problem in more depth). I'm raising the issue in case somebody else has observed other use cases that could benefit from a flag to unconditionally use #1067 even if symlinks are supported by the underlying os.

**Comment by pcuenca** [comment]
Yeah, I supposed there might be other scenarios where users need a exact copy of the file structure. Building a docker container sounds like one of them (or deployment tasks, in general). `snapshot_download` is much better than `git clone` because you can specify branches or patterns (as in my example above) and don't have to download stuff you don't need or keep a humongous `.git` directory with all the lfs blobs. Admittedly, we tend to create heavily overloaded repos with multiple variants for different frameworks, floating-point precision, etc.

Happy to propose a PR if you do decide to go this way.

**Comment by peterschmidt85** [comment]
I'm having the same issue.

Our ML platform syncs the HF cache folder to S3. Due to the use of symlinks, this doesn’t work correctly. We'd love it if HF allowed disabling symlinks for the cache. 

Otherwise, using HF by all of our users will require workarounds that are hard to discover and use.

**Comment by Wauplin** [comment]
Otherwise yes, we could have a method to download to an arbitrary folder and without any versioning. I'm a bit worried that if we do such a thing, some integrations will be messy (not versioning means no caching, no sharing between libs, no way to scan/delete the cache,...)

**Comment by Wauplin** [comment]
Opening up again this issue after some talks with @philschmid (after for docker-related purposes). I think the best way to tackle this is to allow users to download stuff independently from the cache-system. It feels safer than playing with a "disable_symlinks" flag.

What I propose is to add a new parameter "destination" to both `hf_hub_download` and `snapshot_download`. When `destination` is set, `cache_dir` must explicitly be set to `False`.

```py
# Download checkpoints/ folder without cache
snapshot_download("my-cool-model", allow_patterns="checkpoints/**", cache_dir=False, destination="/path/to/local/folder")

# Download model weights folder without cache
hf_hub_download("my-cool-model", "pytorch_model.bin", cache_dir=False, destination="/path/to/local/folder")
```

Having `cache_dir` set to False is a bit a redundant information to provide but I think it makes it very clear to the user that there will not be any caching done. And `cache_dir=True` would have no meaning (raise exception in that case).

WDYT @philschmid @pcuenca @patrickvonplaten?
@julien-c I already have an intuition that you will not like the idea (:smile:) but making it explicit should prevent misuse from users, isn't it? At least I prefer this solution than passing environment variables.

**Comment by peterschmidt85** [comment]
> EDIT: Actually, maybe we should still use the internal cache just in case the entry exist. If it does, we do a simple shutil.copyfile instead of re-downloading. But if entry is not there, we don't update the cache.

IMO the suggestion above is a good one: the user has full control, and when it makes sense, the cache still can be leveraged.

**Comment by julien-c** [comment]
what about still using the cache (unless another flag is passed) but copying (or .... symlinking?) to `destination` at the end?

**Comment by Wauplin** [comment]
We could do forget about the clunky `cache_dir=False` that I suggested and do add a `use_symlinks` input flag instead (default True):
- if `destination` is set + `use_symlinks=True` => blobs are downloaded in the cache directory + symlinked to the destination folder
- if `destination` is set + `use_symlinks=False`
    - if blob is already in cache directory => we copy-paste it in the destination directory
    - if blob is not cached => we download it directly to the destination directory. If user does this in multiple locations, the file will be downloaded multiple times but it would be a user's choice
- if `destination` is not set + `use_symlinks=False` => raise ValueError (doesn't make sense)

Seems to be a good compromise for everyone, right?

**Comment by julien-c** [comment]
i would personally say that'd be reasonable^

**Comment by pcuenca** [comment]
@Wauplin that sounds reasonable to me too.

**Comment by patrickvonplaten** [comment]
Sounds good to me as well ! Just regarding naming, if `destination` always only contains symlinks (not 100% sure if that's the case), then `symlink_to` could maybe be a better name?

**Comment by Wauplin** [comment]
Yep sorry I did not re-post here. I made a PR for that (https://github.com/huggingface/huggingface_hub/pull/1360). The naming is the following:

```py
# pip install git+https://github.com/huggingface/huggingface_hub1240-snapshot-download-to-destination
from huggingface_hub import snapshot_download

# Download and cache files
snapshot_download(repo_id)

# Download and cache files + add symlinks in "my-folder"
snapshot_download(repo_id, local_dir="my-folder")

# Duplicate files already existing in cache
# and/or
# Download missing files directly to "my-folder"
#     => if ran multiple times, files are re-downloaded
snapshot_download(repo_id, local_dir="my-folder", local_dir_use_symlinks=False)
```

I tried to be consistent with the existing naming (especially in `transformers` and `huggingface_hub.Repository`) + made it explicit that we are talking about symlink to the local dir (and not inside the cache).

**Comment by Wauplin** [comment]
@peterschmidt85 , glad you like the solution :)

About having it natively handled in `StableDiffusionPipeline.from_pretrained`, I _guess_ that should be doable. However it needs adaptation in the `diffusers` library. Could you create [a new issue](https://github.com/huggingface/diffusers/issues/new/choose) to keep track of this in the diffusers repository? Thanks in advance!

**Comment by peterschmidt85** [comment]
@Wauplin  Done: https://github.com/huggingface/diffusers/issues/2886
Thank you!
