### ISSUE TITLE
space can't reach getElementById inside the iframe

### ISSUE THREAD

**Issue by camenduru** [huggingface/huggingface_hub#1242]
### Describe the bug

direct link working https://camenduru-webui.hf.space but space not 😭 https://huggingface.co/spaces/camenduru/webui

```py
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getElementById')
    at requestProgress (?__theme=system:1502:22)
    at submit (?__theme=system:1629:5)
    at eval (eval at <anonymous> (index.73c7a9d5.js:54:2889), <anonymous>:3:28)
    at index.73c7a9d5.js:56:5418
    at HTMLButtonElement.<anonymous> (index.73c7a9d5.js:55:2156)
    at index.73c7a9d5.js:4:1266
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.Kn (index.73c7a9d5.js:4:1253)
    at HTMLButtonElement._ (Button.svelte:10:48)
    at index.73c7a9d5.js:4:1266
```

related codes: https://huggingface.co/spaces/camenduru/webui/discussions/2

I am doing something wrong please help 😐

### System info

```shell
🤗 T4 medium
```

**Comment by Wauplin** [comment]
Hi @camenduru :wave: This but is not related to `huggingface_hub` python library. For what I understand it is related [to some code](https://github.com/camenduru/stable-diffusion-webui/blob/8504db51704d238cc7616f6bf59eb049d3eb101d/javascript/progressbar.js#L145) forked from [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui).
i can't really help on that. Maybe have open an issue on the AUTOMATIC1111 repo instead as they built the UI ?

**Comment by Wauplin** [comment]
(cc @apolinario)

**Comment by camenduru** [comment]
hi @Wauplin yes I am trying to run AUTOMATIC1111/stable-diffusion-webui on 🤗 spaces I always think huggingface_hub is huggingface.co 🤣 sorry maybe the gradio team can help maybe huggingface side iframe cors problem I will find 🤔

**Comment by Wauplin** [comment]
@camenduru no worries. Usually you can open issues on https://github.com/huggingface/hub-docs if you have a bug on hugginface.co .
