### ISSUE TITLE
http-based upload function should have a progress bar and show upload speed

### ISSUE THREAD

**Issue by sijunhe** [huggingface/huggingface_hub#1244]
**Is your feature request related to a problem? Please describe.**
When uploading big model files, it'd be good to have feedback and UI elements to show the progress and the upload speed. This is implemented in LFS-based upload function but not in http-based upload functions.

**Describe the solution you'd like**
Plenty of solutions (such as [this one](https://gist.github.com/tyhoff/b757e6af83c1fd2b7b83057adf02c139)) on the web that uses `tqdm` to track the progress of `requests.put` (i think that's what is used under the hood?).

**Comment by Wauplin** [comment]
Hi @sijunhe , thanks for posting. I looked a bit at the feature request and it's not _that_ easy to implement the progress bars. What is possible to do is to have a progress bar when uploading a lot of LFS files (examples: thousands of images in a dataset). Bar shows progress for each uploaded file.

However in a lot of cases you would like to see the individual progress of a single file (let's say a 10GB model weights for example). In this case, `requests` does not provide a convenient way to monitor it. When uploading a very huge file (>5GB) the upload is done in multiple parts. But 5GB per chunk is already a lot (a 10GB file would display a bar with 2 steps...).

**Comment by Wauplin** [comment]
**EDIT:** there seem to be a possibility to monitor huge uploads with `requests`: https://stackoverflow.com/a/13911048. Would you like to check if it works and maybe try to implement it in `huggingface_hub`. I can really help with the integration once it's confirmed that it works (and that it's indeed the feature you were thinking about). For integration, everything is under `_commit_api.py` and `lfs.py`.

**Comment by julien-c** [comment]
maybe related to `class SliceFileObj`?
