### ISSUE TITLE
Allow path and path_or_fileobj to be pathlib.Path

### ISSUE THREAD

**Issue by adrinjalali** [huggingface/huggingface_hub#1246]
Right now if the user passes a `pathlib.Path` object to `upload_file` for example, they get a validation error. All methods which accept a `path` or a `path_or_fileobj` should also accept `pathlib.Path`, instead of:

```py
ValueError: path_or_fileobj must be either an instance of str, bytes or io.BufferedIOBase. If you passed a file-like object, make sure it is in binary mode.
```

**Comment by Wauplin** [comment]
Definitely agree, I'm even wondering why the issue has not been raised earlier :smile:

**Comment by Wauplin** [comment]
Fixed it in https://github.com/huggingface/huggingface_hub/pull/1247 if you could review. Thanks for reporting it :)
