### ISSUE TITLE
Feature request: enable search and download of dataset metadata

### ISSUE THREAD

**Issue by lewtun** [huggingface/huggingface_hub#126]
As an end-user, I would like to be able to query and download the dataset metadata on the Hub in a similar fashion to `HfApi.list_models`

In particular, I would like to extract the information stored in the `dataset_infos.json` file that is associated with each canonical (and community?) dataset. 

Thanks to a tip from @lhoestq, the current way we can do this is by using `datasets.load.prepare_module` to download and cache the files: 

```python
from datasets import_main_class, prepare_module

module, module_hash = prepare_module(dataset_name)
builder_cls = import_main_class(module)
builder = builder_cls(hash=module_hash, name=dataset_config)
# get infos
builder.info
```

However, this is much, much slower than `HfApi.list_models`, presumably because we don't expose the `dataset_infos.json` information as an endpoint. 

Would it make sense to implement an something analogous to `ModelFile`, `ModelInfo` and `HfApi.list_models` but for datasets?

**Comment by julien-c** [comment]
For completeness, you'd also want to mention the current API: https://huggingface.co/api/datasets?full=true

which is called by `datasets.list_datasets()`

**Comment by severo** [comment]
see also #129
