### ISSUE TITLE
hf_hub_download call does not increase the download counter

### ISSUE THREAD

**Issue by fcakyon** [huggingface/huggingface_hub#1275]
### Describe the bug

I have downloaded this model more than 100 times in the last week, but the counter shows 0 downloads: https://huggingface.co/fcakyon/yolov5s-v7.0

Can you tell me which request triggers the download counter? Does `hf_hub_download` function trigger this counter?

### Reproduction

Using [yolov5 pypi package](https://pypi.org/project/yolov5/) for downloading the model.

Here is the download code: https://github.com/fcakyon/yolov5-pip/blob/main/yolov5/utils/downloads.py#L131-L145

### System info

```shell
I have downloaded this model from windows 10 and ubuntu 18.04 with huggingface=hub==0.11.1.
```

**Comment by julien-c** [comment]
Hi @fcakyon, which library are you downloading this model from?

For models which are not recognized to be used by a particular library, we only count file downloads for a list of a few potential filenames:

```ts
[
  "config.json",
  "config.yaml",
  "hyperparams.yaml",
  "meta.yaml",
]
```

- One potential workaround could be to download a file with one of those names, from `yolov5`. 
- Another solution (on our side) could be for us to make the "downloaded file spec" able to be overriden from the model card metadata
- Finally, another solution (maybe the simplest) would be to add yolov5 support to hf.co/models supported libraries. cc @osanseviero This should not be super hard!

**Comment by fcakyon** [comment]
Thanks a lot for the detailed answer @julien-c!

- Currently, there is no need for a config or meta file for loading yolov5 models (all required info is present in the torch binary) and I want to keep things simple by not requiring any additional files to be uploaded to the hub other than torch binary 👍 
- It would be awesome if "downloaded file spec" could be overridden from the model card!
- I am the maintainer of the [yolov5 package](https://pypi.org/project/yolov5/) and could try to help you adding yolov5 support to community hub 👍

**Comment by fcakyon** [comment]
> Hi @fcakyon, which library are you downloading this model from?

Using [yolov5 pypi package](https://pypi.org/project/yolov5/) for downloading the model.

**Comment by Wauplin** [comment]
I opened an internal issue to make the "downloaded file spec" configurable in model cards (see https://github.com/huggingface/moon-landing/issues/4927 - internal link). 
Let's wait for @osanseviero 's feedback on how we could add yolov5 as a supported library. Otherwise, I'll close this issue as it's not exactly related to `huggingface_hub` (but will still keep you updated if the internal ticket is implemented).

**Comment by julien-c** [comment]
@fcakyon how many yolov5 models do you expect to publish on the Hub? Also, noob question, but have you considering upstreaming/merging your changes to https://github.com/ultralytics/yolov5?

**Comment by fcakyon** [comment]
@julien-c I have just added an automated hub upload function to the package and expect lots of yolov5 models to be published on the hub: https://github.com/fcakyon/yolov5-pip/releases

Original repo is not interested in adding PYPI support, Neptune.ai integration and other features so I am maintaining this package separately.

Maybe my package can be added with the name `yolov5-pip` into the community API instead of name `yolov5`.

**Comment by fcakyon** [comment]
Meanwhile, I have added a `config.json` file to the repo and package download this config file at each call before the weight file, but counter still does not increase: https://huggingface.co/fcakyon/yolov5s-v7.0/tree/main

**Comment by Wauplin** [comment]
@fcakyon I'll close this issue as I think we can consider it as solved (by adding a `config.json` file).
About making this file configurable, it is already tracked here (https://github.com/huggingface/moon-landing/issues/4927 - internal link) but it is more a Hub-related topic, not really `huggingface_hub` anymore :)
Feel free to reopen the issue if you think it's wiser.

**Comment by fcakyon** [comment]
Thanks a lot!
