### ISSUE TITLE
Unable to install huggingface-cli

### ISSUE THREAD

**Issue by xianbaoqian** [huggingface/huggingface_hub#1283]
### Describe the bug

Default environment with Mac + virtualenv

### Reproduction

% pip3 install huggingface-cli
ERROR: Could not find a version that satisfies the requirement huggingface-cli (from versions: none)
ERROR: No matching distribution found for huggingface-cli

### Logs

```shell
(notebook) wangtz@Tiezhens-MBP translation % python
Python 3.9.6 (default, Sep 26 2022, 11:37:49)
```

### System info

```shell
- huggingface_hub version: 0.11.1
- Platform: macOS-13.0.1-arm64-arm-64bit
- Python version: 3.9.6
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /Users/wangtz/.huggingface/token
- Has saved token ?: False
- Configured git credential helpers: osxkeychain
- FastAI: N/A
- Tensorflow: N/A
- Torch: N/A
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A

{'huggingface_hub version': '0.11.1', 'Platform': 'macOS-13.0.1-arm64-arm-64bit', 'Python version': '3.9.6', 'Running in iPython ?': 'No', 'Running in notebook ?': 'No', 'Running in Google Colab ?': 'No', 'Token path ?': PosixPath('/Users/wangtz/.huggingface/token'), 'Has saved token ?': False, 'Configured git credential helpers': 'osxkeychain', 'FastAI': 'N/A', 'Tensorflow': 'N/A', 'Torch': 'N/A', 'Jinja2': '3.1.2', 'Graphviz': 'N/A', 'Pydot': 'N/A'}
```

**Comment by abhi-11nav** [comment]
Hey, trying doing this **!pip install huggingface_hub**
Then  **!huggingface-cli login**. Now, generate a token and login.
(OR)
Since you mentioned virtual environment, type **from huggingface_hub import notebook_login()** followed by **notebook_login()**

**Comment by julien-c** [comment]
Yes @xianbaoqian `huggingface-cli` command is installed by the `huggingface_hub` package out of the box

**Comment by julien-c** [comment]
feel free to close if this is solved

**Comment by xianbaoqian** [comment]
Ah. I see. Thanks for the help!

**Comment by brando90** [comment]
(iit_synthesis) brandomiranda~/pycoq ❯ pip install hugging_face_hub
ERROR: Could not find a version that satisfies the requirement hugging_face_hub (from versions: none)
ERROR: No matching distribution found for hugging_face_hub

**Comment by Wauplin** [comment]
Naming is wrong:
```bash
# pip install hugging_face_hub => doesn't exist
pip install huggingface_hub
```

**Comment by maxloosmu** [comment]
When I run:
`pip install -U "huggingface_hub[cli]"`

I get this output:
```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: huggingface_hub[cli] in /home/maxloo/.local/lib/python3.10/site-packages (0.19.4)
Requirement already satisfied: filelock in /home/maxloo/.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in /home/maxloo/.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (2023.10.0)
Requirement already satisfied: requests in /home/maxloo/.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in /home/maxloo/.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (4.66.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from huggingface_hub[cli]) (5.4.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/maxloo/.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (4.8.0)
Requirement already satisfied: packaging>=20.9 in /home/maxloo/.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (23.2)
Collecting InquirerPy==0.3.4 (from huggingface_hub[cli])
  Downloading InquirerPy-0.3.4-py3-none-any.whl (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.7/67.7 kB 2.4 MB/s eta 0:00:00
Collecting pfzy<0.4.0,>=0.3.1 (from InquirerPy==0.3.4->huggingface_hub[cli])
  Downloading pfzy-0.3.4-py3-none-any.whl (8.5 kB)
Requirement already satisfied: prompt-toolkit<4.0.0,>=3.0.1 in /usr/lib/python3/dist-packages (from InquirerPy==0.3.4->huggingface_hub[cli]) (3.0.28)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/maxloo/.local/lib/python3.10/site-packages (from requests->huggingface_hub[cli]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/maxloo/.local/lib/python3.10/site-packages (from requests->huggingface_hub[cli]) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/maxloo/.local/lib/python3.10/site-packages (from requests->huggingface_hub[cli]) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /home/maxloo/.local/lib/python3.10/site-packages (from requests->huggingface_hub[cli]) (2023.7.22)
Installing collected packages: pfzy, InquirerPy
Successfully installed InquirerPy-0.3.4 pfzy-0.3.4
```

Then I tried:
`huggingface-cli login`

I get this error:
`huggingface-cli: command not found`

**Comment by ljhOfGithub** [comment]
> When I run: 当我执行时： `pip install -U "huggingface_hub[cli]"`
> 
> I get this output:我得到这个输出：
> 
> ```
> Defaulting to user installation because normal site-packages is not writeable
> Requirement already satisfied: huggingface_hub[cli] in /home/maxloo/.local/lib/python3.10/site-packages (0.19.4)
> Requirement already satisfied: filelock in /home/maxloo/.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (3.13.1)
> Requirement already satisfied: fsspec>=2023.5.0 in /home/maxloo/.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (2023.10.0)
> Requirement already satisfied: requests in /home/maxloo/.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (2.31.0)
> Requirement already satisfied: tqdm>=4.42.1 in /home/maxloo/.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (4.66.1)
> Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from huggingface_hub[cli]) (5.4.1)
> Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/maxloo/.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (4.8.0)
> Requirement already satisfied: packaging>=20.9 in /home/maxloo/.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (23.2)
> Collecting InquirerPy==0.3.4 (from huggingface_hub[cli])
>   Downloading InquirerPy-0.3.4-py3-none-any.whl (67 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.7/67.7 kB 2.4 MB/s eta 0:00:00
> Collecting pfzy<0.4.0,>=0.3.1 (from InquirerPy==0.3.4->huggingface_hub[cli])
>   Downloading pfzy-0.3.4-py3-none-any.whl (8.5 kB)
> Requirement already satisfied: prompt-toolkit<4.0.0,>=3.0.1 in /usr/lib/python3/dist-packages (from InquirerPy==0.3.4->huggingface_hub[cli]) (3.0.28)
> Requirement already satisfied: charset-normalizer<4,>=2 in /home/maxloo/.local/lib/python3.10/site-packages (from requests->huggingface_hub[cli]) (3.3.2)
> Requirement already satisfied: idna<4,>=2.5 in /home/maxloo/.local/lib/python3.10/site-packages (from requests->huggingface_hub[cli]) (3.4)
> Requirement already satisfied: urllib3<3,>=1.21.1 in /home/maxloo/.local/lib/python3.10/site-packages (from requests->huggingface_hub[cli]) (2.0.7)
> Requirement already satisfied: certifi>=2017.4.17 in /home/maxloo/.local/lib/python3.10/site-packages (from requests->huggingface_hub[cli]) (2023.7.22)
> Installing collected packages: pfzy, InquirerPy
> Successfully installed InquirerPy-0.3.4 pfzy-0.3.4
> ```
> 
> Then I tried: 然后我试着： `huggingface-cli login`
> 
> I get this error: 我得到这个错误： `huggingface-cli: command not found`

Hello,I also meet the problem.How do you solve the problem.

**Comment by Wauplin** [comment]
Hey @ljhOfGithub, sorry for this inconvenience. It has to do with the installation setup. Can you refer to https://github.com/huggingface/huggingface_hub/issues/1840#issuecomment-1820714284 and let me know if it solves your problem?

**Comment by aycaecemgul** [comment]
`python3 -m pip install -U "huggingface_hub[cli]" `solved the problem.

**Comment by varungupta31** [comment]
For folks on `conda`, this should work

`conda install -c conda-forge huggingface_hub`

(worked for me)

**Comment by vallamost** [comment]
The huggingface-cli on Windows 10 was located in C:\Users\%username%\AppData\Roaming\Python\Python313\Scripts 

If you have a different version of Python it might be somewhere close. You can add this location to your PATH env variable then you can call ./huggingface-cli.exe from anywhere. Otherwise just open a terminal in that folder and run the exe.

**Comment by gitlonglong** [comment]
This work for me: pip install huggingface_hub==0.20.0

**Comment by hogagatech** [comment]
> This work for me: pip install huggingface_hub==0.20.0
 
This worked!

uninstall the previous version 
python -m pip uninstall huggingface_hub -y

then install again
python -m pip install huggingface_hub==0.20.0
