### ISSUE TITLE
Repository does not work on HF spaces

### ISSUE THREAD

**Issue by lukasfolle** [huggingface/huggingface_hub#1284]
Hi,

I am recently getting an error when trying to use my [HF space ](https://huggingface.co/spaces/lfolle/DeepNAPSI) together with the `Repository` from HF hub resulting in the following error message.

I would assume this is a bug since before it worked nicely. On my local machine the entrypoint.py below also works.
I am open for any suggestions 😃 

```bash
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/repository.py", line 742, in clone_from
    run_subprocess("git lfs install", self.local_dir)
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/utils/_subprocess.py", line 61, in run_subprocess
    return subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'lfs', 'install']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "entrypoint.py", line 6, in 
    Repository("repos/hand-ki-model", f"https://oauth2:{os.getenv('HANDKIGIT5')}@git5.cs.fau.de/folle/hand-ki-model.git", use_auth_token=os.getenv(""))
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/repository.py", line 528, in __init__
    self.clone_from(repo_url=clone_from)
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/repository.py", line 797, in clone_from
    raise EnvironmentError(exc.stderr)
OSError: Hook already exists: pre-push

	#!/bin/sh
	command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/pre-push'.\n"; exit 2; }
	git lfs pre-push "$@"

To resolve this, either:
  1: run `git lfs update --manual` for instructions on how to merge hooks.
  2: run `git lfs update --force` to overwrite your hook.
```

This is my entrypoint.py:
```python
import os
import sys
import subprocess
from huggingface_hub import Repository

Repository("repos/hand-ki-model", f"https://oauth2:{os.getenv('HANDKIGIT5')}@git5.cs.fau.de/folle/hand-ki-model.git", use_auth_token=os.getenv(""))
subprocess.check_call([sys.executable, "-m", "pip", "install", "repos/hand-ki-model/"])
import app
```

**Comment by Wauplin** [comment]
Hi @lukasfolle :wave: First of all, sorry for the long delay to respond. I've looked a bit at your issue and don't really understand why this is happening. 

We already had such an issue with git lfs prehooks at some point. It was due to an already installed pre-hook named "pre-push" conflicting with the lfs pre-hook (see [stackoverflow](https://stackoverflow.com/questions/72186566/hook-already-exists-pre-push-after-adding-new-git-hook)). Does that ring a bell to you?

Otherwise, I think I'll need more information to debug. [I made a simple space](https://huggingface.co/spaces/Wauplin/test-issue-1284/blob/main/app.py) to reproduce your issue but couldn't get the same error. Is it possible that something different has been configured on [hand-ki-model](https://git5.cs.fau.de/folle/hand-ki-model) which caused that ?

**Comment by Wauplin** [comment]
cc @chrisemezue as you also had this issue once. See [related slack thread](https://huggingface.slack.com/archives/C02EMARJ65P/p1663108768637689) (internal link). Seems that your issue has been solved but idk how precisely. Thanks in advance if you have an input! (cc @osanseviero as well)

**Comment by lukasfolle** [comment]
Hi @Wauplin, thanks for your answer!
I am not sure it is due to the gitlab project (you should be able to see the contents). Locally, everything works fine for me..

**Comment by lukasfolle** [comment]
Solved it by deleting all git hooks. But this should not be the recommended way right?
```python
hooks_path = ".git/hooks/"
if os.path.exists(hooks_path):
    shutil.rmtree(hooks_path)
```

**Comment by Wauplin** [comment]
@lukasfolle thanks for your feedback and to post a workaround that worked for you. It's definitely a bit hacky to be the recommended way to doing this. Do you happen to know which git hook was already installed in the folder or not ?

**Comment by lukasfolle** [comment]
No, I didnt use anything unusual. Debugging the startup of the container should reveal, what creates the hooks. Maybe thats worth a try.

**Comment by LysandreJik** [comment]
Hmmm no, I don't recall anything of the sort, unfortunately @Wauplin

**Comment by Wauplin** [comment]
@lukasfolle Good news, the issue has been spotted and fixed server-side! It was due to how the container was built.
You can now remove the hacky workaround that deletes `.git/hooks` folder from your Space and retry. Please let us know if you encounter any other issues :)

**Comment by lukasfolle** [comment]
Thank you @lucain it works now without the workaround!
