### ISSUE TITLE
Add Documentation page on `list_models`, `model_info`, and similar methods

### ISSUE THREAD

**Issue by julien-c** [huggingface/huggingface_hub#129]
...as well as the underlying HTTP API endpoints:

- https://huggingface.co/api/models?full=true to get the full list of models
- https://huggingface.co/api/models/elgeish/wav2vec2-large-xlsr-53-arabic (replace with relevant model id) to get info on one specific model
- ...

**Comment by osanseviero** [comment]
Where do you think this should be documented?
* As it's own page such as the library docs like transformers, dataset, etc. and the Inference API docs.
* In the Hub docs
* In a README in src/huggingface_hub

**Comment by severo** [comment]
For the REST APIs (Inference, Hub), it might be good to generate an [OpenAPI](https://www.openapis.org/) spec from the code and publish it with [ReDoc](https://redocly.github.io/redoc/) or [another tool](https://openapi.tools/).

(maybe you already have something like this)

**Comment by julien-c** [comment]
@osanseviero I'd say in the Hub docs, what do you think?

**Comment by julien-c** [comment]
the most important is to have a place to link to with a list of public API methods (as even inside the team not everyone knows them :) )

**Comment by osanseviero** [comment]
@severo, for Inference API we already have [some docs](https://api-inference.huggingface.co/docs/python/html/index.html). 

I would do two things, add an "Endpoints" site with a table explaining each endpoint. I really like ReDoc so that can be a follow-up, I think the priority right now is to get some documentation asap on this :) 

For the `huggingface_hub` methods, it's not very clear to me where it would fit better. For now I guess the Hub docs is fine.

**Comment by julien-c** [comment]
Yes, adding a `Hub API endpoints` page to the `/docs` sound great 🔥 

(for each endpoint you can also mention the corresponding `huggingface_hub` method)

Thanks!

**Comment by severo** [comment]
re: redoc via @Narsil (as I understood it): ReDOC has already been considered (https://api-inference.huggingface.co/docs/redoc/) but it included too much friction with the code and the current docs to be fully useful and efficient.

**Comment by Narsil** [comment]
Yes, it was mostly the easiness to make the docs as explicit as possible. So we went for raw docs instead to get full control of what was displayed.

**Comment by julien-c** [comment]
yeah unless for super complex API (Stripe?) I think that words are actually clearer than an API playground

Same as when the authors of mkdocs say that they don't actually want to automatically parse docstrings.
