### ISSUE TITLE
`huggingface-cli login` should indicate if I am already logged in

### ISSUE THREAD

**Issue by lonnen** [huggingface/huggingface_hub#1290]
When I run `whoami` I am clearly logged in

```
$ huggingface-cli whoami
lonnen
```

Yet when I run `login` 

```
$ huggingface-cli login

    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

    To login, `huggingface_hub` now requires a token generated from https://huggingface.co/settings/tokens .

Token:
```

I am given clear next steps for putting in a token "to login".

**Describe the solution you'd like**

I expect it to: 
1. tell me I'm already logged in
2. tell me to logout before proceeding
3. exit non-zero

something like:
```
$ huggingface-cli login

    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

    You're already logged in as lonnen
    To login with a different token, please run `logout` first.
```

**Describe alternatives you've considered**

A simple alternative would be to indicate that a user is already logged in and bail, but making the user remember or figure out where the token sits in order to manually log out is unergonomic at best.

Going one step further, another alternative that may still be useful to display that the user is already logged in but continue with the prompt's current behavior of overwriting the token.

```
$ huggingface-cli login

    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

    You're already logged in as 'lonnen'
    To login, `huggingface_hub` now requires a token generated from https://huggingface.co/settings/tokens .

Token:
```
This at least indicates that you're already logged in. It leaves it to the user to bail if they need to, and the language for the remainder of the prompt is awkward. Since tokens-to-users is a many-to-one thing it's unclear if this should be "to login again" or "to login as a different user" when the same user could just be rotating tokens. The whole line could stand to be reworked but that seems like a different issue.

**Additional context**

I did only a cursory check for other issues or guidance around the CLI API and didn't see anything.

I looked at the source and I'd be happy to write up any version of this as a PR

**Comment by Wauplin** [comment]
(I replied directly in https://github.com/huggingface/huggingface_hub/pull/1291#issuecomment-1384209737)

**Comment by Wauplin** [comment]
Closed as part of https://github.com/huggingface/huggingface_hub/pull/1291.
