### ISSUE TITLE
Feature request: Allow upload_file to upload multiple files

### ISSUE THREAD

**Issue by Lime-Cakes** [huggingface/huggingface_hub#1301]
Currently, the upload_file feature allows uploading in memory file like objects, which is a very good feature, allowing users to upload their data directly, without having to save to disk. Though, the API doesn't allow multiple files to be uploaded. Being able of uploading multiple in memory object without having to save to disk would be useful.

Upload folder allows multiple files (all in folder), but it's slower, and would require saving to disk first.
https://github.com/huggingface/huggingface_hub/blob/fb9f63793d69316d0957772e962ac6346da7f167/src/huggingface_hub/hf_api.py#L2094

Looking through the code, it seemed like a rather easy change to make upload_file take a list of input instead of just one. I'm down to opening a PR if the feature is useful to others

**Comment by Wauplin** [comment]
Hi @Lime-Cakes , thanks for your feedback.  `upload_file` is actually only a wrapper around the `create_commit` API. It's designed to be easy to use without providing all its flexibility. If you want to upload multiple files on the fly (from memory), you can defined several `CommitOperationAdd` manually. [See the guide](https://huggingface.co/docs/huggingface_hub/how-to-upstream#createcommit) for more details.

**Comment by Lime-Cakes** [comment]
Thanks! I'll use the low level API then
