### ISSUE TITLE
Unexpected characters in progress bar when downloading with hf_hub_download

### ISSUE THREAD

**Issue by sijunhe** [huggingface/huggingface_hub#1318]
### Describe the bug

Seeing some unexpected chars in progress bar when downloading from HF hub with the hf_hub_download API.

`Downloading (…)del_state.pdparams";:   2%|██▋`

the text `";` at the end is unexpected

### Reproduction

```
>>> from huggingface_hub import hf_hub_download
>>> from huggingface_hub import __version__
>>> __version__
'0.12.0'
>>>model_file = hf_hub_download(
  repo_id="sijunhe/stable-diffusion-v1-5",
  filename="model_state.pdparams",
  subfolder="text_encoder")

Downloading (…)del_state.pdparams";:   2%|██▋
```

### System info

```shell
- huggingface_hub 0.12.0
- python 3.8.15
```

**Comment by Wauplin** [comment]
Thanks for opening a ticket @sijunhe . Indeed header was badly parsed. I made a quick PR https://github.com/huggingface/huggingface_hub/pull/1320 to fix this.

**Comment by sijunhe** [comment]
> Thanks for opening a ticket @sijunhe . Indeed header was badly parsed. I made a quick PR #1320 to fix this.

thanks for the fast turnaround!
