### ISSUE TITLE
missing 1 required positional argument: 'response' in `huggingface_hub.utils.EntryNotFoundError`

### ISSUE THREAD

**Issue by sijunhe** [huggingface/huggingface_hub#1319]
### Describe the bug

Getting the following error when using `EntryNotFoundError`
```
TypeError: __init__() missing 1 required positional argument: 'response'
```
According to https://huggingface.co/docs/huggingface_hub/v0.12.0/en/package_reference/utilities#huggingface_hub.utils.EntryNotFoundError, `response` should be optional.

### Reproduction

```
>>> from huggingface_hub.utils import EntryNotFoundError
>>> error = EntryNotFoundError("error")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'response'
```

### System info

```shell
- huggingface_hub 0.12.0
```

**Comment by Wauplin** [comment]
Hey, made a quick fix as part of https://github.com/huggingface/huggingface_hub/pull/1320 :)
