### ISSUE TITLE
Public / private toggle on models is broken

### ISSUE THREAD

**Issue by jslegers** [huggingface/huggingface_hub#1322]
### Describe the bug

I'm currently unable to change any of my models from private to public or vice versa.

The toggle button for this is broken / not responsive...

![image](https://user-images.githubusercontent.com/883647/217018969-ba4e1d0c-d95d-4f1f-bbc0-feec85bb6411.png)

### Reproduction

Go to any model.

Try changing settings from "public" to "private" or vice versa.

### System info

```shell
N/A
```

**Comment by Kakulukian** [comment]
Hello jsleggers,
Thanks for reporting the issue with the hub. The problem is now solved, sorry for the inconvenience!

Cheers
