### ISSUE TITLE
Add a `SpaceCard` class or make `RepoCard` as top-level + few tweak

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1348]
`from huggingface_hub import RepoCard` not possible at the moment.
Also, could be good to have a `SpaceCard` object for Spaces. 

In the "few tweaks" mentioned, it would be nice to have methods like:
- `card.get("key")` / `card.get("key", default_value)`
- `card.pop("key")` / `card.pop("key", default_value)`
- `card["key"]`

=> basically same keyfeatures of a dictionary

(At the moment we have to do `getattr(card, "something", default_value)` which is not very pythonic)

(first mentioned in this [internal discussion](https://huggingface.slack.com/archives/C04D61EHNA1/p1676640893313689))

**Comment by merveenoyan** [comment]
I think `RepoCard` itself should be enough (given it has attributes that a Space needs), but rather maybe only making it importable should be cool and help people out when they develop Spaces.

**Comment by Wauplin** [comment]
(@merveenoyan: I just opened [a PR](https://github.com/huggingface/huggingface_hub/pull/1354) for this :) )

**Comment by julien-c** [comment]
i still think a `SpaceCard` would be nice, just for elegance/symmetry (can be just an alias to `RepoCard`)

**Comment by Wauplin** [comment]
Yeah, why not. I just added a `SpaceCard` that inherits from `Repocard` without implementing anything else.
