### ISSUE TITLE
Add `duplicate_space` endpoint

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1349]
Currently kinda unofficial. Scripts to duplicate Spaces have to do it "manually" at the moment (requests.post(url) + hf_raise_for_status). Let's make it a clearly supported endpoint.

**Comment by julien-c** [comment]
i think there was an internal discussion about this back in the day, but might be hard to dig and find it

In any case, i think it'd be reasonable to support, now
