### ISSUE TITLE
bart_lfqa: content has to be taken into account and a message is to be uttered if no reply is being found instead of going freestyle.

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [huggingface/huggingface_hub#1350]
### Describe the bug

When using https://huggingface.co/vblagoje/bart_lfqa, it does not seem to matter, which content you serve, you can pass documents of length 0 or 1B. Expected behaviour: Content has to be taken into account and a message is to be uttered if no reply is being found instead of going freestyle.

### System info

```shell
- huggingface_hub version: 0.12.0
- Platform: Windows-10-10
- Python version: 3.8.16
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Has saved token ?: False
- Configured git credential helpers: manager-core
- FastAI: N/A
- Tensorflow: N/A
- Torch: 1.13.1
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.4.0
- hf_transfer: N/A
- ENDPOINT: https://huggingface.co
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by Wauplin** [comment]
@ErfolgreichCharismatisch I'm not sure to understand the issue but it seems to be related to the `transformers` library itself, isn't it? I think you should open an issue there instead. 

For the record, `huggingface_hub` is focused on the python client (with same name) that interact with the Hub.

**Comment by ErfolgreichCharismatisch** [comment]
You are right, can be closed.

**Comment by ErfolgreichCharismatisch** [comment]
You are right, can be closed.
