### ISSUE TITLE
Private token does not work 

### ISSUE THREAD

**Issue by banochkabb** [huggingface/huggingface_hub#1363]
### Describe the bug

When I try to clone private Huggingface Space, I always receive "repository not found" even when using newly generated access token with read / write access. 

If I set repo to be public than everything works fine. 

<img width="913" alt="image" src="https://user-images.githubusercontent.com/79999401/221852791-230d1782-17ff-4020-ab0e-97bae3b82db3.png">

### Reproduction

Create private space and try to clone it

### System info

```shell
- huggingface_hub version: 0.12.1
- Platform: macOS-13.1-arm64-arm-64bit
- Python version: 3.9.12
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /Users/varya/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: BarbaraDefinely
- Configured git credential helpers: osxkeychain
- FastAI: N/A
- Tensorflow: 2.9.2
- Torch: N/A
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.4.0
- hf_transfer: N/A
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /Users/varya/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /Users/varya/.cache/huggingface/assets
- HF_HUB_OFFLINE: False
- HF_TOKEN_PATH: /Users/varya/.cache/huggingface/token
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by Wauplin** [comment]
Hi @banochkabb, thanks for the detailed issue. Seems to be an issue with `git-credential` even though it says that you configured it correctly. Could you try to run this command in the folder where you are running git clone:

```
echo "url=https://huggingface.co\nusername=hf_user" | git credential fill
```

If it configured correctly, you should have something like (**DO NOT COPY-PASTE** the output -raw token is in it-):
```
protocol=https
host=huggingface.co
username=hf_user
password=hf_***
```
Can you confirm ?

**Comment by banochkabb** [comment]
I see

```
(base) [13:05:48 varya:~/Documents/huggingface]$ echo "url=https://huggingface.co\nusername=hf_user" | git credential fill
Username for 'https://huggingface.co\nusername=hf_user': BarbaraDefinely
Password for 'https://BarbaraDefinely@huggingface.co\nusername=hf_user': 

```
and the output is 
```
protocol=https
host=huggingface.co\nusername=hf_user
username=BarbaraDefinely
password=*****
```

**Comment by Wauplin** [comment]
Ok, this wasn't expected (maybe a difference between our shells). Could you write:
```
git credential fill
```
then press enter => on the next line (1 line per item), write:
```
url=https://huggingface.co
username=hf_user
```

If it's correctly set, it shouldn't ask for your password. If it does, it means osxkeychain did not store the HF password.

**Comment by banochkabb** [comment]
I did what you said, after I filled credentials I saw 

```
protocol=https
host=huggingface.co
username=hf_user
password=<HF_ACCESS_TOKEN>
```
output in terminal (however, I was not asked to write token anywhere except `huggingface-cli login`). But I still can't clone private repo with the same error: 

`fatal: repository 'https://huggingface.co/spaces/BarbaraDefinely/Summarisation/' not found`

**Comment by Wauplin** [comment]
Thanks for trying. It really seems that the git credentials is well configured.

Could you try using `huggingface_hub` ?
```py
from huggingface_hub import Repository

repo = Repository(local_dir="Summarisation", clone_from="[facebook/wav2vec2-large-960h-lv60](https://huggingface.co/spaces/BarbaraDefinely/Summarisation/)")
```

or using hardcoding directly your password (replacing only the *****):
```
git clone https://hf_user:[******]@huggingface.co/spaces/BarbaraDefinely/Summarisation
```

**Comment by banochkabb** [comment]
@Wauplin Thank you, hardcoded git command worked for me!
