### ISSUE TITLE
Support for Temporal Point Processes / continuous-time sequence models

### ISSUE THREAD

**Issue by mmcdermott** [huggingface/huggingface_hub#1378]
I'm not sure if this is the right place to post this, but I work with medical record datasets, which consist of continuous-time sequences of complex events, with multi-modal structured data recorded in various ways per event. I'd like to use huggingface's infrastructure and API to build and potentially distribute pre-trained generative sequence models for data of this type. Such models would, unlike an NLP sequence model, also need to predict the time until the subsequent event and be capable of representing intra-event dependency logic to reflect the multiple modalities recorded per event. Note that such models would also be examples of multivariate marked temporal point processes. Furthermore, note that such models would have applications beyond healthcare, as data comprised of continuous time streams of events are not uncommon.

I've built a library (https://github.com/mmcdermott/EventStreamML) to adapt the huggingface infrastructure for data of this type and am interested in adding it to the huggingface hub and/or the huggingface ecosystem. However, given that this data modality and task setup is nontrivially different from existing hugginface supported models / architectures, I wanted to reach out to see what the best way to do this is. Naturally, I can just follow [these instructions](https://huggingface.co/docs/hub/models-adding-libraries) to add my existing repository to the hub, but in case there is interest in supporting this kind of modeling task / data modality more formally, I thought I should reach out here first to see if there are any better options.

Some of my concerns are things like: 
1. Task type doesn't align between these models and existing huggingface approaches.
2. Dataset pre-processing for this modality is more involved than tokenization and such in existing models.
3. The generation pipeline for this modality of data differs from that of NLP sequence models.
4. A number of configuration file variables don't apply the models of this type, etc.

Please advise on what the best way to proceed here is, and regardless thank you for providing such a powerful and useful tool for the ML community.

**Comment by Wauplin** [comment]
Hi @mmcdermott , thank you for your kind message :relaxed: Not sure where it's best to post to let's keep the discussion here for now.

The use case seems interesting and legit. I've briefly looked at [EventStreamML](https://github.com/mmcdermott/EventStreamML) but haven't dig too much into details. It seems that the specificities of event stream ML have consequences on quite a lot of parts (datasets, pipelines, inference,...). I guess we'll have to address them 1 by 1. Let's say you _follow these instructions to add your existing repository to the hub_ , what would be your first step? (FYI, there is also [this guide](https://huggingface.co/docs/huggingface_hub/main/en/guides/integrations) for technical guidance)

Let me ping @katielink who's our ML-4-healthcare expert, @lhoestq from the `datasets` team and @kashif who works on timeseries transformers.

**Comment by kashif** [comment]
@mmcdermott so in terms of the time series side we have a schema for representing time series data together with its covariates which as you might know are categorized into the cross product of "static"/"dynamic" and "real-valued"/"categorical", with the caveat that any "dynamic" covariate needs to be known at prediction time.

The time index is then also represented as a "dynamic-real-valued" covariate and thus the models learn the future distribution of the target value conditioned on the prediction time and past.

I believe the schema can be adapted to your usecase. 

Regarding your point 2: indeed the data-processing, feature creating etc. would be done outside of the HF lib. and the models would need to just take the appropriate sequence of vectors for the task at hand. That is not a bad thing, and models exist that do not have any tokenization etc.

Regarding 3, also as you rightly imagined generating can be implemented for the model itself and does not need to rely on the standard NLP based generation techniques like beam search which may or may not even make sense.

I do not understand your point 4, so if you can clarify.

**Comment by lhoestq** [comment]
Also if you want you can use `datasets` instead of `pandas` to load and process the data - this way users will be able to use larger-than-memory datasets (with `datasets` the data is memory mapped from arrow files on disk)

**Comment by mmcdermott** [comment]
@Wauplin and @kashif thanks for the comments! A few responses below:

1. Regarding @lhoestq 's comment, that's a great idea. I'll look into this. My current solution is definitely not fast enough for the scales I intend to handle. Thank you!
2. Regarding @Wauplin's comment re what my first step would be: I think it would be pretty seamless to create a model card and a PR to submit models to the hub -- indeed, the EventStreamTransformer submodule is built to be as inter-operable with HF model conventions as possible, so the configuration objects are subclasses of pre-trained model configs, etc. My concern with this approach would just be that some functionality would have to be missing from these models, as the existing infrastructure lacks some aspects to handle those. Some examples of that are included in my response to @kashif 's comments below regarding this application vs. the traditional timeseries applications.
3. Regarding @kashif 's comment about the TimeSeries schema -- you're right, there is definitely a lot of synergy there. I had looked at that when I started my work but didn't investigate it sufficiently closely, or I would've ensured the configuration / schema between the two settings was more closely aligned. That said, there are some key differences, I think, between the timeseries case and the point process case (which I'm calling EventStream in my code for not necessarily any good reason). In particular, the timeseries API is built (at least, I think it is built for this, but please correct me if I'm mistaken) to handle cases where the timepoints of the future events are known even at inference time. This is not the case in my setting. Instead, in a temporal point process / EventStreamTransformer, the model predicts the time until the next event alongside the event contents for each new event, and there is significant work in the codebase I shared to make this work smoothly in the context of generation. This is also where there needs to be a bit tighter integration with the dataset used for the source data, because some features are not things the model will predict for each new event, but are rather deterministic functions of the time-point at which future events will occur, which is again not known in advance at inference time. So, the configuration object needs to know how to do those calculations given newly generated timepoints. This is a significant complication to the API, but necessary for any real-world point process use case as time-dependent features (such as time-of-day, month-of-year, age-of-subject, etc.) are often quite important. 

Actually, I realize now that in the public release codebase I linked above handling those features during generation isn't included -- I have a private version that we're using for development and some experiments over medical data (hence why it is private) which includes functionality to handle generation in those cases. Either way, that functionality is I think an important distinction between the timeseries case and the point process case. Does that make sense?

3. Regarding @kashif's comment about generating not overlapping with standard NLP based generation techniques, this is true but I actually think there are sufficient similarities between point-process generation and NLP generation to consider closer integration. The way I've set things up, the point process system, much like for NLP, still generates by simply using the past timeseries of events to predict the next event in the sequence. The difference is that this prediction task is much more complicated than it is for NLP, as you need to deal with time-to-event prediction, continuous probabilistic regression and categorical prediction for event contents, time-dependent features that are calculated deterministically given event time, and lastly to account for intra-event dependencies (e.g., generate the time of the next event first, then use that to generate the contents of that event, rather than generating both the time of the next event and the contents of the event independently given the history). However, those complications aside, the ideas of NLP generation still make sense -- e.g., maintaining the top k most likely generated sequences to date and updating that as new events are sampled is still a reasonable strategy. There are other complications, of course (e.g., a greedy decoding strategy actually almost certainly _doesn't_ make sense in my context as some continuous distributions lack modes within their support), but there are also a number of similarities. That said, if the best thing to do is to keep things totally separate, I understand as well.

4. Re @kashif 's question about my point 4, I meant that I'm having my configuration objects subclass from HuggingFace Trasnsformer's PretrainedConfig objects, which brings along with it a number of parameters that don't apply to this use-case, so I'm wondering if there is a better way to do that (e.g., should I not be subclassing that class, should I just ignore the parameters that don't apply, etc.). It is not as big of a concern as the other points.

I should also say that if this area is of interest to the team and this is worth scheduling a call at some point, I'm happy to chat about things that way as well to see what makes sense here. I think supporting this functionality would be valuable to the broader community and want to help with that process as much as I can, even beyond my own interests in integrating this codebase with the Hub.

**Comment by kashif** [comment]
@mmcdermott did you get my slack invite?

**Comment by Wauplin** [comment]
For the record, we started a slack channel to discuss this topic with @mmcdermott. Anyone else reading this message and interested in continuing the discussion, please let us know :)

**Comment by Wauplin** [comment]
I'm closing this issue as the discussion is now continued further over Slack (for quicker iteration). As mentioned before, anyone interested is welcomed :hugs:
