### ISSUE TITLE
When uploading an image to a HF Dataset, don't clone locally

### ISSUE THREAD

**Issue by lakshman111** [huggingface/huggingface_hub#1379]
**Is your feature request related to a problem? Please describe.**
I want to upload images that a user puts into Gradio to a HuggingFace dataset.  Even though I'm just uploading, gradio by default will clone the dataset locally: [https://github.com/huggingface/huggingface_hub/issues/1373#issuecomment-1453106338](https://github.com/huggingface/huggingface_hub/issues/1373#issuecomment-1453106338)

The only code I have uploading:

```
HF_API_TOKEN = os.environ.get("HF_API_TOKEN")
hf_writer = gr.HuggingFaceDatasetSaver(HF_API_TOKEN, "virtual_staging_attempts")

demo = gr.Interface(
fn=make_new_style,
allow_flagging="auto",
flagging_callback=hf_writer,
```

**Describe the solution you'd like**
When I write an image to a HF dataset, only upload it and don't clone it locally (don't 'git pull')

**Describe alternatives you've considered**
Manually deleting images from my machine

**Comment by Wauplin** [comment]
The `HuggingfaceDatasetSaver` has been updated in https://github.com/gradio-app/gradio/pull/3973 to avoid using a local git clone. So it closes this issue as well :)
