### ISSUE TITLE
Detect and track large files automatically

### ISSUE THREAD

**Issue by nreimers** [huggingface/huggingface_hub#138]
When pushing sentence-transformers models to the hub, I had the issue that tokenizers for some multilingual transformers models were creating a unigram.json file that is larger 10 MB. The push to the hub / git resulted in an error, due to the file limit size of 10 MB.

```
remote: -------------------------------------------------------------------------
remote: Your push was rejected because it contains files larger than 10M.
remote: Please use https://git-lfs.github.com/ to store larger files.
remote: -------------------------------------------------------------------------
remote: Offending files:
remote:  - unigram.json (ref: refs/heads/main)
To https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
 ! [remote rejected] main -> main (pre-receive hook declined)
error: Fehler beim Versenden einiger Referenzen nach 'https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2'

```` 

I currently test a fix to detect large files in a repo and to add them to git-lfs before the push:
https://github.com/UKPLab/sentence-transformers/blob/695f12f9a7839e3697957271bbc9108caaf24ca8/sentence_transformers/SentenceTransformer.py#L525

I think this could be relevant for other libraries and also for transformers as well, when someone tries to push tokenizers files that are larger then 10MB.

In the best case, files larger than 10MB should be detected automatically and pushed to git-lfs.

**Comment by julien-c** [comment]
sounds reasonable to me to have this (as an option or by default) in `Repository.push_to_hub` but interested in others' thoughts.

(ideally, not adding the same pattern multiple times if it's already in .gitattributes, etc)

**Comment by cccntu** [comment]
I think this should be the default. The `Repository.push_to_hub` already adds everything with `git_add`, so I think it should also track everything large that it adds.
https://github.com/huggingface/huggingface_hub/blob/0d185de837846859668a0ee5b1aa5ef71a4f9ac4/src/huggingface_hub/repository.py#L452-L460
I think it would make it too complex if I need to pass `what-to-track` into `PretrainedModel.save_pretrained()`.
Users can `add, track, commit` themselves if they don't like to track everything.

**Comment by LysandreJik** [comment]
Fixing this in https://github.com/huggingface/huggingface_hub/pull/177
