### ISSUE TITLE
notebook_login() does not update UI on Databricks

### ISSUE THREAD

**Issue by fwetdb** [huggingface/huggingface_hub#1384]
### Describe the bug

When using the `notebook_login` function on Databricks, the output is not adjusted [when calling `clear_output`](https://github1s.com/huggingface/huggingface_hub/blob/HEAD/src/huggingface_hub/_login.py#L217-L218) because this is not supported on Databricks and there is little chance that it will be supported in the future.

There is an easy fix. The content of the VBox can be adjusted (cleared explicitly) and the subsequent print statements can be appended to the VBox content.

I work for Databricks and I will provide a PR if you signal your willingness to take a look.

What do you think?

### Reproduction

from huggingface_hub import notebook_login

notebook_login()

### System info

```shell
Copy-and-paste the text below in your GitHub issue.

- huggingface_hub version: 0.12.1
- Platform: Linux-5.15.0-1030-aws-x86_64-with-glibc2.35
- Python version: 3.10.6
- Running in iPython ?: Yes
- iPython shell: DatabricksShell
- Running in notebook ?: Yes
- Running in Google Colab ?: No
- Token path ?: /root/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: cache
- FastAI: N/A
- Tensorflow: 2.11.0
- Torch: 1.13.1+cpu
- Jinja2: 2.11.3
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.2.0
- hf_transfer: N/A
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /root/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /root/.cache/huggingface/assets
- HF_HUB_OFFLINE: False
- HF_TOKEN_PATH: /root/.cache/huggingface/token
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by Wauplin** [comment]
Hi @fwetdb, thanks for reporting the issue and proposing your help. The suggested idea makes sense to me. Would you do it only in Databrick notebooks or would that be applied ik any notebook? (Note that I'm not against it if it doesn't change the workflow for the user :) )

**Comment by fwetdb** [comment]
Thank you for the fast feedback! The solution would work for all types of notebooks that support ipywidgets.Sent from mobileOn 9 Mar 2023, at 19:39, Lucain ***@***.***> wrote:﻿
Hi @fwetdb, thanks for reporting the issue and proposing your help. The suggested idea makes sense to me. Would you do it only in Databrick notebooks or would that be applied ik any notebook? (Note that I'm not against it if it doesn't change the workflow for the user :) )

**Comment by Wauplin** [comment]
That's good to know! Yes I think it's a good idea. Would you like to implement it? Thank you in advance!

**Comment by fwetdb** [comment]
Yes, I will go ahead and propose a PR

**Comment by fwetdb** [comment]
I opened a [PR to fix this issue](https://github.com/huggingface/huggingface_hub/pull/1414)
