### ISSUE TITLE
Harmonize attributes returned by `model_info`, `dataset_info` and `space_info`

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1389]
Suggested by @sgugger.

If you do `dir(model_info("albert-base-v1")`, you get:

```
'author',
 'cardData',
 'config',
 'disabled',
 'downloads',
 'gated',
 'id',
 'lastModified',
 'library_name',
 'likes',
 'mask_token',
 'model-index',
 'modelId',
 'pipeline_tag',
 'private',
 'securityStatus',
 'sha',
 'siblings',
 'spaces',
 'tags',
 'transformersInfo',
 'widgetData'
```

which have 3 types of syntax (-, _, and camelCase).

Would be good to harmonize this in a more pythonic way (e.g snake_case). Let's keep both syntax possible for backward compatibility  but only have the snake_case one in __repr__.

**Comment by Wauplin** [comment]
(see also [this comment](https://github.com/huggingface/moon-landing/pull/5681#discussion_r1134159697)  -private link-: we should handle `id` and `modelId` consistently)

**Comment by julien-c** [comment]
that being said i think it's nice to have the same attributes in the Python wrapper as in the actual API
