### ISSUE TITLE
[Feature proposal] Ignore files for snapshot_download

### ISSUE THREAD

**Issue by nreimers** [huggingface/huggingface_hub#139]
I use the `snapshot_download` method to download all model files for sentence-transformers.

@patrickvonplaten converted the transformers models to flax and added them to the respective repository, e.g. for the LaBSE model:
https://huggingface.co/sentence-transformers/LaBSE/tree/main

Right now when you load the LaBSE model with sentence-transformers, the flax_model.msgpack is also downloaded, but never used (only the pytorch files are used).  This adds another 1.8 GB to the download and to the storage requirement. This gets potentially worse if models are converted to further formats, e.g. to tensorflow.

Would it make sense to add a blacklist / whitelist parameter for the `snapshot_download` method? So that you can control which files should be checked out? Potentially also with wildcard, e.g. only download '*.json' and '*.bin' files?

Or do you know a better way how you could determine which files are needed and must be downloaded by your library? For sentence-transformers, the number of files you must download can greatly vary from model to model, i.e. using `cached_download` on a fixed set of files would not be possible.

**Comment by nreimers** [comment]
Drafted a first version that ignores any *.msgpack file:
https://github.com/UKPLab/sentence-transformers/blob/312be2a90a8779daecf9113a319b576588c2ab91/sentence_transformers/util.py#L379

Not yet really happy about the solution, because it will fail if the flax file gets a different extension or when other model types (tensorflow) are added.

**Comment by julien-c** [comment]
> For sentence-transformers, the number of files you must download can greatly vary from model to model

But each model does not know the list of files it needs? (haven't dived into sentence-transformers too much, so I'm curious)

In any case, if required by the use case, a black/whitelist of patterns in `snapshot_download` wouldn't be shocking to me

**Comment by nreimers** [comment]
A sentence-transformers model is like a tree: A model consists of a variable number of sequential modules, and each module can branch to multiple sub-modules (which could again branch).  The setup is quite similar to the functional API from Keras:
https://keras.io/guides/functional_api/

Each layer has its own files. One layer is e.g. AutoModel and AutoTokenizer from transformers. Which files the different tokenizers were saving changed quite significant overtime.

So it is hard to know a-priori which files are needed by the model.

One way could be to create an overview.json file with all the files that belong to the model. Files later added would be ignored. But this would also be quite prone to errors to updates, e.g. when you just update the tokenizer which creates some new (required) files.

**Comment by julien-c** [comment]
Thanks for the explanation. yes it is very similar to what AllenNLP is doing if I understand correctly
