### ISSUE TITLE
resumable download and file integration check

### ISSUE THREAD

**Issue by guoyk93** [huggingface/huggingface_hub#1396]
**Is your feature request related to a problem? Please describe.**

Once download failed, corrupted data files will left and folow up download attemptations will fail definitely, unless cached directores are manually deleted

For example:

```
RuntimeError: self.size(-1) must be divisible by 4 to view Byte as Float (different element sizes), but got 702038
```

These things happend again and again

**Describe the solution you'd like**

I hope huggingface_hub cound do file integration check and resume download from where interrupted

**Describe alternatives you've considered**

**Additional context**

**Comment by guoyk93** [comment]
And, **Please** use **relative** soft link in local cache directory `~/.cache/huggingface/hub/xxxxxx/snapshots/xxxxx/`

**Comment by Wauplin** [comment]
Hi @guoyk93 , thanks for reporting this issue. Can you give me an example of script you are using? In particular, are you using `resume_download=True` in `hf_hub_download`? Can you also provide a bigger traceback and context about the setup you have (by running `huggingface-cli env`).

> And, Please use relative soft link in local cache directory

About that, can you explain a bit more what you find problematic with the current symlinks and why you think it should be changed?

**Comment by guoyk93** [comment]
```python
import sys

import torch

from diffusers import StableDiffusionPipeline

model, cached_dir = StableDiffusionPipeline.from_pretrained(
    sys.argv[1],
    torch_dtype=torch.float16,
    resume_download=True,
    return_cached_folder=True,
)

print("cached to: " + cached_dir)
```

Error stack trace

```text
Fetching 15 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 38037.82it/s]
Traceback (most recent call last):
  File "/home/xxxxxx/Developer/src/gitee.com/xxxxxx-net/_deprecated/sd-scripts/models/diffusers-model-cache.py", line 7, in <module>
    model, cached_dir = StableDiffusionPipeline.from_pretrained(
  File "/home/xxxxxx/Developer/src/gitee.com/xxxxxx-net/lora-webui/venv/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 944, in from_pretrained
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/home/xxxxxx/Developer/src/gitee.com/xxxxxx-net/lora-webui/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2429, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/home/xxxxxx/Developer/src/gitee.com/xxxxxx-net/lora-webui/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 413, in load_state_dict
    return safe_load_file(checkpoint_file)
  File "/home/xxxxxx/Developer/src/gitee.com/xxxxxx-net/lora-webui/venv/lib/python3.10/site-packages/safetensors/torch.py", line 101, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: self.size(-1) must be divisible by 4 to view Byte as Float (different element sizes), but got 6053826
```

Specific exceptions will vary, but delete the cache directory and re-download should fix it.

---

As to symlinks, using relative symlinks can make the whole cache directory portable (for example, backup to NAS and restored to home directory of another user on another computer).

Currently, it is not possible to do this because symlinks are absolute

Current:

```text
~/.cache/huggingface/hub/models--andite--anything-v4.0/snapshots/c1527fac4734bb170c60138bb79ac3a1c9262848/
  model_index.json -> /home/myusername/.cache/huggingface/hub/models--andite--anything-v4.0/blobs/20eb64902de8a63eb8759c1467281b19cc70689b
```

Expectation:

```text
~/.cache/huggingface/hub/models--andite--anything-v4.0/snapshots/c1527fac4734bb170c60138bb79ac3a1c9262848/
  model_index.json -> ../../models--andite--anything-v4.0/blobs/20eb64902de8a63eb8759c1467281b19cc70689b
```

**Comment by Wauplin** [comment]
Thanks for your input! I'll not have time today to investigate it but I'll keep you updated next week.

About relative symlinks, I get your point. I'll see what we can do (it has been changed to absolute links quite recently)

**Comment by guoyk93** [comment]
@Wauplin Thanks a lot

**Comment by Wauplin** [comment]
@guoyk93 I reverted back to use relative symlinks in the cache in huggingface `0.13.3` (as it was causing other issues). See [release notes](https://github.com/huggingface/huggingface_hub/releases/tag/v0.13.3).

About the resumable download, I'll have a look this week.

**Comment by Wauplin** [comment]
@guoyk93 I don't know what could have happened when you experienced this issue. Just in case it happens again for another user, I opened [this PR](https://github.com/huggingface/huggingface_hub/pull/1403) to raise an exception if the downloaded file doesn't have the expected size. If the error is reported more often, we will put more effort to track it down (for context, resume_download has been there for a few years now without any user reporting. So before investing too much time trying to reproduce it, I'd prefer to have more feedback). 

In the meantime, I hope you've been able to work correctly :)

**Comment by guoyk93** [comment]
@Wauplin I'm not sure, my network is not good, so I often Ctrl+C when it takes too long to download. And follow up tries will keep raising exceptions, as mentioned above.

Thanks for your responding.

**Comment by Wauplin** [comment]
@guoyk93 I'm sorry you are still experiencing issues :confused: Even when doing Ctrl+C in the middle of a download, it shouldn't corrupt the downloaded files in the end. At least I am not able to reproduce the error even though I Ctrl+C+restart 10 times on the same file.

_Maybe_ the problem is elsewhere. Could you try to list all cached files + their size + their size on the Hub. If there is a discrepancy, we should be able to see it. Something like this script should work for you:

```py
from pathlib import Path
from huggingface_hub import get_hf_file_metadata, hf_hub_url
from huggingface_hub.constants import HUGGINGFACE_HUB_CACHE

model_id = "andite/anything-v4.0"
snapshot_path = (
    Path(HUGGINGFACE_HUB_CACHE)
    / "models--andite--anything-v4.0"
    / "snapshots"
    / "45660379eaed07da4a059eb655ee37b70c575ae7"
)

for file in snapshot_path.glob("**/*"):
    if file.is_file():
        filename = file.relative_to(snapshot_path)
        metadata = get_hf_file_metadata(hf_hub_url(repo_id=model_id, filename=str(filename)))

        print()
        print("file    :", file)
        print("size    :", file.stat().st_size)
        print("expected:", metadata.size)
```

**Comment by guoyk93** [comment]
@Wauplin 

I see a lot of incorrect size.

It seems that every time I press Ctrl+C, the next time it will treat the unfinished file as a downloaded file and go to download other remaining files.

I think adding a file size check is enough to deal with this problem for now.

I will update to newer version of `diffusers` and `huggingface_hub` once released.

And don't worry, I have been using the tools I developed myself during this time, using Github Workflow to download models from `huggingface`, package in `tar`, upload files to aliyun oss (s3 bucket-like service) near my city, and then download them to local folder. It's surprisingly quite handy 🤣.

```
/home/myusername/.cache/huggingface/hub/models--andite--anything-v4.0/snapshots/c1527fac4734bb170c60138bb79ac3a1c9262848

file    : /home/myusername/.cache/huggingface/hub/models--andite--anything-v4.0/snapshots/c1527fac4734bb170c60138bb79ac3a1c9262848/model_index.json
size    : 584
expected: 584

file    : /home/myusername/.cache/huggingface/hub/models--andite--anything-v4.0/snapshots/c1527fac4734bb170c60138bb79ac3a1c9262848/vae/diffusion_pytorch_model.safetensors
size    : 826642
expected: 334643276

file    : /home/myusername/.cache/huggingface/hub/models--andite--anything-v4.0/snapshots/c1527fac4734bb170c60138bb79ac3a1c9262848/vae/config.json
size    : 582
expected: 582

file    : /home/myusername/.cache/huggingface/hub/models--andite--anything-v4.0/snapshots/c1527fac4734bb170c60138bb79ac3a1c9262848/text_encoder/config.json
size    : 617
expected: 617

file    : /home/myusername/.cache/huggingface/hub/models--andite--anything-v4.0/snapshots/c1527fac4734bb170c60138bb79ac3a1c9262848/text_encoder/model.safetensors
size    : 6314324
expected: 492265874

file    : /home/myusername/.cache/huggingface/hub/models--andite--anything-v4.0/snapshots/c1527fac4734bb170c60138bb79ac3a1c9262848/tokenizer/special_tokens_map.json
size    : 472
expected: 472

file    : /home/myusername/.cache/huggingface/hub/models--andite--anything-v4.0/snapshots/c1527fac4734bb170c60138bb79ac3a1c9262848/tokenizer/merges.txt
size    : 524619
expected: 524619

file    : /home/myusername/.cache/huggingface/hub/models--andite--anything-v4.0/snapshots/c1527fac4734bb170c60138bb79ac3a1c9262848/tokenizer/vocab.json
size    : 1059962
expected: 1059962

file    : /home/myusername/.cache/huggingface/hub/models--andite--anything-v4.0/snapshots/c1527fac4734bb170c60138bb79ac3a1c9262848/tokenizer/tokenizer_config.json
size    : 806
expected: 806

file    : /home/myusername/.cache/huggingface/hub/models--andite--anything-v4.0/snapshots/c1527fac4734bb170c60138bb79ac3a1c9262848/unet/diffusion_pytorch_model.safetensors
size    : 1892598991
expected: 3438167540

file    : /home/myusername/.cache/huggingface/hub/models--andite--anything-v4.0/snapshots/c1527fac4734bb170c60138bb79ac3a1c9262848/unet/config.json
size    : 1021
expected: 1021

file    : /home/myusername/.cache/huggingface/hub/models--andite--anything-v4.0/snapshots/c1527fac4734bb170c60138bb79ac3a1c9262848/feature_extractor/preprocessor_config.json
size    : 520
expected: 520

file    : /home/myusername/.cache/huggingface/hub/models--andite--anything-v4.0/snapshots/c1527fac4734bb170c60138bb79ac3a1c9262848/safety_checker/config.json
size    : 4905
expected: 4905

file    : /home/myusername/.cache/huggingface/hub/models--andite--anything-v4.0/snapshots/c1527fac4734bb170c60138bb79ac3a1c9262848/safety_checker/model.safetensors
size    : 899170405
expected: 1215981830

file    : /home/myusername/.cache/huggingface/hub/models--andite--anything-v4.0/snapshots/c1527fac4734bb170c60138bb79ac3a1c9262848/scheduler/scheduler_config.json
size    : 346
expected: 346
```

**Comment by guoyk93** [comment]
I'm closing this issue, and discuss at PR #1403

Thanks 😊
