### ISSUE TITLE
keeps saying "remote: Your push was rejected because it contains binary files." after I deleted that file

### ISSUE THREAD

**Issue by stunlocked1** [huggingface/huggingface_hub#1404]
### Describe the bug

The thing is, I have long deleted the offending file, and it still says that whenever I try to push. It says 

remote: Offending files:        
remote:  - stuff/example1_detection_test.mp3 (ref: refs/heads/main)  

but I deleted that file, it doesn't exist anymore. Why does it keep saying that. I tried restarting vscode and it doesn't help.

### Reproduction

Force push binary file
it says no
delete binary file
it still says this file exists and is offensive

### Logs

```shell
2023-03-22 17:50:58.987 [info] > git push --force-with-lease hug main [8969ms]
2023-03-22 17:50:58.987 [info] remote: -------------------------------------------------------------------------        
remote: Your push was rejected because it contains binary files.        
remote: Please use https://git-lfs.github.com/ to store binary files.        
remote: See also: https://hf.co/docs/hub/repositories-getting-started#terminal        
remote: -------------------------------------------------------------------------        
remote: Offending files:        
remote:  - stuff/example1_detection_test.mp3 (ref: refs/heads/main)        
To https://huggingface.co/spaces/superman/myspace1
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://huggingface.co/spaces/superman/myspace1'
2023-03-22 17:50:59.053 [info] > git config --get commit.template [59ms]
2023-03-22 17:50:59.062 [info] > git for-each-ref --format=%(refname)%00%(upstream:short)%00%(objectname)%00%(upstream:track)%00%(upstream:remotename)%00%(upstream:remoteref) refs/heads/main refs/remotes/main [60ms]
2023-03-22 17:50:59.132 [info] > git status -z -uall [63ms]
```

### System info

```shell
usage: huggingface-cli <command> [<args>]
huggingface-cli: error: argument {login,whoami,logout,repo,lfs-enable-largefiles,lfs-multipart-upload,scan-cache,delete-cache}: invalid choice: 'env' (choose from 'login', 'whoami', 'logout', 'repo', 'lfs-enable-largefiles', 'lfs-multipart-upload', 'scan-cache', 'delete-cache')
```

**Comment by Wauplin** [comment]
It seems to be more a `git` problem than an issue in `huggingface_hub`.

When you say you deleted the binary file, what do you mean by that? Did you deleted the failing commit or just created another commit on top of it? When doing `git push`, it will push all the local commits that are not yet on remote.

If it's not that, could you copy-paste the output of `git status` and `git log`?

**Comment by stunlocked1** [comment]
> It seems to be more a `git` problem than an issue in `huggingface_hub`.
> 
> When you say you deleted the binary file, what do you mean by that? Did you deleted the failing commit or just created another commit on top of it? When doing `git push`, it will push all the local commits that are not yet on remote.
> 
> If it's not that, could you copy-paste the output of `git status` and `git log`?

idk i was using vs code. I just deleted the file from windows file explorer. And now I am trying to do force push through vscode and it doesn't work
```
git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```
but thats because it is set to a github repo and idk how to change it but i was using vscodes push (force) to upload on hugging face.

**Comment by Wauplin** [comment]
@stunlocked1 I think git-lfs is not installed or not configured correctly on your machine. If you look at the first message you posted you can see

```
remote: Please use https://git-lfs.github.com/ to store binary files.        
remote: See also: https://hf.co/docs/hub/repositories-getting-started#terminal   
```

So I would advice you to follow this guide to get started: https://huggingface.co/docs/hub/repositories-getting-started#terminal

**Comment by stunlocked1** [comment]
> @stunlocked1 I think git-lfs is not installed or not configured correctly on your machine. If you look at the first message you posted you can see
> 
> ```
> remote: Please use https://git-lfs.github.com/ to store binary files.        
> remote: See also: https://hf.co/docs/hub/repositories-getting-started#terminal   
> ```
> 
> So I would advice you to follow this guide to get started: https://huggingface.co/docs/hub/repositories-getting-started#terminal

I ran the command
```
>git lfs install
Updated Git hooks.
Git LFS initialized.
```
unfortunately didn't fix the issue, still says there is a binary file even though I deleted that file 5 days ago

**Comment by Wauplin** [comment]
I'm sorry but it's quite hard to know where the issue comes from.

> still says there is a binary file even though I deleted that file 5 days ago.

I am pretty sure that you deleted the file 5 days ago but before that a commit has been created with the file in it. When pushing to HF repo, all the commits are pushed including the one with the .mp3 file. Said otherwise, I think you have a git history that looks like this:

```
Latest commit: monkey
commit sandstone
commit
commit "remove mp3" <- another commit to delete the .mp3 file
commit
commit
commit "add mp3" <- commit to add the .mp3 files
commit
...
```

HF rejects your push because you are not only pushing the latest commit but also all the previous one.
If you don't care about your git history, what you can do is to reset it completely:

* either by squashing all the commits into a single one. See https://stackoverflow.com/a/23486788 to understand what it's doing.
```
git reset $(git commit-tree HEAD^{tree} -m "A new start")
```
* either by deleting the `.git/` folder. **Warning: you loose all the git config/history.** Make sure that's fine for you before doing it. You'll need to re-configure the github and huggingface remote urls.

**Comment by Wauplin** [comment]
I'm closing this issue as it's not `huggingface_hub` related and got no replies in 3 weeks.

**Comment by ceteri** [comment]
It appears to be a `huggingface_hub` problem, i.e., in terms of the pre-receive hooks configuration.

We have a similar case where a file grew to a slightly larger size, and then the `push was rejected because it contains binary files` issue emerged.

Note that `git-lfs` had been installed and configured per the HF docs.

The file was a compressed XML, needed for generating online docs.

After removing the file, and ~6 commits later, any push to HF continues to fail. Tried squashing all the commits into a single one, but the push still fails.

Question: **Is there any way to clear the commit history on a HF git repo?**

Otherwise we'll probably need to delete the Space and start over.

Thank you.

---

```
$ git log
commit 29cbc4fcafca32e15d224693d90cb54f3495c156 (HEAD -> main)
Author: Paco Nathan <XXXXXXX@gmail.com>
Date:   Thu Feb 15 10:01:32 2024 -0800

    A new start
```

**Comment by Wauplin** [comment]
Hi @ceteri, [`super_squash_history`](https://huggingface.co/docs/huggingface_hub/v0.20.3/en/package_reference/hf_api#huggingface_hub.HfApi.super_squash_history) might help you in this case. However, simply force-pushing the local history to the Hub (with a single commit) should also work. If it's not the case, it might be that a binary file is still not tracked as LFS locally.

**Comment by ceteri** [comment]
Thank you kindly @Wauplin, the force push fixed this.

I also made sure to track the file explicitly in LFS locally.
FWIW, its size is only 1.3M

**Comment by Wauplin** [comment]
Great! Glad to hear your problem's solved :)

**Comment by LeoBorai** [comment]
Similar issue, ended up squashing all commits to the very first one using `git reset --soft <VERY FIRST COMMIT>` and then push with _force_ mode.

Seems to me that the Git snapshots contains the long file in history, and at the moment of uploading these snapshots HuggingFace complains about it with the LFS suggestion.

**Comment by LeoBorai** [comment]
In my case the large file was a dataset, so I think best practice is moving that dataset to a Database Repo in Hugging Face (as Im uploading in a Space) and then pull it via HF API.
