### ISSUE TITLE
Huggingface space python version

### ISSUE THREAD

**Issue by Kashif-Raza6** [huggingface/huggingface_hub#1409]
How to install python specific version on huggingface spaces rather than by default?

**Comment by Wauplin** [comment]
Hi @Kashif-Raza6, you can set `python_version` in the README.md metadata section: https://huggingface.co/docs/hub/spaces-config-reference. Default is `3.8.9`. Hope this helps! :)

**Comment by Wauplin** [comment]
I'm closing this issue but feel free to open the topic again if needed.

**Comment by Shoaib-33** [comment]
altair==4.2.2
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz#sha256=06c80936324012d1223291d2af41a5229e746dc2dee8fe31a532666ee3d18aaa

gTTS==2.3.2

h5py==3.9.0



matplotlib==3.7.1

newspaper3k==0.2.8

nltk==3.8.1
numpy==1.23.5

pandas==2.1.0

googletrans==4.0.0rc1


scikit-learn==1.3.0

streamlit==1.22.0

tensorboard==2.12.3

tensorflow==2.12.0

textblob==0.17.1

wordcloud==1.9.2

yake==0.4.8

I am using this in my requirements.txt and also using python version 3.9.17 the same one I used for this locally but when i am deploying in huggingface space it is saying no module named "Newspaper" whereas it is already present in requirements.txt. How can i solve this issue??
