### ISSUE TITLE
Document `metadate_update` in model cards guide

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1448]
_Originally [on Slack](https://huggingface.slack.com/archives/C02EMARJ65P/p1681845146581649?thread_ts=1681835326.152219&cid=C02EMARJ65P) by @osanseviero (private link):_

```python
from huggingface_hub import metadata_update

for repo_id in repo_ids:
    metadata = {"pipeline_tag": "image-classification"}
    metadata_update(repo_id, metadata, overwrite=True, create_pr=True)
```

Btw @Wauplin maybe this should be documented in https://huggingface.co/docs/huggingface_hub/v0.13.4/en/guides/model-cards too as an option

**Comment by kunjshukla** [comment]
Hey There, I would like to contribute in this issue. Please can you assign me.

**Comment by Wauplin** [comment]
Hi @kunjshukla , thank you for proposing your help! :heart: 
I assigned the issue to you. Please let me know if you have any question regarding the task :)

**Comment by sifisKoen** [comment]
@Wauplin hey dude can you explain more this issue? And what do you want to be done :smile:

**Comment by Wauplin** [comment]
Hi @sifisKoen, agree this issue is not well documented :grin:  

It is about documenting the fact that we have multiple ways to handle modelcards with `huggingface_hub`. The most feature-complete way is to use `ModelCard` class as described [in this guide.](https://huggingface.co/docs/huggingface_hub/main/en/guides/model-cards). But we also have a quick and handy [`metadata_update`](https://huggingface.co/docs/huggingface_hub/main/en/package_reference/cards#huggingface_hub.metadata_update) helper that does the process of loading a modelcard from the Hub, updating its metadata and pushing it back on the Hub.

What I would do for this issue is to add a section in [modelcards.md](https://github.com/huggingface/huggingface_hub/blob/main/docs/source/en/guides/model-cards.md) docs explaining what metadata are and how to use `update_metadata`. Maybe having a "normal" example 
(something like `metadata_update(repo_id, {"pipeline_tag": "image-classification"})`, followed by an example with `overwrite=True` (to overwrite an existing field), followed by an example with `create_pr=True` (allowing to suggest a modification on a repo you don't own).

What do you think about it?

**Comment by sifisKoen** [comment]
Ok so you need to expand the [modelcards.md](https://github.com/huggingface/huggingface_hub/blob/main/docs/source/en/guides/model-cards.md) a documentation for this functionality of changing the metadata. 
- First, what is Metadata in this case and where it's using.
> For example: In the ModelCard context the metadata refers a hash map (or key value) context witch provides high-level information about the user's model. Those information can include details such as model's pipeline type, model_id or model_description. (Should I include all the metadata that you mention in the documentation?) [here](https://huggingface.co/docs/huggingface_hub/main/en/guides/model-cards#share-model-cards)
(
- Then I will include some examples as you said.
(I don't know if I need to include the import part in the examples.) I think the user should include `from huggingface_hub import card.data`

### Basic update
```python
repo_id = "User's repo id"
metadata_update(repo_id, {"pipeline_tag": "image-classification"})
```
This example will update (or will add, of not existing) the `pipeline_tag` metadata to the `image-classification`.


### Overwrite existing Fields
```python
metadata_update(repo_id, {"pipeline_tag": "text-generation"}, overwrite=True)
```
With the `overwrite=True` field, even if the `pipeline_tag` field exists, it will be update to the new value. (It will over write the field)

### Propose Metadata updates on Repositories the user doesn't own
```python
metadata_update(repo_id, {"pipeline_tag": "text-classification"}, create_pr=True)
```
If a user wants to suggest a change to a repository witch belongs to other user, can use simply the `create_pr=True` filed. This will create a pull request on the model repository, witch will allow the owner of this repository to review and merge the suggestions if approve them.

@Wauplin hey dude let me know if this is good enough for you, and if I understood correctly what I need to do. I will have a new local branch in my laptop ready for a PR if everything is ok and ready to go. :smile:

**Comment by Wauplin** [comment]
@sifisKoen This looks good to me yes! Please open the PR and I'll make small comments on it directly so that we can iterate on the phrasing if needed (although it's already good :) ). For specific questions:

> First, what is Metadata in this case, and where is it used?

In addition to your explanation, I would also link to these guides about metadata: [Model Card](https://huggingface.co/docs/hub/model-cards#model-card-metadata), [Dataset Card](https://huggingface.co/docs/hub/datasets-cards#dataset-card-metadata) and [Space Settings](https://huggingface.co/docs/hub/spaces-settings#spaces-settings)

> I don't know if I need to include the import part in the examples.

It's usually best to add the import part so that each example is usable on its own. It's not a strict rule though if you feel it's too redundant on the page.

> Instead, "a user" change it to "you" where it needs to be.

Usually we use a casual tone with a "you" where appropriate.

**Comment by sifisKoen** [comment]
@Wauplin hey dude I made the PR for documentation. It's ready for review. :smile:

**Comment by Wauplin** [comment]
Thanks @sifisKoen ! I reviewed and merged it!

Closing this issue as part of https://github.com/huggingface/huggingface_hub/pull/1631.
