### ISSUE TITLE
InferenceAPI: sleep and loop if `wait_for_model=True` 

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1454]
if `wait_for_model=True` and server returns "model loading try again later", we should sleep and try again later (and still hang for the user). At the moment an error is raised.

Originally requested by @sgugger on slack.

---

**EDIT:** actually it might be worth sending `wait_for_model=False` and looping so that we can log to the user that it's loading.

**Comment by osanseviero** [comment]
> if wait_for_model=True and server returns "model loading try again later", we should sleep and try again later (and still hang for the user). At the moment an error is raised.

This sounds like a bug. If `wait_for_model=True`, then the server should not respond until the model is loaded. Docs from API
> (Default: false) Boolean. If the model is not ready, wait for it instead of receiving 503. It limits the number of requests required to get your inference done. It is advised to only set this flag to true after receiving a 503 error as it will limit hanging in your application to known places.

In the JS widgets on the Hub, we do a first request with `wait_for_model=False`, and if we get a model loading error (503), we do a second request with `wait_for_model=True`.

**Comment by sgugger** [comment]
> This sounds like a bug. If wait_for_model=True, then the server should not respond until the model is loaded. Docs from API

This was happening all day yesteday and has been fixed now. Depending on how often that bug can happen, I think it doesn't hurt if `InferenceApi` adds a layer of safety on top of the actual inference API.

**Comment by sgugger** [comment]
No the response was immediate with "Model loading, try again in 20s" (or something like that).

**Comment by Narsil** [comment]
Oh that must mean the query was not properly issued, or something dropped the information somewhere (if the thing is passed through headers, maybe some component could drop it).

Anyway I could reproduce simply ?

**Comment by sgugger** [comment]
> This was happening all day yesteday and has been fixed now.

**Comment by Narsil** [comment]
We didn't make any change.... this is peculiar...

**Comment by Wauplin** [comment]
Probably won't fix as `InferenceClient` is now replacing `InferenceAPI` as the preferred client in `huggingface_hub`. Regarding timeouts and retries, it's handled differently now (including client-side retries) and should solves this issue (though we don't have a reproducible example).
[See timeout docs](https://huggingface.co/docs/huggingface_hub/guides/inference#timeout) for some details.

**Comment by aosama** [comment]
Newbie getting started, The deploy server less Inference button on upper right of model page,  produces the below code snippets which replies with "model loading" as below. it doesn't respect the "wait_for_model": True parameter in the JSON. which led me to this thread here. would be great to have the getting started code accessible from the deploy "server less" button

{'error': 'Model microsoft/Phi-3-mini-128k-instruct is currently loading', 'estimated_time': 305.6863708496094}


import requests

API_URL = "https://api-inference.huggingface.co/models/microsoft/Phi-3-mini-128k-instruct"
headers = {"Authorization": "Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}

def query(payload):
	response = requests.post(API_URL, headers=headers, json=payload)
	return response.json()
	
output = query({
	"inputs": "Can you please let us know more details about your ",
})
