### ISSUE TITLE
Handle hardware, storage, secrets and variables when creating or duplicating repos

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1457]
With the new reworked duplicate modal, one can set both hardware, storage, secrets and variables directly when duplicating a Space. We should reflect that in `huggingface_hub`. See https://github.com/huggingface/moon-landing/pull/6159 (internal link).

cc @SBrandeis 

---

Requested features in this issue can be implemented in separate PRs if it makes it easier.
- [x] handle hardware + sleep_time in `duplicate_repo`
- [x] handle hardware + sleep_time in `create_repo`
- [x] handle storage in `duplicate_repo`
- [x] handle storage in `create_repo`
- [x] handle secrets + variables in `duplicate_repo`
- [x] handle secrets + variables in `create_repo`

**EDIT:** everything got implemented in https://github.com/huggingface/huggingface_hub/pull/1625 by @martinbrose !

--- 

The idea is to extend the `duplicate_space` method in [hf_api.py](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/hf_api.py). Currently, `repository` and `private` parameters are sent in the payload. New parameters should be supported as well:
- `hardware`: used to request hardware for the duplicated Space. Must be of type `SpaceHardware`.
- `storageTier`: used to request persistent storage for the duplicated Space. Must be of type `SpaceStorage` (see https://github.com/huggingface/huggingface_hub/issues/1553)
- `sleepTimeSeconds`: set a custom sleep time if  upgraded hardware is used. Must be of type `int`. See `set_space_sleep_time` method as an example.
- `secrets`: list of secrets to set on the Space
- `variables`: list of variables to set on the Space

For secrets and variables, input type must be `List[Dict[str, str]]`. For each secret/variable, `key` and `value` are mandatory. A third item `description` is optional. Example: `[{"key": "MY_SECRET_KEY_1", "value": "MY_SECRET_VALUE_1"}, {"key": ..., "value": ..., "description": "This is a description."}, ...]`. Description is then displayed in the UI for a better user experience.

By default, all parameters are `Optional` in Python with default value `None`. Value must be sent in json payload only if not None.

Once implemented, tests must be added to `HfApiDuplicateSpaceTest` class (in [test_hf_api.py](https://github.com/huggingface/huggingface_hub/blob/main/tests/test_hf_api.py)). 1 test for hardware + sleep_time , 1 test for storage and 1 test for secrets + variables should be enough. 

---

Similarly to the duplicate endpoint, config values like hardware, storage, sleep time, secrets and variables should be supported on the `create_repo` endpoint. Requirements are exactly the same as above.

**Comment by martinbrose** [comment]
@Wauplin, I think this can be closed now?

**Comment by Wauplin** [comment]
Yes indeed! Closing as part of https://github.com/huggingface/huggingface_hub/pull/1625. Thanks for noticing :)
