### ISSUE TITLE
HTTP error 404 during installation

### ISSUE THREAD

**Issue by JisuHann** [huggingface/huggingface_hub#1459]
### Describe the bug

Hi. I was trying to install hugging face_hub repository, but somehow the installation not works, and I think this is because there is no URL matched with the program. 

I tried `pip install huggingface-hub` on the condo environment, and the error message is shown as follows:

> Looking in indexes: http://ftp.daumkakao.com/pypi/simple
> Collecting huggingface-hub
>   ERROR: HTTP error 404 while getting http://mirror.kakao.com/pypi/packages/55/4c/eea4460e8da50ce16465615126ce013b8024346a28eae3a0a0e36027cdef/huggingface_hub-0.14.0-py3-none-any.whl#sha256=fa6a6139fe4a8a164bfd0cda90c225fe8471b47c12811738b6db8348a2f703a0 (from http://mirror.kakao.com/pypi/simple/huggingface-hub/) (requires-python:>=3.7.0)
> ERROR: Could not install requirement huggingface-hub from http://mirror.kakao.com/pypi/packages/55/4c/eea4460e8da50ce16465615126ce013b8024346a28eae3a0a0e36027cdef/huggingface_hub-0.14.0-py3-none-any.whl#sha256=fa6a6139fe4a8a164bfd0cda90c225fe8471b47c12811738b6db8348a2f703a0 because of HTTP error 404 Client Error: Not Found for url: http://mirror.kakao.com/pypi/packages/55/4c/eea4460e8da50ce16465615126ce013b8024346a28eae3a0a0e36027cdef/huggingface_hub-0.14.0-py3-none-any.whl for URL http://mirror.kakao.com/pypi/packages/55/4c/eea4460e8da50ce16465615126ce013b8024346a28eae3a0a0e36027cdef/huggingface_hub-0.14.0-py3-none-any.whl#sha256=fa6a6139fe4a8a164bfd0cda90c225fe8471b47c12811738b6db8348a2f703a0 (from http://mirror.kakao.com/pypi/simple/huggingface-hub/) (requires-python:>=3.7.0)

Are there some solutions to debug this?

### Reproduction

Just typed `pip install huggingface-hub` on conda environment.

### System info

```shell
- Platform: 'Linux-5.19.0-41-generic-x86_64-with-glibc2.10'
- Python version: 3.8.13
```

**Comment by Wauplin** [comment]
Hi @JisuHann, the package in named `huggingface_hub` (note the _ instead of -). So

```
pip install huggingface_hub
```

will solve your problem:)

**Comment by Wauplin** [comment]
Here is a short installation guide if you have more questions: https://huggingface.co/docs/huggingface_hub/installation. 

I'm closing this issue but feel free to re-open if you're still struggling with it.
