### ISSUE TITLE
Download files by SHA256

### ISSUE THREAD

**Issue by VivekPanyam** [huggingface/huggingface_hub#1470]
**Is your feature request related to a problem? Please describe.**

For a project I'm working on, it would be useful to download files by SHA256. [`hf_hub_url`](https://huggingface.co/docs/huggingface_hub/v0.14.1/en/package_reference/file_download#huggingface_hub.hf_hub_url) currently requires a `repo_id` and `filename`. The URL it generates is of the form `https://huggingface.co/{repo_id}/resolve/{branch}/{filename}`

**Describe the solution you'd like**
According to the docs, LFS data is stored in a content addressable way so it would be great if there was a resolve endpoint that only required sha256 (e.g. `https://huggingface.co/resolve/sha256/{some_sha_256}`)

Would this be possible to implement? Thank you!

**Comment by julien-c** [comment]
there's probably a way to do it with the current APIs (maybe in two HTTP calls), but out of curiosity, what's the use case?

**Comment by VivekPanyam** [comment]
> there's probably a way to do it with the current APIs (maybe in two HTTP calls)

Thanks for the response! Do you have more details on how that would work?

A component of a library I'm working on packages ML and DL models into another format on disk. Instead of storing a copy of the weights, it may be preferable to store a link to them so they can be downloaded if needed (useful for cases that only need model metadata). For most public models, there's a decently high likelihood that the weights will be on HF, but I don't know the corresponding repo/branch at packaging time. That's why it would be helpful to resolve files by sha256.

**Comment by Wauplin** [comment]
Hi @VivekPanyam IMO this is not a feature we support currently. LFS files are stored "per repo" meaning that even if 2 repos have the same LFS file, we will store them twice. To support your use case we should create a special `/resolve` endpoint accepting only a sha256 and no repo_id/repo_type but I don't think this will be on our roadmap (cc @julien-c)

Just FYI, let's say you have this LFS file:
- repo_id: `allenai/nllb`
- repo_type: `datasets`
- filepath: `/dummy/ace_Latn-ban_Latn/1.0.0/dummy_data.zip`
- revision: `main`
- sha256: `6d3271cf0f9cd9398f375d801538058b416c63d5784ad500fb4f7d0df468d7f8`
- Browser URL: https://huggingface.co/datasets/allenai/nllb/blob/main/dummy/ace_Latn-ban_Latn/1.0.0/dummy_data.zip
- Resolve URL (to download): https://huggingface.co/datasets/allenai/nllb/resolve/main/dummy/ace_Latn-ban_Latn/1.0.0/dummy_data.zip
- Resolved URL (once redirected): https://cdn-lfs.huggingface.co/repos/39/84/39840492c0ef4057866a224d6d8dd7ff6a4bc08519f11cd15dcf9fd5f7c5e370/6d3271cf0f9cd9398f375d801538058b416c63d5784ad500fb4f7d0df468d7f8?....

**Comment by julien-c** [comment]
i think @VivekPanyam still has access to the repo_id/repo_type, just not the filename, is my understanding correct?

**Comment by VivekPanyam** [comment]
@julien-c Unfortunately, I don't have access to the repo_id/repo_type. All I have is the sha256 of the file.

@Wauplin how much effort do you think it would be to create that endpoint? I'd assume the db backing the current `resolve` endpoint already contains all LFS files and their sha256s.

Thanks!

**Comment by julien-c** [comment]
Ah ok, then no, unfortunately we don't have this

**Comment by happypigzy** [comment]
I have a related question, when I download a file from https://huggingface.co/{repo_id}/resolve/{branch}/{filename} using some download tools, how can I verify the download file is ok or broken. Concretely, how can I know the hub's file MD5SUM value, it's possible?

**Comment by happypigzy** [comment]
I have tried this code
```
from huggingface_hub import model_info
model_info("lmsys/vicuna-7b-delta-v1.1", revision="main")
```
but I get returns
```
ModelInfo: { 
  {'_id': '643630447e07c5aee23ad30e',
   'author': 'lmsys',
   'cardData': {'inference': False, 'license': 'apache-2.0'},
   'config': {'architectures': ['LlamaForCausalLM'], 'model_type': 'llama'},
   'disabled': False,
   'downloads': 22700,
   'gated': False,
   'id': 'lmsys/vicuna-7b-delta-v1.1',
   'lastModified': '2023-04-29T23:01:59.000Z',
   'library_name': 'transformers',
   'likes': 154,
   'model-index': None,
   'modelId': 'lmsys/vicuna-7b-delta-v1.1',
   'pipeline_tag': 'text-generation',
   'private': False,
   'securityStatus': None,
   'sha': '981921c2f3815acee666973b05628c3f3d0bc7a4',
   'siblings': [RepoFile: {'blob_id': None, 'lfs': None, 'rfilename': '.gitattributes', 'size': None},
                RepoFile: {'blob_id': None, 'lfs': None, 'rfilename': 'README.md', 'size': None},
                RepoFile: {'blob_id': None, 'lfs': None, 'rfilename': 'config.json', 'size': None},
                RepoFile: {'blob_id': None, 'lfs': None, 'rfilename': 'generation_config.json', 'size': None},
                RepoFile: {'blob_id': None, 'lfs': None, 'rfilename': 'pytorch_model-00001-of-00002.bin', 'size': None},
                RepoFile: {'blob_id': None, 'lfs': None, 'rfilename': 'pytorch_model-00002-of-00002.bin', 'size': None},
                RepoFile: {'blob_id': None, 'lfs': None, 'rfilename': 'pytorch_model.bin.index.json', 'size': None},
                RepoFile: {'blob_id': None, 'lfs': None, 'rfilename': 'special_tokens_map.json', 'size': None},
                RepoFile: {'blob_id': None, 'lfs': None, 'rfilename': 'tokenizer.model', 'size': None},
                RepoFile: {'blob_id': None, 'lfs': None, 'rfilename': 'tokenizer_config.json', 'size': None}],
   'spaces': ['AlekseyKorshuk/model-evaluation'],
   'tags': ['pytorch', 'llama', 'text-generation', 'transformers', 'license:apache-2.0', 'has_space'],
   'transformersInfo': {'auto_model': 'AutoModelForCausalLM',
                        'pipeline_tag': 'text-generation',
                        'processor': 'AutoTokenizer'},
   'widgetData': [{'text': 'My name is Julien and I like to'}, {'text': 'My name is Thomas and my main'},
                  {'text': 'My name is Mariama, my favorite'}, {'text': 'My name is Clara and I am'},
                  {'text': 'My name is Lewis and I like to'}, {'text': 'My name is Merve and my favorite'},
                  {'text': 'My name is Teven and I am'}, {'text': 'Once upon a time,'}]}
}
```
