### ISSUE TITLE
Pushing a 1.5TB dataset keeps throwing RPC error

### ISSUE THREAD

**Issue by AntreasAntoniou** [huggingface/huggingface_hub#1472]
### Describe the bug

I have followed the instructions to the letter as to how to upload a large dataset, specifically:

1. I kept the dataset broken down into 5GB chunks.
2. Enabled the `git lfs install` and `huggingface-cli lfs-enable-largefiles .` modes
3. Connected the dataset folder to https://huggingface.co/datasets/Antreas/TALI/tree/main/video_data
4. Used a python script that once a file is added and converted to a .git object, it would be pushed and subsequently deleted. 

I keep running into

```bash
Tracking "/data-unified/TALI/video_data/video_data_part.7z.247"                                                                                        
Adding /data-unified/TALI/video_data/video_data_part.7z.247                                                                                            
fatal: pathspec '/data-unified/TALI/video_data/video_data_part.7z.247' did not match any files                                                         
Tracking /data-unified/TALI/video_data/video_data_part.7z.206                                                                                          
Tracking "/data-unified/TALI/video_data/video_data_part.7z.206"                                                                                        
Adding /data-unified/TALI/video_data/video_data_part.7z.206                                                                                            
Auto packing the repository in the background for optimum performance.                                                                                 
See "git help gc" for manual housekeeping.                                                                                                             
[main af1cef4] Adding remaining files                                                                                                                  
 1 file changed, 0 insertions(+), 0 deletions(-)                                                                                                       
 create mode 100644 video_data/video_data_part.7z.206                                                                                                  
Enumerating objects: 438, done.                                                                                                                        
Counting objects: 100% (438/438), done.                                                                                                                
Delta compression using up to 16 threads                                                                                                               
Compressing objects: 100% (108/108), done.                                                                                                             
error: RPC failed; HTTP 408 curl 22 The requested URL returned error: 408                                                                              
send-pack: unexpected disconnect while reading sideband packet                                                                                         
Writing objects: 100% (433/433), 1620.81 GiB | 204.71 MiB/s, done.                                                                                     
Total 433 (delta 70), reused 325 (delta 0), pack-reused 0                                                                                              
fatal: the remote end hung up unexpectedly                                                                                                             
Everything up-to-date                  
```

Uploading this large dataset to hugging face hub has been a nightmare as I had to get around so many issues, so I finally decided to reach out to see if someone could help me resolve this. 

### System info

```shell
- huggingface_hub version: 0.14.1
- Platform: Linux-5.19.0-38-generic-x86_64-with-glibc2.35
- Python version: 3.10.9
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/evolvingfungus/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: Antreas
- Configured git credential helpers: store
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.0.0
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.4.0
- hf_transfer: N/A
- gradio: 3.21.0
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /home/evolvingfungus/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /home/evolvingfungus/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/evolvingfungus/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by AntreasAntoniou** [comment]
Anyone have any ideas? This is blocking a fairly major release.

**Comment by Wauplin** [comment]
Hi @AntreasAntoniou , I'm sorry to ear you are facing those issues. Unfortunately it's quite hard to know the root cause of the problem at the moment.

My guess is that a file that should be tracked as LFS in your local repo is not. "RPC failed HTTP 408 ..." usually means you are trying [to push too much changes at once](https://github.com/orgs/community/discussions/49789#discussioncomment-5276609). If files are correctly tracked as LFS, it should only push a pointer (very small) and do not trigger this issue. I took a look at your [.gitattributes](https://huggingface.co/datasets/Antreas/TALI/blob/main/.gitattributes) files and there are some "weird" lines.

Those lines could be grouped. Since your chunked files have suffixes like ".193", they are not tracked as LFS with the generic rule on the first line. It is possible that a file has not been added to this list which cause your error.
```
*.7z filter=lfs diff=lfs merge=lfs -text
(...)
(...)
video_data/video_data_part.7z.193 filter=lfs diff=lfs merge=lfs -text
video_data/video_data_part.7z.287 filter=lfs diff=lfs merge=lfs -text
video_data/video_data_part.7z.360 filter=lfs diff=lfs merge=lfs -text
video_data/video_data_part.7z.048 filter=lfs diff=lfs merge=lfs -text
video_data/video_data_part.7z.251 filter=lfs diff=lfs merge=lfs -text
video_data/video_data_part.7z.229 filter=lfs diff=lfs merge=lfs -text
```
To fix it, you can update the first line by `*.7z.* filter=lfs diff=lfs merge=lfs -text`.

Another weird aspect that you might want to look into is to have `.git` files listed as well which doesn't make sense. (for example, `/data-unified/TALI/.gitattributes` shouldn't be an LFS file since it's just a text.
```
/data-unified/TALI/.git/index filter=lfs diff=lfs merge=lfs -text
/data-unified/TALI/.git/HEAD filter=lfs diff=lfs merge=lfs -text
/data-unified/TALI/.git/config filter=lfs diff=lfs merge=lfs -text
/data-unified/TALI/.git/FETCH_HEAD filter=lfs diff=lfs merge=lfs -text
/data-unified/TALI/.git/description filter=lfs diff=lfs merge=lfs -text
/data-unified/TALI/.git/COMMIT_EDITMSG filter=lfs diff=lfs merge=lfs -text
/data-unified/TALI/.gitattributes filter=lfs diff=lfs merge=lfs -text
```

**Comment by Wauplin** [comment]
@AntreasAntoniou That been said, I would strongly advice you to push your dataset using `huggingface_hub` python library. You can find a complete guide here: https://huggingface.co/docs/huggingface_hub/guides/upload. This library has several advantages:
- No need to mess with git/git+lfs locally. Also no need to have a local clone of the repo to make some updates in the future.
- Files that are already uploaded are not uploaded again.
- Easier to debug if an error happen (more verbose output)
- Progress bar while uploading.
I would advice to try to upload a file/a few files using `upload_file` first and if it works as expected, use `upload_folder` (maybe on some subfolder to avoid a commit with thousands of files).

You can also speed-up the upload by installing hf_transfer (`pip install hf_transfer`) and enabling it by setting [`HF_HUB_ENABLE_HF_TRANSFER=1`](https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfhubenablehftransfer) as env variable. This is a library that will take advantage of your bandwidth as much as possible. Drawback is a degraded UI (no progress bars).

**Comment by Wauplin** [comment]
All in all, very excited to know that you are publishing such a dataset! I hope the information above will help you in the process. Good luck with your release! :hugs: :hugs:

**Comment by AntreasAntoniou** [comment]
Hello there! I am doing what you said, and things appear to be working now. Thank you so much! I had previously tried using the huggingface hub API to commit and push, but that one caused issues. This alternative path of upload_file and upload_folder seem a lot easier to work with.

**Comment by AntreasAntoniou** [comment]
It's a new large scale dataset for weekly supervised, or self-supervised learning! It has lots of modalities! 

BTW. I have somehow set MIT as the license when I need this to be CC4. How can I change that?

**Comment by Wauplin** [comment]
> BTW. I have somehow set MIT as the license when I need this to be CC4. How can I change that?

Add `license: cc-by-4.0` in your Model Card (the README file). See https://huggingface.co/docs/hub/repositories-licenses#licenses.
--

**Comment by AntreasAntoniou** [comment]
Thank you. It all worked fine. I have more questions, but those are for another thread!
