### ISSUE TITLE
Multiple attempts to download the model resulted in errors

### ISSUE THREAD

**Issue by idesign2018** [huggingface/huggingface_hub#1480]
### Describe the bug

![image](https://github.com/huggingface/huggingface_hub/assets/42263070/f68049db-b1d6-4b71-94a6-f4d1f7dfeaea)
Download model error, try many times is not clear, seeking help, "pytorch_model.bin" file how to download, placed in which folder?

### System info

```shell
![image](https://github.com/huggingface/huggingface_hub/assets/42263070/f68049db-b1d6-4b71-94a6-f4d1f7dfeaea)
```

**Comment by Wauplin** [comment]
Hi @idesign2018, it seems the file you are trying to download is somehow corrupted. Either an HTTP/connection error occurred silently or the file stored on the Hub is not valid. Could you share which model/file you are trying to download? Thank you in advance.

**Comment by Abhishek-cmd13** [comment]
I have the same Issue

**Comment by Yetiowner** [comment]
same issue for CLIPTokenizer.from_pretrained("openai/clip-vit-large-patch14")

**Comment by osanseviero** [comment]
This issue was fixed!
