### ISSUE TITLE
Streamlit based spaces are not being loaded

### ISSUE THREAD

**Issue by omri374** [huggingface/huggingface_hub#1499]
### Describe the bug

Streamlit based spaces, such as https://huggingface.co/spaces/presidio/presidio_demo are not loading. The message is "Please wait...", despite working as usual previously. Please see this thread as well: https://discuss.huggingface.co/t/streamlit-please-wait-after-multiple-days-of-running-fine/42347/5

### Reproduction

Go to https://huggingface.co/spaces/presidio/presidio_demo or https://huggingface.co/spaces/ludvigolsen/plot_confusion_matrix. 

### Logs

```shell
Logs don't show any error:

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.


  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:7860
```

### System info

```shell
N/A
```

**Comment by Wauplin** [comment]
@omri374 Thanks for reporting. The bugt was due to an internal infra update and has been solved. If you go to https://huggingface.co/spaces/presidio/presidio_demo, the Space is running correctly.
