### ISSUE TITLE
cached_download, but with custom file name

### ISSUE THREAD

**Issue by TParcollet** [huggingface/huggingface_hub#15]
Hi there !

Thanks for building this very helpful interface. We are integrating hugging face to SpeechBrain to release all our pretrained speech models. However, we would like to be able to allow users to specify what will be the name of the file that they download. In practice cached_download stores the downloaded file with a very long and hashed filename. What is the best way to allow for a custom name (in the end, it's custom save dir + custom file name). 

Thanks !

**Comment by julien-c** [comment]
The issue is that we are using this hash to find out if we already have the file or not.

Hard to say how to work around this without seeing your use case – maybe just mv the file after downloading it in that case?

**Comment by TParcollet** [comment]
Well, doing a "mv" wouldn't be very clean in this case. The problem is that the model would be downloaded again and again every time the user restarts the script (or a slurm scheduler) even if already downloaded once. It's just not super "user friendly" but we can live with it.

**Comment by julien-c** [comment]
What about a symlink? Otherwise feel free to open a PR if you have an idea!

**Comment by TParcollet** [comment]
I feel I will just go with your hash-style file names. It will just not be super transparent for users, but that's ok I guess.
