### ISSUE TITLE
hf_hub_download doesn't retry on ReadTimeout

### ISSUE THREAD

**Issue by alexmojaki** [huggingface/huggingface_hub#1526]
I got a test failure in https://app.circleci.com/pipelines/github/huggingface/transformers/66984/workflows/0a4f87b2-f6eb-4a8f-ba6f-8edead4065fd/jobs/835240 that came down to a `ReadTimeout`. Here's part of the traceback:

```
../.pyenv/versions/3.8.12/lib/python3.8/site-packages/huggingface_hub/file_download.py:1364: in hf_hub_download
    http_get(
../.pyenv/versions/3.8.12/lib/python3.8/site-packages/huggingface_hub/file_download.py:505: in http_get
    r = _request_wrapper(
../.pyenv/versions/3.8.12/lib/python3.8/site-packages/huggingface_hub/file_download.py:442: in _request_wrapper
    return http_backoff(
../.pyenv/versions/3.8.12/lib/python3.8/site-packages/huggingface_hub/utils/_http.py:212: in http_backoff
    response = session.request(method=method, url=url, **kwargs)
```

In particular in `_request_wrapper` is this line:

https://github.com/huggingface/huggingface_hub/blob/3832f67d50702706e1755fde9741759ed7821a7b/src/huggingface_hub/file_download.py#L448

I don't know the reasoning behind this choice of exceptions to retry, but failures in CI where the network is presumably good seems like a data point in favour of adding `ReadTimeout` to that tuple.

**Comment by Wauplin** [comment]
Thanks for opening the issue @alexmojaki. I opened a PR (https://github.com/huggingface/huggingface_hub/pull/1529) to fix this. No strong choice on the `(ConnectTimeout, ProxyError)` tuple in my opinion. I think `ReadTimeout` has been forgotten just because it's a quite rare issue.

**Comment by Wauplin** [comment]
Fix by https://github.com/huggingface/huggingface_hub/pull/1529.
