### ISSUE TITLE
Evaluation on the Hub does not see all public datasets

### ISSUE THREAD

**Issue by edmcman** [huggingface/huggingface_hub#1527]
### Describe the bug

Evaluation on the Hub does not allow the user to select all datasets.

I believe this is because https://huggingface.co/spaces/autoevaluate/model-evaluator/blob/main/requirements.txt requires an ancient version of huggingface-hub that does not understand pagination, and so only returns the first 10000 datasets.

### Reproduction

1. Go to https://huggingface.co/spaces/autoevaluate/model-evaluator?dataset=ejschwartz%2Foo-method-test-split
2. Note the dataset changes to acronym_identification
3. Type "ejschwartz" in dataset search
4. No results are found

### System info

```shell
NA -- running on spaces
```

**Comment by julien-c** [comment]
maybe for @lewtun

**Comment by osanseviero** [comment]
It might be better to report this in this particular repo - https://huggingface.co/spaces/autoevaluate/model-evaluator/discussions

**Comment by edmcman** [comment]
> It might be better to report this in this particular repo - https://huggingface.co/spaces/autoevaluate/model-evaluator/discussions

[I did](https://huggingface.co/spaces/autoevaluate/model-evaluator/discussions/45) but it doesn't seem like anyone is monitoring it

**Comment by Wauplin** [comment]
Thanks for [the PR](https://huggingface.co/spaces/autoevaluate/model-evaluator/discussions/47) @edmcman. I quickly reviewed the use of `huggingface_hub` on the Space and bumping the version shouldn't break anything. I'd still wait for @lewtun's confirmation since he implemented most of the Space :)

**Comment by edmcman** [comment]
Thanks!  My dataset is listed now, yay!  I did run into another problem, but I think it's unrelated.  Seems like the autotrain API is timing out:

![image](https://github.com/huggingface/huggingface_hub/assets/1017189/cfdeca6d-72ef-4aa6-8462-164dc3e5cf45)

I'll close this and open a new issue if the new problem persists.
