### ISSUE TITLE
model safetensors

### ISSUE THREAD

**Issue by ArashDehghanyan** [huggingface/huggingface_hub#1531]
### Describe the bug

Hi everybody
I implemented a simple code to word embedding using huggingface transformers on my vscode windows 10 os . 
however, while running it , it cannot download model.safetensors on my system 
OSError: Consistency check failed: file should be of size 440449768 but has size 76954576 (model.safetensors).
is it possible to solve it or not? 
Kind regards

### Reproduction

import transformers
import tensorflow as tf
from transformers import BertTokenizer, TFBertModel

MODEL_NAME = "bert-base-uncased"

tokenizer = BertTokenizer.from_pretrained(MODEL_NAME)
model = TFBertModel.from_pretrained(MODEL_NAME)

if __name__ == "__main__":
    input_ids = tf.constant(tokenizer.encode_plus("Hello, my dog is cute", add_special_tokens=True))[None, :]
    outputs = model(input_ids)
    last_hidden_state = outputs[0]

    print(input_ids)
    print(outputs[0])
  

### System info

```shell
- huggingface_hub version: 0.15.1
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.10.7
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: C:\Users\MegaSystem\.cache\huggingface\token
- Has saved token ?: False
- Configured git credential helpers: manager-core
- FastAI: N/A
- Tensorflow: 2.11.0
- Torch: N/A
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.4.0
- hf_transfer: N/A
- gradio: N/A
- numpy: 1.24.2
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: C:\Users\MegaSystem\.cache\huggingface\hub
- HUGGINGFACE_ASSETS_CACHE: C:\Users\MegaSystem\.cache\huggingface\assets
- HF_TOKEN_PATH: C:\Users\MegaSystem\.cache\huggingface\token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by Wauplin** [comment]
Hi @ArashDehghanyan, sorry for the inconvenience. 

Can you confirm that the model you try to instanciate is ``?
I tried your exact code in a google colab and it worked for me ([see notebook](https://colab.research.google.com/drive/11H9G4EKgg8bvZK3sWPiVWHctASYQellI?usp=sharing)). It's weird because in your case it seems that the file has not been correctly downloaded. Could it be caused by a connection issue on your side?

---

For the record, I checked this exact file (https://huggingface.co/bert-base-uncased/resolve/main/model.safetensors) and the content is consistent (file stored in S3 is indeed 440449768 large)

```
curl --head -L https://huggingface.co/bert-base-uncased/resolve/main/model.safetensors | grep "HTTP/2\|content-length\|location"
```
```
HTTP/2 302 
content-length: 1002
location: https://cdn-lfs.huggingface.co/bert-base-uncased/68d45e234eb4a928074dfd868cead0219ab85354cc53d20e772753c6bb9169d3?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1688139078&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4tbGZzLmh1Z2dpbmdmYWNlLmNvL2JlcnQtYmFzZS11bmNhc2VkLzY4ZDQ1ZTIzNGViNGE5MjgwNzRkZmQ4NjhjZWFkMDIxOWFiODUzNTRjYzUzZDIwZTc3Mjc1M2M2YmI5MTY5ZDM%7EcmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjg4MTM5MDc4fX19XX0_&Signature=srTAThGiHufAao9CccvPzInYNdoexs18pNn1SJCE5CcdY4w3b%7EDdBxYok8WCsFBmQOP0SqKh9f%7EWYIebsZTpKl0qv%7EmXDpP%7EorrjtclgykJ4mK4OpSVxe99olugztvZ4yTLt2108ciJSRza-kigzxPiQPqbdySTrGPkZWockwnAQaObys-6cnw4FDi3TazatzM5Pp6%7EVUagtGRkGlHD3X5pjs3du8kYyj9MPpz3dbjkwSkFEjl3G62f-k%7EmdsQwucvs1MkGGonRqTL%7E2GRpr2%7EWM17n47kq8yYJQ2SZsUQtBbJ9ZW0F4rCUQaJ5MnpOm0K%7EukGu6MJSTh%7Eahmp7H7A__&Key-Pair-Id=KVTP0A1DKRTAX
HTTP/2 200 
content-length: 440449768
```
