### ISSUE TITLE
Update Streamlit Spaces support to version 1.24.0

### ISSUE THREAD

**Issue by zachschillaci27** [huggingface/huggingface_hub#1532]
With the recent release of Streamlit [1.24.0](https://docs.streamlit.io/library/changelog), featuring the long awaited chatbot elements, it would be great to extend Streamlit Spaces to support this new version. Currently the version is limited to 1.22.0, according to the documentation here https://huggingface.co/docs/hub/spaces-config-reference. 

If I can ask a naive question, why is there a version restriction for Streamlit in the first place? I suppose this has something to do with the pre-configured images you have in place to host the apps. But given that the additional Python dependencies are already installed from `requirements.txt`, is it not possible to specify the Streamlit version here, thereby providing continuous support for new versions? Please let me know!

I am happy to help with any needed open-source contributions if pointed in the right direction!

**Comment by whitphx** [comment]
Thank you. Yes, the chat UI released in 1.24 is so important, and we are working on releasing it.

>  why is there a version restriction for Streamlit in the first place? 

Very important and critical question.
We have been managing our forked version of Streamlit customized to work well with the Hugging Face platform, and it has a separate release and test flow. This is the reason of the delay.
However, we are switching to use the original version of Streamlit, and planning to make it available since 1.23.0, but it's still taking time for our internal technical restrictions.

It's active in our release flow now, but sorry for the several days delay. Thanks for your patience.
The release should be more fast in near future.

**Comment by zachschillaci27** [comment]
> Thank you. Yes, the chat UI released in 1.24 is so important, and we are working on releasing it.
> 
> > why is there a version restriction for Streamlit in the first place?
> 
> Very important and critical question. We have been managing our forked version of Streamlit customized to work well with the Hugging Face platform, and it has a separate release and test flow. This is the reason of the delay. However, we are switching to use the original version of Streamlit, and planning to make it available since 1.23.0, but it's still taking time for our internal technical restrictions.
> 
> It's active in our release flow now, but sorry for the several days delay. Thanks for your patience. The release should be more fast in near future.

Got it, thanks for the clear explanation!

**Comment by whitphx** [comment]
Hi, 1.24.0 has been released on HF Spaces, so let me close this issue.

However, there is still a problem with `st.chat_input()` that the chat input UI isn't located at the right position. We are working on it, sorry.

**Comment by whitphx** [comment]
HF Spaces has started supporting the upstream Streamlit packages so 1.25 is now available and future versions will be available immediately when they are published on the PyPI registry.
Also, the `st.chat_input()` layout problem has been fixed on 1.25.

**Comment by zachschillaci27** [comment]
> HF Spaces has started supporting the upstream Streamlit packages so 1.25 is now available and future versions will be available immediately when they are published on the PyPI registry. Also, the `st.chat_input()` layout problem has been fixed on 1.25.

Amazing, thank you!
