### ISSUE TITLE
🚀 Manage access requests approval / rejection via API

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1535]
_Initially from @osanseviero on slack_

Models can now be gated with a manual review process. Only users for which usage has been manually granted can access the repo. 5 endpoints exists to see list of pending/accepted/rejected + grant/ungrant access to the model (see screenshot).

At the moment there isn't much usage for this use case. Let's reassess if we see more demand.
We could also add an endpoint to set a repo as Gated (or Manual Approval-gated).

![image__54_](https://github.com/huggingface/huggingface_hub/assets/11801849/5e808389-ba84-4fd5-a41f-8058f083c32f)

Documentation for manual approval: https://huggingface.co/docs/hub/models-gated#manual-approval

**Comment by Wauplin** [comment]
As of now, I wrote a quick (untested) implementation if needed. 
It would need to be reworked to be included in `huggingface_hub` (especially better method naming, add them to `HfApi`, test them, document them). 

```py
from huggingface_hub.constants import ENDPOINT
from huggingface_hub.utils import get_session, build_hf_headers, hf_raise_for_status
from typing import Optional, Literal
from tqdm.contrib.concurrent import thread_map


def get_pending_requests(repo_id: str, *, token: Optional[str]) -> None:
    response = get_session().get(
        f"{ENDPOINT}/api/models/{repo_id}/user-access-request/pending", headers=build_hf_headers(token=token)
    )
    hf_raise_for_status(response)
    return response.json()


def get_accepted_requests(repo_id: str, *, token: Optional[str]) -> None:
    response = get_session().get(
        f"{ENDPOINT}/api/models/{repo_id}/user-access-request/accepted", headers=build_hf_headers(token=token)
    )
    hf_raise_for_status(response)
    return response.json()


def get_rejected_requests(repo_id: str, *, token: Optional[str]) -> None:
    response = get_session().get(
        f"{ENDPOINT}/api/models/{repo_id}/user-access-request/rejected", headers=build_hf_headers(token=token)
    )
    hf_raise_for_status(response)
    return response.json()


def handle_access(
    repo_id: str, user_id: str, status: Literal["accepted", "rejected", "pending"], *, token: Optional[str]
) -> None:
    response = get_session().post(
        f"{ENDPOINT}/api/models/{repo_id}/user-access-request/handle",
        headers=build_hf_headers(token=token),
        json={"userId": user_id, "status": status},
    )
    hf_raise_for_status(response)
    return response.json()


def grant_access(repo_id: str, user_id: str, *, token: Optional[str]) -> None:
    response = get_session().post(
        f"{ENDPOINT}/api/models/{repo_id}/user-access-request/grant",
        headers=build_hf_headers(token=token),
        json={"userId": user_id},
    )
    hf_raise_for_status(response)
    return response.json()


if __name__ == "__main__":
    repo_id = "username/my-cool-model"

    # Get listing
    pending_users = get_pending_requests(repo_id)
    accepted_users = get_accepted_requests(repo_id)
    rejected_users = get_rejected_requests(repo_id)

    # Grant access to a user
    grant_access(repo_id, "Wauplin")

    # Grant access to a list of users (multithreaded)
    users = ["Wauplin", "julien-c", "osanseviero"]
    thread_map(lambda user: grant_access(repo_id, user), users)

    # Reject access for a user
    handle_access(repo_id, "Wauplin", "rejected")

```

**Comment by apolinario** [comment]
Btw, requring the hex `userId` may be not ideal for giving user access (in `handle_access`) . It is not documented, but `user` with their HF username also works and I think could be preferred.

**Comment by osanseviero** [comment]
`user` was not supported until Friday in https://github.com/huggingface/moon-landing/pull/6842 :) cc @SBrandeis 

We now support `user` rather than the hexadecimal, so indeed let's go with that :)

**Comment by Wauplin** [comment]
Yep, thanks for the heads up. I've updated the snippet of code :arrow_up:

**Comment by julien-c** [comment]
cool snippet @Wauplin, and yes i agree to wait to merge until we know if there's a lot of demand for this programattic feature

**Comment by Wauplin** [comment]
Opened a PR to officially add this: https://github.com/huggingface/huggingface_hub/pull/1905 :slightly_smiling_face:

**Comment by Wauplin** [comment]
Closed by https://github.com/huggingface/huggingface_hub/pull/1905.
