### ISSUE TITLE
Facebook models missing from hub

### ISSUE THREAD

**Issue by davidmezzetti** [huggingface/huggingface_hub#1537]
### Describe the bug

https://huggingface.co/facebook is currently giving a 404. Any model string from facebook is failing, for example, https://huggingface.co/facebook/m2m100_418M. 

Could be others but that is only known broken link right now.

### System info

```shell
Web browser
```

**Comment by ChangOliver** [comment]
Basically, every model by Meta AI disappeared from huggingface. In my case, I found that https://huggingface.co/facebook/wav2vec2-base is also broken

**Comment by ChangOliver** [comment]
They are back
