### ISSUE TITLE
ValueError on Windows when loading a repo card with empty YAML

### ISSUE THREAD

**Issue by lhoestq** [huggingface/huggingface_hub#1546]
For example with a dataset card like this

```
---
---
# Begin of markdown

Some cool dataset card
```

It fails on windows with ValueError, while on macos and linux we can load the repo card and get and empty DatasetCardData.
This is because the regex used does find a match but it's empty. Therefore `yaml.safe_load` returns `None` and we get a ValueError since its not a dict as expected.

```
ValueError: repo card metadata block should be a dict
```

This is not super important but makes our CI fail at `datasets` (I'll just skip a test for now)

**Comment by lhoestq** [comment]
yea it's fine, thanks

**Comment by Wauplin** [comment]
Closed by https://github.com/huggingface/huggingface_hub/pull/1547.
