### ISSUE TITLE
[hffs] Alias for the refs/convert/parquet branch

### ISSUE THREAD

**Issue by lhoestq** [huggingface/huggingface_hub#1550]
Right now users have to load datasets in pandas/dask using using

```python
df = dd.read_parquet("hf://datasets/lhoestq/demo1@refs%2Fconvert%2Fparquet")
```

It would be nice to have some sort of alias for that branch, maybe using a special character to signify that it's not a git revision but an alias

```python
df = dd.read_parquet("hf://datasets/lhoestq/demo1@~parquet")
```

This is open to discussion, what do you think ?

The alternative is to create the "parquet" git tag for all the datasets repos

**Comment by julien-c** [comment]
Alias is nice IMO

Could be implemented on server-side for consistency and instant backward compat

**Comment by Wauplin** [comment]
I'd also be in favor of a server-side alias. Git tags seems clunky as it would mean each time the parquet ref is updated, you'd need to delete a tag and recreate one. 

If we do a server-side alias, should we just go for `parquet` and forbid this name as revision? If we use a special character we would need to url-encode it as well which is what we want to avoid here.

**Comment by Wauplin** [comment]
Created an issue on moon-landing: https://github.com/huggingface/moon-landing/issues/6978 (internal).

**Comment by julien-c** [comment]
yes `urlencode(~) == ~`

**Comment by severo** [comment]
Done and in prod. We can close, I think

**Comment by Wauplin** [comment]
Thanks @severo :) 
@lhoestq can you confirm your use case is addressed and close the issue?
