### ISSUE TITLE
Add support for space `variables`

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1552]
API for Spaces got a nice update server side to introduce `variables`. We should reflect this on `huggingface_hub`'s side. Variables and secrets are a way to configure a Space without hardcoding values in your app. The big difference is that Variables [are publicly accessible](https://huggingface.co/docs/hub/spaces-overview#managing-secrets-and-environment-variables) and copied when a user duplicates your Space.

Similar to [`add_space_secret`](https://huggingface.co/docs/huggingface_hub/v0.16.3/en/package_reference/hf_api#huggingface_hub.HfApi.add_space_secret) and [`delete_space_secret`](https://huggingface.co/docs/huggingface_hub/v0.16.3/en/package_reference/hf_api#huggingface_hub.HfApi.delete_space_secret), we should have `add_space_variable` and `delete_space_variable` methods in `HfApi`. Implementation will be very similar but use the `/variables` endpoint instead of `/secrets`.

In details, the steps I see are:
- Implement `add_space_variable`. User must be able to provide `repo_id`, `key`, `value` and `description`. Description is optional (defaults to None).
- Implement `delete_space_variable`. Takes as input only `repo_id` and `key`.
- Implement `get_space_variables`. Takes as input `repo_id`. Same endpoint but with GET method.
- All three methods must return the current variables in the Space (after update). This is a dictionary which keys are variable keys and values are dictionaries (e.g. `{"value":"42","description":"This is a variable.","updatedAt":"2023-07-11T09:49:34.623Z"}`). Return type can be defined as a Python dataclass in [./_space_api.py](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/_space_api.py). There is an utility to parse the `updated_at` datetime (`from huggingface_hub.utils import parse_datetime`).

**Note:** variables should also be supported at repo creation or duplication. A separate issue is opened to implement that: https://github.com/huggingface/huggingface_hub/issues/1457.

**Comment by julien-c** [comment]
would be an awesome first issue if someone wants to work on it!

**Comment by martinbrose** [comment]
Hi @Wauplin and @julien-c,

my PR mentioned above should take care of this issue.

Not 100% sure how I return the current variables is like you envisioned it.

Looking forward to your feedback.

Cheers

**Comment by Wauplin** [comment]
Issue completed by @martinbrose as part of https://github.com/huggingface/huggingface_hub/pull/1592. Thanks for the great work! :fire:
