### ISSUE TITLE
Add endpoint to retrieve space logs 

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1554]
Users can watch logs from their own Spaces on the Hub. These logs are accessible via API. It would be cool to be able to retrieve them with `huggingface_hub`. There are 2 types of logs for a Space:
- Build logs: `GET "https://huggingface.co/api/spaces/{repo_id}/logs/build"` (logs when building the docker image)
- Container logs: `GET "https://huggingface.co/api/spaces/{repo_id}/logs/container"` (logs when container is running)

Implementation-wise, we can have a method signature like this:

```py
def get_space_logs(self, repo_id:str, target: Literal["build", "container"] = "container", *, token: Optional[str] = None) -> str:
    ... 
```

Logs are returned as a raw string.

**Comment by sifisKoen** [comment]
Hello,

I think I understand what you need here. You want a function which will return a raw text response to the user. I think I have the solution to this issue.

Do you want something like this?
```python
def get_space_logs(self, repo_id:str, target: Literal["build", "container"] = "container", *, token: Optional[str] = None) -> str:
    logs_url = f"https://huggingface.co/api/spaces/{repo_id}/logs/{target}"

    headers={}
    if self.token is not None:
    # I use this if statement just to check if there is any token provided.
        headers["Authorization"] = f"{self.token}"
    
    response = request.get(url=logs_url, headers=headers)
    
    if response.status.code == 200:
        return response.text
    else:
       response.raise_for_status()

```

Of course, I can make adjustments to your project's needs. I try to understand if this is what you need. :smile:

**Comment by Wauplin** [comment]
Yes that would be it @sifisKoen from a logic point of view! I would change a few things to be more consistent with the existing codebase. In particular, such a method should be added to the `HfApi` object in [`./hf_api.py`](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/hf_api.py). This implies that you have a few helpers you can use:

1. Url would be `f"{self.endpoint}/api/spaces/{repo_id}/logs/{target}"`
2. Headers are generated with `headers = self._build_hf_headers(token=token)`. This is more robust has it would also try to retrieve the token from the machine of the user if `huggingface-cli login` has been run previously.
3. It's best to prefer `get_session().get` instead of `requests.get`. Long story short, this is a helper that generated 1 session common to the thread. If multiple consecutive calls are made to the Hub, the same connection will be reused hence saving some time for the user.
4. It's best to prefer `hf_raise_for_status(response)` instead of `response.raise_for_status()`. Under the under it uses the same logic but `hf_raise_for_status` is more specific to HF Hub. In particular errors are made more explicit.

Overall the implementation become:

```py
def get_space_logs(self, repo_id:str, target: Literal["build", "container"] = "container", *, token: Optional[str] = None) -> str:
    response = get_session().get( # Use get_session
        url=f"{self.endpoint}/api/spaces/{repo_id}/logs/{target}", # Use self.endpoint -easier for testing-
        headers=self._build_hf_headers(token=token) # Retrieve token from machine if not provided
    )
    hf_raise_for_status(response) # "better" error handling
    return response.text # return if error not raised
```

Does that work for you? Would you like to open a PR including a test and some docstring? I'd be happy to review and help if needed :) Thank you in advance!

**Comment by sifisKoen** [comment]
@Wauplin hey ! I will open a PR for this issue too. Implemented what we said here. I will use the code we discussed here and I will write the docstring. Finally could you please tell me in witch file I should add the tests ? :smile:

**Comment by Wauplin** [comment]
Great to hear @sifisKoen! :hugs: A good place for the tests would be in [`TestSpaceAPIMocked`](https://github.com/huggingface/huggingface_hub/blob/4c8e64e523b91dbabbd5cf6b4ba546f0aa2e6483/tests/test_hf_api.py#L2626). You can mock the GET method in `setUp` the same way POST and DELETE are already mocked. If you have question, don't hesitate to ask. And if you have a suggestion of code, feel free to directly push them to the PR even if they are not finalized so that we can discuss them easily :)

**Comment by sifisKoen** [comment]
@Wauplin  hey dude now I am writing this PR. I had too many things to do. Sorry for my delay :face_exhaling:

**Comment by Wauplin** [comment]
No worries! Everyone has their own schedule anyway :wink:

**Comment by Wauplin** [comment]
Doing a bit of cleaning. Given https://github.com/huggingface/huggingface_hub/pull/1678#issuecomment-1727453749, I'll close this issue as "wont fix".
