### ISSUE TITLE
Add support for `secrets`'s description

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1556]
Users can set [secrets](https://huggingface.co/docs/hub/spaces-overview#managing-secrets-and-environment-variables) on their Space using [`add_space_secret`](https://huggingface.co/docs/huggingface_hub/v0.16.3/en/package_reference/hf_api#huggingface_hub.HfApi.add_space_secret). The Hub API has been recently updated to set an (optional) description to the secrets. This is useful if you plan to create a Space that will be duplicated by other users. It let you describe the intended use of the secret key.

![image](https://github.com/huggingface/huggingface_hub/assets/11801849/33eae235-9c24-4bd8-9003-6f37e5d0518c)
 
It would be cool to add a `description: Optional[str] = None` parameter to `add_space_secret`. Docstring and test should be updated as well to reflect this change.

**Comment by sifisKoen** [comment]
Hello,

Reading this issue, I understand that you need to add one more parameter to the `add_space_secret` function of hf_api.py

This issue can be solved very quickly. You can insert this variable and add it to the `json` in the post method.

What I think:
```python
def add_space_secret(<your initial variables>, description: Optional[str] = None) -> None:
    response = get_session().post(
            f"{self.endpoint}/api/spaces/{repo_id}/secrets",
            headers=self._build_hf_headers(token=token),
            json={"key": key, "value": value, "description": description},
        )
    hf_raise_for_status(r)
```

Is this what you want to do here?

**Comment by Wauplin** [comment]
Yes that would be very clean! Would you like to open a PR? :)

**Comment by martinbrose** [comment]
Apologies @sifisKoen, basically snatched this away from you.

Just wanted to have this in a release that may include my PR on the variables, where I implemented this already for the variables.

**Comment by martinbrose** [comment]
@Wauplin, I think this can be closed now?

**Comment by Wauplin** [comment]
Right! Closed by https://github.com/huggingface/huggingface_hub/pull/1594.
