### ISSUE TITLE
Colab `notebook_login` goes to hf.co login page in Safari

### ISSUE THREAD

**Issue by lvwerra** [huggingface/huggingface_hub#1566]
### Describe the bug

When clicking on the token link in Colab of `notebook_login` I get to `https://huggingface.co/login?next=%2Fsettings%2Ftokens` which asks me to login even if I am logged in. But if I right click and copy paste the link I see that the link was actually `https://huggingface.co/settings/tokens`. So I don't think this is a `huggingface_hub` issue per se but something in the browser/HF website.

**Note:** It works in Chrome.

**Comment by Wauplin** [comment]
@coyotte508 @Pierrci can it be a cookie issue on Safari? Can't really test myself here since it requires a mac.
