### ISSUE TITLE
Ability to add ReadMe tags from create_repo

### ISSUE THREAD

**Issue by freddyaboulton** [huggingface/huggingface_hub#1568]
**Is your feature request related to a problem? Please describe.**

When calling `create_repo`, I sometimes want to add a specific tag to the README.md. In order to do so, I have to create a README.md on the fly with the appropriate tags and I have to commit it myself. Which is a bit cumbersome, would be cool if I could do so from `create_repo` directly.

**Describe the solution you'd like**
Add a `List[str]` `tags` parameter to `create_repo`

```python
huggingface_hub.create_repo(
    "freddyaboulton/llama-demo",
    repo_type="space",
    space_sdk="gradio",
    token=hf_token,
    tags=['llm', 'llamav2']
)
```

**Describe alternatives you've considered**
I have looked for existing solution and couldn't find it. 
**Additional context**

**Comment by julien-c** [comment]
have you seen the `metadata_update` function? might solve your use case

https://huggingface.co/docs/huggingface_hub/v0.16.3/en/package_reference/cards#huggingface_hub.metadata_update

**Comment by freddyaboulton** [comment]
Thank you @julien-c !! 🙏
