### ISSUE TITLE
License information can't be accessed from gated repos

### ISSUE THREAD

**Issue by antoche** [huggingface/huggingface_hub#1579]
### Describe the bug

Right now it is not possible to access license information from gated repos via the API, even though the information is clearly publicly accessible via the Web interface, and can even be found via indirect means such as search.

The API docs are not so clear regarding how to get license information, but from what I can see, the best way seems to be using 
```python
from huggingface_hub import ModelCard
card = ModelCard.load("google/ddpm-ema-church-256")
card.data['license']
# 'apache-2.0'
```

But this fails on gated repos (see repro case below), even though access to the license is required to know whether one can agree to it.

This is despite the license being visible on the web interface, and that information being leaked via other means, e.g.:

```python
models = list(api.list_models(search="DeepFloyd/IF-I-XL-v1.0"))
models
# [ModelInfo: { 
#   {'_id': '642f382128a26b5c89b231fa',
#    'author': None,
#    'config': None,
#    'downloads': 41844,
#    'id': 'DeepFloyd/IF-I-XL-v1.0',
#    'lastModified': None,
#    'likes': 473,
#    'modelId': 'DeepFloyd/IF-I-XL-v1.0',
#    'pipeline_tag': 'text-to-image',
#    'private': False,
#    'securityStatus': None,
#    'sha': None,
#    'siblings': [],
#    'tags': ['pytorch', 'diffusers', 'arxiv:2205.11487', 'arxiv:2110.02861', 'if', 'text-to-image',
#             'license:deepfloyd-if-license', 'has_space']}
# }]
```

It would be great for calls such as `ModelCard()` and `model_info()` to be valid on gated repositories, given that they don't actually share the contents of the model, and help users (programmatically) decide whether they can go through with requesting access to the gated models in question.

### Reproduction

```python
from huggingface_hub import ModelCard
card = ModelCard.load("DeepFloyd/IF-I-XL-v1.0")
# Traceback (most recent call last):
# [...]
# huggingface_hub.utils._errors.GatedRepoError: 401 Client Error. (Request ID: Root=1-64d046aa-6ae94971277d49361afe0aca)
# Cannot access gated repo for url https://huggingface.co/api/models/DeepFloyd/IF-I-XL-v1.0.
# Repo model DeepFloyd/IF-I-XL-v1.0 is gated. You must be authenticated to access it.
```

### System info

```shell
- huggingface_hub version: 0.15.1
- Platform: Linux-4.15.0-213-generic-x86_64-with-glibc2.27
- Python version: 3.9.10
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Has saved token ?: False
- Configured git credential helpers: store
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.0.0a0+gite9ebda2
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.2.0
- hf_transfer: N/A
- gradio: N/A
- numpy: 1.22.3
- ENDPOINT: https://huggingface.co
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: True
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by Wauplin** [comment]
@antoche You can retrieve the license information for a model using an API endpoint like this:

```py
>>> from huggingface_hub.hf_api import model_info
>>> model_info("google/ddpm-ema-church-256").cardData["license"]
'apache-2.0'
```

This is directly [this public endpoint](https://huggingface.co/api/models/google/ddpm-ema-church-256) that is served server-side. What happens when doing `ModelCard.load` is that you download the `README.md` file locally and load/parse it into a Python object. It fails to download it since the `/resolve` endpoints to download files are disabled on gated repo (if not accepted the license).

---

@julien-c @Pierrci What do you think about opening `https://huggingface.co/REPO_ID/resolve/main/README.md` for all users on public gated repos? This is already the case on the UI since anyone can see the model card.

**Comment by Wauplin** [comment]
This issue has been solved server-side in Aug 2023. The README file of any gated repo is accessible to download so I'll close this issue :)
