### ISSUE TITLE
Hosted inference inactive on Llama 2 models

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/huggingface_hub#1589]
### Describe the bug

Hosted inference seems to be disabled for Llama 2 models. Is there a configuration change that could fix this?

On a related topic, is hosted inference available to anyone (when enabled) or does it require access to the underlying dataset?

### Reproduction

Sample repos:
- https://huggingface.co/meta-llama/Llama-2-13b-chat-hf
- Trelis/Llama-2-7b-chat-hf-function-calling (fork)

### System info

```shell
NA
```

**Comment by RonanKMcGovern** [comment]
Closing this, the reason is simply because hosted inference only works for models <10 GB.

I tried to turn on hosted inference for GPTQ and GGML models, but AFAIK they aren't supported by hosted inference. They didn't work.

**Comment by julien-c** [comment]
the _widget_ is indeed disabled on that model page, but please note that the Inference API is active (available to PRO and Enterprise Hub users):

https://www.linkedin.com/posts/julienchaumond_llama-2-just-landed-in-hugging-face-inference-activity-7089986843839979521-e1vT/?utm_source=share&utm_medium=member_desktop

cc @osanseviero @gary149 for visibility

**Comment by RonanKMcGovern** [comment]
Yes thanks @julien-c , sorry, I afterwards found that I could enable inference, but it is so slow that it doesn't load (given I don't have a PRO or Enterprise Hub account).
