### ISSUE TITLE
Show number of parameters on model card

### ISSUE THREAD

**Issue by darabos** [huggingface/huggingface_hub#1596]
**Is your feature request related to a problem? Please describe.**
I often want to see the model size (the number of parameters). Often this is documented on the model card (or even the model name), but not always. So I sometimes have to download the model and check the size myself.

**Describe the solution you'd like**
There could be a dedicated spot on the model card page that lists the number of parameters. It could list more details that can be read from the model files: the layers it has, parameters in each layer, and quantization.

**Describe alternatives you've considered**
It's possible that this information is already on the model card and I'm just missing it. Or I'm in the wrong repo! Deep apologies in either case.

**Additional context**
I would be happy to help implement this if it's a reasonable feature request. (I don't know whether there is already a pipeline that extracts something from the model files. Or if I'm in the right repo. 😰 )

**Comment by Wauplin** [comment]
Hey @darabos, thanks for your interest. This is actually a feature we launched a few weeks ago! Here is an example for [bigscience/bloomz](https://huggingface.co/bigscience/bloomz) which has 176B BF16 parameters. 

![image](https://github.com/huggingface/huggingface_hub/assets/11801849/023142e3-41e9-484f-bb37-dbc3af7fdc2d)

You can even have the details of all the layers when clicking on the arrow.

![image](https://github.com/huggingface/huggingface_hub/assets/11801849/f674c39d-695d-47f7-ad0b-b47569715cd6)

This feature is enabled only for models saved in the [safetensors](https://huggingface.co/blog/safetensors-security-audit) format. This is a format made to be both safe and fast to use. Even though not every model uses safetensors, a [growing number](https://huggingface.co/docs/safetensors/index#featured-projects) of projects is using it by default which should hopefully solve your issue.

The main reason why we implement your requested feature only for safetensors is that reading the layer structure is made very easy _by design_ as opposite to pickle formats where we would need to actually load the model on your server to get the information.

**Comment by darabos** [comment]
Oh, this is fantastic, thanks! Only doing it for safetensors makes sense! Thanks for the explanation.
