### ISSUE TITLE
Hi, we need java/scala  hub api client

### ISSUE THREAD

**Issue by mullerhai** [huggingface/huggingface_hub#1599]
Hgface  is popular tools ,we want to use hgface in java project ,if convinient ,please support java api client develop ,thanks

**Comment by Wauplin** [comment]
Hi @mullerhai, we currently focus our efforts on the [Python client](https://github.com/huggingface/huggingface_hub) and the [JS client](https://github.com/huggingface/huggingface.js), languages in which we have the larger audience. There are other clients [in Rust](https://github.com/huggingface/hf-hub) and in [C#](https://github.com/huggingface/unity-api), implementing only a subset of features - depending on the usage/requirements in each language. In general, we encourage community-driven development so we will definitely help with questions and reviews if you want to start building a Java/Scala client. 
Cheers, Wauplin :hugs:

**Comment by Wauplin** [comment]
Closing this issue as "wont fix" as it's not related to the Python client. Feel free to ping me for any question/review on a Java/Scala project :)
