### ISSUE TITLE
Netlify authorization issue on `JS Widgets` action

### ISSUE THREAD

**Issue by mishig25** [huggingface/huggingface_hub#160]
When I push new widget code, [JS Widgets action](https://github.com/huggingface/huggingface_hub/actions/workflows/js-widgets-tests.yml) run fails with:
```bash
Run npx netlify deploy --auth "$NETLIFY_AUTH_TOKEN" --dir ./build/ --site ${NETLIFY_SITE_ID} ${NETLIFY_EXTRA_FLAG}
Logging into your Netlify account...
Opening https://app.netlify.com/authorize?response_type=ticket&ticket=3991f04ac8fafbce2ad54c29bf5fd8b6
- Waiting for authorization...
 ›   Error: Timed out waiting for authorization. If you do not have a Netlify 
 ›   account, please create one at https://app.netlify.com/signup, then run 
 ›   netlify login again.
Error: Process completed with exit code 2.
```

See [failed workflow run here](https://github.com/huggingface/huggingface_hub/runs/2988565843?check_suite_focus=true).
What should I do to solve this issue? Thanks!

**Comment by mishig25** [comment]
Could this be the reason: I'm creating a PR from **my fork's** branch, not a branch on the **original** repository. Because when I create a test branch on the original repostory, `JS Widgets` action runs fine (see [here](https://github.com/huggingface/huggingface_hub/runs/2996581375?check_suite_focus=true)).

**Comment by julien-c** [comment]
Yeah that's probably it

**Comment by mishig25** [comment]
Great, I'll then transfer branches from my fork into the original repo

**Comment by julien-c** [comment]
GH Actions run on fork don't have access to the repo's secrets
