### ISSUE TITLE
Can no longer connect to HuggingFaceHub. "Distant resource does not seem to be on huggingface.co "

### ISSUE THREAD

**Issue by Sleemanmunk** [huggingface/huggingface_hub#1600]
### System Info

    transformers version: 4.31.0
    Platform: Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.35
    Python version: 3.10.12
    Huggingface_hub version: 0.16.4
    Safetensors version: 0.3.2
    Accelerate version: not installed
    Accelerate config: not found
    PyTorch version (GPU?): not installed (NA)
    Tensorflow version (GPU?): not installed (NA)
    Flax version (CPU?/GPU?/TPU?): not installed (NA)
    Jax version: not installed
    JaxLib version: not installed
    Using GPU in script?: No
    Using distributed or parallel set-up in script?: No

### Who can help?

We cannot continue our work because yesterday, huggingface hub failed and it hasn't come back. We've been using HuggingFaceHub for years with no issue.

Yesterday we opened the bug huggingface/transformers#25552. In a minimal test environment we have downgraded requests and applied the CURL environment variable fix described in huggingface/transformers#17611. This skipped SSL and the SSL error, but we got a new equally fatal error:

/home/saleem/.local/lib/python3.10/site-packages/urllib3/connectionpool.py:1056: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
Traceback (most recent call last):
  File "/mnt/c/Users/saleem/Desktop/test.py", line 2, in <module>
    tokenizer = AutoTokenizer.from_pretrained('gpt2')
  File "/home/saleem/.local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 652, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/home/saleem/.local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 496, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/home/saleem/.local/lib/python3.10/site-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "/home/saleem/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/saleem/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1214, in hf_hub_download
    raise OSError("Distant resource does not seem to be on huggingface.co (missing commit header).")
OSError: Distant resource does not seem to be on huggingface.co (missing commit header).

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

*create test.py* 

```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('gpt2')

```
1. `pip3 install requests==2.27.1`
1. `export CURL_CA_BUNDLE=''`
1. `python3 test.py`

### Expected behavior

Tokenizer downloads successfully from HuggingfaceHub

**Comment by ArthurZucker** [comment]
Transfered to `huggingface_hub` as they might have more ideas here! @Wauplin

**Comment by Sleemanmunk** [comment]
Thank you! I had no idea this was its own separate project!

**Comment by ashleypchurch** [comment]
Following as we were facing identical errors and now getting this error: 

`File "/app/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 695, in cached_download
raise OSError(
OSError: Distant resource does not have an ETag, we won't be able to reliably ensure reproducibility.
`

**Comment by mrobertsonavidxchange** [comment]
I have the same issue here, after fixing the issue on 

https://github.com/huggingface/transformers/issues/17611

**Comment by Sleemanmunk** [comment]
Cisco umbrella automatically registered huggingface.co as a malicious site and we had to get our company security admin to whitelist it. Now we can download models again.

**Comment by Anonymous-sdlcovid** [comment]
> Cisco umbrella automatically registered huggingface.co as a malicious site and we had to get our company security admin to whitelist it. Now we can download models again.

Yes, seems that way, because my university also uses cisco networking and there was some issue establishing the connection, its  working now by the way.
