### ISSUE TITLE
I want to fork this Hugging Face hub GitHub repository to do a translation. Is this feasible?

### ISSUE THREAD

**Issue by jimtom40395** [huggingface/huggingface_hub#1601]
I want to fork this Hugging Face hub GitHub repository to do a translation. Is this feasible? @xianbaoqian

**Comment by 1359989** [comment]
translation to  chinese.

**Comment by 1359989** [comment]
and build  a  CN  folder, it's  can  or  not?

**Comment by xianbaoqian** [comment]
Hi @1359989 

Thank you for offering to translate the Python Hub documentation into Chinese! That would be incredibly helpful for our Chinese user community. 


Dear Hub team,

Is this possible to add multi-language support in the docs? (apart from the reference section)

<img width="258" alt="image" src="https://github.com/huggingface/huggingface\_hub/assets/38108242/60feea24-11bc-40d5-b1dc-bf345641fb05">

I took a look at the Diffusers library, and it's great that they have built-in support for multi-lingual. 
<img width="292" alt="image" src="https://github.com/huggingface/huggingface_hub/assets/38108242/7e7564e6-33c8-48c4-97a0-eef2646fb133">

Alternatively, for the Hub library, having a forked repo with translations that we link to from the main README could work well if built-in multi-lingual support is too complex. User can read the markdown file preview and we can also post some of the translated content on our Chinese social medias (e.g. WeChat / Zhihu)

Also it would appreciate if you can help with some instructions on how to preview the docs page locally to catch early issues. doc-builder preview doesn't seem to work well.

Any thoughts / suggestions? Looking forward to collaborating to make the Hub docs more accessible to Chinese users. 

Thanks,
Tiezhen

**Comment by Wauplin** [comment]
Hi @1359989 @xianbaoqian :wave: Thank you both for offering to translate `huggingface_hub`'s content! Actually this is something we've discussed internally not that long ago. Our plan is to do the same as in [`transformers`](https://github.com/huggingface/transformers):
- provide several a different README file for each language, referencing each other
- provide the same [translating guide](https://github.com/huggingface/transformers/blob/main/docs/TRANSLATING.md)
- have [1 folder per language](https://github.com/huggingface/transformers/tree/main/docs/source) in the `docs/`, which would enable multi-lingual support as in transformers and diffusers

I'll keep you updated about the progress :)

**Comment by Wauplin** [comment]
I opened an issue (https://github.com/huggingface/huggingface_hub/pull/1602) to enable translations to other languages than English (like in transformers/diffusers).

**Comment by 1359989** [comment]
One more question,my pull request Should I submit my pull request after I finish the translation, or before I finish the translation?@Wauplin

**Comment by 1359989** [comment]
Because  I  first  to do  it , I don't  know  how  to do.  😥😥😥😥😥

**Comment by Wauplin** [comment]
@jimtom40395 It's not yet possible to translate documentation on this repo. The best you can do at the moment, if you want, is to translate the existing guides offline and wait for my PR to be merged first. I'll provide you more details once it's done (I'm not 100% sure yet how we will proceed). Due to holidays the PR will not be merged before the end of August.

**Comment by jimtom40395** [comment]
No problem. The work I'm doing now is to fork the repository to my github local, and then do the translation.Also, I would like to thank you for taking the time to reply to me amidst your busy schedule.☺@Wauplin

**Comment by Wauplin** [comment]
@jimtom40395 Translating documentation for this repo is now possible! (see https://github.com/huggingface/huggingface_hub/pull/1602). 

To start translating to a new language, you should check if an issue already exists ([here](https://github.com/huggingface/huggingface_hub/issues)) which is not the case for chinese at the moment. Then if it doesn't exist, you should [create a new one](https://github.com/huggingface/huggingface_hub/issues/new?assignees=&labels=WIP&projects=&template=i18n.md&title=%5Bi18n-%3ClanguageCode%3E%5D+Translating+docs+to+%3ClanguageName%3E) to track the work progress. For example, here is the issue for [Korean translation](https://github.com/huggingface/huggingface_hub/issues/1626). Then you can share in your community and start organizing the work!

**Comment by Wauplin** [comment]
I'll therefore close this issue.
