### ISSUE TITLE
Outstanding issues with model evaluator

### ISSUE THREAD

**Issue by edmcman** [huggingface/huggingface_hub#1619]
### Describe the bug

There are outstanding issues in the model evaluator.  These are reported on the model evaluator discussion page, but it doesn't seem like anyone is monitoring or responding to that.

[eval_info KeyError](https://huggingface.co/spaces/autoevaluate/model-evaluator/discussions/52)

[UI Problems (and video of eval_info problem)](https://huggingface.co/spaces/autoevaluate/model-evaluator/discussions/54)

### Reproduction

See the above issues.

### Logs

```shell
NA
```

### System info

```shell
NA
```

**Comment by Wauplin** [comment]
This project is now archived in favor of other leaderboards initiatives. See https://huggingface.co/spaces/autoevaluate/model-evaluator.
