### ISSUE TITLE
Failed to push data to a dataset repository 

### ISSUE THREAD

**Issue by lurauch** [huggingface/huggingface_hub#1623]
### Describe the bug

I created a (private) dataset repository (in an org) and wanted to push ~1k of `.mp3` files via terminal. I get the error of "too many password attempts" as you can see in the logs. 

Other users had a similar issue: https://discuss.huggingface.co/t/batch-response-too-many-password-attempts-while-uploading-the-dataset-files-with-lfs/38458

### Reproduction

Cannot be easily reproduced, but a minimal process: 

- create a dataset repository
- login via `huggingface-cli login`
- git clone via `git clone git@hf.co:<your-username>/<your-model-name>`
- add ~1k .mp3 files in a folder to the repository
- enable git lfs via `git lfs install`
- git commit, add, push: 
 ```
  git add .
  git commit -m "text" 
  git push
```

### Logs

```shell
Terminal logs: 

Too many password attempts% (94/1000), 94 MB | 2.5 MB/s                                                                                                                                        
Uploading LFS objects:  10% (99/1000), 94 MB | 2.5 MB/s, done.
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
error: failed to push some refs to 'hf.co:datasets/DBD-research-group/gadme-test2'
remote: 
remote: ========================================================================
remote: 
remote: ERROR: 

remote: 
remote: ========================================================================
```

### System info

```shell
- huggingface_hub version: 0.16.4
- Platform: Linux-6.2.0-26-generic-x86_64-with-glibc2.35
- Python version: 3.11.4
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/lukas/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: lrauch
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.0.1
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 10.0.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.24.0
- pydantic: N/A
- aiohttp: 3.8.4
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /home/lukas/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /home/lukas/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/lukas/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by Wauplin** [comment]
Hi @lurauch sorry you've experienced this issue and thanks for letting us know. I don't have a clear explanation yet on why such an error is triggered. As a workaround, what I would advice you to do is to upload your data using `huggingface_hub.upload_folder`. You can follow [this guide](https://huggingface.co/docs/huggingface_hub/guides/upload#upload-a-folder) on how to upload files to the Hub using `huggingface_hub`. In general we are more and more trying to switch from [git commands to http-based utilities](https://huggingface.co/docs/huggingface_hub/concepts/git_vs_http) in the normal workflow which increases performances for the users and maintainability on our side.

**Comment by lurauch** [comment]
Hey @Wauplin, thank you for pointing that out! I tried the recommended http-based utilities on the weekend, and the `upload_folder` function worked seamlessly during my test upload. Would you like me to close this issue?

**Comment by Wauplin** [comment]
That's great to hear! Yes let's close this issue. Thanks for the feedback :)
