### ISSUE TITLE
Building takes an insanely long time

### ISSUE THREAD

**Issue by eben-vranken** [huggingface/huggingface_hub#1632]
Even though I upgraded to a T4 Medium I still can't get any improvement on the building time of my space. 

```
from transformers import AutoTokenizer, AutoModelForCausalLM
import gradio as gr
from pathlib import Path

access_token = "hf_****"
DATA_PATH = Path("./")
MODEL_NAME = "meta-llama/Llama-2-7b-chat-hf"

# Define the cache directory for Hugging Face models
CACHE_DIR = DATA_PATH / "huggingface_cache"

# Ensure the cache directory exists
CACHE_DIR.mkdir(parents=True, exist_ok=True)

def get_storage():
    files = [
        {
            "orig_name": file.name,
            "name": file.resolve(),
            "size": file.stat().st_size,
            "data": None,
            "is_file": True,
        }
        for file in DATA_PATH.glob("**/*")
        if file.is_file()
    ]
    usage = sum([f['size'] for f in files])
    return files, f"{usage / (1024.0 ** 3):.3f}GB"

# Check if the model is available in the cache directory
try:
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, token=access_token, cache_dir=CACHE_DIR)
    model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, token=access_token, cache_dir=CACHE_DIR)
except Exception as e:
    print(f"An error occurred while loading the model: {str(e)}")
    tokenizer = None
    model = None

def text_generation(input_text):
    if tokenizer is None or model is None:
        return "Error: Model not loaded"
    
    input_ids = tokenizer(input_text, return_tensors="pt").input_ids
    outputs = model.generate(input_ids, num_beams=4, do_sample=True)
    generated_text = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]
    return generated_text

# Vue Property Decorator -> Options API
def propertyDecoratorRemoval(input_code):
    prompt = f"Perform a seamless migration from 'vue-property-decorator' code to the native Vue options API for the provided code snippet. Ensure that the refactoring maintains the functionality of the original code while leveraging the benefits of the Vue options API. Following is the code: {input_code}"
    agent_answer = text_generation(prompt)
    return agent_answer

propertyDecoratorRemovalTab = gr.Interface(
    fn=propertyDecoratorRemoval,
    article="This tab will take the inputted code (which utilizes the vue-property-decorator package) and migrates it to the native Options API in Vue.",
    inputs=gr.Textbox(lines=30, placeholder="vue-property-decorator code here..."),
    outputs=gr.Textbox(lines=30, placeholder="Options API code will be outputted here...")
)

# Vue Property Decorator -> Options API
def vueVersionMigration(input_code):
    return "Migration"

vueVersionMigrationTab = gr.Interface(
    fn=vueVersionMigration,
    description="❗ Please ensure that your code does not have any breaking changes when migrated to Vue 3.",
    article="This tab takes the inputted Vue 2 code and migrates it to Vue 3.",
    inputs=gr.Textbox(lines=30, placeholder="To migrate Vue 2 here..."),
    outputs=gr.Textbox(lines=30, placeholder="Migrated Vue 3 code will be outputted here...")
)

gr.TabbedInterface([propertyDecoratorRemovalTab, vueVersionMigrationTab], ["Vue Property Decorator removal", "Vue Version Migration"]).launch(allowed_paths=[str(DATA_PATH)])
```

**Comment by eben-vranken** [comment]
Okay, after a very long time of building, it finishes; But I still get `Connection Errored`

I wrote an issue for this on the hugging face forum yesterday, but to no avail.

![image](https://github.com/huggingface/huggingface_hub/assets/92394428/f0abc5df-7ad7-4253-9e49-a5d789412ddf)

**Comment by Wauplin** [comment]
@eben-vranken We have manually revoked your access token. This means that scripts using it will not work anymore. You can of course regenerate tokens for your need. The reason why we revoked it is that it gives access to everything on your account, including starting Spaces or Inference Endpoints that would cost you money. In the future, please be careful about what you share publicly :wink:

**Comment by eben-vranken** [comment]
> @eben-vranken We have manually revoked your access token. This means that scripts using it will not work anymore. You can of course regenerate tokens for your need. The reason why we revoked it is that it gives access to everything on your account, including starting Spaces or Inference Endpoints that would cost you money. In the future, please be careful about what you share publicly 😉

I'm terribly sorry for forgetting to keep them in a .env

**Comment by Wauplin** [comment]
> I'm terribly sorry for forgetting to keep them in a .env

No worries! The best way to handle your token is to login by running `huggingface-cli login` on your machine. In a Space, it's best to use an [environment variable](https://huggingface.co/docs/hub/spaces-overview#managing-secrets).  Otherwise it's also fine to have them in your code but have to be extra careful not to share it with others :)

About your initial issue, any way we can help? (https://github.com/huggingface/huggingface_hub/issues/1632#issuecomment-1705457253)

**Comment by eben-vranken** [comment]
> > I'm terribly sorry for forgetting to keep them in a .env
> 
> 
> 
> No worries! The best way to handle your token is to login by running `huggingface-cli login` on your machine. In a Space, it's best to use an [environment variable](https://huggingface.co/docs/hub/spaces-overview#managing-secrets).  Otherwise it's also fine to have them in your code but have to be extra careful not to share it with others :)
> 
> 
> 
> About your initial issue, any way we can help? (https://github.com/huggingface/huggingface_hub/issues/1632#issuecomment-1705457253)

I was working on a work laptop and was not able to use huggingface-cli correctly due to how the permissions were set-up :/

**Comment by Wauplin** [comment]
In the end, is this issue solved or not? If not, what is the issue exactly? If it's resolved, we can close this issue :)

**Comment by eben-vranken** [comment]
I moved away from huggingface. Since I did not have the time frame to develop a space there. Interesting platform though.
