### ISSUE TITLE
Document more prominently the use of `hf_transfer`

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1652]
(from internal [slack thread](https://huggingface.slack.com/archives/C03V11RNS7P/p1694186667458409))

Let's promote it a bit more (e.g. in upload/download guides + in upload/download CLI) but still explain the existing limitations inherent to this solution (lack of feedback + some issues can still happen). 

cc @osanseviero @Narsil

**Comment by sifisKoen** [comment]
Hey @Wauplin could you please be more specific here? 

I have found `download.md` and `upload.md`, and as I can understand you want to improve these two markdowns. Am I right?

**Comment by Wauplin** [comment]
Hi @sifisKoen thanks for proposing your help on this :)
As I see it, we should add a section somewhere in the docs specifically about `hf_transfer` (what is it?, how to enable it?, what are the caveats?) and refer to this section from several places (in the upload/download guides, in the CLI,...). To be honest, I'd prefer to take care about it myself as I want to think about the content + structure a bit more -also discuss it internally with the Team. I created the issue mostly to avoid forgetting about it :smile: I'll let you know when I actually start to work on it.

**Comment by sifisKoen** [comment]
@Wauplin yep I understand no problem :smile:

**Comment by Wauplin** [comment]
Closed by https://github.com/huggingface/huggingface_hub/pull/1714.
