### ISSUE TITLE
[CLI] Support `--create-branch` option in huggingface-cli upload

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1657]
_Originally requested by @TheBloke on [slack](https://huggingface.slack.com/archives/C05FEPUFP6C/p1694449890883489?thread_ts=1694447769.928859&cid=C05FEPUFP6C) (private)_

> It'd be nice if it would also create a branch that didn't exist, or if there was a --create-branch boolean as it seems currently a branch (revision) has to exist before it can be uploaded to?

Q.: would we create it from `latest` or `orphan`. Might not be useful if https://github.com/huggingface/huggingface_hub/issues/1655 is implemented as well.

**Comment by kxhit** [comment]
HI @Wauplin 
Would also want to have such a feature that I can upload to a specific new branch in the hf-repo. This will typically be useful when I have a project but want to store different implementation's model ckpt.

**Comment by Wauplin** [comment]
@kxhit thanks for letting us know! @martinbrose started to work on the CLI to manage branches in https://github.com/huggingface/huggingface_hub/pull/1672. I think that if we have this, we'll keep the branch creation separated from the upload. You would have to launch 2 separate CLI commands, WDYT? Otherwise we could implement this one just after :)

**Comment by Wauplin** [comment]
Hi @kxhit thanks for letting us know. As I see it, it would require to:
- add a `--create-branch` argument [here](https://github.com/huggingface/huggingface_hub/blob/e3061b4623ac419b5169acbfa89b69f4a8a681b0/src/huggingface_hub/commands/upload.py#L83) and [here](https://github.com/huggingface/huggingface_hub/blob/e3061b4623ac419b5169acbfa89b69f4a8a681b0/src/huggingface_hub/commands/upload.py#L127)
- add a check in [`__init__`](https://github.com/huggingface/huggingface_hub/blob/e3061b4623ac419b5169acbfa89b69f4a8a681b0/src/huggingface_hub/commands/upload.py#L139) that `--create-branch` and `--create-pr` are not used at the same time (print message otherwise + `exit(1)`). Also same for `--every` that is a particular case that we don't want to handle (yet?) IMO
- add a check in [`__init__`](https://github.com/huggingface/huggingface_hub/blob/e3061b4623ac419b5169acbfa89b69f4a8a681b0/src/huggingface_hub/commands/upload.py#L139) that both `--create-branch` and `--revision` are used at the same time
- add a `create_branch(..., exists_ok=True)` call just after repo creation [here](https://github.com/huggingface/huggingface_hub/blob/e3061b4623ac419b5169acbfa89b69f4a8a681b0/src/huggingface_hub/commands/upload.py#L238)
- add a unit test for that

Would you like to open a PR for it?

**Comment by kxhit** [comment]
Hi, thanks for your guidance. I will take a look but I'm currently busy on my diffusion/diffusers project. It would be great if someone could contribute to it!

**Comment by Wauplin** [comment]
In the end we went for a simpler solution where branch is automatically create if it doesn't exist. Discussed in https://github.com/huggingface/huggingface_hub/issues/1841 and implemented in https://github.com/huggingface/huggingface_hub/pull/1857. 
Therefore closing this issue as "wont fix".
