### ISSUE TITLE
progress bar trims important part of filename: `Downloading (…)of-00081.safetensors`

### ISSUE THREAD

**Issue by poedator** [huggingface/huggingface_hub#1674]
The progress bar during model download trims the loaded file name to the last 20 characters. 
```
    # Truncate filename if too long to display
    if len(displayed_name) > 22:
        displayed_name = f"(…){displayed_name[-20:]}"

```
[link to trimming code.](https://github.com/huggingface/huggingface_hub/blob/42cfad6cb6a7f28a971475366af41135532a7829/src/huggingface_hub/file_download.py#L539-L541)

Quite often it leads to the confusion over what exactly is being loaded. Especially when using `.safetensors` ). 
Yet the progress bar moving line takes at least 1/3 of screen, but often much more (with wide terminals).

Example: 
```
Downloading (…)of-00081.safetensors: [progress bar for at least 1/3 of screen][value / total / time / speed]
Downloading (…)of-00081.safetensors: [progress bar for at least 1/3 of screen][value / total / time / speed]
Downloading (…)of-00081.safetensors: [progress bar for at least 1/3 of screen][value / total / time / speed]
...
```
I see these  possible improvements here (could be combined):
1) relax the 20 characters limit
2) make the character limit adaptive to screen width
3) adjust the size of the actual progress bar from present 1/3 of line length
4) instead of 15 chars `Downloading (…)` use 1 char prefix: `…`. Code:
```
    if len(displayed_name) > 35:
        displayed_name = f"…{displayed_name[-35:]}"
```

I'd be glad to make a quick PR once the maintainers express their preferences.
@Wauplin

**Comment by Wauplin** [comment]
Hi @poedator, thanks for asking the question :wink: I agree with you that the current solution is not ideal, especially on large terminal. However, I would prefer not to enter the world of maintaining an adaptive limit size (can start to be a nightmare to be cross-platform) just for a slight UI improvement. 
What I'd be fine to do however is to remove the "Downloading" prefix as you suggested in _4._ given how little information it provides. Let's also relax the characters limit to 40. With both changes, it should now be fine to disambiguate enough cases. Let's remember it's only for convenience that we display this info so I prefer not to over-engineer it.

```py
    if len(displayed_name) > 40:
        displayed_name = f"…{displayed_name[-40:]}"
```

**Comment by poedator** [comment]
Hi, @Wauplin!
I agree that the simplest solution should be best here. [My 3-line pull request](https://github.com/huggingface/huggingface_hub/pull/1679) is based on your suggestion and is ready for your review .

**Comment by Wauplin** [comment]
Great, thanks for the PR. Looks great, I merged it :hugs:
