### ISSUE TITLE
Add `--filename` support for `git lfs track`

### ISSUE THREAD

**Issue by cccntu** [huggingface/huggingface_hub#168]
We need this to reliably track individual file with their file names.

Here in the doc:
https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-track.1.ronn

> `git lfs track --filename "project [1].psd"`

relevant issue #138 (identify large files and track by their file names.)

**Comment by julien-c** [comment]
Should be fairly easy to add (though the number of cases where it's needed, vs. a pattern, is fairly small – need to have a `{*, ?, [, ]}` in your filename)

**Comment by cccntu** [comment]
Yes, I just think it's safer when I read the man page.
