### ISSUE TITLE
Non-blocking `git_push`

### ISSUE THREAD

**Issue by cccntu** [huggingface/huggingface_hub#169]
On local machine, the push can take a while, but usually there is no need to wait for it to complete, it would be great to keep training while the `git-push` uploads model in background. 
This can be done by replacing `subprocess.run` with `subprocess.Popen`.
 https://github.com/huggingface/huggingface_hub/blob/0d185de837846859668a0ee5b1aa5ef71a4f9ac4/src/huggingface_hub/repository.py#L431

**Comment by LysandreJik** [comment]
I think that's a solid idea! We could have a flag to control the behavior; by default, it would be blocking, with the option to spin it in a non-blocking subprocess.

**Comment by osanseviero** [comment]
What would happen in this scenario in the case `git push` has errors for some reason? Will they be hidden?

**Comment by cccntu** [comment]
In my implementation, the stderr and stdout are inherited from parent, so you will see the output, but the error will be ignored.
I think error in push is mostly fine, as long as the commit is done and the repo is not removed (e.g. using temp dir to clone and push). 
This is intended for more custom behavior that directly calls `git_push`, you can set `non_blocking=True` during training, and `non_blocking=False` after training is finished.

**Comment by LysandreJik** [comment]
I believe this was closed by #315 :)
