### ISSUE TITLE
Return the liked users for for a huggingface model

### ISSUE THREAD

**Issue by abstrcode** [huggingface/huggingface_hub#1705]
Currently, the is a function "list_liked_repos" to list user-liked models by inputting the user name. It would be better to have a function that outputs the list of liked users for a given model.

**Comment by Wauplin** [comment]
Hi @abstrcode, thanks for raising the question. It is currently not possible to get this information in `huggingface_hub` but an API endpoints exists for it. For example for [mistralai/Mistral-7B-v0.1](https://huggingface.co/mistralai/Mistral-7B-v0.1) model: https://huggingface.co/api/models/mistralai/Mistral-7B-v0.1/likers.

We can definitely add a method in `huggingface_hub` to wrap it:

```py
class HfApi:
    (...)

    def list_repo_likers(self, repo_id: str, *, repo_type: Optional[str] = None, token: Optional[str] = None) -> List[User]:
        (...)
```

Would you like to open a PR for that? I can give some guidance about what to update and where. First step would be to implement this method and create a `User` data type for the returned value (with `fullname`, `avatarUrl` and `name`). Then a test should be added in `tests/test_hf_api.py`.

WDYT?

**Comment by julien-c** [comment]
yes, would be a https://github.com/huggingface/huggingface_hub/labels/good%20first%20issue

**Comment by Wauplin** [comment]
Hi @issamarabi , the implementation would be very similar to `get_spaces_variables` for example (see [code here](https://github.com/huggingface/huggingface_hub/blob/5d2d297084b230d7725b9ccafe6eb9a7f7c9a40e/src/huggingface_hub/hf_api.py#L5486)). You have to build the URL given an endpoint+repo_id+repo_type, build the headers given the token and make the call (no parameters/no payload). Then the output must be parsed correctly as a `User` dataclass (that has to be defined as well). Would you be interested in opening a PR?
