### ISSUE TITLE
Thoughts: `stream`ing for `conversational`

### ISSUE THREAD

**Issue by jamesbraza** [huggingface/huggingface_hub#1729]
I am implementing a Hugging Face Inference API wrapper for [LlamaIndex](https://www.llamaindex.ai/) ([repo](https://github.com/run-llama/llama_index)). I am subclassing its `LLM` object, and need to implement methods like `chat` and `stream_chat`: https://github.com/run-llama/llama_index/blob/v0.8.42/llama_index/llms/base.py#L363

It seems like `InferenceClient.conversational` is the function to use in `chat`, but I can't use it in `stream_chat`.

Any thoughts on exposing `stream` as an argument in `conversational`?  Does it make sense to have a streaming endpoint for `conversational`?

**Comment by Wauplin** [comment]
Hey @jamesbraza, `InferenceClient.conversational` is designed to support the conversational pipeline from `transformers` (see https://huggingface.co/tasks/conversational). This is not to use with LLMs hosted with TGI for example. As far as I understand, for a chat-based task you will have to encode the messages into a prompt before sending the request with `InferenceClient.text_generation`. Then you will have to decode the generated message for you. This can be done using [chat-templates](https://huggingface.co/docs/transformers/main/chat_templating) and especially `tokenizer.apply_chat_template`. AFAIK, chat templates are not meant to be directly applied by TGI.

cc @Rocketknight1 who worked on chat templates (https://github.com/huggingface/transformers/pull/25323) (cc @LysandreJik as well).

**Comment by Rocketknight1** [comment]
I don't think chat templates are necessary to decode the output! Chat templates encode the input conversation, but generally the output message is just generated with a standard `generate()` method. cc @gante - do we have any clean way to stream outputs from `generate`?

**Comment by Wauplin** [comment]
Yes sorry my mistake! So @jamesbraza you would have to use `tokenizer.apply_chat_template` to encode the message and then `InferenceClient.text_generation(.., stream=True)` to stream tokens generated by the server!

> @gante - do we have any clean way to stream outputs from generate?

We are talking about InferenceClient + TGI integration here so streaming is already handled @Rocketknight1 , thanks!

**Comment by jamesbraza** [comment]
> `InferenceClient.conversational` is designed to support the conversational pipeline from `transformers` (see [huggingface.co/tasks/conversational](https://huggingface.co/tasks/conversational)). This is not to use with LLMs hosted with TGI for example.

Of the tasks in https://huggingface.co/tasks/, which are supported with TGI?  It's not clear to me from looking at their pages.

Also, how would `text_generation` support chat history (it seems to just be one-shot)?  Is that what you were talking about with `tokenizer.apply_chat_template`?

**Comment by Wauplin** [comment]
> Of the tasks in https://huggingface.co/tasks/, which are supported with TGI? It's not clear to me from looking at their pages.

TGI (text-generation-inference) is only meant for the `text-generation` task.

> Also, how would text_generation support chat history (it seems to just be one-shot)? Is that what you were talking about with tokenizer.apply_chat_template?

[Chat-templating](https://huggingface.co/docs/transformers/main/chat_templating) is the process to turn all the chat history into a single prompt. So yes for each "new message" from the user you need to encode all the history using `tokenizer.apply_chat_template`, and send to text inference to generate the "response".

**Comment by jamesbraza** [comment]
Alright thanks for answering.  So my takeaways so far are, starting with backends:
- Text Generation Inference (TGI) backend: supports streaming
- `transformers` backend: doesn't support streaming

Then for the tasks:
- Text generation task can be backed by TGI, thus it can support streaming
- Conversational task is only backed by `transformers`, thus it does not support streaming

---

Is there some way the conversational task can support streaming?  Or is that just totally unsupported

**Comment by Wauplin** [comment]
@jamesbraza Yes, that's a good summary! About your last question, it is very likely that the conversational task in `transformers` will never support streaming as it is not designed in that way (compared to TGI that is inference-focused).

It is good for you to close this issue then?

**Comment by jamesbraza** [comment]
Yep, all good, cheers!
