### ISSUE TITLE
Request: leaderboard for models in `InferenceClient.list_deployed_models`

### ISSUE THREAD

**Issue by jamesbraza** [huggingface/huggingface_hub#1741]
You can query models usable with the Inference API using `InferenceClient.list_deployed_models`.

I am trying to figure out which one to use for text to SQL, and thus think it would be cool if there was a mini-leaderboard for the models hosted.

It could be shown on task pages like https://huggingface.co/tasks/text-generation

**Comment by jamesbraza** [comment]
Maybe a higher level question is, if one were to want to query the best model for text generation task, how would one go about that?  A leaderboard is one way to make that easy to figure out

**Comment by Wauplin** [comment]
Hey @jamesbraza :wave: Building a generic leaderboard is no easy job as the range of downstream tasks is very diverse. One leaderboard that is becoming a reference for that is the [🤗 Open LLM Leaderboard](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard) so make sure to give it a look! (cc @clefourrier)

**Comment by Wauplin** [comment]
That said, I don't plan to update the `huggingface_hub` library to incorporate the LLM Leaderboard data in `list_deployed_models`. In any case if you know which task you want to achieve (e.g. "text-to-SQL") you need to check which benchmark/leaderboards are interesting for you and chose the model accordingly. @clefourrier made a Collection of the [LLM leaderboards and benchmarks](https://huggingface.co/collections/clefourrier/llm-leaderboards-and-benchmarks-%E2%9C%A8-64f99d2e11e92ca5568a7cce) out there.

Also don't forget that `InferenceAPI` is a service built to try out models easily so don't hesitate to do so with your specific examples.

**Comment by jamesbraza** [comment]
Thank you @clefourrier for the great response! 🥳 

I also agree with what you're saying on further ways to constrain the leaderboard's output.

The [Open LLM Leaderboard](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard) supports the query field in the LLM Benchmark. Here's how I made the query:

```python
text_generation_models = client.list_deployed_models("all")["text-generation"]
print(str(text_generation_models)[1:-1].replace("'", "").replace(",", ";"))
```

Thought not all leaderboards have that querying capability, for example the [MTEB Leaderboard](https://huggingface.co/spaces/mteb/leaderboard).  So that suggestion is good, just it's not universally applicable.

I think it would be useful if Hugging Face had an extension on the `InferenceClient` for programmatically integrating with and filtering choices leveraging known-reputable leaderboards.

**Comment by Wauplin** [comment]
> I think it would be useful if Hugging Face had an extension on the InferenceClient for programmatically integrating with and filtering choices leveraging known-reputable leaderboards.

That's a good idea but as a first step I would prefer to have it as a community-contributed tool outside of `huggingface_hub`. Selecting a "good model" is a very subjective question and the simple fact to design an API to allow users to filter models based on some leaderboards is already a task on its own.

**Comment by jamesbraza** [comment]
Okay I follow!  I will close this out as resolved then, feel free to reopen anyone/anytime
