### ISSUE TITLE
`InferenceClient.feature_extraction` allowing for `List[str]`

### ISSUE THREAD

**Issue by jamesbraza** [huggingface/huggingface_hub#1745]
I believe the feature extraction task can support `List[str]` (not just `str` as it does in v0.18.0).

Fwiw, this is how LangChain does it: https://github.com/langchain-ai/langchain/blob/v0.0.314/libs/langchain/langchain/embeddings/huggingface.py#L323

**Comment by Wauplin** [comment]
As explained in https://github.com/huggingface/huggingface_hub/pull/1746#issuecomment-1766640525 I would prefer not to support `List[str]`, in order to keep the API minimal.
