### ISSUE TITLE
Improve download display for end users

### ISSUE THREAD

**Issue by rsxdalv** [huggingface/huggingface_hub#1747]
https://github.com/huggingface/huggingface_hub/blob/3ae8d53cd0bd2be11ba531674e01186ed5eee2ef/src/huggingface_hub/file_download.py#L990

Users of my project are suggesting that the downloads better highlight a) size of the download b) where it is being stored.
I think some the size information is partially being shown but the location could also be highlighted.

Here's the discussion: https://github.com/rsxdalv/tts-generation-webui/discussions/186

**Comment by Wauplin** [comment]
Hey @rsxdalv, I am not sure where/how you would prefer to have this information. At the moment:
- `hf_hub_download` returns the path to the cached file
- `snapshot_download` returns the path to the cached folder
- downloading a huge file displays a progress bar with the remaining time + file size:
```
decoder_model_merged.onnx:   3%|███▋                                                                                                               | 21.0M/655M [01:26<35:37, 297kB/s]
```
- at `INFO` level, we log the URL
```
downloading https://huggingface.co/gpt2/resolve/11c5a3d5811f50298f278a704980280950aedb10/README.md to /home/wauplin/.cache/huggingface/hub/tmpnjup4c8c
```
- at `DEBUG` level, we have more logs: symlink creation, moving files,...

About cache management, the best resource we have to understand how it works and how to configure it is [this guide](https://huggingface.co/docs/huggingface_hub/guides/manage-cache).

---

Please let me know if you have a more precise suggestion on what to add/what to change. Thank you in advance!

**Comment by rsxdalv** [comment]
Thank you for the detailed response! It's a great usage of log levels, and perhaps enabling users access to these would already give them the full awareness they are looking for.

If I was to go by the original post I received, I would ask - would it make sense to add:
```
Saved to ...
```
when using INFO?

I understand that this information is API accessible but here's what I'm stacked up against: newer models, such as Bark, have fully embraced the hub and have this code backed into them. Getting this information would require changing the model's code. Meanwhile, if I want to support a pipeline of functions, I'm bound to have multiple models (i.e. generation + upscaling).

**Comment by rsxdalv** [comment]
Sorry I reread the original and noticed that there's the file path as well. In this case, INFO should be all I need, great!

**Comment by Wauplin** [comment]
Ah, great to hear! I was about to dig again into to look at what I could change but let's not change anything then. Ok for you to close the issue now?

**Comment by rsxdalv** [comment]
Tell you what, I will close but if there's someone else or if I have a problem I will reopen.
Thank you!

**Comment by Wauplin** [comment]
Yes sure, feel free to reopen any time! :hugs:
