### ISSUE TITLE
How can I search a ner model with date and money label in the HuggingFace website? Should I enter the homepage of every ner model and look what label it support?

### ISSUE THREAD

**Issue by Chanwb** [huggingface/huggingface_hub#1748]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Wauplin** [comment]
> How can I search a ner model with date and money label in the HuggingFace website? Should I enter the homepage of every ner model and look what label it support?

I'm afraid yes, that's the way to go. AFAIK there is no proper metadata for NER labels on the Hub (but also in general). I don't know your use case but what I would try to do in your case is to find datasets related or similar to the data you have and then check which models are trained on it.

For more information about token classification (and therefore NERs), check out [this page](https://huggingface.co/tasks/token-classification).

**Comment by julien-c** [comment]
for transformers models, the label classes mapping is encoded in the model's `config.json` – but yes this will require some specific development to be able to iterate on all models and check out their labels

**Comment by Wauplin** [comment]
Will closed this issue since no answer + not really related to `huggingface_hub` itself. Feel free to reopen if you have further questions :)
