### ISSUE TITLE
Request: `InferenceClient` being able to query model metadata

### ISSUE THREAD

**Issue by jamesbraza** [huggingface/huggingface_hub#1751]
As part of my effort to bring Hugging Face Inference API to [LlamaIndex](https://github.com/run-llama/llama_index), I need to implement `LLMMetadata`. Here is [a PR](https://github.com/run-llama/llama_index/pull/8144/files) where I add a `description` for each attribute there, so you can see what fields I need to populate.  The work in progress PR for the Hugging Face Inference API is https://github.com/run-llama/llama_index/pull/8098.

Ideally, I can use `InferenceClient` to somehow query model metadata from Hugging Face to infer information like context window, max output size, or if chatting is supported.  From what I am reading in the docs, the `InferenceClient` doesn't yet have a `get_model_info`-like function supported.

This is halfway a question and halfway a request:
- Is there a way to query model metadata using `InferenceClient`?
- If not, can we add that capability?

**Comment by Wauplin** [comment]
@jamesbraza all models served on InferenceAPI are hosted on the Hugging Face Hub meaning that you can use [`model_info`](https://huggingface.co/docs/huggingface_hub/v0.18.0.rc0/en/package_reference/hf_api#huggingface_hub.HfApi.model_info) to get information about them. In general, anything to query the Hub will be under `HfApi` while you'll use `InferenceClient` only to perform the inference. That being said I am not sure all the information you require is exposed via API as the Hub is not focused on LLM. 

In general I would say:
- `context_window`: depends on the model. Maybe you'll have to look into the `config.json` file (meaning you need to download it using `hf_hub_download`)
- `num_output`: depends but you can set it as parameter value if that's easier
- `is_chat_model`: as discussed in https://github.com/huggingface/huggingface_hub/issues/1729 LLMs served via TGI on the Hub are not chat models except if you apply a chat -template preprocessing.
- `is_function_calling_model`: no
- `model_name`: just use the model id

**Comment by jamesbraza** [comment]
Thank you @Wauplin ! I appreciate you helping me work through these fields one at a time. I upstreamed your knowledge to LlamaIndex `description` fields.

I am going to close this in favor of https://github.com/huggingface/huggingface_hub/issues/1759.
