### ISSUE TITLE
Facing issue no module named Newspaper

### ISSUE THREAD

**Issue by Shoaib-33** [huggingface/huggingface_hub#1752]
altair==4.2.2
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz#sha256=06c80936324012d1223291d2af41a5229e746dc2dee8fe31a532666ee3d18aaa

gTTS==2.3.2

h5py==3.9.0

matplotlib==3.7.1

newspaper3k==0.2.8

nltk==3.8.1
numpy==1.23.5

pandas==2.1.0

googletrans==4.0.0rc1

scikit-learn==1.3.0

streamlit==1.22.0

tensorboard==2.12.3

tensorflow==2.12.0

textblob==0.17.1

wordcloud==1.9.2

yake==0.4.8

I am using this in my requirements.txt and also using python version 3.9.17 the same one I used for this locally but when i am deploying in huggingface space it is saying no module named "Newspaper" whereas it is already present in requirements.txt. How can i solve this issue??

**Comment by Wauplin** [comment]
Hey @Shoaib-33 could you share which Space it is? And could you check also the build logs to see if the dependencies are installed? Also can it be simply a problem with the import (`import newspaper` instead of `import Newspapers`). 
Without more information is it hard to help :)
