### ISSUE TITLE
Request: `model_info` opt-in inclusion of `config.json` under `ModelInfo.config`

### ISSUE THREAD

**Issue by jamesbraza** [huggingface/huggingface_hub#1759]
**Is your feature request related to a problem? Please describe.**

`config.json` files have a lot of meaningful info, and I think it should be part of `ModelInfo.config` from `model_info`. Currently, `ModelInfo.config` has just a small amount of metadata:

```python
from huggingface_hub import InferenceClient, model_info
from huggingface_hub.hf_api import ModelInfo

client = InferenceClient(model="HuggingFaceH4/zephyr-7b-alpha")
info: ModelInfo = model_info(client.model)
print(info.config)
# {'architectures': ['MistralForCausalLM'], 'model_type': 'mistral'}
```

However, https://huggingface.co/HuggingFaceH4/zephyr-7b-alpha/blob/main/config.json has a lot of meaningful metadata.

**Describe the solution you'd like**

I propose creating an opt-in flag for `model_info` that includes the contents of `config.json`.

**Describe alternatives you've considered**

Manually:

1. Downloading `config.json` to a temporary file
2. Importing to a `dict`

**Additional context**

N/a

**Comment by Wauplin** [comment]
cc @osanseviero @julien-c who might know more about what data is returned in the `info.config` object and what are the reason behind. 

And just as curiosity, what useful information/use case would be interesting for you in https://huggingface.co/HuggingFaceH4/zephyr-7b-alpha/blob/main/config.json?

**Comment by Wauplin** [comment]
(and just for the sake of completeness, the current way of getting this info would be to do:

```py
import json
from huggingface_hub import hf_hub_download

def get_config(model_id: str) -> dict:
    path = hf_hub_download(model_id, "config.json")  
    with open(path) as f:
        return json.load(f)

# will raise `huggingface_hub.utils.EntryNotFoundError` if config.json doesn't exist on repo
```
which is suboptimal (requires to download+cache the file) but "it works")

**Comment by jamesbraza** [comment]
Thanks for sharing that `hf_hub_download` technique, I will use that for now.  And I realized tempfile isn't necessary since behind the scenes it uses Hugging Face's cache directory.

Two examples of `config.json` inclusion enabling automatic discerning:

- Embedding size of models like [BAAI/bge-large-en-v1.5](https://huggingface.co/BAAI/bge-large-en-v1.5).  The output dimensions of `InferenceClient.feature_extraction` is its `hidden_size` of 1024, which can be found in its `config.json`
- Allowable context window as per https://github.com/huggingface/huggingface_hub/issues/1751

**Comment by julien-c** [comment]
yes, that's the way to go IMO: if you want all of config.json, the way to go is to download/load the actual file

**Comment by osanseviero** [comment]
Config files for some repos can be huge, so at the moment we have an allowlist of which fields are returned in `model_info` to keep the load small. Using `hf_hub_download` to obtain the config info is indeed the way to go!

**Comment by Wauplin** [comment]
Thanks for the additional inputs @julien-c @osanseviero. I'll close this issue as "not planned" then :)

**Comment by jamesbraza** [comment]
One related question is, are config files set up against a known schema?

I don't think I fully agree per the `hf_hub_download` solution, because it uses the Hugging Face cache, which exists in a local filesystem (by default). For most use cases, `InferenceClient` can run in a Python process without a local filesystem present.

Ideally the config can just be in the JSON blob coming back from Hugging Face inference API.

**Comment by Wauplin** [comment]
> One related question is, are config files set up against a known schema?

Not necessarily no. `transformers` defines its own schema for example (though I'm not sure we have a proper spec somewhere given the vast diversity of supported models) but the Hugging Face Hub itself doesn't enforce any schema as it is a "library-agnostic" (or at least semi-agnostic).

> I don't think I fully agree per the hf_hub_download solution, because it uses the Hugging Face cache, which exists in a local filesystem (by default). For most use cases, InferenceClient can run in a Python process without a local filesystem present.

If you want to access files without using the cache system, you can use the `HfFileSystem` (see [guide](https://huggingface.co/docs/huggingface_hub/guides/hf_file_system)). Here is a snippet to load json data from a remote file: 

```py
import json
from huggingface_hub import HfFileSystem

fs = HfFileSystem()

with fs.open("HuggingFaceH4/zephyr-7b-alpha/config.json", "r") as f:
    data = json.load(f)
```

**Comment by julien-c** [comment]
or you can `request.get` a remote file and keep it as a string in memory `requests.get(hf_hub_url(...)).json()`
