### ISSUE TITLE
Repo set up: autolinks for Hugging Face

### ISSUE THREAD

**Issue by jamesbraza** [huggingface/huggingface_hub#1760]
GitHub repos supports autolinks (like they do with issues and PRs): https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-autolinks-to-reference-external-resources

For this repo, it would be https://github.com/huggingface/huggingface_hub/settings/key_links.

It would enable auto-converting https://huggingface.co/BAAI/bge-large-en-v1.5 to [BAAI/bge-large-en-v1.5](https://huggingface.co/BAAI/bge-large-en-v1.5).

I just think this would be a nice repo set up things for Hugging Face repos.

**Comment by Wauplin** [comment]
Thanks for the suggestion but I quickly had a look and I don't think we can easily configure this. The "num" reference for `https://huggingface.co/BAAI/bge-large-en-v1.5` would be `BAAI/bge-large-en-v1.5` but GH only allows alphanumerical or numerical identifiers. (like `https://jira.example.com/issue?query=123` for example)

![image](https://github.com/huggingface/huggingface_hub/assets/11801849/0c6ead33-fc31-4d33-bddf-668441e026b0)

Nevertheless a TIL for me :smile:
