### ISSUE TITLE
Hitting usage limits, what are rate limits for Pro?

### ISSUE THREAD

**Issue by jamesbraza** [huggingface/huggingface_hub#1762]
Today I was doing a parameter sweep with the Inference API, and hit a rate limit :/

Please forgive me, but I don't know where else to ask this. It seems similar questions in the Hugging Face forums all went unanswered. For $9/month Pro, https://huggingface.co/subscribe/pro:

> Higher rate limit for the Free Inference API

This is vague in that I don't know how many more queries/hr one gets by paying $9/month.  Is anyone here able to point me to docs actually stating what is the rate limit for free tier, and what is the rate limit for pro tier (or other upgrades)?

**Comment by Wauplin** [comment]
Hey @jamesbraza, rate limits are dependent on the traffic and load, but always extremely high (meaning good enough for prototypes, demos and small products). For more production-ready use cases we encourage looking into [inference endpoints](https://huggingface.co/docs/inference-endpoints/index). cc @osanseviero

**Comment by jamesbraza** [comment]
Thanks for sharing! Yeah just when I buy something, I like to know concretely what I am paying for. I am wishing there was more concrete info on the increased limits for Pro, like what % more requests comes with Pro, or an increased count of requests/hr.

I think Inference Endpoints is a good example of explicit on what you get with pricing: https://huggingface.co/pricing#endpoints
