### ISSUE TITLE
Support `src_lang`/`tgt_lang` in `InferenceClient.translation()`

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1763]
_Originally from @LysandreJik :_

For some models (and some models only), it is possible to specify a source and target language in `transformers` and InferenceAPI. It would be nice to support it in `InferenceClient` as well. Example: [facebook/mbart-large-50-many-to-many-mmt](https://huggingface.co/facebook/mbart-large-50-many-to-many-mmt)

```py
from huggingface_hub import InferenceClient

data = InferenceClient().post(
    json={
        "inputs": "My name is Sarah Jessica Parker but you can call me Jessica",
        "parameters": {"src_lang": "en_XX", "tgt_lang": "fr_XX"},
    },
    model="https://api-inference.huggingface.co/models/facebook/mbart-large-50-many-to-many-mmt",
)

print(data)
```
```
b'[{"translation_text":"Mon nom est Sarah Jessica Parker mais vous pouvez m\'appeler Jessica"}]'
```

---
TODO:
- [ ] add both parameters `src_lang: Optional[str] = None` and `tgt_lang: Optional[str] = None` to [`InferenceClient.translation`](https://github.com/huggingface/huggingface_hub/blob/89cc69105074f1d071e0471144605f3cdfe1dab3/src/huggingface_hub/inference/_client.py#L1697)
- [ ] raise a ValueError if only one of them is set but not the other (?)
- [ ] send them as "parameters" only if not None
- [ ] add test with `facebook/mbart-large-50-many-to-many-mmt`
- [ ] update docstring

**Comment by AkshathRaghav** [comment]
@Wauplin I'd like to work on this. Could you tell me how I can find all the models which support these params?

**Comment by Wauplin** [comment]
Hi @AkshathRaghav, thanks for proposing your help on this one! :pray: Unfortunately, there is no easy way to list models supporting these parameters. This is why it should be made clear in the docstring that it is at the user discretion to select a model that handles them. In general, the information will be found in the Model Card of the model on the Hub (along with the list of support language codes).

Therefore as a first step, I would simply implement the feature in `InferenceClient` for users that want to use it. Then in a second time, and if there is some demand, we could try to find a way to suggest models that support them but it's not trivial (that's the counterpart of having a versatile `transformers` library).

**Comment by Wauplin** [comment]
Closing this issue thanks to https://github.com/huggingface/huggingface_hub/pull/1869 by @ceferisbarov ! :rocket: 

```py
>>> from huggingface_hub import InferenceClient
>>> client = InferenceClient()
>>> client.translation("My name is Sarah Jessica Parker but you can call me Jessica", model="facebook/mbart-large-50-many-to-many-mmt", src_lang="en_XX", tgt_lang="fr_XX")
"Mon nom est Sarah Jessica Parker mais vous pouvez m'appeler Jessica"
>>> client.translation("My name is Sarah Jessica Parker but you can call me Jessica", model="facebook/mbart-large-50-many-to-many-mmt", src_lang="en_XX", tgt_lang="es_XX")
'Mi nombre es Sarah Jessica Parker pero puedes llamarme Jessica'
```
