### ISSUE TITLE
Endpoint cannot support http:// protocol with proxy

### ISSUE THREAD

**Issue by gaius-qi** [huggingface/huggingface_hub#1764]
### Describe the bug

If endpoint is `http://huggingface.co` and use `http` proxy, can not donwload the file.

```python
from huggingface_hub import hf_hub_download
hf_hub_download(endpoint="http://huggingface.co", repo_id="gaius-qi/dragonfly", filename="README.md", proxies={'https': 'http://127.0.0.1:65001', 'http': 'http://127.0.0.1:65001'})
```

```shell
python3 hf_hub_download.py
```

### Logs

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/file_download.py", line 1252, in hf_hub_download
    raise FileMetadataError(
huggingface_hub.utils._errors.FileMetadataError: Distant resource does not seem to be on huggingface.co. It is possible that a configuration issue prevents you from downloading resources from https://huggingface.co. Please check your firewall and proxy settings and make sure your SSL certificates are updated.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hf_hub_download_dragonfly.py", line 2, in <module>
    hf_hub_download(endpoint="http://huggingface.co", repo_id="gaius-qi/dragonfly", filename="README.md", proxies={'https': 'http://127.0.0.1:65001', 'http': 'http://127.0.0.1:65001'})
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/file_download.py", line 1363, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
```

### System info

```shell
- Huggingface Version: v0.18.0
- Python Verison: 3.9.10
```

**Comment by gaius-qi** [comment]
Requires support for forcing the use of the `http://` protocol and using an `http://` proxy to forward traffic, which allows for faster transfer of large files.

**Comment by Wauplin** [comment]
Hi @gaius-qi, sorry you are facing this issue. Could you try to run the following snippet and report back with the error/output you get for each of the 4 tests?

```py
import requests
from huggingface_hub import get_hf_file_metadata

http_url = "http://huggingface.co/gaius-qi/dragonfly/resolve/main/README.md"
https_url = "http://huggingface.co/gaius-qi/dragonfly/resolve/main/README.md"
proxies = {"https": "http://127.0.0.1:65001", "http": "http://127.0.0.1:65001"}

get_hf_file_metadata(http_url, proxies=proxies)
get_hf_file_metadata(https_url, proxies=proxies)
requests.head(http_url, proxies=proxies)
requests.head(https_url, proxies=proxies)
```

This is just a simpler version of the code, without all the HF-logic around the HTTP call.

**Comment by gaius-qi** [comment]
@Wauplin 

```python
import requests
from huggingface_hub import get_hf_file_metadata

http_url = "http://huggingface.co/gaius-qi/dragonfly/resolve/main/README.md"
https_url = "http://huggingface.co/gaius-qi/dragonfly/resolve/main/README.md"
proxies = {"https": "http://127.0.0.1:65001", "http": "http://127.0.0.1:65001"}

get_hf_file_metadata(http_url, proxies=proxies)
get_hf_file_metadata(https_url, proxies=proxies)
r1 = requests.head(http_url, proxies=proxies)
r2 = requests.head(https_url, proxies=proxies)
print("Status Code: " + str(r1.status_code))
print("Status Code: " + str(r2.status_code))
```

Response:
```text
Status Code: 301
Status Code: 301
```

`http://huggingface.co` redirects to `https://huggingface.co` with 301 status code.

Can we visit `http://huggingface.co` directly without redirect(301)?

**Comment by Wauplin** [comment]
> Can we visit http://huggingface.co directly without redirect(301)?

No I don't think so cc @XciD

**Comment by Wauplin** [comment]
> Requires support for forcing the use of the http:// protocol and using an http:// proxy to forward traffic, which allows for faster transfer of large files.

If you want faster transfer, you can look at `hf_transfer` and the [`$HF_HUB_ENABLE_HF_TRANSFER`](https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfhubenablehftransfer) environment variable. It is still https-based and runs faster thanks to a Rust-based library (and parallelism)

**Comment by gaius-qi** [comment]
@Wauplin @XciD Thanks

**Comment by gaius-qi** [comment]
@Wauplin Can you provide a solution to use other SDKs when downloading files, because we hope to increase the download speed of large models by passing the Huggingface SDK download traffic through [Dragonfly](https://github.com/dragonflyoss/Dragonfly2).

**Comment by gaius-qi** [comment]
> @Wauplin Can you provide a solution to use other SDKs when downloading files, because we hope to increase the download speed of large models by passing the Huggingface SDK download traffic through [Dragonfly](https://github.com/dragonflyoss/Dragonfly2).

Replace the downloaded function with plugin.

**Comment by Wauplin** [comment]
> Can you provide a solution to use other SDKs when downloading files, because we hope to increase the download speed of large models by passing the Huggingface SDK download traffic through [Dragonfly](https://github.com/dragonflyoss/Dragonfly2).

To answer the first question, we did not have in mind to be able to plug different download SDKs when building `huggingface_hub`. You can maybe monkeypatch the `huggingface_hub.file_download.http_get` method but that would be at your own risks.

**Comment by Wauplin** [comment]
I'll close this issue given that we'll not support http in any case. Please let us know if you have more questions about how to use `huggingface_hub` or feedback about new features.

**Comment by ketaiq** [comment]
For anyone who uses `v2ray` as a proxy tool, you should do following steps:

1. Set up **socks** proxy on the port 1080 and **http** proxy on the port 1081 using the `config.json` file of `v2ray`.
2. Add the argument `proxies={"https": "http://127.0.0.1:1081", "http": "socks5://127.0.0.1:1080"}` to the place you call the function `hf_hub_download` or any similar function for downloading models.

**Comment by yaner-here** [comment]
> For anyone who uses `v2ray` as a proxy tool, you should do following steps:
> 
> 1. Set up **socks** proxy on the port 1080 and **http** proxy on the port 1081 using the `config.json` file of `v2ray`.
> 2. Add the argument `proxies={"https": "http://127.0.0.1:1081", "http": "socks5://127.0.0.1:1080"}` to the place you call the function `hf_hub_download` or any similar function for downloading models.

It works well for me. I didn't expect that it's impossible to connect a `https` url via http proxy protocal. After using socks5 proxy, it works.
