### ISSUE TITLE
Request: discerning what the default model is when using `InferenceClient` without a `model`

### ISSUE THREAD

**Issue by jamesbraza** [huggingface/huggingface_hub#1767]
When doing something like the below:

```python
client = InferenceClient()  # NOTE: no model specified
client.feature_extraction("hi")
```

It would be cool to know what model is being used behind the scenes.  How can one figure this out programmatically?

I am thinking there may be a need for a new `InferenceClient` method resembling the following:

```python
    def get_default_model(task: str) -> str:
        """Get the model's name used by default for the input task."""
```

**Comment by Wauplin** [comment]
Definitely a good idea yes!
Would you like to open a PR for it? It should be relatively straightforward with the existing code.

**Comment by Wauplin** [comment]
Yes exactly, it's basically exposing `_get_recommended_model`. Maybe you can make it a staticmethod of `InferenceClient` for ease of use :) Thanks in advance!

**Comment by jamesbraza** [comment]
@Wauplin any chance you'd be willing to cut a new release after this PR is merged?

**Comment by Wauplin** [comment]
> any chance you'd be willing to cut a new release after this PR is merged?

Hey @jamesbraza! So I merged your PR, thanks for the changes :hugs: About a new release, I'd prefer to wait a bit. We don't have much to add to a release yet and making a release takes quite some time for me (draft + review release notes, make prerelease, test external HF libs, make release, communicate about it,...). I will let you know once we have more to add to a release -most probably within 2 weeks-. In the meantime you can install `huggingface_hub` [from source](https://huggingface.co/docs/huggingface_hub/installation#install-from-source) and already benefit from the code changes.

**Comment by jamesbraza** [comment]
Oh gotchu, sounds good! One comment is you could add integration testing with external HF libs to the `pytest` suite, to at least automate that step. I wouldn't be afraid to have a "less featured" release every so often. I do admire your super well done release notes though.

I will add this new feature into LlamaIndex upon the next release of `huggingface_hub`, so I will be patiently waiting 🤓

**Comment by Wauplin** [comment]
> One comment is you could add integration testing with external HF libs to the pytest suite, to at least automate that step. I wouldn't be afraid to have a "less featured" release every so often. I do admire your super well done release notes though.

Thanks for the kind words :hugs: Yes automating the release process is something I'm willing to do as well (and it's already far better than a few months ago, believe me! :smile:). At the moment what we do is to trigger the other CIs since transformers/diffusers have very specific settings to run the CI (and I don't want to duplicate it). We could have some specific integration tests but it feel safer to rerun all tests. In any case, I'll let you know when I start to move forward on it so that `LlamaIndex` can benefit from it :)

**Comment by Wauplin** [comment]
Hey @jamesbraza! Release `0.19.0` is shipped, including your work on the `InferenceClient` :fire: 
Thanks again for your contributions and let me know how the integration with LlamaIndex goes! Don't hesitate to ping me on a PR if needed :)
