### ISSUE TITLE
Raise RepositoryNotFoundError if repository is not found when adding a repo to a collection

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#1769]
At the moment, when adding a repo to a collection, I get the following error. I think a `RepositoryNotFoundError` might be a better fit, but no strong opinion as I understand it would not encapsulate papers 

```
HfHubHTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/collections/osanseviero/historical-spaces-of-the-week-6532465b9824bcc3f44cea3c/items (Request ID: Root=1-65329fd7-3e569eb24a070d6c0c820247;5d852b78-c691-4dd7-bdf8-0e854a12f245)

Repo or paper not found
```

**Comment by Wauplin** [comment]
Maybe what would be nice is to still raise a basic HTTP 404 (no RepoNotFound wrapper) but update the error message from the server to include the URL/ID that has not been found. At least it would be clear to the user what is missing. What do you think?
(so a moon-landing-only fix)

**Comment by osanseviero** [comment]
Yes, that would be clearer!

**Comment by Wauplin** [comment]
As discussed, the better error message has being shipped server-side (see https://github.com/huggingface/moon-landing/pull/7843 -internal repo-). Should be proded soon.

Error message is now:

```
HfHubHTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/collections/osanseviero/historical-spaces-of-the-week-6532465b9824bcc3f44cea3c/items (Request ID: Root=1-65329fd7-3e569eb24a070d6c0c820247;5d852b78-c691-4dd7-bdf8-0e854a12f245)

Cannot add item to collection: space 'username/my-space' not found
```
