### ISSUE TITLE
Upcoming releases

### ISSUE THREAD

**Issue by oriyafe** [huggingface/huggingface_hub#1777]
Can someone share please the release program/lifecycle?

Thanks!

**Comment by Wauplin** [comment]
What would you like to know precisely? We don't have a strict release program for `huggingface_hub`. Usually you can expect a minor release every 4 to 6 weeks depending on how active has been the development. But we don't refrain ourselves to release more often if new cool features are added quickly. Latest version is `0.18.0`. 

About lifecycle, we always try to ensure backward compatibility when making changes to an existing API. If a breaking change will be introduced, we usually deprecate the feature 3 releases before breaking it. Deprecation are mentioned in the release notes and a warning message is triggered each time a deprecation method is used. For some legacy features that have been at the core of the library in the past (for example `Repository` or `InferenceAPI` classes) but are now abandoned in favor of more robust/feature-complete classes, we set a deprecation cycle until the next major release `1.0.0`, which is not planned yet.

Hope this will help you. Please let me know if you want any further details.

**Comment by oriyafe** [comment]
Can you share the exact next release date?

**Comment by Wauplin** [comment]
@oriyafe most likely tomorrow

**Comment by oriyafe** [comment]
thanks!

**Comment by Wauplin** [comment]
And it's live! You can update huggingface_hub to the latest version using `pip install -U huggingface_hub`. Here are the [release notes](https://huggingface.co/spaces/Wauplin/huggingface_hub/discussions/2) :)
