### ISSUE TITLE
Add text classification for spaCy

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#178]
This requires adding a `text-classification` script [here](https://github.com/huggingface/huggingface_hub/tree/main/api-inference-community/docker_images/spacy/app/pipelines) that can be based in the `token-classification` [implementation](https://github.com/huggingface/huggingface_hub/blob/main/api-inference-community/docker_images/spacy/app/pipelines/token_classification.py).

There is useful spaCy documentation in https://spacy.io/api/textcategorizer, but I think this should be straightforward to implement. Here is an example repo to use for testing - https://huggingface.co/edichief/en_textcat_goemotions

**Comment by g4brielvs** [comment]
I'm very interested in contributing!

**Comment by osanseviero** [comment]
Hi @g4brielvs, I'm glad you're interested in this one. Let me know if you require further pointers or discussion from what is above. Overall, you should implement the pipeline and a test, then you can do `pytest -sv docker_images/spacy/tests/` to check out it works

**Comment by devpramod** [comment]
I'd like to take a crack at it too. Is that okay given @g4brielvs is probably working already working on it. @osanseviero

**Comment by osanseviero** [comment]
Hi @devpramod thanks for your interest. ⚡⚡⚡

Since @g4brielvs already expressed interest, let's give him the chance to complete this. There will be more good first issues with nice impact in the future, so stay tuned!

**Comment by devpramod** [comment]
@osanseviero Absolutely! I'll stay tuned

**Comment by osanseviero** [comment]
Hi @g4brielvs! Did you have a chance to take a look into this?

**Comment by g4brielvs** [comment]
Hi @osanseviero! Sorry for taking too long. I still haven't completed the task unfortunately.

**Comment by devpramod** [comment]
@osanseviero I have looked into the PR, please let me know If I'm needed.

**Comment by devpramod** [comment]
@osanseviero I have looked into the PR as well, please let me know if I can be of help to @g4brielvs, with their permission of course.

**Comment by osanseviero** [comment]
No worries @g4brielvs, just wanted to check in :). Let @devpramod know if you would like to collaborate on this together or let me know if you would require additional guidance/pointers!

**Comment by osanseviero** [comment]
Hi @g4brielvs, since some time has passed I'm re-assigning this issue. 

@devpramod, please let me know if you're still interested on this.

**Comment by devpramod** [comment]
Hi @osanseviero I'm still interested!

**Comment by osanseviero** [comment]
Hi @devpramod. Let me know if you have any questions or if there's anything I can unblock you with.

**Comment by devpramod** [comment]
Hi @osanseviero The link to the example repo does not work for me; 404 error.

**Comment by osanseviero** [comment]
Hi @devpramod,

* You can try out the `text-classification` models with `spacy` tag: https://huggingface.co/models?filter=spacy&pipeline_tag=text-classification. `en_textcat_goemotions` might be a good one.
* I'm not sure I follow your question. From the `api-inference-community` directory, you should be able to run `make style` and `make quality` commands so everything is styled properly.
* This is the first `text-classification` model in `api-inference-community`, so you will also need to create a template in `docker_images/common` such as [this one](https://github.com/huggingface/huggingface_hub/blob/main/api-inference-community/docker_images/common/app/pipelines/token_classification.py).
* The input expectation is exactly the same as `TokenClassificationPipeline`, you expect `inputs` which is a string.
* The output expectation should be the same as the `transformers` [TextClassificationPipeline](https://huggingface.co/transformers/main_classes/pipelines.html#textclassificationpipeline). "Each result comes as list of dictionaries with the following keys: label, score". Meaning it can really be multi-label. @Narsil might have additional comments on this.

Let me know if this clears things up and if you have any follow-up questions

**Comment by osanseviero** [comment]
Btw maybe this helps you

```
!pip install https://huggingface.co/explosion/en_textcat_goemotions/resolve/main/en_textcat_goemotions-any-py3-none-any.whl
!pip install spacy_transformers

import spacy
model = spacy.load("en_textcat_goemotions")
doc = nlp("i am very angry")
doc.cats
``` 

This returns

> 
> {'admiration': 0.005308344028890133,
>  'amusement': 0.002079125726595521,
>  'anger': 0.9939950108528137,
>  'annoyance': 0.044465720653533936,
>  'approval': 0.002119749318808317,
>  'caring': 0.0020760963670909405,
>  'confusion': 0.01418229565024376,
>  'curiosity': 0.0010452986462041736,
>  'desire': 0.009178760461509228,
>  'disappointment': 0.005141303408890963,
>  'disapproval': 0.014760484918951988,
>  'disgust': 0.01622140407562256,
>  'embarrassment': 0.006369160022586584,
>  'excitement': 0.012096453458070755,
>  'fear': 0.011918637901544571,
>  'gratitude': 0.008078442886471748,
>  'grief': 0.012948076240718365,
>  'joy': 0.010376991704106331,
>  'love': 0.004759719595313072,
>  'nervousness': 0.005560097750276327,
>  'neutral': 0.014362489804625511,
>  'optimism': 0.004656228236854076,
>  'pride': 0.008055202662944794,
>  'realization': 0.0026857955381274223,
>  'relief': 0.005299292970448732,
>  'remorse': 0.004002446308732033,
>  'sadness': 0.019491763785481453,
>  'surprise': 0.0050389766693115234}

**Comment by Narsil** [comment]
~~`TokenClassificationPipeline`~~ -> `TextClassificationPipeline`.
Otherwise fully agree with you @osanseviero

**Comment by devpramod** [comment]
@osanseviero Thanks! This helps a great deal.

**Comment by devpramod** [comment]
@osanseviero I'm trying to write test cases for my code. I'm trying to run `pytest -sv docker_images/spacy/tests/`, I'm a beginner at Docker, I get an `AssertionError: 500 != 200` from test_simple. I used the Dockerfile to build an image and I'm running the container on localhost. Any input would be really helpful, thanks!

for reference, I used the following to run the image 
`sudo docker run -d --name mycontainer -p 80:80 myimage`

**Comment by osanseviero** [comment]
Hi there!

To clarify, there are two types of tests:

* The tests that require docker (under `tests/test_docker`).
* And the unit tests you're running. When you run `pytest -sv docker_images/spacy/tests/test_api_token_classification.py` you're not using Docker, which makes development much faster.

As for how to debug this issue, I would recommend you to print the error (`response.json()` for example) and see what error you're getting. This could go from missing dependencies/imports to you returning incorrect value. Let me know if you have any other questions.

**Comment by devpramod** [comment]
hi @osanseviero, I added the pipeline, please review and let me know about any changes.

**Comment by devpramod** [comment]
Hi! @osanseviero I've added the pipeline. Please let me know about any changes.
