### ISSUE TITLE
Proxies parameters of hf_hub_download and snapshot_download cannot proxy LFS's HTTP file download requests.

### ISSUE THREAD

**Issue by gaius-qi** [huggingface/huggingface_hub#1780]
### Describe the bug

Proxies parameters of hf_hub_download and snapshot_download cannot proxy LFS's HTTP file download requests.

### Reproduction

Download [timm/mobilenetv3_large_100.ra_in1k](https://huggingface.co/timm/mobilenetv3_large_100.ra_in1k/tree/main) `README.md` and `model.safetensors`.

![image](https://github.com/huggingface/huggingface_hub/assets/15955374/2f845932-bbd9-46ea-ad3e-703737e43d08)

If download `README.md`, then you can proxy it through proxies.

```python
from huggingface_hub import hf_hub_download
hf_hub_download(repo_id="timm/mobilenetv3_large_100.ra_in1k", filename="README.md", proxies={'https': 'http://127.0.0.1:65001'})
```

If download `model.safetensors`, then you can not proxy it through proxies.

```python
from huggingface_hub import hf_hub_download
hf_hub_download(repo_id="timm/mobilenetv3_large_100.ra_in1k", filename="model.safetensors", proxies={'https': 'http://127.0.0.1:65001'})
```

### System info

```shell
- Huggingface Version: v0.18.0
- Python Verison: 3.9.10
```

**Comment by gaius-qi** [comment]
@Wauplin Can you help me? 😊

**Comment by Wauplin** [comment]
Hey @gaius-qi , what is the error you are getting? Could you copy-paste the full stacktrace?
Also how is set your proxy? Regular files as `README.md` are downloaded from https://huggingface.co but LFS files are fetched directly from S3. Can it be a proxy config to update?

**Comment by gaius-qi** [comment]
Can I set the protocol of all requests to `http://` and my proxy service will convert `http://` to `https://`.

**Comment by gaius-qi** [comment]
I set the endpoint to `http://huggingface.co`, but the address get by the LFS protocol is `https://huggingface.co/xxx`. Can I change the `https://huggingface.co/xxx` download URL returned by the LFS protocol to `http://huggingface.co/xxx`.

**Comment by gaius-qi** [comment]
Not a same problem with #1764. Is it possible to change the LFS download URL from `https://` to `http://`?

**Comment by Wauplin** [comment]
> Is it possible to change the LFS download URL from https:// to http://?

No.

**Comment by gaius-qi** [comment]
@Wauplin I'm very sorry that I didn't explain my intention clearly.

I need to distribute Hugging Face's LFS download file request through Dragonfly P2P, refer to https://d7y.io/docs/next/setup/integration/hugging-face.

During the downloading of datasets or models, the file size is large and there are many services downloading the files at the same time. The bandwidth of the storage will reach the limit and the download will be slow. 
![image](https://github.com/huggingface/huggingface_hub/assets/15955374/f511f8ca-a690-4da5-ae98-8fdabf38acfb)

Dragonfly can be used to eliminate the bandwidth limit of the storage through P2P technology, thereby accelerating file downloading.
![image](https://github.com/huggingface/huggingface_hub/assets/15955374/058356ec-c199-438b-b473-50ba96aa0cd5)

Dragonfly HTTP proxy is accessed through `http://`, and Dragonfly will convert `http://` to `https://` to access https://huggingface.co. I have solved this problem according to the documentation, please help Is there anything that needs to be modified?

Hub Python Library use `http://lfs-cdn/huggingface.co/repo/xxx/xxxxxx`  => Dragonfly HTTP Proxy accepts `http://lfs-cdn/huggingface.co/repo/xxx/xxxxxx` convert to `https://lfs-cdn/huggingface.co/repo/xxx/xxxxxx` => Hugging Face Hub accepts `https://lfs-cdn/huggingface.co/repo/xxx/xxxxxx`

**Comment by Wauplin** [comment]
Thank for the more details explanation @gaius-qi! As far as I understand, https://d7y.io/docs/next/setup/integration/hugging-face/#download-a-single-file-with-dragonfly is indeed the way to go to achieve what you are trying to do -especially redirecting to http:// on cdn-lfs.huggingface.co-. Looks a very cool project!

Just to be sure I understand correctly, this useful when you have a cluster of machines trying to reach the same models/datasets, right? Is it designed to help single-users as well?
Asking because in this case it would be useful for the [benchmark section](https://d7y.io/docs/next/setup/integration/hugging-face/#performance-testing) to compare download speed using plain `huggingface_hub` (as already done) but also when using [`huggingface_hub`+`hf_transfer`](https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfhubenablehftransfer). On machines with high bandwidth you can already get much higher download speeds (up to ~1GB/s). What the maximum throughout do you hope to reach with P2P?

**Comment by gaius-qi** [comment]
@Wauplin Yes, adding Dragonfly P2P technology is very useful when multiple machines are downloading models/datasets.
The download speed of a single machine will not be better than using Hugging Face Python Library directly.

For example, we have 1,000 inference services in the cluster, the model needs to be downloaded 1,000 times at the same time:
1. When the model has not been downloaded in the cluster, 1,000 inference services are started at the same time. When using Dragonfly, it is guaranteed that only one inference service downloads the model back to the Hugging Face Hub, and other inference services use the intranet for data distribution. It can also reduce Hugging Face Hug’s back-to-origin traffic.
2. If the model is not downloaded for the first time in the cluster. It has been downloaded by any inference service in the cluster, then when other inference services download the model, they can use the intranet to download the model instead of back to Hugging Face Hub download download model. In this way, intranet bandwidth users can configure better hardware and increase download speeds. It can also reduce Hugging Face Hug’s back-to-origin traffic.
3. Users can also preheat the model to a node in the cluster, refer to [preheat](https://d7y.io/docs/next/reference/preheat), so that any inference service in the cluster can use the intranet bandwidth to download the model. In this way, intranet bandwidth users can configure better hardware and increase download speeds. It can also reduce Hugging Face Hug’s back-to-origin traffic.
4. Of course, not all regions download data from Hugging Face Hub very quickly. For example, in China, the download speed may be slower, and the model needs to be preheated in advance in the cluster. So that any inference service in the cluster can use the intranet bandwidth to download the model. In this way, intranet bandwidth users can configure better hardware and increase download speeds.

**Comment by Wauplin** [comment]
That looks really cool! Makes everything clearer to me now.
So if I understand correctly, you've successfully solved your problem using `configure_http_backend`, right? (which is the way to go). If that's the case, I think we can close this issue. Do not hesitate to ping me in the future if you have any news about this `huggingface_hub` x Dragonfly P2P integration!

**Comment by gaius-qi** [comment]
@Wauplin Thanks! My problems have been solved and you can close this issue. We will publish a technical article on the [CNCF blog](https://www.cncf.io/blog/) on November 16, and I will create a new issue to track.

**Comment by gaius-qi** [comment]
@Wauplin I created an Issue to track this, added a TODO List and need your help, refer to https://github.com/dragonflyoss/Dragonfly2/issues/2849. Thanks 😊😊😊
