### ISSUE TITLE
Broken stream=True in text_generation for TGI endpoint

### ISSUE THREAD

**Issue by danielpcox** [huggingface/huggingface_hub#1787]
### Describe the bug

I get `AttributeError: 'dict' object has no attribute 'text'` from the following code, with 0.18.0:

```
from huggingface_hub import InferenceClient
client = InferenceClient(model="http://127.0.0.1:8080")
for t in client.text_generation(prompt="Write a code for snake game", stream=True):
    print(t, end='')
```

Where I have a Text Generation Inference container running at that address. If I add `details=True`, and then manually extract the token text with `t.token["text"]`, it works, because `t.token` is a dictionary.

I think the problem is here, where if you don't specify `details=True`, it calls `output.token.text` where output.token is a dictionary:

https://github.com/huggingface/huggingface_hub/blob/v0.18.0/src/huggingface_hub/inference/_common.py#L281

### Reproduction

```
from huggingface_hub import InferenceClient
client = InferenceClient(model="http://127.0.0.1:8080")
for t in client.text_generation(prompt="Write a code for snake game", stream=True):
    print(t, end='')
```

### System info

```shell
Forgive me for omitting this, but it contains sensitive information and it doesn't seem relevant. I'll supply it offline if it turns out to be necessary. Let me know.
```

**Comment by Wauplin** [comment]
Hi @danielpcox, thanks for reporting the issue. This might be happening because `pydantic` is not installed. If it's the case, could you install it and report me back if you still have an issue?

And if pydantic missing is the actual problem, we should handle is more explicitly in the error message :+1:

**Comment by danielpcox** [comment]
Installing pydantic like so did indeed fix the problem:

```
mamba install pydantic huggingface_hub=0.17.3
```

Since it works fine without pydantic otherwise, I'd suggest adjusting just the lines of code that assume `text` is available as an attribute in preference to improving the error message.

Thanks for looking into it!

**Comment by Wauplin** [comment]
Hey @danielpcox! Glad to hear it fixed your problem! I recreated the error locally and I agree we should either fix it or raise a more informative error. I chose to push a fix (see https://github.com/huggingface/huggingface_hub/pull/1793) that parses the nested dataclasses correctly. In addition to fixing things when `stream=True`, it also fixes the dataclass when `details=True`. Once this is merged, it will be shipped in next release (`v0.19.0`) that should happen within a week :)

Wishing you good continuation :hugs:

**Comment by danielpcox** [comment]
Thank you sir. It's been a pleasure working with you.

**Comment by Wauplin** [comment]
Closing this issue as fixed by https://github.com/huggingface/huggingface_hub/pull/1793. Should be released soon otherwise you can already use it [by installing `huggingface_hub` from source](https://huggingface.co/docs/huggingface_hub/installation#install-from-source).
