### ISSUE TITLE
Added to conda-forge

### ISSUE THREAD

**Issue by BastianZim** [huggingface/huggingface_hub#18]
Hi, this is more of an FYI than an issue but I just wanted to let the maintainers here know that I added huggingface_hub to conda-forge. Repo: https://github.com/conda-forge/huggingface_hub-feedstock
I think you're already pushing to your own Anaconda channel but let me know if you'd like to be maintainers there (or take over completely) as well. Otherwise, feel free to just close the issue. 
Thanks!

**Comment by julien-c** [comment]
Thanks for the note – pinging @LysandreJik as he's the author of our conda integration.

**Comment by LysandreJik** [comment]
We'll continue maintaining the package on our own Anaconda channel, but happy to also be available on conda-forge! Let us know if you run into any issues maintaining it down the road and we'll look into it.

**Comment by BastianZim** [comment]
Thank you, sounds good!
