### ISSUE TITLE
Entire operation get cancelled when 1 file fails when using api.upload_folder - how to make it iterative

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/huggingface_hub#1801]
I am using below code. Uploaded like 80 GB file and the entire operation failed just because of 1 png failed to upload for some reason

I see uploaded repo has 0 changes

How can I make it iterative? So after each file upload it is committed to the repo

I don't need commit or file history. Just upload newer files and overwrite if newer

```
from huggingface_hub import HfApi
api = HfApi()

# Upload all the content from the local folder to your remote Space.
# By default, files are uploaded at the root of the repo
api.upload_folder(
    folder_path="/workspace/path",
    repo_id="username/repo",
    repo_type="model",
)
```

### System info

```shell
- huggingface_hub version: 0.16.4
- Platform: Linux-5.15.0-86-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /root/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: ME
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.0.1+cu118
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.5.0
- hf_transfer: N/A
- gradio: 3.41.2
- tensorboard: N/A
- numpy: 1.23.5
- pydantic: 1.10.12
- aiohttp: 3.8.5
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /root/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /root/.cache/huggingface/assets
- HF_TOKEN_PATH: /root/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by Wauplin** [comment]
Hi @FurkanGozukara, I am sorry you are facing this issue. What you can do in this case is to use `multi_commit=True`. This will push your folder to a PR branch. Files will be uploaded by chunks to this PR. If the upload process fails at some point, you can restart the script and it will resume to the same PR branch. By default, files will be grouped as chunks of at most 50 files or 2GB. If a file is above 2GB, it is uploaded as a chunk of one file. For more details, please check out the [related documentation](https://huggingface.co/docs/huggingface_hub/guides/upload#upload-a-folder-by-chunks).

```python
upload_folder(
    folder_path="/workspace/path",
    repo_id="username/repo",
    multi_commits=True,
    multi_commits_verbose=True,
)
```

Hope this will prove useful to your use case. Please let me know how it goes.

**Comment by FurkanGozukara** [comment]
@Wauplin thank you so much will test it

**Comment by FurkanGozukara** [comment]
> Hi @FurkanGozukara, I am sorry you are facing this issue. What you can do in this case is to use `multi_commit=True`. This will push your folder to a PR branch. Files will be uploaded by chunks to this PR. If the upload process fails at some point, you can restart the script and it will resume to the same PR branch. By default, files will be grouped as chunks of at most 50 files or 2GB. If a file is above 2GB, it is uploaded as a chunk of one file. For more details, please check out the [related documentation](https://huggingface.co/docs/huggingface_hub/guides/upload#upload-a-folder-by-chunks).
> 
> ```python
> upload_folder(
>     folder_path="/workspace/path",
>     repo_id="username/repo",
>     multi_commits=True,
>     multi_commits_verbose=True,
> )
> ```
> 
> Hope this will prove useful to your use case. Please let me know how it goes.

I made it work like this. Do you see any error etc?

![image](https://github.com/huggingface/huggingface_hub/assets/19240467/60cd235b-83e0-44dc-becb-5af83fb0fe8d)

**Comment by Wauplin** [comment]
Hi @FurkanGozukara yes, this is exactly how it should be used!

**Comment by FurkanGozukara** [comment]
> Hi @FurkanGozukara yes, this is exactly how it should be used!

great ty
