### ISSUE TITLE
`SpaceInfo` does not load tags from Spaces

### ISSUE THREAD

**Issue by abidlabs** [huggingface/huggingface_hub#1806]
### Describe the bug

The `SpaceInfo` does not load tags from Spaces, at least when used like this:

### Reproduction

```py
import huggingface_hub

api = huggingface_hub.HfApi()
space_info = api.space_info("gradio/seafoam")
space_info.tags
```

shows an empty list even though there are tags in this Space: https://huggingface.co/spaces/gradio/seafoam/blob/main/README.md

### System info

```shell
- huggingface_hub version: 0.18.0
- Platform: macOS-13.3-arm64-arm-64bit
- Python version: 3.11.3
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /Users/abidlabs/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: abidlabs
- Configured git credential helpers: osxkeychain
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.0.1
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.5.0
- hf_transfer: N/A
- gradio: 4.0.0b14
- tensorboard: N/A
- numpy: 1.26.1
- pydantic: 2.3.0
- aiohttp: 3.8.4
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /Users/abidlabs/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /Users/abidlabs/.cache/huggingface/assets
- HF_TOKEN_PATH: /Users/abidlabs/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by Wauplin** [comment]
Looks like a server-side issue (cc @Pierrci @coyotte508?). It seems tags are never returned from the server. Even the Space SDK is missing.
- https://huggingface.co/spaces/gradio/seafoam/blob/main/README.md (tags are set in readme)
- https://huggingface.co/api/spaces/gradio/seafoam => returns `"tags": []`
- https://huggingface.co/api/spaces/gradio/seafoam?expand[]=tags  => returns `"tags": []`

I suspect this is only happening when some tags are defined in the readme metadata (see https://huggingface.co/api/spaces/fffiloni/ProPainter for example that returns `"tags": ["docker"]`).

**Comment by julien-c** [comment]
yes, looks server side

**Comment by Wauplin** [comment]
This issue has been fixed both server-side and in Gradio. Problem was a non-valid `colorFrom` metadata in the repocard making the whole parsing fail.
