### ISSUE TITLE
HTTP request to `https://huggingface.co/api/repos/move` fails unexpectedly

### ISSUE THREAD

**Issue by strickvl** [huggingface/huggingface_hub#1813]
### Describe the bug

I'm trying to use the Huggingface Hub API to rename a space/repo and it fails saying that the original repository cannot be found (though it does actually exist).

### Reproduction

I'm making an HTTP request using the Huggingface API:

```bash
http POST "https://huggingface.co/api/repos/move" \
  Authorization:"Bearer MY_WRITE_TOKEN" \
  fromRepo="strickvl/my-renamed-space" toRepo="strickvl/my-renamed-space2" repoType="space"
```

Using the HF Hub docs it seems that this is the way to rename a repository / space. I'm assuming that the new repo doesn't need to exist yet. But the first repo/space definitely does exist.

I get a 404 Error with the following error message:

```
{
    "error": "Repository not found"
}

X-Error-Code: RepoNotFound
X-Error-Message: Repository not found
```

I assume I'm making the request in the wrong way, but can't seem to figure out from the documentation how to make this request.

Things I also tried:

- creating an empty second repository/space with the target name before making this call. (Fails again). 
- Taking the `repoType` param out completely. (Also fails).

### System info

```shell
- Mac Sonoma 14.0
- Using httpie for the request
```

**Comment by strickvl** [comment]
I just tried the following:

```bash
http POST "https://huggingface.co/api/repos/move" \
  Authorization:"Bearer MY_WRITE_TOKEN" \
  fromRepo="my-renamed-space" toRepo="my-renamed-space2" repoType="space"
```

...and now I get a new 403 error:

```
{
    "error": "You don't have the rights to move this model"
}
```

So it seems that the docs are misleading in asking us to provide the org/user name in the `fromRepo` and `toRepo` params. (Possibly I'm making a false assumption here?)

But now the question comes, why don't I have the rights to move the space given that I have a write token etc?

**Comment by Wauplin** [comment]
Hey @strickvl, sorry for the inconvenience and thanks for reporting! The documentation is indeed missing the `type` parameter. Can you please retry with `type="space"` in the payload and let me know if it worked? In the meantime, I opened a PR to fix the documentation: https://github.com/huggingface/hub-docs/pull/1095.

**Comment by strickvl** [comment]
Thanks for getting back in touch, @Wauplin! I am still getting the error I mentioned above:

```
{
    "error": "You don't have the rights to move this model"
}
```

It's the same token I used to create the space, so I would have assumed it is enough to rename... For clarity, the command I'm running is:

```bash
http POST "https://huggingface.co/api/repos/move" \
  Authorization:"Bearer MY_TOKEN_GOES_HERE" \
  fromRepo="my-renamed-space" toRepo="my-renamed-space2" type="space"
```

**Comment by Wauplin** [comment]
Really weird, there must be a problem somewhere. Could you try the following command and report what's working/what's not.

- (0) `pip install huggingface_hub`
- (1) run in Python script
```py
from huggingface_hub import whoami

whoami(token=token)
```
and print the output here. Especially it should tell you if the token is still valid (and write permission)

- (2) run in python
```py
from huggingface_hub import move_repo

move_repo(from_id="...", to_id="...", repo_type="space", token=token)
```
Does it work?

- (3) run in python
```py
from huggingface_hub import space_info

print(space_info(from_id))
print(space_info(to_id))
```
what is the output of each?

- (4) also, are you trying to rename a Space that is part of an organization? or are you trying to rename a Space to transfer it to an organization?

---

The above should help understand your problem. Please let me know if you get errors (and if yes, copy-paste the errors).

**Comment by strickvl** [comment]
(1):

```
{
    'type': 'user',
    'id': 'SOME_ID_WAS_HERE',
    'name': 'strickvl',
    'fullname': 'Alex Strick van Linschoten',
    'email': 'SOME_EMAIL_WAS_HERE',
    'emailVerified': True,
    'plan': 'NO_PLAN',
    'canPay': False,
    'isPro': False,
    'periodEnd': None,
    'avatarUrl':
'https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/16302440299
24-60cc8e3794ab6115ab6ecf1a.png?w=200&h=200&f=face',
    'orgs': [
        {SOME ORGS WERE HERE: true}
    ],
    'auth': {
        'type': 'access_token',
        'accessToken': {'displayName': 'api-testing', 'role': 'write'}
    }
}
```

(2) this works now.
(it also works using the `http` request I pasted above, but adding the `strickvl/` in front of the repo names.

So I think this is solved now? Still not fully sure what was going on...

Thank you for your help on this!

**Comment by Wauplin** [comment]
Great to know your issue has been solved! :rocket: 

> but adding the strickvl/ in front of the repo names.

That's most likely the source of your problem. On the Hugging Face Hub in general what is called "repo_id" is the full id with namespace + repo name (e.g. `Wauplin/my-cool-model`).

**Comment by strickvl** [comment]
@Wauplin for my own understanding, is there someone I can go to check the implementation of the API if I have any other questions going forward? As far as I can figure out atm, this repo isn't the actual implementation, just the Python wrapper around it etc.
