### ISSUE TITLE
Behavior of `list_models/datasets/spaces` 

### ISSUE THREAD

**Issue by ademait** [huggingface/huggingface_hub#1814]
Hi!

First of all, congrats on the team for the advancements on the Hub client library. I've seen a lot of improvements in particular with the `list_models` and so.

I am reporting a behavior on these calls that I don't know if it is the desired one. Regarding the `list_dataset` call I've seen that the files (`siblings` attribute) is never retrieved. I guess it is because some dataset may have thousands of them, which I find it suitable. However, in the [docs](https://huggingface.co/docs/huggingface_hub/v0.19.0.rc0/en/package_reference/hf_api#huggingface_hub.HfApi.list_datasets) it is said that this call returns a DatasetInfo object, which contains the `siblings` attribute. Maybe a warning would be useful. I know that an alternative is to call `list_repo_files` if we want to get only the filenames. If we want to get the full `RepoSibling` object, I've seen we can gathered it using `repo_info` method with `files_metadate=True`, which contains the `siblings` attribute with the `RepoSibling` object structure.

The other point has a bit of connection with this last note. When calling `list_models` or spaces, the `siblings` attribute is not empty, unlike datasets. However, the data of the `RepoSibling` object is all empty but the `rfilename`. We can also do the workaround with `repo_info`, but I guess that this time it is not the desired behavior. I don't get why it is not retrieved the other fields (`blob_id`, `size` and `lfs`). I don't know if it's a bug, but I think the `siblings` attribute from models and spaces should retrieve the whole info of `RepoSibling` object, as it's done in the `repo_info` method.

I share the code to replicate the second point:
```
from huggingface_hub import HfApi
api = HfApi()
models = api.list_models(full=True, cardData=True, fetch_config=True)
```
With this if we check a model:
```
for m in models:
    print(m.id)
    print(m.siblings)
    break
```
I get:
```
'45SK/opus-tatoeba-en-ja-finetuned-en-to-ja-gt-2797388'
[RepoSibling(rfilename='.gitattributes', size=None, blob_id=None, lfs=None), RepoSibling(rfilename='config.json', size=None, blob_id=None, lfs=None), RepoSibling(rfilename='model.safetensors', size=None, blob_id=None, lfs=None), RepoSibling(rfilename='source.spm', size=None, blob_id=None, lfs=None), RepoSibling(rfilename='special_tokens_map.json', size=None, blob_id=None, lfs=None), RepoSibling(rfilename='target.spm', size=None, blob_id=None, lfs=None), RepoSibling(rfilename='tokenizer_config.json', size=None, blob_id=None, lfs=None), RepoSibling(rfilename='training_args.bin', size=None, blob_id=None, lfs=None), RepoSibling(rfilename='vocab.json', size=None, blob_id=None, lfs=None)]
```
And when checking it with `repo_info`:
```
api.repo_info(m.id, repo_type="model", files_metadata=True).siblings
```
```
[RepoSibling(rfilename='.gitattributes', size=1519, blob_id='a6344aac8c09253b3b630fb776ae94478aa0275b', lfs=None),
 RepoSibling(rfilename='config.json', size=1114, blob_id='653414e0d9725c14f21335e1817e48e113fe6d3c', lfs=None),
 RepoSibling(rfilename='model.safetensors', size=309965092, blob_id='339cbad0d083e13f3aafe22e4b41051eb3a1e724', lfs={'size': 309965092, 'sha256': 'a08238bf5ed7a727f33226324de9a70b39d8b0e48640702408535d98c757f2e9', 'pointer_size': 134}),
 RepoSibling(rfilename='source.spm', size=807923, blob_id='9af4822c9875aaecd7983c0948ba23484fc01048', lfs=None),
 RepoSibling(rfilename='special_tokens_map.json', size=74, blob_id='79ae7ea5bf033de69d0055820c57885e3d377bbb', lfs=None),
 RepoSibling(rfilename='target.spm', size=834449, blob_id='92fb3035efd8e9772fd35cfabdc8f84314336790', lfs=None),
 RepoSibling(rfilename='tokenizer_config.json', size=818, blob_id='b798f6f20db18bfd71f37dfa829df9afbac33ef5', lfs=None),
 RepoSibling(rfilename='training_args.bin', size=4792, blob_id='95b79d299650ed1e98ae6dc9452e27406280a20c', lfs={'size': 4792, 'sha256': 'fa8c6e9a7e93a00ab6f6180fe1922fd8dbf6831a6f99ae68318ce7aeb82569b7', 'pointer_size': 129}),
 RepoSibling(rfilename='vocab.json', size=1831457, blob_id='6f817bc35438ba76d9c40cf5a2cd440ebd35e794', lfs=None)]
```

**Comment by Wauplin** [comment]
Hi @ademait, first of all thanks for the kind words and thanks for reporting feedback on those endpoints. Given what you have described, an harmonization step would be good indeed. I'll have to make some tests first and will let you know when I move forward on this. 

Just to be sure, are you using the latest version of huggingface_hub (v0.19.0 from this week)? I believe yes but wanted to double check as some modifications have been done there.

**Comment by ademait** [comment]
Hi @Wauplin , yes, I'm using v0.19.0
```
huggingface_hub.__version__
```
throws: `'0.19.0'`

I am open to collaborate/give feedback with this 👍

**Comment by Wauplin** [comment]
Hey @ademait, I came back to this issue today. The main reasons behind these discrepancies is that fetching files for a repo takes more time that fetching metadata (due to backend information). Also when fetching files, it's more lightweight to simply fetch filenames rather than getting info like `lfs`/`blob_id`/`size`... This is why `list_models`/`list_datasets`/`list_spaces` do not return files by default and when they do, they only return the filenames. When fetching only 1 repo (`model_info`/`dataset_info`/`space_info`), it is more ok to fetch these details because we do it only for 1 repo.

I don't think we want to change this behavior in the near future, due to the constrains it would put on the server. However, we could change the wording in the documentation. Which sections do you think would benefit from it?

**Comment by Wauplin** [comment]
Also cc-ing @Pierrci @coyotte508 from the backend team. Have the constraints changed since we last updated the logic behind the "listing endpoints" (more caching?) or not? If not, that's fine - let's not change it.

**Comment by Pierrci** [comment]
> Regarding the `list_dataset` call I've seen that the files (`siblings` attribute) is never retrieved. I guess it is because some dataset may have thousands of them, which I find it suitable.

Indeed, this is the reason @ademait, we should probably update the doc to reflect this.

Regarding `RepoSibling` with only `rfilename`, this is a nominal behavior too, the `list_xxx` methods all use cache to retrieve the data, and we only store the filename in cache; to reply to @Wauplin, nothing changed in this regard for now.

**Comment by ademait** [comment]
Hi @Wauplin and @Pierrci , thanks for the fast response! 

I understand to not retrieve the whole `RepoSibling` info, I think it is reasonable to keep it this way. However, as @Wauplin said, the docs aren't quite clear about that. 

The `list_models` (datasets/spaces) [docs](https://huggingface.co/docs/huggingface_hub/v0.19.1/en/package_reference/hf_api#huggingface_hub.HfApi.list_models) says it returns `Iterable[ModelInfo]`. Then, when looking for `ModelInfo` attributes, you end up finding that the `siblings` are of type `RepoSibling`, which includes all atributes. The solution may be just having some kind of warning, as the `siblings` attribute is returned as a `RepoSibling` object with just the `rfilename` attribute filled.

**Comment by Wauplin** [comment]
I created a PR to (slightly) improve the docs, please let me know what you think: https://github.com/huggingface/huggingface_hub/pull/1823

**Comment by Wauplin** [comment]
Closing as done in https://github.com/huggingface/huggingface_hub/pull/1823.
