### ISSUE TITLE
Add support for `/health` and `/info` endpoints for TGI

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1819]
_Originally from @thomwolf on slack (private)_

> I think we could add wraping for health and info endpoints in TGI to the huggingface_hub client at some point

Docs:
- [`/health`](https://huggingface.github.io/text-generation-inference/#/Text%20Generation%20Inference/health)
- [`/info`](https://huggingface.github.io/text-generation-inference/#/Text%20Generation%20Inference/get_model_info)

Thought I'm not sure yet how/where to integrate those in `InferenceClient`. Fow now, let's see if there's more demand for it (=> anyone landing on this issue and that is interested, please let us know!)

**Comment by MoritzLaurer** [comment]
@Wauplin , this came up in a conversation with a customer recently and I think it would be great to support his. if I understand correctly, via /info users of serverless API endpoints could check which TGI version/sha an LLM like llama-3/dbrx/command-r is running on. That's quite important for debugging and understanding which recent features of TGI are supported (e.g. if guidance/function calling finally works or if the model runs on an old TGI version which is incompatible). At the moment, I'm trying to get guidance to work for llama-3 for example and I'm not sure if users can know which TGI version it is running with.

Based on this [internal conversation](https://huggingface.slack.com/archives/C016D661PAN/p1710173421516389), the TGI version/sha is only available in a private HF repo. would be great to enable users to query this information via our library.

**Comment by MoritzLaurer** [comment]
Another example for why it's very useful for users to know the exact TGI version an endpoint is running on: ([internal conversation](https://huggingface.slack.com/archives/C016D661PAN/p1713806595772839))
