### ISSUE TITLE
Respect `.gitignore` file in `upload_folder`

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1826]
Related to https://github.com/huggingface/moon-landing/issues/7870 (internal). It would be nice to respect `.gitignore` file when it exists in a folder. This would allow more flexible and standard way to filter which files to upload (compared to using `allow_patterns` / `ignore_patterns`). The server now returns a `shouldIgnore` boolean value in the `/preupload` endpoint (just before committing files) by checking the .gitignore file at the root of the folder.

Let's add an option `respect_gitignore` to the `upload_folder` method. I'm still unsure about whether it should default to True (more intuitive but introduce a breaking change) or to False (meaning less impact).

~**Note:** the gitignore file has to already exist on the Hub to benefit from it.~ not anymore

**Comment by julien-c** [comment]
hmm i'd say it'd be nice to have it as default no? as it's probably 99.9% of the time the intended behavior

i.e. it's more of a bugfix really

**Comment by Wauplin** [comment]
Done in https://github.com/huggingface/huggingface_hub/pull/1868 :)
