### ISSUE TITLE
pydantic deprecated validator, migrate to field_validator

### ISSUE THREAD

**Issue by mattf** [huggingface/huggingface_hub#1836]
environment
```
huggingface-hub==0.19.4
pydantic==2.5.1
```

issue is a deprecation warning
```
.../lib/python3.10/site-packages/huggingface_hub/inference/_text_generation.py:204: PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.5/migration/
```

details about deprecation: https://docs.pydantic.dev/latest/migration/#changes-to-validators

source of issue: https://github.com/huggingface/huggingface_hub/blame/main/src/huggingface_hub/inference/_text_generation.py#L36

potential fix: `from pydantic import field_validator as validator`

desired outcome: same behavior, no warnings

**Comment by Wauplin** [comment]
Thanks for reporting @mattf ! I opened a PR to fix this using your suggestion: https://github.com/huggingface/huggingface_hub/pull/1837
I also checked the migration guide but the changes don't impact us for what I understand :)
