### ISSUE TITLE
Unable to run huggingface-cli

### ISSUE THREAD

**Issue by maxloosmu** [huggingface/huggingface_hub#1840]
### Describe the bug

When I run:
`pip install -U "huggingface_hub[cli]"`

I get this output:
```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: huggingface_hub[cli] in /home/maxloo/.local/lib/python3.10/site-packages (0.19.4)
Requirement already satisfied: filelock in /home/maxloo/.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in /home/maxloo/.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (2023.10.0)
Requirement already satisfied: requests in /home/maxloo/.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in /home/maxloo/.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (4.66.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from huggingface_hub[cli]) (5.4.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/maxloo/.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (4.8.0)
Requirement already satisfied: packaging>=20.9 in /home/maxloo/.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (23.2)
Collecting InquirerPy==0.3.4 (from huggingface_hub[cli])
  Downloading InquirerPy-0.3.4-py3-none-any.whl (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.7/67.7 kB 2.4 MB/s eta 0:00:00
Collecting pfzy<0.4.0,>=0.3.1 (from InquirerPy==0.3.4->huggingface_hub[cli])
  Downloading pfzy-0.3.4-py3-none-any.whl (8.5 kB)
Requirement already satisfied: prompt-toolkit<4.0.0,>=3.0.1 in /usr/lib/python3/dist-packages (from InquirerPy==0.3.4->huggingface_hub[cli]) (3.0.28)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/maxloo/.local/lib/python3.10/site-packages (from requests->huggingface_hub[cli]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/maxloo/.local/lib/python3.10/site-packages (from requests->huggingface_hub[cli]) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/maxloo/.local/lib/python3.10/site-packages (from requests->huggingface_hub[cli]) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /home/maxloo/.local/lib/python3.10/site-packages (from requests->huggingface_hub[cli]) (2023.7.22)
Installing collected packages: pfzy, InquirerPy
Successfully installed InquirerPy-0.3.4 pfzy-0.3.4
```

### Reproduction

Then I tried:
`huggingface-cli login`

I get this error:
`huggingface-cli: command not found`

### Logs

```shell
The command `huggingface-cli` does not work.
```

### System info

```shell
The command `huggingface-cli` does not work.
```

**Comment by Wauplin** [comment]
Hi @maxloosmu I'm sorry you're facing this issue. It seems you're having a problem in your setup. If you look at the first log, it says `Defaulting to user installation because normal site-packages is not writeable`. This means that the package is installed but not at the expected location. To fix this you can try to run `python3 -m pip install -U "huggingface_hub[cli]"` as suggested in https://stackoverflow.com/a/62227035. Otherwise I would advice you to use virtual environments when installing python environments. This is what we recommend in our [installation guide](https://huggingface.co/docs/huggingface_hub/installation#install-with-pip). Hope this will prove useful.

**Comment by SID262000** [comment]
@maxloosmu, Were you able to fix this issue using the above-suggested steps by @Wauplin?
Happy to help dive deeper into the issue and help resolve it, Thanks!

**Comment by Wauplin** [comment]
Closing this issue as stale (no news for 6 weeks).

**Comment by saurabh-singh-rajput** [comment]
Had the same issue, installing it on a virtual env resolved it for me.

**Comment by Ghost---Shadow** [comment]
bump

**Comment by LiberiFatali** [comment]
You need to use sudo. In case installing to the user folder, the path `~/.local/bin` needs to be added to the environment variable `PATH`.

**Comment by idofilus** [comment]
You could also try [Huggingface quickstart](https://huggingface.co/docs/huggingface_hub/main/en/quick-start) e.g. Python 3.8:

```bash
sudo apt install python3.8-venv -y
python3 -m venv .env
source .env/bin/activate
pip install --upgrade huggingface_hub

huggingface-cli --help
```

**Comment by GaurangaKrB** [comment]
Hugging Face’s own docs say you can authenticate by setting `HF_TOKEN` as an environment variable; the hub libraries automatically pick it up. So do this **in the same terminal session where you’ll run Python**:
        
In the remote terminal, use:

    export HF_TOKEN="hf_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" 
    export  HUGGINGFACE_HUB_TOKEN="$HF_TOKEN"   
    
This worked for me.
