### ISSUE TITLE
Make commands fail to execute

### ISSUE THREAD

**Issue by SID262000** [huggingface/huggingface_hub#1863]
### Describe the bug

On running `make style` or `make quality` at the root level of the repository,
it fails to run successfully.

### Reproduction

`make style`
`make quality`

### Logs

```shell
On running make style:

ruff check --fix contrib src tests utils setup.py # linter
ruff format contrib src tests utils setup.py # formatter
warning: `ruff format` is a work-in-progress, subject to change at any time, and intended for internal use only.
ruff failed
  Cause: Could not read contrib: 
  Cause: Is a directory (os error 21)
make: *** [style] Error 2

On running make quality:
ruff check contrib src tests utils setup.py  # linter
ruff format --check contrib src tests utils setup.py # formatter
error: unexpected argument '--check' found

  tip: to pass '--check' as a value, use '-- --check'

Usage: ruff format [OPTIONS] [FILES]...

For more information, try '--help'.
make: *** [quality] Error 2
```

### System info

```shell
N/A
```

**Comment by Wauplin** [comment]
Hi @SID262000 I think your installation is broken, or at least packages are not installed to the correct version. What I advice you to do is install the project in a virtualenv as explain [in this guide](https://huggingface.co/docs/huggingface_hub/installation#install-with-pip). And since you want the dev tools to be installed as well to run `make` commands, you need to install them like this:

```
pip install -U "huggingface_hub[dev]"
```

Hope this will fix your issue!

**Comment by SID262000** [comment]
Thanks, @Wauplin for the guidance! 

Yes, both the commands do work as required, but I still see the below error messages in `huggingface_hub/utils/check_static_imports.py` on running `make style` & `make quality`, although I don't see it affecting the final checks. Can you look into it once.

` from ruff.__main__ import find_ruff_bin
ModuleNotFoundError: No module named 'ruff'`

**Comment by Wauplin** [comment]
```
 from ruff.__main__ import find_ruff_bin ModuleNotFoundError: No module named 'ruff'
```
=> this means ruff is not installed correctly on your machine. Working inside a virtualenv and installing `.[dev]` should fix it.

**Comment by SID262000** [comment]
I continue to see the above error even though I'm working inside virtualenv and using the hugging face dev setup.

**Comment by SID262000** [comment]
On running the above command I do see the below version  of ruff
`ruff==0.1.6`

**Comment by SID262000** [comment]
Looks like there isn't any fix for this issue, closing this Issue, thanks!
