### ISSUE TITLE
Repository `use_auth_token` should default to `True` when in a HF-hub specific workflow

### ISSUE THREAD

**Issue by LysandreJik** [huggingface/huggingface_hub#187]
The `Repository` class is thought out as a wrapper to git/git-lfs, and isn't specific to the Hugging Face Hub. It's a useful helper to manage offline repositories.

However, the recent PRs https://github.com/huggingface/huggingface_hub/pull/132, https://github.com/huggingface/huggingface_hub/pull/143, https://github.com/huggingface/huggingface_hub/pull/150 and https://github.com/huggingface/huggingface_hub/pull/151 allow cloning repositories from the hub using only `<namespace>/<model_id>` or even `<model_id>` as identifiers, which is hf-hub specific.

@thomwolf rightfully asks why the `use_auth_token` parameter isn't `True` by default, and I tend to agree that for hf-specific workflows this should be the default as it would prevent a lot of pain points when cloning a repository without authentication.

**Comment by julien-c** [comment]
I have no objection to setting `use_auth_token` to True if it helps onboard users not very familiar with git.

Just a note that git authentication is usually handled by the user themselves on the system level, using e.g. a credential helper. For instance when cloning from, or pushing to GitHub, I suspect most people don't have to re-type their password or token each time.

We might want to add some doc about how to do this, or to expose helpers that help do this.

It might be semi-orthogonal to this issue though.
