### ISSUE TITLE
Add the normalize and truncate parameters to feature_extraction to be compatible with Text Embeddings Inference (TEI)

### ISSUE THREAD

**Issue by datavistics** [huggingface/huggingface_hub#1877]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use feature_extraction with full compatibility with Text Embeddings Inference: https://huggingface.github.io/text-embeddings-inference/#/Text%20Embeddings%20Inference/embed

**Describe the solution you'd like**
We should add the ability to put truncate and normalize in the post call

**Describe alternatives you've considered**
Ive tried workarounds, which involve overwriting the methods, but my friends made fun of my ugly code.

**Comment by Wauplin** [comment]
As explained in https://github.com/huggingface/huggingface_hub/pull/1885#issuecomment-1845142394, I prefer to put this feature request on hold until we have a proper parameter definition for inference. For now, let's close as "won't fix" and we get back to it once we have a more global approach to this.
