### ISSUE TITLE
Error on upload_file function comment

### ISSUE THREAD

**Issue by Jone20231102** [huggingface/huggingface_hub#1881]
When I looked at the code, I found that the comment about the uoload file size info inconsistent with the information on the guides,
![upload](https://github.com/huggingface/huggingface_hub/assets/149677114/a906f0f2-5e9b-46b3-9cb3-b8e34fabc2fc)

"up to 50 GB", maybe should be "up to 5GB'

**Comment by Wauplin** [comment]
Hi @Jone20231102. It is true that you can upload file up to 50GB. What is recommended on this page (https://huggingface.co/docs/hub/repositories-recommendations) is to split the file into chunks of 5GB but this is only a recommendation for our users. The hard limit we've set is 50GB.
But I agree with you that this docstring could be improve. I suggest to remove the `(up to 50 GB)` and in a sentence below add a link to https://huggingface.co/docs/hub/repositories-recommendations for more recommendations. What do you think? Would you like to create a PR to update this? :)

**Comment by Jone20231102** [comment]
Hey, @Wauplin thanks for the quick reply. I'm sorry I didn't notice this, you solved my doubts, thank you very much.
About PR, I don't think there's anything wrong with the current comments, and I'm not going to submit a PR
