### ISSUE TITLE
[Feature Request] An operation for collapse large number of commits in hf repo

### ISSUE THREAD

**Issue by narugo1992** [huggingface/huggingface_hub#1891]
Can you provide an operation to collapse a large number of commits in the Hugging Face repository, similar to `git rebase -i`?

We have several repositories used for long-term data synchronization, some of which have been active for over a year. Despite our efforts to control the number of commits, some repositories have accumulated over 3000 commits (and potentially over 30,000 if left uncontrolled).

For example, in this repository: [https://huggingface.co/datasets/deepghs/game_character_skins](https://huggingface.co/datasets/deepghs/game_character_skins), the large number of commits has started to slow down repository access.

Therefore, we hope for:

1. Ideally, the ability to perform a rebase on all commits older than a certain time (e.g., one month ago). Commits that are too old often have little need for retention. If this can be achieved, we can use a scheduled task on GitHub Action to ensure that the repository's commit count remains within a manageable range.

2. If the above operation is not possible, we would like an operation to collapse all commits in the repository at once. This would retain only one commit and the current data. This approach poses higher risks for data maintenance but would be acceptable.

If none of the above can be achieved in the short term, we would appreciate some advice on how to handle such situations more effectively.

**Comment by Wauplin** [comment]
Hi @narugo1992 :wave: You can use [`super_squash_commit`](https://huggingface.co/docs/huggingface_hub/v0.19.3/en/package_reference/hf_api#huggingface_hub.HfApi.super_squash_history) to squash all commits of a branch. We don't promote it much as it's a quite heavy and non-revertible operation that most users don't need. We don't have a way to squash only some commits yet and I don't think we will implement it in the near future except if we start to get a high demand for it. What I would advice you to do if you want to keep 1 commit per month for example is to:
1. always commit on `main`
2. every month, create a branch from `main` using `create_branch` (for example `branch="2023-12-06"`).
3. use `super_squash_commit` on both the `main` branch and the new branch
4. continue commits on `main`

This way you would not have a full history but at least you can keep standalone snapshots over time.
**Warning:** once the branch is squashed, its history is completely decorrelated from the other branches. This means you cannot merge/rebase them anymore.

Please let me know if you have any further question.

**Comment by narugo1992** [comment]
Okay, my problems have been solved with `super_squash_commit`. thks

**Comment by Wauplin** [comment]
Glad to hear that!
