### ISSUE TITLE
Upload anonymously to public repository

### ISSUE THREAD

**Issue by avivStudy** [huggingface/huggingface_hub#1894]
Hello HuggingFace Team!

I noticed it is technically possible to download anonymously (without access token), but not to upload.
I wonder, should this be a limit on the client side? Isn't it best to let the repository decide whether or not to allow it (by responding either with 401 or 200)?

When I try to upload without specifying a token (I use HfApi.upload_folder), a pre-upload request is sent. However, if the repository responds with 200, the client then fails to build the next request due to the missing access token:
```
raise LocalTokenNotFoundError(
huggingface_hub.utils._headers.LocalTokenNotFoundError: Token is required (`token=True`), but no token found. You need to provide a token or be logged in to Hugging Face with `huggingface-cli login` or `huggingface_hub.login`. See https://huggingface.co/settings/tokens.
```

**Comment by Wauplin** [comment]
> I noticed it is technically possible to download anonymously (without access token), but not to upload.

Hi @avivStudy. Yes, this is intended. What would be your use case to upload files anonymously?
Currently all repos (models/datasets/spaces) are stored under a namespace. This namespace is either the username or the organization name. If a repository wouldn't have a owner or a namespace we wouldn't be able to know who can push to it or not (i.e. either it will be a read-only repo or everyone would be able to push to it). It also raises questions on who is responsible for the model/data that are pushed anonymously.

**Comment by avivStudy** [comment]
I don't really need it, just wondered why is it a limitation on the client instead of server.
Thank you @Wauplin!

**Comment by Wauplin** [comment]
> why is it a limitation on the client instead of server.

Mostly to fail early on obvious error (saves time + make the error message explicit).

**Comment by avivStudy** [comment]
I see. It could fail even earlier though - not send the pre-upload request at all, and print the error once the client figures it has no token to send.
