### ISSUE TITLE
snapshot_download timeout will not resume

### ISSUE THREAD

**Issue by merlinarer** [huggingface/huggingface_hub#1903]
### Describe the bug

I use snapshot_download to download datasets. While when timeout occurs, the snapshot_download will not resume from previous files.

### Reproduction

```
def snapdown_dataset(repo_id, save_dir="Datasets", symlinks=False):
    local_dir = f"{save_dir}/{repo_id.replace('/', '_')}"
    logging.info(f"Saving {repo_id} to {local_dir}")
    snapshot_download(
        repo_id=repo_id,
        repo_type="dataset",
        cache_dir=".cache",
        local_dir=local_dir,
        local_dir_use_symlinks=symlinks,
        resume_download=True,
        etag_timeout=600,
        max_workers=2
    )

snapdown_dataset("CASIA-LM/ChineseWebText")
```
### Logs

```shell
2023-12-14 00:45:15,775 - Datasets-general - INFO - [2/2] CASIA-LM/ChineseWebText - Start[3]
INFO:Datasets-general:[2/2] CASIA-LM/ChineseWebText - Start[3]
Downloading .gitattributes: 100%|████████████████| 2.35k/2.35k [00:00<00:00, 21.0MB/s]
Fetching 298 files:   0%|                         | 1/298 [15:39<77:30:15, 939.44s/it]
Downloading part-0002.jsonl:  12%|█▋            | 1.25G/10.7G [14:18<4:01:14, 655kB/s]
Downloading part-0001.jsonl:  59%|███████     | 6.29G/10.7G [1:02:07<1:34:14, 786kB/s]
2023-12-14 01:47:30,572 - Datasets-general - ERROR - [2/2] CASIA-LM/ChineseWebText - Error:oading part-0001.jsonl:  59%|█████▊    | 6.29G/10.7G [1:02:07<26:12:52, 47.1kB/s]HTTPSConnectionPool(host='cdn-lfs-us-1.huggingface.co', port=443): Read timed out.

ERROR:Datasets-general:[2/2] CASIA-LM/ChineseWebText - Error:
HTTPSConnectionPool(host='cdn-lfs-us-1.huggingface.co', port=443): Read timed out.

Downloading part-0000.jsonl:  12%|█▎         | 1.24G/10.7G [1:02:09<14:53:58, 177kB/s]
2023-12-14 01:47:30,573 - Datasets-general - INFO - [2/2] CASIA-LM/ChineseWebText - Start[4]
INFO:Datasets-general:[2/2] CASIA-LM/ChineseWebText - Start[4]
Downloading .gitattributes: 100%|████████████████| 2.35k/2.35k [00:00<00:00, 15.2MB/s]
Fetching 298 files:   0%|                             | 1/298 [00:02<14:45,  2.98s/it]
Downloading part-0000.jsonl:  28%|███▊          | 2.96G/10.7G [32:56<2:21:46, 915kB/s]
Downloading part-0001.jsonl:  11%|█▌            | 1.16G/10.7G [24:40<8:41:58, 306kB/s]
Downloading part-0002.jsonl:   1%|              | 62.9M/10.7G [01:29<3:41:04, 805kB/s]
Downloading part-0003.jsonl:   3%|▍              | 294M/10.7G [04:52<3:34:48, 810kB/s]
```

### System info

```shell
- 'huggingface_hub version': '0.13.0'
- 'Platform': 'Linux-6.2.0-37-generic-x86_64-with-glibc2.35'
- 'Python version': '3.11.5'
I tried on v0.19.0 and consistency checking error always happens so I change to 0.13.
```

**Comment by Wauplin** [comment]
Hi @merlinarer, sorry you are facing problems while downloading. I'm not exactly sure why it's behaving like this though. I think `local_dir_use_symlinks=False` and `resume_download=True` don't play well together. As explained in [this guide](https://huggingface.co/docs/huggingface_hub/guides/download#download-files-to-local-folder), downloading to a local folder + disabling symlinks means the cache-system is not used and that re-triggering a download will re-download the files. To get the best user experience, it's usually better to let `huggingface_hub` download the file into the cache (see [guide](https://huggingface.co/docs/huggingface_hub/guides/manage-cache)) which will be very beneficial if you try to download the same data several times (due to timeout error or any other reason).

**Comment by Wauplin** [comment]
As a side note, you can also avoid the read timeout issues by setting `HF_HUB_DOWNLOAD_TIMEOUT=60` as environment variable. This should prevent most of the timeouts. Default is 10s. See [this reference](https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfhubdownloadtimeout) for details. Only the latest version of `huggingface_hub` (0.19.x) uses this environment variable.

**Comment by merlinarer** [comment]
> Hi @merlinarer, sorry you are facing problems while downloading. I'm not exactly sure why it's behaving like this though. I think `local_dir_use_symlinks=False` and `resume_download=True` don't play well together. As explained in [this guide](https://huggingface.co/docs/huggingface_hub/guides/download#download-files-to-local-folder), downloading to a local folder + disabling symlinks means the cache-system is not used and that re-triggering a download will re-download the files. To get the best user experience, it's usually better to let `huggingface_hub` download the file into the cache (see [guide](https://huggingface.co/docs/huggingface_hub/guides/manage-cache)) which will be very beneficial if you try to download the same data several times (due to timeout error or any other reason).

It works! Many thanks for your helpful advice !

**Comment by Wauplin** [comment]
Glad to know your problem is solved!
