### ISSUE TITLE
hf_hub_download() not checking the local_dir and just return pointer_path

### ISSUE THREAD

**Issue by Jone20231102** [huggingface/huggingface_hub#1909]
when i review the hf_hub_download(), I found when the process get the FileLock, first to check the exist of the pointer_path. if the pointer_path exists, instead of checking the local_dir, it just returns. Refer to the preceding implementation, if local_dir is set, copy it to local_dir and return local_dir?
![Untitled](https://github.com/huggingface/huggingface_hub/assets/149677114/ea95b7a4-40ca-42b5-b080-a9868e714406)

**Comment by Wauplin** [comment]
Thanks for reporting @Jone20231102! Looks like a bug indeed. I'll have a look how we will fix this.
(note: might also be the case when returning with `local_files_only` or failed connection...)
