### ISSUE TITLE
Uniformized logging with other HF libs

### ISSUE THREAD

**Issue by thomwolf** [huggingface/huggingface_hub#191]
The `huggingface_hub` library should also have a logging module like the other libraries (and maybe we should actually centralize all the logging command in this library once both `datasets` and `transformers` depend on it so that people can simply control all the logging of our tools.

Current reason to raise the issue is that uploading a very large dataset has no indication of status (since the logging is to info level by default).

**Comment by thomwolf** [comment]
Actually this might come from another origin (like piping conveniently the output of the subprocess).

I'll just describe the problem instead of giving my feeling on its source then.

Problem:
- uploading a large dataset
- with the Repository.commit context manager
- in a notebook
shows no indication of progress (out-of-the-box).

Changing the logging level doesn't seem to solve the issue.

**Comment by thomwolf** [comment]
In general I think that all the output of the git commands in the `Repository` class (e.g. from `lfs_track` or other `git pull`) should be redirected to the python logging

**Comment by LysandreJik** [comment]
I think having centralized logging in the `huggingface_hub` is a good idea. I'm not too sure of having both `datasets` and `transformers` depend on it: while I understand the convenience of having a single command to control all logging, we'll have to ensure that `datasets` & `transformers` & `huggingface_hub` all have the same philosophy regarding logging levels.

I agree with you that having the output of the git commands should be redirected to the Python logging with the option to control that with `logging`.

**Comment by LysandreJik** [comment]
Solved by https://github.com/huggingface/huggingface_hub/pull/262
