### ISSUE TITLE
Using `DISABLE_TELEMETRY` is deprecated

### ISSUE THREAD

**Issue by allo-** [huggingface/huggingface_hub#1917]
### Describe the bug

Huggingface hub 0.19.4 outputs:

```
Using `DISABLE_TELEMETRY` is deprecated and will be removed in v5 of Transformers. Use `HF_HUB_DISABLE_TELEMETRY`
```

This is a bad idea because `DISABLE_TELEMETRY` is intended to be an opt-out standard (I even think telemetry should be opt-in) for users to disable all telemetry. Many users wouldn't even know that the environment variable `HF_HUB_DISABLE_TELEMETRY` exists without this message.

It is a good idea to support both. Then `DISABLE_TELEMETRY` is the global kill switch for users who don't want any application to send telemetry, and `HF_HUB_DISABLE_TELEMETRY` is the option to disable only huggingface-hub's telemetry, without opting out of telemetry from other applications.

No longer supporting the global option is against the user's expressed wish to disable all telemetry and ignoring an opt-out flag.

### Reproduction

Run a program that uses huggingface hub and wants to send telemetry data.

### Logs

```shell
FutureWarning: Using `DISABLE_TELEMETRY` is deprecated and will be removed in v5 of Transformers. Use `HF_HUB_DISABLE_TELEMETRY` instead.
```

### System info

```shell
- huggingface_hub version: 0.19.4
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
...
- ENDPOINT: https://huggingface.co
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: True
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment]
Hi @allo-, thanks for opening the discussion. I haven't thought about that but your suggestions make sense yes. Do you have examples of other libraries using this environment variables just to get an idea of how common this is?

**Comment by allo-** [comment]
Here is a page about the `DO_NOT_TRACK` (I had in mind that they would also use `DISABLE_TELEMETRY`) environment variable: https://consoledonottrack.com

And my current set of do-not-track settings is now:

```
export DO_NOT_TRACK=1
export DISABLE_TELEMETRY=1
export STNOUPGRADE=1
export HF_HUB_DISABLE_TELEMETRY=1
```

It looks like quite a few cli tools are adding telemetry and update checks (even when installed via package managers), and many are even pinging third party sites like google-analytics, which may correlate the telemetry data with other data known about the user. I think it may be more common in certain communities, but let's not blame projects as long as there is an opt-out.

Unfortunately, many projects seem to use only custom variables, I've found for `DISABLE_TELEMETRY`:
- Powershell
- Docker
- Huggingface
- Chatwoot

I think agreeing on a common switch to disable unexpected telemetry/update checks is user friendly, and in some environments it may even be a compliance requirement that software should not make unexpected network connections or transmit information about the system it runs on.

Reading that page again, `DO_NOT_TRACK` is the another choice, as they are trying to establish it as some kind of standard, but `DISABLE_TELEMETRY` is already implemented. The `HF_HUB_DISABLE_TELEMETRY` variable, on the other hand, is something you would only know about if you read the developer documentation, and would be unknown to users of downstream projects using huggingface-hub.

I would suggest:
- Keep `DISABLE_TELEMETRY`. People already have it configured, its name is easy to remember, and it is likely to be used by more software.
- Maybe implement `DO_NOT_TRACK`.
- Possibly also keep `HF_HUB_DISABLE_TELEMETRY` as some people may have upgraded to the new variable now. It also allows you to opt-out huggingface telemetry (or opt-in, when `0` is treated as enabling telemetry) without affecting other softwares.
- I wonder if a switch in a configuration file (which may have an example file) would be useful, but I only seem to find the cache and login token in my current installation and no global configuration files for huggingface.

**Comment by Wauplin** [comment]
Thanks for the detailed list @allo-! On the principle, I agree with you that having a standard in addition to a custom environment variable is a good idea.

Regarding the warning + deprecation cycle, this was my fault - I overlooked the default behavior already done in `huggingface_hub` [that consider both `HF_HUB_DISABLE_TELEMETRY` and `DISABLE_TELEMETRY` as valid](https://github.com/huggingface/huggingface_hub/blob/c4ddfc77b788f7e48558f6faeccf2e088aab00b2/src/huggingface_hub/constants.py#L118). The warning is not thrown by `huggingface_hub` but by `transformers` itself. I opened a PR to remove it: https://github.com/huggingface/transformers/pull/28113

Regarding having a standard to deactivate telemetry, it looks like a global consensus doesn't exist (yet?). As of now, telemetry in the HF ecosystem is quite sparse (see usage [here](https://github.com/search?q=org%3Ahuggingface+send_telemetry&type=code)) and doesn't use any third-party tools. However I can understand that people still want to disable it and that's why we have this config value. What I suggest for now is to respect `HF_HUB_DISABLE_TELEMETRY` (already the case), `DISABLE_TELEMETRY` (already the case) and `DO_NOT_TRACK` (open PR https://github.com/huggingface/huggingface_hub/pull/1920).

Does that work for you?

**Comment by Wauplin** [comment]
> It does not implement a HF-specific opt-in and one might think that DO_NOT_TRACK=1 HF_HUB_DISABLE_TELEMETRY=0 could be a signal to disable tracking for all but the huggingface hub. On the other hand, I wonder how many people would want to do that, and if they can't just wrap the call in a small script that unsets the DO_NOT_TRACK flag.

Yes indeed. For now opting out from any of the environment variable result in telemetry been disabled. Honestly I don't know how much people wants to disable telemetry globally except for HF so I think it's best not to over-engineer it. Having a rule "if any is set, let's disable it" is the safest and simplest to explain in my opinion. 

> The problem with telemetry is that it is often intransparent.

Agree. And yes, didn't want to argue people should not disable it. Just wanted to give some context.

**Comment by Wauplin** [comment]
Let's close this issue since https://github.com/huggingface/huggingface_hub/pull/1920 is now merged. Is that ok for you @allo- ?

**Comment by allo-** [comment]
Yes. I only waited if you still want to add something. And it also was a quite fast merge!
