### ISSUE TITLE
Make note that token from hugging face will not echo

### ISSUE THREAD

**Issue by vtrenton** [huggingface/huggingface_hub#1924]
### Describe the bug

I'm embarrassed to say I didn't realize at first that the program would not echo my token and pasted it a few times in the process. I've created a PR to add a little note stating that the token will not echo to the user as part of this issue. This will hopefully help people like me in the future not make this mistake.

### Reproduction

log in to huggingface using the cli

### System info

```shell
Package: huggingface-hub 0.19.4, installed using Python 3.11.6
OS: OpenSUSE MicroOS (tumbleweed distrobox)
Kernel: 6.6.6-1-default
```

**Comment by Wauplin** [comment]
Thanks for opening this issue + PR. I commented directly on the PR!
