### ISSUE TITLE
Fail early if modelcard metadata is not correct on `create_commit`

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1927]
On the `/commit` endpoint, if a `README.md` file is uploaded, the metadata section is parsed and validated by the server. If the format is not correct, a HTTP 400 Bad Request is returned and the commit fails. This can be annoying when it happens after having uploaded LFS files to S3. It would be good to keep the same rule but to check the yaml metadata first and fail early in case it's not valid.

We can do this using the `/api/validate-yaml` endpoint. In `create_commit` we should loop through the `CommitOperationAdd` and if `operation.path_in_repo == "README.md"`, then we make an extra call to this endpoint and gracefully fail with a custom error message. Here is an example on how to use it:  

```py
from huggingface_hub.utils import get_session, hf_raise_for_status

modelcard = """
---
language: en
license: apache-2.0
model-index: not correct
---

This is a model card.
"""

response = get_session().post("https://huggingface.co/api/validate-yaml", json={"content": modelcard, "repoType": "model"})
hf_raise_for_status(response)
```

which leads to
```
Traceback (most recent call last):
  File "/home/wauplin/projects/huggingface_hub/src/huggingface_hub/utils/_errors.py", line 286, in hf_raise_for_status
    response.raise_for_status()
  File "/home/wauplin/projects/huggingface_hub/.venv310/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://huggingface.co/api/validate-yaml

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wauplin/projects/huggingface_hub/validate.py", line 15, in <module>
    hf_raise_for_status(response)
  File "/home/wauplin/projects/huggingface_hub/src/huggingface_hub/utils/_errors.py", line 329, in hf_raise_for_status
    raise BadRequestError(message, response=response) from e
huggingface_hub.utils._errors.BadRequestError:  (Request ID: Root=1-6582b191-1613cfc028067d6c3f70c2e6;098e8e39-4860-4c16-bc96-fd2ddb6ffbd8)

Bad request:
"model-index" must be an array
```

**Comment by manlattan** [comment]
Is this issue still open? If not I would like to work on this! Please let me know.

**Comment by Wauplin** [comment]
Hi @manlattan, thanks for proposing you! This issue has been completed as part of https://github.com/huggingface/huggingface_hub/pull/1934 but you can find other "good first issues" on this page: https://github.com/huggingface/huggingface_hub/contribute. Thanks in advance!

**Comment by manlattan** [comment]
@Wauplin No worries! Thanks for responding.
