### ISSUE TITLE
Maximum individual file size is 50.0GB error when my file is less than 50.0GB

### ISSUE THREAD

**Issue by ysig** [huggingface/huggingface_hub#1933]
### Describe the bug

Hi,

I'm trying to upload a private dataset .zip file that is 47GB and I receive the error:

```
Maximum individual file size is 50.0GB
```

in both the programmatic and the web api.

Is this an implementation bug?

Thanks,
ysig

### System info

```shell
- huggingface_hub version: 0.17.3
- Platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.31
- Python version: 3.11.5
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/isig/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: <>
- Configured git credential helpers: remove
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.0.1
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.4.0
- hf_transfer: N/A
- gradio: 3.44.0
- tensorboard: N/A
- numpy: 1.23.5
- pydantic: 2.4.2
- aiohttp: 3.8.5
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /home/isig/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /home/isig/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/isig/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False

{'huggingface_hub version': '0.17.3', 'Platform': 'Linux-5.15.0-91-generic-x86_64-with-glibc2.31', 'Python version': '3.11.5', 'Running in iPython ?': 'No', 'Running in notebook ?': 'No', 'Running in Google Colab ?': 'No', 'Token path ?': PosixPath('/home/isig/.cache/huggingface/token'), 'Has saved token ?': True, 'Who am I ?': '<>', 'Configured git credential helpers': 'remove', 'FastAI': 'N/A', 'Tensorflow': 'N/A', 'Torch': '2.0.1', 'Jinja2': '3.1.2', 'Graphviz': 'N/A', 'Pydot': 'N/A', 'Pillow': '9.4.0', 'hf_transfer': 'N/A', 'gradio': '3.44.0', 'tensorboard': 'N/A', 'numpy': '1.23.5', 'pydantic': '2.4.2', 'aiohttp': '3.8.5', 'ENDPOINT': 'https://huggingface.co', 'HUGGINGFACE_HUB_CACHE': '/home/isig/.cache/huggingface/hub', 'HUGGINGFACE_ASSETS_CACHE': '/home/isig/.cache/huggingface/assets', 'HF_TOKEN_PATH': '/home/isig/.cache/huggingface/token', 'HF_HUB_OFFLINE': False, 'HF_HUB_DISABLE_TELEMETRY': False, 'HF_HUB_DISABLE_PROGRESS_BARS': None, 'HF_HUB_DISABLE_SYMLINKS_WARNING': False, 'HF_HUB_DISABLE_EXPERIMENTAL_WARNING': False, 'HF_HUB_DISABLE_IMPLICIT_TOKEN': False, 'HF_HUB_ENABLE_HF_TRANSFER': False}
```

**Comment by Wauplin** [comment]
Hi @ysig, thanks for reporting. Usually we recommend to avoid pushing such big files. Main reasons is that 1. it's hard to upload/download in case a ConnectionError happens and 2. files are not served via our CDN, making it slower to download. A good file size for big dataset would be in the range 5-10GB. Maybe you can split you zipped files in several chunks? To learn more about repo limits and recommendation, check out this [guide](https://huggingface.co/docs/hub/repositories-recommendations).

Regarding your exact error, I don't know the issue here. It might be due to a confusion between `GB` (1000^3) and `GiB` (1024^3).

**Comment by ysig** [comment]
What you call GiB is actually GB no?
![image](https://github.com/huggingface/huggingface_hub/assets/28439529/d005a30d-90a6-41fa-810c-ac0962e17e46)

Also whatever `du -sh` gives should be 'the ground truth' of how many GBs a file is.

Thank you for your suggestion however, I will try to follow it :))

**Comment by ysig** [comment]
@Wauplin I want to upload ~5M image files. Can you suggest the best way to do so? From what you write it sounds like I should just upload a folder with the files as is, however is this the best option? `api.upload_folder` takes already a significant amount of time without starting the upload.

**Comment by Wauplin** [comment]
(re: 50.0GB => if you have a file containing 1_000_000_000 bytes, `du -sh` will display `954M` (you can easily try it locally). What we call "50.0GB" as a limit is literally 50_000_000_000 bytes, which is slightly lower than 47*1024*1024*1024. No big impact though as it's not good practice anyway.) 

About the question "how to upload 5 millions images" the best approach in my opinion would be to store it in parquet files. The maximum number of files per repo is 100k so you can't simply upload the individual files. I'm not sure what's the best approach to upload a dataset of this size as parquet files I'll ping @lhoestq @severo @mariosasko @albertvillanova from the `dataset` team :)

**Comment by mariosasko** [comment]
It's simpler to store it as a [web dataset](https://github.com/webdataset/webdataset) (can be sharded to avoid the file size error). [This doc](https://huggingface.co/docs/datasets/main/en/image_dataset#webdataset) explains creating one in a few sentences.

**Comment by Wauplin** [comment]
Going to close this issue as fixed. @ysig if you need further assistance, feel free to reach out :)
