### ISSUE TITLE
Key error [0]

### ISSUE THREAD

**Issue by surya-narayanan** [huggingface/huggingface_hub#1941]
Hi, 

It seems that commenting out the `[0]` in this line of code 

https://github.com/huggingface/huggingface_hub/blob/2effe3f9d0fc47c8c6a934b321f5a2551f330caf/src/huggingface_hub/inference/_client.py#L1541

seems to produce intended behavior when `client.text_generation()` is called. Keeping the `[0]`, results in a `KeyError`

**Comment by Wauplin** [comment]
Hi @surya-narayanan. Thanks for reporting. Could you tell us more about your bug? Which model are you using? Served on which platform? (TGI, Inference API, Inference Endpoint, AWS, etc.). Can you also copy-paste your script and full stacktrace? Thanks in advance :)

**Comment by Wauplin** [comment]
Closing this issue as stale (not  enough information about the problem). Feel free to comment and I'll reopen :)
