### ISSUE TITLE
Spaces: Third party component streamlit-tags not loading

### ISSUE THREAD

**Issue by dk-crazydiv** [huggingface/huggingface_hub#195]
Link:https://huggingface.co/spaces/dk-crazydiv/streamlit-tags-breaking

Requirements installed:
```
streamlit==0.82.0
transformers==4.8.2
torch==1.9.0
streamlit-tags==1.2.6
```

#### Error Message on Spaces
![image](https://user-images.githubusercontent.com/47515542/125831786-9ab6ebad-a090-41ff-9da3-47b713454a5e.png)

#### Expected behaviour
![image](https://user-images.githubusercontent.com/47515542/125832181-73fb838b-9ab0-4100-8ad9-32bd3ee61809.png)

### Info:
- The same code works fine on local & on [streamlit share ](https://share.streamlit.io/dk-crazydiv/recipe-generator/dev/server.py)
-  A request in console is 404 on spaces page, but works on share.streamlit.io (looks like it might be an iframe blocking issue)

Thanks for help!

**Comment by gagan3012** [comment]
Hi @osanseviero 
Can I help fix this I created streamlit-tags and maybe I can help fix this issue

**Comment by osanseviero** [comment]
Hi @gagan3012,

Thanks for offering help with the issue! Unfortunately the Spaces code has not been open sourced. @cbensimon from the team will be looking into this 👍 

Thanks again for offering help!

**Comment by gagan3012** [comment]
No Worries Thanks for letting me know

**Comment by cbensimon** [comment]
HF Spaces now supports Streamlit components (see https://huggingface.co/docs/hub/spaces#changelog)

https://huggingface.co/spaces/dk-crazydiv/streamlit-tags-breaking is now working as expected

**Comment by julien-c** [comment]
Great job @cbensimon! 🥳
