### ISSUE TITLE
Missing `= None` in `GitRefs` for `pull_requests`.

### ISSUE THREAD

**Issue by PhilipMay** [huggingface/huggingface_hub#1956]
https://github.com/huggingface/huggingface_hub/blob/a331e82aad1bc63038194611236db28fa013814c/src/huggingface_hub/hf_api.py#L1097

`pull_requests` is marked as `Optional` but I think an `= None` is missing.

Also see the issue here: https://github.com/UKPLab/sentence-transformers/pull/2396#issuecomment-1877083654

**Comment by Wauplin** [comment]
Thanks for reporting @PhilipMay! I opened https://github.com/huggingface/huggingface_hub/pull/1960 to fix this.
