### ISSUE TITLE
Always broken when nearly finish.

### ISSUE THREAD

**Issue by bobby20180331** [huggingface/huggingface_hub#1959]
### Describe the bug

OSError: Consistency check failed: file should be of size 492265168 but has size 447786685 (model.safetensors).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.

### Reproduction
When I try download repo：stabilityai/sd-turbo 
"huggingface-cli download %s %s %s --local-dir-use-symlinks False --resume-download %s %s"
        % (token_option, include_option, exclude_option, args.model, save_dir_option)

### Logs

```shell
OSError: Consistency check failed: file should be of size 492265168 but has size 447786685 (model.safetensors).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.
```

### System info

```shell
- huggingface_hub version: 0.20.1
- Platform: Linux-5.15.0-25-generic-x86_64-with-glibc2.35
- Python version: 3.9.1
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/ubuntu/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: N/A
- Jinja2: N/A
- Graphviz: N/A
- Pydot: N/A
- Pillow: N/A
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.26.3
- pydantic: N/A
- aiohttp: N/A
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /home/ubuntu/.cache/huggingface/hub
- HF_ASSETS_CACHE: /home/ubuntu/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/ubuntu/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10

{'huggingface_hub version': '0.20.1', 'Platform': 'Linux-5.15.0-25-generic-x86_64-with-glibc2.35', 'Python version': '3.9.1', 'Running in iPython ?': 'No', 'Running in notebook ?': 'No', 'Running in Google Colab ?': 'No', 'Token path ?': '/home/ubuntu/.cache/huggingface/token', 'Has saved token ?': False, 'Configured git credential helpers': '', 'FastAI': 'N/A', 'Tensorflow': 'N/A', 'Torch': 'N/A', 'Jinja2': 'N/A', 'Graphviz': 'N/A', 'Pydot': 'N/A', 'Pillow': 'N/A', 'hf_transfer': 'N/A', 'gradio': 'N/A', 'tensorboard': 'N/A', 'numpy': '1.26.3', 'pydantic': 'N/A', 'aiohttp': 'N/A', 'ENDPOINT': 'https://huggingface.co', 'HF_HUB_CACHE': '/home/ubuntu/.cache/huggingface/hub', 'HF_ASSETS_CACHE': '/home/ubuntu/.cache/huggingface/assets', 'HF_TOKEN_PATH': '/home/ubuntu/.cache/huggingface/token', 'HF_HUB_OFFLINE': False, 'HF_HUB_DISABLE_TELEMETRY': False, 'HF_HUB_DISABLE_PROGRESS_BARS': None, 'HF_HUB_DISABLE_SYMLINKS_WARNING': False, 'HF_HUB_DISABLE_EXPERIMENTAL_WARNING': False, 'HF_HUB_DISABLE_IMPLICIT_TOKEN': False, 'HF_HUB_ENABLE_HF_TRANSFER': False, 'HF_HUB_ETAG_TIMEOUT': 10, 'HF_HUB_DOWNLOAD_TIMEOUT': 10}
```

**Comment by Wauplin** [comment]
@bobby20180331 I'm sorry you're facing this issue. Did you try to re-run the command and got the same error? This error is raised when the downloaded content does not match the expected size. It can happen on slow/intermittent network and is most of the time a transient error. Unfortunately we can't do much about it except retrying as it's very hard to investigate (I actually never been able to reproduce this issue myself on a laptop).

Also, are you sure it was when downloading from `stabilityai/sd-turbo`? I'm asking since I can't find any `model.safetensors` file under https://huggingface.co/stabilityai/sd-turbo/tree/main that is ~500MB. The only one I've found is [this one](https://huggingface.co/stabilityai/sd-turbo/blob/main/text_encoder/model.safetensors) which weights 1.36GB.

**Comment by Wauplin** [comment]
Closing this issue as stale (not enough info). Please feel free to comment again and I'll reopen.
