### ISSUE TITLE
Docs request: CLI default of `--repo-type`

### ISSUE THREAD

**Issue by jamesbraza** [huggingface/huggingface_hub#1963]
**Is your feature request related to a problem? Please describe.**

With `huggingface-hub[cli]==0.20.2`, running 

```bash
> huggingface-cli download --help
...
options:
  -h, --help            show this help message and exit
  --repo-type {model,dataset,space}
                        Type of repo to download from (e.g. `dataset`).
...
```

The default of `--repo-type` is not shown. I believe the default is `model`, or it may be inferred.

**Describe the solution you'd like**

Documenting what the default behavior is.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by jamesbraza** [comment]
Hi @Wauplin okay can help here. Let me ask you, are you open to using `ArgumentDefaultHelpFormatter` as detailed [here](https://stackoverflow.com/a/12151325)?

As opposed to one-off editing `help` messages, it would be nice to have all defaults used

**Comment by Wauplin** [comment]
Yes definitely open to this suggestion, thanks! 
We just need to make sure we won't duplicate a `defaults to ...` somewhere (if already present in the "raw" help message).
