### ISSUE TITLE
Request: `setup.py` extra for `hf_transfer`

### ISSUE THREAD

**Issue by jamesbraza** [huggingface/huggingface_hub#1964]
As of `huggingface_hub==0.20.2`, there is no extra for  [`hf_transfer`](https://pypi.org/project/hf-transfer/).

It would be cool if there was a `setup.py` extra for `hf_transfer` at https://github.com/huggingface/huggingface_hub/blob/v0.20.2/setup.py#L24-L94

```bash
pip install huggingface_hub[transfer]
```

Which would auto-include `hf_transfer` in the requirements

**Comment by Wauplin** [comment]
Yes, true :) Would you like to open a PR for it? I would name the extra `hf_transfer` to keep a single naming.
From a quick look at the documentation, we are suggesting to run `pip install hf_transfer` in both `upload.md` and `download.md`. Could you update both docs to install from the extra if that's the case? Thanks in advance!
