### ISSUE TITLE
Inconsistent warning raising

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#1978]
Some parts of the codebase use `warnings.warn` and some use `logger.warning`. Due to this, some warnings ignore the set logging verbosity level.

E.g.

```python
dataset = load_dataset("huggan/smithsonian_butterflies_subset", split="train")
```

Will give a user warning

```
warnings.warn("Repo card metadata block was not found. Setting CardData to empty.")
```

Should we just use `logger.warning` everywhere?

**Comment by Wauplin** [comment]
I tend to make a difference between `logger.warn` and `warnings.warn`. From [Python official documentation](https://docs.python.org/3/howto/logging.html#when-to-use-logging):

> [warnings.warn()](https://docs.python.org/3/library/warnings.html#warnings.warn) in library code if the issue is avoidable and the client application should be modified to eliminate the warning
> [logging.warning()](https://docs.python.org/3/library/logging.html#logging.warning) if there is nothing the client application can do about the situation, but the event should still be noted

We are most likely not 100% consistent with this rule in the codebase but I think we should aim for it.

> warnings.warn("Repo card metadata block was not found. Setting CardData to empty.")

I agree that for this specific example, we should use `logger.warn` instead :+1:
