### ISSUE TITLE
[Feature request] Allow specifying `save_dir`  in `snapshot_download`

### ISSUE THREAD

**Issue by cccntu** [huggingface/huggingface_hub#198]
This will make it easier to load without relying on `cache_dir`. IMO it also matches the function name `snapshot_download` better. (The current functionality of `snapshot_download` feels more like `cached_download`.)
```python
snapshot_download('bert-base-uncased', save_dir='local_dir')
AutoModel.from_pretrained('local_dir')
```

Currently it's like this:
https://github.com/huggingface/huggingface_hub/blob/eed85ca66fd29618870d630a067ec641e0e98085/src/huggingface_hub/snapshot_download.py#L47-L49

**Comment by osanseviero** [comment]
Hi @cccntu,

`snapshot_download` already returns the path to where the repo was saved, so you can do this

```
local_repo_path = snapshot_download('bert-base-uncased')
model = AutoModel.from_pretrained(local_repo_path)
```

No need of building the path yourself :) Let us know if this works for you

**Comment by cccntu** [comment]
I am aware of that, thanks. @osanseviero 
I intend to run it in two separate scripts, so the best alternative is to rename/move the dir in first script, but I think it's better if there is a built-in option.

**Comment by LysandreJik** [comment]
Hi @cccntu, `snapshot_download` is actually similar to `cached_download` in that both of those cache the repositories downloaded; so that with the repository identifier only you won't need to specify whether to redownload the new version, as it will do so automatically.

If specifying a `save_dir` then we would lose that caching ability

**Comment by osanseviero** [comment]
As an addition to that, if you use `snapshot_download` in two different scripts, both will point to same place, so you will have access to the same cached files in both.

**Comment by cccntu** [comment]
For context, my use case is first downloading a snapshot, then COPY to docker image at build time. So when the docker images starts, it won't need to download the model, or even call the api, it can immediately load the local copy.

But I guess I don't really care about the storage used by cache, copying (instead of moving) the snapshot sounds better. And copying doesn't feel like something that should be supported. Closing the issue.
Thanks for the comments! @LysandreJik @osanseviero
