### ISSUE TITLE
Use safetensors by default for PyTorchModelHubMixin class

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/huggingface_hub#1989]
**Is your feature request related to a problem? Please describe.**

The PyTorchModelHubMixin currently saves weights as a `pytorch_model.bin` file, which is considered unsafe.

**Describe the solution you'd like**

Would be great to update to leverage the `safetensors` format by default.

**Describe alternatives you've considered**

/

**Additional context**

/

**Comment by bmuskalla** [comment]
Pushed a potential fix as #2033 - the big open question is whether to keep this backwards-compatible and/or issue a warning if the mixin is still loading it from a pickle file

**Comment by Wauplin** [comment]
Thanks @bmuskalla! I continued the discussion on the PR directly. General guidelines is to prevent unannounced breaking changes as much as possible. So what we should do is to support safetensors right now and after a few releases, make it the default + slowly remove support for unsafe loading.

**Comment by Wauplin** [comment]
@NielsRogge this issue has been completed by @bmuskalla in https://github.com/huggingface/huggingface_hub/pull/2033 and will be available in the soon-to-be-published release! Together with https://github.com/huggingface/huggingface_hub/pull/2001 it fixes the biggest problems you've mentioned about the mixin right? (except handling sharding that should be done soon now that https://github.com/huggingface/huggingface_hub/pull/1938 have been merged)
