### ISSUE TITLE
Spaces: Gradio interface title and description is invisible in darkmode

### ISSUE THREAD

**Issue by cccntu** [huggingface/huggingface_hub#199]
Example Space:
https://huggingface.co/spaces/flax-community/FT5-demo

Dark mode:
![image](https://user-images.githubusercontent.com/31893406/125904655-7a7908e1-4d6c-4e81-8e10-5d0c43585e2d.png)
![image](https://user-images.githubusercontent.com/31893406/125904735-f132eb40-4acb-4b57-bfcd-2da92141b15a.png)

Light mode:
![image](https://user-images.githubusercontent.com/31893406/125904707-7f60b7b0-c929-4020-a5d8-6e84415f00d9.png)

**Comment by abidlabs** [comment]
Tagging @aliabid94 here as well to see if a styling fix can come from the Gradio library itself

**Comment by cbensimon** [comment]
It's fixed ! Dark theme now works well in Gradio Spaces
