### ISSUE TITLE
Is it possible to create a pull request from an existing branch? 

### ISSUE THREAD

**Issue by x54-729** [huggingface/huggingface_hub#1998]
**Is your feature request related to a problem? Please describe.**
```bash
git clone https://huggingface.co/repo_anme/model_name
git branch update
git checkout update
# add and commit
git push origin update
```

Then is it possible to create a PR from branch `update` in website or `huggingface-cli`?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Wauplin** [comment]
Hi @x54-729, no this is not possible at the moment. What you can do is create an empty PR on the Hub (either in the browser or with `huggingface_hub`) and then push changes to it. 

Here is a the `huggingface-cli` command to do it in a single line:
```bash
# Upload local folder to new ref + create a PR
>>> huggingface-cli upload bigcode/the-stack . . --repo-type dataset --create-pr
https://huggingface.co/datasets/bigcode/the-stack/blob/refs%2Fpr%2F104/
```

**Comment by x54-729** [comment]
> Hi @x54-729, no this is not possible at the moment. What you can do is create an empty PR on the Hub (either in the browser or with `huggingface_hub`) and then push changes to it. Creating a PR gives you a git `ref` to which you can push, even if you don't have author permission on the target repo.
> 
> Here is a the `huggingface-cli` command to do it in a single line:
> 
> ```shell
> # Upload local folder to new ref + create a PR
> >>> huggingface-cli upload bigcode/the-stack . . --repo-type dataset --create-pr
> https://huggingface.co/datasets/bigcode/the-stack/blob/refs%2Fpr%2F104/
> ```
> 
> If this does not support your use case, please let us know :)

Thanks a lot, I will try huggingface_hub

**Comment by Wauplin** [comment]
Just for reference for you (or anyone landing on this issue), creating a PR with `huggingface_hub` is as easy as adding `create_pr=True` in any upload method (`upload_file`, `upload_folder` or `create_commit`). Check out the [upload guide](https://huggingface.co/docs/huggingface_hub/guides/upload) for more details.

**Comment by x54-729** [comment]
Sorry for bother again @Wauplin , what if I want to push files to an existing pr with huggingface_hub?

**Comment by Wauplin** [comment]
Hey, no worries. You can find the revision on the PR page (e.g. `refs/pr/1`, `refs/pr/2`, etc.). All `huggingface_hub` methods support `revision` as parameter, both to upload or download files. It also work in the CLI with `--revision "refs/pr/1"`.

```py
from huggingface_hub import upload_file

upload_file(repo_id=..., path_in_repo=..., ..., revision="refs/pr/26")
```

**Comment by x54-729** [comment]
Thanks! There is another question, how can I set upstream to refs/pr? The scenario is that I want to create prs and apply same changes to multiple model repositories to avoid push one by one. I want to treat these refs/pr as normal branch, so I can simply checkout and push in different folders in a loop without searching pr num every time

**Comment by Wauplin** [comment]
@x54-729 these docs should help you get starting with PRs: https://huggingface.co/docs/hub/repositories-pull-requests-discussions#how-do-i-manage-pull-requests-locally

**Comment by x54-729** [comment]
It this mean that I have to now the num of pr every time I push changes?

**Comment by Wauplin** [comment]
You need to know the num of the pr you want to push to yes. You can list PRs programmatically but don't think that's what you need, right?

**Comment by x54-729** [comment]
Thanks a lot!
