### ISSUE TITLE
Spaces: Feature Request: Include git submodules in codebase.

### ISSUE THREAD

**Issue by Fraser-Greenlee** [huggingface/huggingface_hub#200]
Submodules allows having editable model code shared across Huggingface projects.

Sadly these aren’t copied into the space code base so don’t work.

See space: https://huggingface.co/spaces/flax-community/t5-vae

hub model: https://huggingface.co/flax-community/t5-vae-python

model sub module code: https://github.com/Fraser-Greenlee/t5-vae-flax

**Comment by julien-c** [comment]
i think submodules are allowed (it's just plain git), but they're not being recursively cloned into the Space at deployment time, right?

**Comment by Fraser-Greenlee** [comment]
Huh, it seems that this works now https://huggingface.co/spaces/Fraser/try_using_submodules

It wasn't copying the code for me before but maybe it was a misunderstanding.
https://huggingface.co/spaces/flax-community/t5-vae/commit/1d30073ba77b45c122fed07ffbc36aafcf12477f

**Comment by julien-c** [comment]
(cc'ing @cbensimon in case he hasn't seen this)

**Comment by cbensimon** [comment]
@Fraser-Greenlee Thanks for the feedback !
You're right, submodules were not cloned (just an empty folder was created).
It's now working properly so I'll let this issue closed
