### ISSUE TITLE
TextGenerationStreamResponse missing a key present in the stream response

### ISSUE THREAD

**Issue by danielpcox** [huggingface/huggingface_hub#2005]
### Describe the bug

I get this using huggingface-hub 0.20.3 against Text Generation Inference 1.4.0:

```
TypeError: TextGenerationStreamResponse.__init__() got an unexpected keyword argument 'index'
```

This appears to be because there is no `index` field in the dataclass: https://github.com/huggingface/huggingface_hub/tree/main/src/huggingface_hub/inference#L408-L411

Here's an actual example response from `/generate_stream`, captured with curl:

```
data:{"index":97,"token":{"id":264,"text":" a","logprob":-0.0003259182,"special":false},"generated_text":null,"details":null}
```

and the JSON after "data:" is passed directly into the `TextGenerationStreamResponse` constructor here: https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/inference/_common.py#L272

`TextGenerationResponse` doesn't have this problem because the non-streaming result of the API call doesn't have that `index` key.

### Reproduction

Launch a Text Generation Inference server with an LLM. I'm doing Mixtral 8x7b at the moment, but any one should do.

Any query to `/generate_stream` will show the `input` key. Here's an example:

```bash
curl -XPOST -H 'Content-Type: application/json' -d '{"inputs":"<s> [INST] <<SYS>> You are a world class chef. Steer the conversation back around to food, but keep it concise.<</SYS>> What is the derivative of the natural logarithm? [/INST]"}' $TGI_IP/generate_stream
```

However if you try to do this with `InferenceClient`, you get the `TypeError`:

```python
import huggingface_hub

tgi_url = "http://localhost:8080"
prompt = "<s> [INST] <<SYS>> You are a world class chef. Steer the conversation back around to food, but keep it concise.<</SYS>> What is the derivative of the natural logarithm? [/INST]"

client = huggingface_hub.InferenceClient(model=tgi_url)
for token in client.text_generation(prompt=prompt, stream=True):
    print(token, end='', flush=True)
```

### System info

```shell
I apologize, but I'm doing this on a work machine and the output is sensitive. I hope it doesn't contain anything relevant beyond what I've provided above.
```

**Comment by danielpcox** [comment]
This might be the root issue... Two weeks ago the index attribute was added to the response to make TGI a drop-in replacement for OpenAI clients: https://github.com/huggingface/text-generation-inference/blame/2d56f106a60c7b698705494e7539f8a7e4c85dd9/router/src/server.rs#L426

**Comment by danielpcox** [comment]
I've added a PR that treats `index` as an optional field in `TextGenerationStreamResponse`.

**Comment by Wauplin** [comment]
Hi @danielpcox, thanks for reporting and fixing this! I reviewed the PR and it should be good to merge it soon :)

**Comment by Wauplin** [comment]
This issue is now solved thanks to @danielpcox!

The fix will be shipped in the next release of `huggingface_hub` (not planned yet but most likely in the next 2 weeks). In the meantime, it is possible to i[nstall it from source](https://huggingface.co/docs/huggingface_hub/installation#install-from-source) to benefit from the fix:

```sh
pip install git+https://github.com/huggingface/huggingface_hub
```

**Comment by danielpcox** [comment]
Thanks @Wauplin ! No worries at all. Cheers.

**Comment by mhddenno** [comment]
@danielpcox  thanks alot :) you saved me
