### ISSUE TITLE
ModelFilter uses tag rather than pipeline_tag

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#2009]
Hey there! @sashavor hit an edge case with `ModelFilter`. It seems using `ModelFilter(task=...` will use tags filtering rather than pipeline_tag, which is inconsistent with filtering on the web.

```py
from huggingface_hub import ModelFilter, list_models

filt = ModelFilter(task="summarization")
models = list(list_models(filter=filt))
len(list(models)) # 1562 models
```

Vs directly querying for the pipeline
from huggingface_hub.utils import build_hf_headers, paginate

```py
headers = build_hf_headers()
url = "https://huggingface.co/api/models?pipeline_tag=summarization"
models  = list(paginate(url, params={}, headers=headers))
len(list(models)) # 1507 models
```

So it's https://huggingface.co/models?pipeline_tag=summarization vs https://huggingface.co/models?other=summarization

It might be by design to support multiple types for a single model, but wanted to raise this.

**Comment by julien-c** [comment]
wondering if we shouldn't just deprecate/remove `ModelFilter`

**Comment by osanseviero** [comment]
SGTM but then we should add a `pipeline_tag` parameter to `list_models`

**Comment by julien-c** [comment]
yes

**Comment by Wauplin** [comment]
Agree to deprecate ModelFilter + add pipeline_tag as a parameter in `list_models`. Should be done as part of https://github.com/huggingface/huggingface_hub/issues/1676.

**Comment by Wauplin** [comment]
Since https://github.com/huggingface/huggingface_hub/pull/2028, `ModelFilter` has been deprecated and parameters can be passed directly to [`list_models`](https://huggingface.co/docs/huggingface_hub/main/en/package_reference/hf_api#huggingface_hub.HfApi.list_models). So now you can pass `tags` and/or `pipeline_tag` separately. I'm therefore closing this issue.
