### ISSUE TITLE
Support `audio_to_audio` task in `InferenceClient`

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#2016]
Similar to the work done in https://github.com/huggingface/huggingface_hub/issues/1539.

`InferenceClient.audio_to_audio` has not been implemented. Let's do it! :)

cc @abidlabs [who requested it](https://huggingface.slack.com/archives/C02V5EA0A95/p1707198606454789) (internal link)

**Comment by Ahmedniz1** [comment]
Hi @Wauplin 
I've gone through the requirement. Currently going through previous commits to understand the structure. Will create a PR regarding this asap. 
Thanks

**Comment by Wauplin** [comment]
Hi @Ahmedniz1, thanks for proposing your help! Please let me know if you need any assistance working on with the audio to audio API :) And more than happy to review a PR if you open one :fire:

**Comment by Ahmedniz1** [comment]
@Wauplin I'm confused how should I test this api. For now I'm considering "speechbrain/sepformer-wham" only which is the recommended model for audio to audio, I used the sample1.flac audio file and used the above mentioned model on the link https://huggingface.co/speechbrain/sepformer-wham , in result, I get 2 separate audios with 1 audio containing the actual audio, and the second audio containing noise. Any guides on this?
Thanks

**Comment by Ahmedniz1** [comment]
@Wauplin can you update on this, I'm not sure how am I supposed to test it. 
Thanks

**Comment by Wauplin** [comment]
Hi @Ahmedniz1 yes, sorry for the delay I needed to test it myself as well. So indeed `speechbrain/sepformer-wham` looks like a good start. Input is a raw audio file so the `audio_to_audio` method should start similarly to audio_classification for example:
```py
    def audio_to_audio(
        self,
        audio: ContentT,
        *,
        model: Optional[str] = None,
    ) -> ???:
    # pass the flac example as 'data' and it will be automatically opened and sent to the server
    # audio can be raw bytes, a file path or a url to a online sample
    response = self.post(data=audio, model=model, task="audio-to-audio")
```

in the example above, `response` is the raw bytes from the server. As you mentioned, the output is a json with multiple samples. What you should do is:
1. define an `AudioOutput` type with label/content_type and blob
2. convert the response to a list of items with `_bytes_to_list`
  1. the `label` and `content_type` values are normal strings => keep them "as it is"
  2. for the `blob` value, you have to convert it from base64 to raw bytes. This can be done using `base64.b64decode`. 
  3. return the list of items which each item being a dictionary label (str), content_type (str), blob (bytes)

Then to test that in a script you can do:
```py
client = InferenceClient(model="speechbrain/sepformer-wham")
output = client.audio_to_audio("sample.flac")
for i, item in enumerate(output):
    with open(f"output_{i}.flac", "wb") as f:
        f.write(item["blob"])
```

=> this way you'll have your 2 audio samples saved locally. You don't have to access if the model is good or bad but simply make sure that the input and output formats are correct. 

Does that help? :)
