### ISSUE TITLE
transformer version on the hub

### ISSUE THREAD

**Issue by lombardata** [huggingface/huggingface_hub#2021]
**Is your feature request related to a problem? Please describe.**
I would like to know the version of the transformer library used on the hub, as shown in this [thread](https://github.com/huggingface/huggingface.js/issues/429#issuecomment-1873745021
) 
 it would be useful to know when a change in a library will be uploaded to the hub. Is it automatically the last version used?

**Comment by Wauplin** [comment]
Hi @lombardata, we've just deployed `transformers` to its latest version (`4.37.2`) on our serverless API platform. This should include the fix you've requested. FYI, the transformers version is manually updated to make sure that releasing a new version of `transformers` won't break our server. Please let me know if you encounter any problem. In the meantime I'll close this issue.

(note: this repo is for the `huggingface_hub` which is the Python client to interact with the Hub. Generic questions about the Hub can be asked in https://github.com/huggingface/hub-docs).
