### ISSUE TITLE
`api.get_repo_discussions` never ends for some model repositories when using `huggingface_hub==0.20.3`

### ISSUE THREAD

**Issue by hysts** [huggingface/huggingface_hub#2029]
### Describe the bug

It works fine with `huggingface_hub==0.19.4`, but it doesn't work properly with `huggingface_hub==0.20.3`.

[internal discussion](https://huggingface.slack.com/archives/C02QZLG8GMN/p1707978571874259?thread_ts=1707930243.986229&cid=C02QZLG8GMN)

### Reproduction

```py
from huggingface_hub import HfApi

api = HfApi()

count = 0
for _ in api.get_repo_discussions("mistralai/Mixtral-8x7B-Instruct-v0.1"):
    count += 1
    print(count)
```

### System info

```shell
- huggingface_hub version: 0.20.3
- Platform: Linux-6.2.0-1018-aws-x86_64-with-glibc2.35
- Python version: 3.10.11
```

**Comment by Wauplin** [comment]
Thanks for reporting @hysts! This issue has already been fixed in https://github.com/huggingface/huggingface_hub/pull/1962. Will be part of the upcoming release (0.21.x).
