### ISSUE TITLE
huggingface_hub.login() does not accept copy&paste

### ISSUE THREAD

**Issue by MoritzLaurer** [huggingface/huggingface_hub#2031]
### Describe the bug

I'm running `huggingface_hub.login()` in a .ipynb file and the text box comes up as expected. When I then copy my token and go cmd+v to paste it into the text field, nothing happens. When I manually type the token, I see small back dots appear indicating that the text field is being filled with text, but nothing like that happens when I cmd+v. 

<img width="541" alt="Screenshot 2024-02-16 at 16 08 48" src="https://github.com/huggingface/huggingface_hub/assets/41862082/897d0102-ad70-40c1-bdbd-33343c678fd3">

Yesterday, when I then clicked on "login", the login still worked, although it didn't look like text was in the text field (this was on an AWS linux EC2 instance). I tried again today locally on my mac and now it doesn't even work when I click login. 

Copy & paste seems to work normally when I do it in a text file, but it does not seem to work for the login text box. 

### Reproduction

Run `huggingface_hub.login()` in an .ipynb notebook and try cmd + c, then cmd + v with macos. 

### System info

```shell
{'huggingface_hub version': '0.20.3',
 'Platform': 'macOS-14.3.1-arm64-arm-64bit',
 'Python version': '3.11.8',
 'Running in iPython ?': 'Yes',
 'iPython shell': 'ZMQInteractiveShell',
 'Running in notebook ?': 'Yes',
 'Running in Google Colab ?': 'No',
 'Token path ?': '/Users/moritzlaurer/.cache/huggingface/token',
 'Has saved token ?': False,
 'Configured git credential helpers': 'osxkeychain',
 'FastAI': 'N/A',
 'Tensorflow': 'N/A',
 'Torch': 'N/A',
 'Jinja2': '3.1.3',
 'Graphviz': 'N/A',
 'Pydot': 'N/A',
 'Pillow': 'N/A',
 'hf_transfer': 'N/A',
 'gradio': 'N/A',
 'tensorboard': 'N/A',
 'numpy': '1.26.4',
 'pydantic': '2.6.1',
 'aiohttp': '3.9.3',
 'ENDPOINT': 'https://huggingface.co',
 'HF_HUB_CACHE': '/Users/moritzlaurer/.cache/huggingface/hub',
 'HF_ASSETS_CACHE': '/Users/moritzlaurer/.cache/huggingface/assets',
 'HF_TOKEN_PATH': '/Users/moritzlaurer/.cache/huggingface/token',
 'HF_HUB_OFFLINE': False,
 'HF_HUB_DISABLE_TELEMETRY': False,
 'HF_HUB_DISABLE_PROGRESS_BARS': None,
 'HF_HUB_DISABLE_SYMLINKS_WARNING': False,
 'HF_HUB_DISABLE_EXPERIMENTAL_WARNING': False,
 'HF_HUB_DISABLE_IMPLICIT_TOKEN': False,
 'HF_HUB_ENABLE_HF_TRANSFER': False,
 'HF_HUB_ETAG_TIMEOUT': 10,
 'HF_HUB_DOWNLOAD_TIMEOUT': 10}
```

**Comment by Wauplin** [comment]
Hmm, that's weird though. I just tried locally and I can see the dots both when I type and when I copy-paste

![image](https://github.com/huggingface/huggingface_hub/assets/11801849/e801c055-cd8c-4ab7-96a9-c6c62b750277)


Which version of ipywidget are you using? (I have `ipywidgets==8.0.2` locally)

**Comment by Wauplin** [comment]
(as a workaround, you can always login by setting the `HF_TOKEN` environment variable or with `login(token="...")`. The first method is preferred though since hardcoding token is very dangerous when sharing/versioning your code.

**Comment by MoritzLaurer** [comment]
I'm using `ipywidgets==8.1.2`

I've just tried in a google colab notebook in my browser and there it works. Maybe it's linked to some setting in VS-code / the vs-code jupyter extension

Yeah, I've used `login(token="...")` as a workaround for now. I suppose then it should be cached and I don't have to do the login again (?)

**Comment by MoritzLaurer** [comment]
mh... seems like it's an issue on the vs-code side, there are several issues related to this ([here](https://github.com/microsoft/vscode-jupyter/issues/591), [here](https://github.com/microsoft/vscode-jupyter/issues/15154)). 

Thanks for looking into it! I'm closing the issue, because it's not linked to the huggingface_hub library

**Comment by MoritzLaurer** [comment]
If someone sees this in the future: `huggingface_hub.interpreter_login()` can be a workaround in vs-code

**Comment by hitchhiker3010** [comment]
> If someone sees this in the future: `huggingface_hub.interpreter_login()` can be a workaround in vs-code

@MoritzLaurer Thanks for the suggestion. Though I was able to enter my token, the cell seems to run forever. Did it work for you?

<img width="1023" alt="image" src="https://github.com/user-attachments/assets/2cd63867-45f4-47bb-a461-f6c6c805bb25">
