### ISSUE TITLE
How to find out the type of files in the repository

### ISSUE THREAD

**Issue by suzukimain** [huggingface/huggingface_hub#2039]
Hello
Is there an option to determine the type of file in the repository, such as "Checkpoint", "LORA", "Textual_Inversion", etc?

I didn't know where to ask the question so sorry if I'm wrong.

**Comment by Wauplin** [comment]
Hi @suzukimain could you provide an example of repo for which you would like this information? In general the repo structure (e.g. the file names and extensions) should help you understand what each file is doing. You can also check the model card to get more information on the model. And finally, model authors can also define tags in the model card metadata to make them discoverable on the Hub. For example, there are currently [4600+ models](https://huggingface.co/models?other=lora) tagged as "lora" on the Hub.

I'm not sure this is exactly the answer you expect so please let me know if it's not the case. The Hub is a collections of repos and each repo is a collection of files. There are some conventions in each ML community but as any convention, they are not always respected/they can evolve.

**Comment by suzukimain** [comment]
Hi, @Wauplin  Thank you for your prompt response. 
I am looking for the equivalent of the `type` parameter in the [civitaiAPI](https://github.com/civitai/civitai/wiki/REST-API-Reference#response-fields-2) in the huggingface endpoint. For example, I would like to know how to acquire information such as file type when acquiring a file name from  
`https://huggingface.co/api/models/<repo_id>/<model>`

**Comment by Wauplin** [comment]
Unfortunately no, we don't have such an API at the moment at the file-level (only tags at a repo level). cc-ing @apolinario here if you have more insights to provide.

(also moving this issue to `hub-docs` which is more suitable for generic questions about the Hub. This repo is for the Python client `huggingface_hub`)

**Comment by suzukimain** [comment]
I understand. Thank you for taking time out of your busy schedule to respond

**Comment by julien-c** [comment]
are you interested in models from a specific library, @suzukimain (like diffusers for instance)?

In addition to repo level tags like @Wauplin mentions, libraries usually have some conventions at the library level

**Comment by suzukimain** [comment]
Hi @julien-c julien-c, sorry for the late reply, I am quite interested in diffusers. 

Would it be possible for you to tell me about those conventions?
