### ISSUE TITLE
Getting the hash of the current local "default" model/dataset

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/huggingface_hub#2045]
**Is your feature request related to a problem? Please describe.**
I'd like it if I can get for a model or dataset the commit hash/revision. This is useful for reproducibility reasons.

**Describe the solution you'd like**
Ideally this is a property of a loaded `Dataset` or `AutoModel`, but that would require too much work, I assume.

**Describe alternatives you've considered**
Currently I use the following. It assumes that if a revision is not specified, the most recent (most recently modified) revision is the default model that would be loaded when only using local files without specifying a revision manually. Is that correct?

```python
from typing import Literal

from huggingface_hub import scan_cache_dir


def get_revision(item_name: str, item_type: Literal["dataset", "model"], revision: str | None = None) -> str | None:
    """
    Get the revision hash of a dataset or model in the local cache. If a revision is not given, get
    the most recent one.

    :param item_name: The name of the dataset or model.
    :param item_type: The type of the item, either "dataset" or "model".
    :param revision: The revision hash to get. If None, get the most recent one.
    :return: The revision hash of the item, or None if it does not exist - although that should not occur.
    """
    hf_cache_info = scan_cache_dir()
    for repo in sorted(hf_cache_info.repos, key=lambda repo: repo.repo_path):
        if item_type != repo.repo_type or item_name != repo.repo_id:
            continue
        revisions = repo.revisions

        if revision is not None:
            revision = next((r for r in revisions if r.commit_hash == revision), None)
        else:
            # Use the most recent one
            revisions = sorted(revisions, key=lambda revision: revision.last_modified, reverse=True)
            revision = revisions[0]

        return revision.commit_hash if revision is not None else None
```

**Additional context**
If something like this - probably better implemented - could be implemented to quickly find the commit hash (and other properties) of a given model on the local file system, that could be useful!

**Comment by Wauplin** [comment]
> It assumes that if a revision is not specified, the most recent (most recently modified) revision is the default model that would be loaded when only using local files without specifying a revision manually. Is that correct?

That is usually correct. If you don't specify anything, the loaded model will be from the latest commit on `main`.
If running in offline mode, it will default to the latest commit on `main` when you last loaded the model with a connection.

However, you cannot base the code on the "last modified" field. Let's say someone loads a model from `main`, then from a different branch/tag, then from `main` again. The last modified files will most likely the one from the different branch/tag since the last loading from `main` will not alter the files (since already downloaded). What you can do however is to loop over `revision.refs`. If you've loaded your model from `main`, you are guaranteed that 1 and only 1 revision will have `main` in their `revision.refs` list.

**Comment by Wauplin** [comment]
Another solution is to manually parse the commit_hash in the file path:

```py
from huggingface_hub import hf_hub_download

>>> hf_hub_download("bigscience/bloom", "README.md")
/home/wauplin/.cache/huggingface/hub/models--bigscience--bloom/snapshots/053d9cd9fbe814e091294f67fcfedb3397b954bb/README.md
```
=> `053d9cd9fbe814e091294f67fcfedb3397b954bb` correspond to the commit hash on the Hub.

**Comment by BramVanroy** [comment]
This is great, thanks a lot @Wauplin. I had been searching the code base for "hash" and "commit" but didn't think of .sha. So with your help, this is the revised snippet. Thanks a lot!

```python
from typing import Literal

from huggingface_hub import dataset_info, model_info


def get_revision(
    item_name: str,
    item_type: Literal["dataset", "model"],
    revision: str | None = None,
    token: bool | str | None = None,
) -> str:
    """
    Get the revision hash of a dataset or model in the local cache. If a revision is not given, get
    the most recent one.

    :param item_name: The name of the dataset or model.
    :param item_type: The type of the item, either "dataset" or "model".
    :param revision: The revision hash to get. If None, get the most recent one. 'main' is not a valid revision
    because every 'new' revision is 'main' until it is changed. So if 'main' is passed, it will be replaced by None.
    :param token: The Hugging Face API token to use for authentication. This is useful if you want to access
    private datasets or models. If None, the token will be taken from the currently logged in HF user.
    :return: The revision hash of the item, or None if it does not exist - although that should not occur.
    """
    revision = None if revision == "main" else revision

    if item_type == "model":
        return model_info(item_name, revision=revision, token=token).sha
    elif item_type == "dataset":
        return dataset_info(item_name, revision=revision, token=token).sha
    else:
        raise ValueError("item_type must be either 'model' or 'dataset'.")
```

**Comment by Wauplin** [comment]
Hey @BramVanroy, yes exactly. Here is an even simpler version you can use, based on the `repo_info` helper which does the handling of repo_type + default to `main` for you if value is not passed.

```py
from typing import Literal

from huggingface_hub import repo_info

def get_commit_hash(
    repo_id: str,
    *,
    repo_type: Literal["model", "dataset", "space"] | None = None,
    revision: str | None = None,
    token: bool | str | None = None,
) -> str:
    """
    Get the commit hash of a repo on the Hub for a given revision.

    Args:
        repo_id (`str`):
            A namespace (user or an organization) and a repo name separated by a `/`.
        repo_type (`str`, *optional*):
            Set to `"dataset"` or `"space"` if listing commits from a dataset or a Space, `None` or `"model"` if
            listing from a model. Default is `None`.
        token (`bool` or `str`, *optional*):
            A valid authentication token (see https://huggingface.co/settings/token).
        revision (`str`, *optional*):
            The git revision to fetch commit hash for. Defaults to the head of the `"main"` branch.

    Returns:
        `str`: the commit hash associated to the revision.
    """
    return repo_info(
        repo_id=repo_id,
        repo_type=repo_type,
        revision=revision,
        token=token,
    ).sha
```

**Comment by BramVanroy** [comment]
Even better, thanks!
