### ISSUE TITLE
How edit cache dir and in bad net download how to redownload with last download point

### ISSUE THREAD

**Issue by caihua** [huggingface/huggingface_hub#2051]
OSError: Consistency check failed: file should be of size 1215993967 but has size 118991296 (pytorch_model.bin).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.
Downloading pytorch_model.bin:  10%|████▌                                         | 119M/1.22G [06:51<1:03:13, 289kB/s]

Hi , I use this in windows and space C: is not enouth space, I want to set download or install cache dir is in D: ,how to do this.
And beacuse I have bad network so it is everytime error in one big file download, and how to download this file in a bad network.

**Comment by Wauplin** [comment]
Hi @caihua, you can do that by setting the `HF_HOME` environment variable to the destination of your choice. Here are some documentation about it: https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfhome.

Hope this will fix your issue :)
