### ISSUE TITLE
Add support for `/oauth/userinfo`

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#2068]
Equivalent to `whoami` but for Oauth tokens.

Todo:
- [ ] add a `HfApi.userinfo()` method
- [ ] parse output is dataclass
- [ ] in userinfo => make sure token in form `hf_oauth_***` => if not raise and tell to use `whoami`
- [ ] in whoami => raise ValueError if token in form `hf_oauth_***` telling to use `userinfo`

**Comment by julien-c** [comment]
btw on the server side shouldn't we make /whoami accept oauth tokens instead of creating a new endpoint? (not sure, cc @coyotte508)

**Comment by coyotte508** [comment]
yes it's planned - see todo of https://github.com/huggingface/moon-landing/pull/8865

**Comment by Wauplin** [comment]
Ah good, that's even better! I thought it was the opposite (previously possible to use oauth+whoami but planned to be removed). Let's close this issue then.
