### ISSUE TITLE
Support User API endpoints

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#2077]
A few user endpoints have been adding server-side over the past few months. Would be good to support them natively in `huggingface_hub`, especially for Spaces that rely on social feats.

Here is a list of them:
- [ ] `/overview` (e.g. https://huggingface.co/api/users/julien-c/overview). Returns details about a user on the Hub: user id, name, profile, avatar url, is_pro, nb_models, nb_datasets, ..., nb_likes, etc.
- [ ] `/likes` (e.g. https://huggingface.co/api/users/julien-c/likes). Returns all repos liked by a user.
- [ ] `/followers` (e.g. https://huggingface.co/api/users/julien-c/followers). Returns all followers of a user.
- [ ] `/following` (e.g. https://huggingface.co/api/users/julien-c/following). Returns all users followed by a user.
- [ ] `/api/organizations/:name/members` (e.g. https://huggingface.co/api/organizations/huggingface/members). List of member of an org.
  
Each endpoint can be added as a separate PR. Return type should always be a dataclass. Might also be good to take the opportunity to document those endpoints in [api.md](https://github.com/huggingface/hub-docs/blob/main/docs/hub/api.md) (separate repo).

More priority on the `/overview` and `/members` endpoints. Lower prio for the others.

**Comment by op8mnl** [comment]
Hi, I would like to work on this issue, could you clarify what you mean by supporting these endpoints natively? Would this mean to create an endpoint in the hf_api.py file that mimics the output of the aforementioned endpoints?

**Comment by Wauplin** [comment]
Hi @op8mnl, thanks for proposing to contribute! Yes that's exactly it :) It would mean having a method for each of those endpoints in the `HfApi` client object. Would you like to start with `/overview` for instance? Please let me know if you have any questions!

**Comment by Wauplin** [comment]
Thanks @bilgehanertan! PR looks good at first glance 🔥. I'll give it a try on Monday and make a review :)

**Comment by bilgehanertan** [comment]
@Wauplin, I can implement the rest til Monday in the same PR if that's ok?

**Comment by Wauplin** [comment]
Please go ahead if you're interested! Thanks a lot 🤗

**Comment by Wauplin** [comment]
Thanks @bilgehanertan! :heart: 
https://twitter.com/Wauplin/status/1773682343514947668
