### ISSUE TITLE
Cannot find huggingface_hub's version in importlib_metadata?

### ISSUE THREAD

**Issue by Hungreeee** [huggingface/huggingface_hub#2085]
### Describe the bug

Hi, I already have installed the `huggingface-hub` package and I can import it. But for some reason `importlib.metadata.version("huggingface_hub")` would return `None`, causing another package `datasets` depending on it to fail. Can I get help on this?

### Logs

The error I am getting:

```
File "d:\Thesis\test.py", line 3, in <module>
    import datasets
  File "F:\Program Files\Python\Lib\site-packages\datasets\__init__.py", line 18, in <module>
    from .arrow_dataset import Dataset
  File "F:\Program Files\Python\Lib\site-packages\datasets\arrow_dataset.py", line 66, in <module>
    from . import config
  File "F:\Program Files\Python\Lib\site-packages\datasets\config.py", line 44, in <module>
    HF_HUB_VERSION = version.parse(importlib.metadata.version("huggingface_hub"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Program Files\Python\Lib\site-packages\packaging\version.py", line 54, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "F:\Program Files\Python\Lib\site-packages\packaging\version.py", line 198, in __init__
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```

### System info

```shell
Name: huggingface-hub
Version: 0.21.3
Summary: Client library to download and publish models, datasets and other repos on the huggingface.co hub
Home-page: https://github.com/huggingface/huggingface_hub
Author: Hugging Face, Inc.
Author-email: julien@huggingface.co
License: Apache
Location: F:\Program Files\Python\Lib\site-packages
Requires: filelock, fsspec, packaging, pyyaml, requests, tqdm, typing-extensions
Required-by: accelerate, datasets, sentence-transformers, tokenizers, transformers
```

**Comment by Wauplin** [comment]
How did you install `huggingface_hub`? It's a Python package available on PyPI and conda so you should be able to install it as any other package. We have an installation guide [here](https://huggingface.co/docs/huggingface_hub/installation) if you want. Usually when you can't import a package that you've already installed, it is because you are working with different environments.

**Comment by Hungreeee** [comment]
I just installed it using `pip install huggingface-hub`.

**Comment by Hungreeee** [comment]
Nevermind. I found that there were some issues with the old `huggingface_hub-0.20.1.dist-info` not being properly removed during pip uninstall so I just manually deleted it and it works. Sorry for bothering you.

**Comment by Wauplin** [comment]
Great to hear your problem's solved! :hugs:
