### ISSUE TITLE
`Malformed soundfile` error when using ASR Widget

### ISSUE THREAD

**Issue by mishig25** [huggingface/huggingface_hub#210]
`Malformed soundfile` error occurs when a sample audio file is picked (example: https://huggingface.co/osanseviero/hubert_s3prl).

Solution: implement the same solution that is implement on image classification would work (downloading the file in the browser (using our proxy endpoint to workaround CORS) and reuploading it)

**Comment by julien-c** [comment]
@n1t0 did we end up deploying the proxyfying endpoint to a permanent URL? If it is, can you add the URL here?

**Comment by julien-c** [comment]
[[internal link](https://github.com/huggingface/moon-landing/blob/18303f7d56a9e6c36648814b18a4856fec849ff1/server/views/components/InferenceWidget/shared/WidgetDropzone/WidgetDropzone.svelte#L23-L56)]

**Comment by osanseviero** [comment]
I just wanted to clarify that this already works in `api-inference`, it's an issue only in `api-inference-community` afaiu.

**Comment by osanseviero** [comment]
[[internal link](https://github.com/huggingface/api-inference/blob/c95f7a3ee10ad3c88309b039c5d5d29184028742/shard/app/validation.py#L164-L167) with potential solution in `validation.py`, but maybe the problem is more complex than I realize]

**Comment by Narsil** [comment]
Yes the solution is there, we just need to add it to community.
