### ISSUE TITLE
Document more methods of HfFileSystem

### ISSUE THREAD

**Issue by severo** [huggingface/huggingface_hub#2100]
https://huggingface.co/docs/huggingface_hub/package_reference/hf_file_system does not contain doc for `rm`, `find`, `glob`, etc

**Comment by lappemic** [comment]
Which methods should all be documented? I assume it would be the following:

1. `__init__(self, *args, endpoint=None, token=None, **storage_options)`
2. `resolve_path(self, path, revision=None)`
3. `invalidate_cache(self, path=None)`
4. `rm(self, path, recursive=False, maxdepth=None, revision=None, **kwargs)`
5. `ls(self, path, detail=True, refresh=False, revision=None, **kwargs)`
6. `glob(self, path, **kwargs)`
7. `find(self, path, maxdepth=None, withdirs=False, detail=False, refresh=False, revision=None, **kwargs)`
8. `cp_file(self, path1, path2, revision=None, **kwargs)`
9. `modified(self, path, **kwargs)`
10. `info(self, path, refresh=False, revision=None, **kwargs)`
11. `exists(self, path, **kwargs)`
12. `isdir(self, path)`
13. `isfile(self, path)`
14. `url(self, path)`
15. `get_file(self, rpath, lpath, callback=_DEFAULT_CALLBACK, outfile=None, **kwargs)`

**Comment by Wauplin** [comment]
Hi @lappemic, how did you find this list? It would be more or less this yes.

To be honest I would like to find a way to (semi-)automate the process and avoid maintaining the documentation manually. For most methods we would just need `fsspec`'s docs but in some cases we will want to complete it with an additional paragraph (e.g. in document in `get_file` that it's more optimized than reading chunks).

Solutions I imagine:
1. list supported methods in a markdown-like file. For each method, redirect to fsspec docs + add a sentence or two to explain the specificities of `HffileSystem`. Pro: easy to maintain/no complex logic. Cons: search bar would not index all specs/extra clicks needed on user's side.
2. have a script to automatically generate docs based on fsspec + custom explanations. Pro: all info would be in our docs dircetly. Cons: more logic to maintain.

 @severo @lhoestq @lappemic any opinion about this? Maybe we can start with 1., at least to have an idea of what we want and then think about 2. if we really need to. I'm open to other suggestions as well.

**Comment by lappemic** [comment]
> Hi @lappemic, how did you find this list? It would be more or less this yes.

It was just condensed from the `fsspec` docs. 

Regarding the solution: same as @severo: Having something is better than nothing. If at some point there is need for a more sophisticated solution, it can still be implemented.

**Comment by lappemic** [comment]
Absolutely! Will open one in the beginning of next week.

**Comment by lappemic** [comment]
Hey @Wauplin here is a Proposal before first PR:
- Using a python file which could be called and updates the `hf_file_system.md` file
- This file would fetch all methods of the `HfFileSystem`, redirect to its corresponding `fsspec` docs (if available) and include the docstring of its function in hf_file_system.py (if available)

e.g. `update_hf_file_system.py`:
```python
import inspect
from huggingface_hub import HfFileSystem
import fsspec

def update_hf_file_system_methods_doc():
    methods = inspect.getmembers(HfFileSystem, predicate=inspect.isfunction)

    with open('home/to/be/defined/hf_file_system_methods.md', 'w') as f:
        f.write("# Filesystem API\n")
        f.write("The `HfFileSystem` class provides a pythonic file interface to the Hugging Face Hub based on [`fsspec`](https://filesystem-spec.readthedocs.io/en/latest/).\n")
        f.write("## HfFileSystem\n")
        f.write("`HfFileSystem` is based on [fsspec](https://filesystem-spec.readthedocs.io/en/latest/), so it is compatible with most of the APIs that it offers. For more details, check out [our guide](../guides/hf_file_system) and fsspec's [API Reference](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractFileSystem).\n\n")

        for name, method in methods:
            if name.startswith('_'):
                continue
            
            f.write(f"- {name}\n\n")

            # Get fsspec documentation link
            fsspec_method = getattr(fsspec.spec.AbstractFileSystem, name, None)
            if fsspec_method:
                f.write(f"[fsspec documentation for {name}](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractFileSystem.{name})\n")

                # Add HuggingFace-specific note if it exists
                hf_doc = method.__doc__
                # Check if fsspec_method.__doc__ is not None before stripping and comparing
                if hf_doc and fsspec_method.__doc__ and hf_doc.strip() != fsspec_method.__doc__.strip(): 
                    f.write(f"**HuggingFace Note:** {hf_doc.strip()}\n\n")

            # Handle cases where the method is not in fsspec.spec.AbstractFileSystem
            else:
                hf_doc = method.__doc__
                if hf_doc:
                    f.write(f"**HuggingFace Documentation:** {hf_doc.strip()}\n\n")

            f.write("\n")

if __name__ == "__main__":
    update_hf_file_system_methods_doc()
```

This would lead to the following `hf_file_system.md`:
```markdown
# Filesystem API
The `HfFileSystem` class provides a pythonic file interface to the Hugging Face Hub based on [`fsspec`](https://filesystem-spec.readthedocs.io/en/latest/).
## HfFileSystem
`HfFileSystem` is based on [fsspec](https://filesystem-spec.readthedocs.io/en/latest/), so it is compatible with most of the APIs that it offers. For more details, check out [our guide](../guides/hf_file_system) and fsspec's [API Reference](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractFileSystem).

- cat

[fsspec documentation for cat](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractFileSystem.cat)

- cat_file

[fsspec documentation for cat_file](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractFileSystem.cat_file)

...

- get_file

[fsspec documentation for get_file](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractFileSystem.get_file)
**HuggingFace Note:** Copy single remote file to local.

...
```

If this would be a viable solution:
1. I realised just 3 of the `HfFileSystem` methods have actually a docstring (`get_file`, `ls` and `url`)- I guess we would have to update the remaining ones as well?
2. Where would the `update_hf_file_system.py` live? I assume we would have to put it in `./utils`?

Looking forward to your feedack and what you think on how to proceed!

Cc: @severo

**Comment by Wauplin** [comment]
Hi @lappemic, thanks for looking into it! I like the way you retrieve the fsspec docstrings + add a link to them!


A question I'm wondering is when it's the most suitable way of doing it. The problem with having a script to generate the markdown is that we loose the nice rendering from the [HF doc builder](https://github.com/huggingface/doc-builder). Here is for example how it looks like for [a properly documented method](https://huggingface.co/docs/huggingface_hub/package_reference/hf_api#huggingface_hub.HfApi.add_space_secret):

![image](https://github.com/huggingface/huggingface_hub/assets/11801849/e8e45443-fa04-46dc-821e-dd4cf2a14e63)
 
What we could do to counter that is to add the docstring to the method directly when defining the class in Python. You can do that by appending this snippet:

```py
for name, function in inspect.getmembers(HfFileSystem, predicate=inspect.isfunction):
    parent = getattr(fsspec.AbstractFileSystem, name, None)
    if parent is not None and parent.__doc__ is not None:
        function.__doc__ = (
            "\n_Docstring taken from "
            f"[fsspec documentation](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.spec.AbstractFileSystem.{name})_"
        ) + "\n\n" + parent.__doc__
```
at the very bottom of [hf_file_system.py](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/hf_file_system.py). I quickly tried it and it takes ~0.2ms to execute so the extra overhead when importing the class is neglectable. 


----

Once you have this, the doc-builder should automatically detect the methods with a docstring and format them in the official docs. This is happening [in this file](https://github.com/huggingface/huggingface_hub/blob/main/docs/source/en/package_reference/hf_file_system.md?plain=1) that gets generated [here](https://huggingface.co/docs/huggingface_hub/package_reference/hf_file_system). All you need to do is to replace 
```md
[[autodoc]] HfFileSystem
    - __init__
    - resolve_path
    - ls
```
by 
```md
[[autodoc]] HfFileSystem
    - __init__
    - all
```
to tell the doc-builder to take all possible methods for you (now that they have a docstring).

I quickly checked and it looks like `cp_file` and `resolve_path` are the two only methods that don't end up with a docstring. Since we are defining them in `huggingface_hub`, it's a matter of adding a docstring to them.

**Comment by lappemic** [comment]
Thanks a lot for the detailed feedback @Wauplin!

This makes a lot of sense on the first glance! I will try to implement this asap (probably beginning of next week).

**Comment by Wauplin** [comment]
Thanks! Have a great weekend in the meantime :hugs:
