### ISSUE TITLE
Only use git credentials, no more token

### ISSUE THREAD

**Issue by LysandreJik** [huggingface/huggingface_hub#211]
The current authentication system isn't ideal for git-based workflows. It isn't clear to users why they should first authenticate with `huggingface-cli`, then re-authenticate with `git push`.

It also isn't simple to `git push` in a colab notebook, a shell-less environment which can't prompt for username and password. All of these issues could be handled in a simpler way by only using git credentials, not an authentication token, in order to handle all git-related operations.

Currently looking at:
`git credentials fill`
`git credential-store store`
`git credential-store get`

**Comment by julien-c** [comment]
> It isn't clear to users why they should first authenticate with huggingface-cli

Disclaimer; they shouldn't
