### ISSUE TITLE
Add to documentation all fo the *_CACHE environment variables that can be configured.

### ISSUE THREAD

**Issue by sealad886** [huggingface/huggingface_hub#2116]
**Is your feature request related to a problem? Please describe.**
It's frustrating when first getting started and trying to configure the cache settings that 1. the cache structure isn't really clearly documented (i.e. not only _what_ the structure is, but _when_ and which tools download into which parts of it); and 2. the different variables that control those settings. 

**Describe the solution you'd like**
One of the documents pages, perhaps the [Manage Cache](https://huggingface.co/docs/huggingface_hub/en/guides/manage-cache) page, should just have the config variables listed and described. 

**Describe alternatives you've considered**
Just use the default $HOME/.cache and symlink out variable parts of the cache to external drives.

**Additional context**

**Comment by Wauplin** [comment]
Hi @amcox886, all environment variables are listed [here](https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfhome). Also the manage cache page says

> The <CACHE_DIR> is usually your user’s home directory. However, it is customizable with the cache_dir argument on all methods, or by specifying either `HF_HOME` or `HF_HUB_CACHE` environment variable.

Would you like to open a PR to link the environment variable page from the manage cache page? Maybe that would create less confusion.

Regarding `when and which tools download into which parts of it`, that's a difficult one. Tens of libraries are using `huggingface_hub` under the hood to cache files from the Hub so we can't really document the usage of it, only how it works internally.
