### ISSUE TITLE
[CLI] Support tag management (create, list, delete)

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#2141]
Requested in https://github.com/huggingface/huggingface_hub/issues/960#issuecomment-2013533386.

Similar to https://github.com/huggingface/huggingface_hub/issues/1655 (branch management from CLI)

**Comment by bilgehanertan** [comment]
I would like to take this issue, but I have some questions about it.

To my understanding, I will be using `api.create_tag`, `api.delete_tag`, yet there is no specific `list_tag` API endpoint. There are only `api.get_dataset_tags` and `api.get_model_tags` which seem to be returning pre-defined valid model/dataset tags. How can I implement the list functionality?

**Comment by Wauplin** [comment]
Hi @bilgehanertan, thanks again for proposing your contribution on this topic! 

To list tags, branches and PR references, you can use [`list_repo_refs`](https://huggingface.co/docs/huggingface_hub/v0.22.2/en/package_reference/hf_api#huggingface_hub.HfApi.list_repo_refs) like this:

```py
>>> from huggingface_hub import list_repo_refs
>>> list_repo_refs("bigcode/the-stack", repo_type="dataset")
GitRefs(branches=[GitRefInfo(name='main', ref='refs/heads/main', target_commit='349a71353fd5868fb90b593ef09e311379da498a'), GitRefInfo(name='v1.2', ref='refs/heads/v1.2', target_commit='5d3ecf104981e98be039c6b397ed479916fcd767'), GitRefInfo(name='v1.1.a1', ref='refs/heads/v1.1.a1', target_commit='f9826b862d1567f3822d3d25649b0d6d22ace714')], converts=[GitRefInfo(name='parquet', ref='refs/convert/parquet', target_commit='2b04cb882b107dd808e084c70c08383fa2f342f4')], tags=[GitRefInfo(name='v1.0', ref='refs/tags/v1.0', target_commit='c37a8cd1e382064d8aced5e05543c5f7753834da'), GitRefInfo(name='v1.1', ref='refs/tags/v1.1', target_commit='20984ef8dc055c571093bf4b6235233ac6cb4596'), GitRefInfo(name='v1.2', ref='refs/tags/v1.2', target_commit='93fc1897d4405b5bfdd5ffaccadfc690f3fd198c')], pull_requests=None)
```

**Comment by bilgehanertan** [comment]
> Hi @bilgehanertan, thanks again for proposing your contribution on this topic!
> 
> To list tags, branches and PR references, you can use [`list_repo_refs`](https://huggingface.co/docs/huggingface_hub/v0.22.2/en/package_reference/hf_api#huggingface_hub.HfApi.list_repo_refs) like this:
> 
> ```python
> >>> from huggingface_hub import list_repo_refs
> >>> list_repo_refs("bigcode/the-stack", repo_type="dataset")
> GitRefs(
>     branches=[
>         GitRefInfo(name='main', ref='refs/heads/main', target_commit='349a71353fd5868fb90b593ef09e311379da498a'),
>         GitRefInfo(name='v1.2', ref='refs/heads/v1.2', target_commit='5d3ecf104981e98be039c6b397ed479916fcd767'),
>         GitRefInfo(name='v1.1.a1', ref='refs/heads/v1.1.a1', target_commit='f9826b862d1567f3822d3d25649b0d6d22ace714')
>     ],
>     converts=[
>         GitRefInfo(name='parquet', ref='refs/convert/parquet', target_commit='2b04cb882b107dd808e084c70c08383fa2f342f4')
>     ],
>     tags=[
>         GitRefInfo(name='v1.0', ref='refs/tags/v1.0', target_commit='c37a8cd1e382064d8aced5e05543c5f7753834da'),
>         GitRefInfo(name='v1.1', ref='refs/tags/v1.1', target_commit='20984ef8dc055c571093bf4b6235233ac6cb4596'),
>         GitRefInfo(name='v1.2', ref='refs/tags/v1.2', target_commit='93fc1897d4405b5bfdd5ffaccadfc690f3fd198c')
>     ],
>     pull_requests=None
> )
> ```

Got it! I will be starting it asap.
