### ISSUE TITLE
[docs] create a diagram image that explains the hf:// paths

### ISSUE THREAD

**Issue by severo** [huggingface/huggingface_hub#2148]
On the same type of https://huggingface.co/docs/hub/gguf

![gguf-spec](https://github.com/huggingface/huggingface_hub/assets/1676121/4d375fd3-82c1-4b79-ab18-db6aabdd569a)

I also did something similar for the converted Parquet files: https://www.linkedin.com/feed/update/urn:li:activity:7092975830020075520

![1691097218243](https://github.com/huggingface/huggingface_hub/assets/1676121/54fc0ec0-3617-4732-9918-8248745fc933)

Figma here: https://www.figma.com/file/Njhkk9wVE5E9tYlXrpSjo5/ParquetURL?type=design&node-id=0%3A1&mode=design&t=m82D8BqyKh2jhtak-1

**Comment by severo** [comment]
cc @julien-c  (https://huggingface.slack.com/archives/C04BP5S7858/p1710583335439119)

**Comment by julien-c** [comment]
the parquet one looks nice!

**Comment by Wauplin** [comment]
Nice idea, yes!

**Comment by severo** [comment]
Another Parquet diagram:

![image](https://github.com/huggingface/huggingface_hub/assets/1676121/cff5f01b-61fd-4c98-a661-9e4c4945eedc)


from https://twitter.com/andy_pavlo/status/1790524064995688660

**Comment by julien-c** [comment]
maybe re-do the parquet one but for DuckDB hf:// paths and display it inside the DuckDB related docs?

**Comment by severo** [comment]
wdyt?

https://www.figma.com/design/D0S8By7C8Use8ZDdVZZj8P/hf%3A%2F%2F-URLs

![hf___ URLs](https://github.com/huggingface/huggingface_hub/assets/1676121/88ce30b8-24d1-4782-9784-f936bbd60084)

**Comment by julien-c** [comment]
maybe do a branch example with a simpler branch name like `@main`?

**Comment by julien-c** [comment]
and i think i would remove spaces and models to keep things focused on **datasets**

**Comment by julien-c** [comment]
and mention that `refs/convert/parquet` is auto-conversion

**Comment by julien-c** [comment]
cc @cfahlgren1 might be interesting to you!

**Comment by cfahlgren1** [comment]
This is great, maybe for the parquet branch, a mention of partial conversions up to 5gb might be helpful.

**Comment by cfahlgren1** [comment]
Not sure if it would clutter the graphic, but an [auth](https://duckdb.org/2024/05/29/access-150k-plus-datasets-from-hugging-face-with-duckdb.html#authentication) example is good to know for users querying their private datasets.

```sql
CREATE SECRET hf_token (
   TYPE HUGGINGFACE,
   TOKEN 'your_hf_token'
);
```

**Comment by severo** [comment]
OK. Version A, for huggingface_hub hf:// docs:

![hf_urls](https://github.com/huggingface/huggingface_hub/assets/1676121/476f7778-24dd-4f40-9d7e-7c4b34cd8522)

**Comment by julien-c** [comment]
neat!

**Comment by severo** [comment]
https://github.com/huggingface/hub-docs/pull/1319 and https://github.com/huggingface/huggingface_hub/pull/2358

**Comment by severo** [comment]
https://huggingface.co/docs/hub/datasets-duckdb
https://huggingface.co/docs/huggingface_hub/main/en/guides/hf_file_system#integrations
