### ISSUE TITLE
use HF_ENDPOINT will still be connected to huggingface.co

### ISSUE THREAD

**Issue by livegoplayer** [huggingface/huggingface_hub#2152]
### Describe the bug

我在尝试写一个通过HF_ENDPOINT设置绕过直接连接huggingface.co的脚本，它的功能是在我连接不上huggingface.co的情况下能通过access_token管理我的项目。目前我发现upload_file 函数在上传的时候可以使用HF_ENDPOINT的设置上传，但是最后上传完成之后依旧会调用huggingface.co:443/api/complete_multipart,这就导致了我必须连上我的vpn才能上传成功，我的网络环境就是在不开代理的情况下连接不上huggingface.co

### Reproduction

```
def test():
    os.environ["HTTP_PROXY"] = ""
    os.environ["HTTPS_PROXY"] = ""
    mirror_url = "https://hf-mirror.com"
    os.environ['HF_ENDPOINT'] = mirror_url
    token = 'hf_****' #my token
    api = HfApi(endpoint=mirror_url, token=token) 
    repo_id = '****/***' # my private repo
    api.upload_file(repo_id=repo_id, path_or_fileobj='8x_NMKD-Superscale_150000_G.pth', path_in_repo="test/8x_NMKD-Superscale_150000_G.pth", commit_message="11", token=token)

if __name__ == "__main__":
    test()
``` 

my upload file:
https://huggingface.co/xjyplayer/stable-diffusion-models/resolve/main/8x_NMKD-Superscale_150000_G.pth?download=true

### Logs

```shell
PS F:\projects\scripts\huggingface_io> python .\huggingface.py
Traceback (most recent call last):
  File "F:\projects\scripts\huggingface_io\huggingface.py", line 504, in <module>
    test()
  File "F:\projects\scripts\huggingface_io\huggingface.py", line 496, in test
    os.environ['HF_ENDPOINT'] = mirror_url
UnboundLocalError: local variable 'mirror_url' referenced before assignment
PS F:\projects\scripts\huggingface_io> python .\huggingface.py
8x_NMKD-Superscale_150000_G.pth: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 67.1M/67.1M [00:13<00:00, 5.09MB/s]
Traceback (most recent call last):
  File "D:\Software\python\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\Software\python\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "D:\Software\python\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\python\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "D:\Software\python\lib\site-packages\urllib3\connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "D:\Software\python\lib\site-packages\urllib3\connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "D:\Software\python\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "D:\Software\python\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000001A0A7500220>, 'Connection to huggingface.co timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\python\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\Software\python\lib\site-packages\urllib3\connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "D:\Software\python\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/complete_multipart?uploadId=e1lFR5Q1s5u6vz1SoipKviueG8J7apyZ8qQsAZ.df3ccwclGgwEqhYtnMdaUm1Ab.SQ7wkcuJgTi3xXBZ3hAOty7VNGUXK5hlGGNNuQu1j5niiKbyiMkT2t8bCoONkY2&bucket=hf-hub-lfs-us-east-1&prefix=repos%2Fc5%2Fb1%2Fc5b11c5c0ca03071bcb78ec2514864c3f4fb5169cfef7a0848223bc4b2e5127e&expiration=Mon%2C+25+Mar+2024+13%3A26%3A40+GMT&signature=4913c0f7b23917bce249b200e50ed26bd3b3139014c56f8131cdc1ae823ed12f (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001A0A7500220>, 'Connection to huggingface.co timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\python\lib\site-packages\huggingface_hub\_commit_api.py", line 400, in _wrapped_lfs_upload
    lfs_upload(operation=operation, lfs_batch_action=batch_action, token=token)
  File "D:\Software\python\lib\site-packages\huggingface_hub\lfs.py", line 228, in lfs_upload
    _upload_multi_part(operation=operation, header=header, chunk_size=chunk_size, upload_url=upload_action["href"])
  File "D:\Software\python\lib\site-packages\huggingface_hub\lfs.py", line 329, in _upload_multi_part
    completion_res = get_session().post(
  File "D:\Software\python\lib\site-packages\requests\sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "D:\Software\python\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Software\python\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Software\python\lib\site-packages\huggingface_hub\utils\_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
  File "D:\Software\python\lib\site-packages\requests\adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/complete_multipart?uploadId=e1lFR5Q1s5u6vz1SoipKviueG8J7apyZ8qQsAZ.df3ccwclGgwEqhYtnMdaUm1Ab.SQ7wkcuJgTi3xXBZ3hAOty7VNGUXK5hlGGNNuQu1j5niiKbyiMkT2t8bCoONkY2&bucket=hf-hub-lfs-us-east-1&prefix=repos%2Fc5%2Fb1%2Fc5b11c5c0ca03071bcb78ec2514864c3f4fb5169cfef7a0848223bc4b2e5127e&expiration=Mon%2C+25+Mar+2024+13%3A26%3A40+GMT&signature=4913c0f7b23917bce249b200e50ed26bd3b3139014c56f8131cdc1ae823ed12f (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001A0A7500220>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: 5353b93e-2d51-4d48-8aa3-a1a778152234)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\projects\scripts\huggingface_io\huggingface.py", line 504, in <module>
    test()
  File "F:\projects\scripts\huggingface_io\huggingface.py", line 501, in test
    api.upload_file(repo_id=repo_id, path_or_fileobj='8x_NMKD-Superscale_150000_G.pth', path_in_repo="test/8x_NMKD-Superscale_150000_G.pth", commit_message="11", token=token)
  File "D:\Software\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Software\python\lib\site-packages\huggingface_hub\hf_api.py", line 1208, in _inner
    return fn(self, *args, **kwargs)
  File "D:\Software\python\lib\site-packages\huggingface_hub\hf_api.py", line 4248, in upload_file
    commit_info = self.create_commit(
  File "D:\Software\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Software\python\lib\site-packages\huggingface_hub\hf_api.py", line 1208, in _inner
    return fn(self, *args, **kwargs)
  File "D:\Software\python\lib\site-packages\huggingface_hub\hf_api.py", line 3558, in create_commit
    self.preupload_lfs_files(
  File "D:\Software\python\lib\site-packages\huggingface_hub\hf_api.py", line 4058, in preupload_lfs_files
    _upload_lfs_files(
  File "D:\Software\python\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Software\python\lib\site-packages\huggingface_hub\_commit_api.py", line 410, in _upload_lfs_files
    _wrapped_lfs_upload(filtered_actions[0])
  File "D:\Software\python\lib\site-packages\huggingface_hub\_commit_api.py", line 402, in _wrapped_lfs_upload
    raise RuntimeError(f"Error while uploading '{operation.path_in_repo}' to the Hub.") from exc
RuntimeError: Error while uploading 'test/8x_NMKD-Superscale_150000_G.pth' to the Hub.
```

### System info

```shell
- huggingface_hub version: 0.20.1
- Platform: Windows-10-10.0.22635-SP0
- Python version: 3.10.11
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: F:\torch_models_cacahe\token
- Has saved token ?: True
- Who am I ?: xjyplayer
- Configured git credential helpers:
- FastAI: N/A
- Tensorflow: 2.12.0
- Torch: 2.1.2+cu121
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 10.1.0
- hf_transfer: N/A
- gradio: 3.41.2
- tensorboard: 2.6.2.2
- numpy: 1.26.2
- pydantic: 2.5.3
- aiohttp: 3.8.6
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: F:\torch_models_cacahe\hub
- HF_ASSETS_CACHE: F:\torch_models_cacahe\assets
- HF_TOKEN_PATH: F:\torch_models_cacahe\token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment]
Hi @livegoplayer, this is most probably because you are importing the `huggingface_hub` library before updating the env variable. We evaluate the HF_ENDPOINT from env variable only once at loading time. What you can do is run your script like this:

```
HTTP_PROXY= HTTPS_PROXY= HF_ENDPOINT=https://hf-mirror.com python my_script.py
```

**Comment by Wauplin** [comment]
I'm closing this issue as it is not a `huggingface_hub`-bug. I hope the command line above will help you fix your problem. If you have any further question, please let me know :)

**Comment by livegoplayer** [comment]
我认为它确实是一个huggingface_hub错误，首先我使用了以下代码初始化HfApi，里面明确指定了endpoint=mirror_url 而HF_ENDPOINT环境变量只是我在确定它不能工作之后的另一个操作，而且我确定我关闭了vpn，我的操作结果是上传成功了，但是最后调用了huggingface的api导致上传失败。
` api = HfApi(endpoint=mirror_url, token=token) `
还有我尝试了你的方法，按照你的说法，如果我在命令行之前设置HTTP_PROXY HTTPS_PROXY HF_ENDPOINT 这些变量是万无一失的，我的代码无论什么情况下都不会再使用huggingface.co的api
![image](https://github.com/huggingface/huggingface_hub/assets/31812698/2809769e-d935-4cb3-8dae-bc0047038423)
如上图所示我按照你的说法做了，并且我还加了另一层保险
![image](https://github.com/huggingface/huggingface_hub/assets/31812698/6696f135-328c-4014-9ae5-9d97974817e1)
在我的代码中我使用了
` 
api.upload_file(repo_id=repo_id, path_or_fileobj=absolute_path, path_in_repo=relative_path + "/"  + file_name, commit_message=commit_message, token=load_access_token(), repo_type=get_repo_type(current_project))
` 
来调用我的上传方法，我的初始化方法依旧是,
`if api == None:
         api = HfApi(endpoint=mirror_url, token=load_access_token())`
并且这个变量只赋值一次
![image](https://github.com/huggingface/huggingface_hub/assets/31812698/ab2cd84b-4c41-49ac-870f-2d6d0f818758)
![image](https://github.com/huggingface/huggingface_hub/assets/31812698/a9f4b265-04e1-4a68-a2f7-3e0e7bf766de)
错误依旧是如此，我想我没必要再写测试函数了，因为你给出的建议没有其他意外错误了，有没有一种可能，你们就是无论如何都要调用huggingface.co 的api函数来确保上传完成？
我可以给你提供我的脚本位置，你可以设置你的hosts文件去屏蔽你和huggingface.co 的连接来测试
https://github.com/livegoplayer/scripts/tree/main/huggingface_io

**Comment by livegoplayer** [comment]
> I'm closing this issue as it is not a `huggingface_hub`-bug. I hope the command line above will help you fix your problem. If you have any further question, please let me know :)

我是想问为什么在我设置了
`api = HfApi(endpoint=mirror_url, token=load_access_token())`
这种情况下，依旧会连接到huggingface.co,你们的sdk函数只能通过读取环境变量的方式来设置镜像地址吗？这不应该是sdk的功能，更像是一个命令行的功能
另外我上面提到的问题，我希望我能得到解释，因为作为一个中国区域的huggingface 使用者，我非常喜欢huggingface的文件托管方式，这让我的模型文件上传和下载都变得方便，但是依旧有很多人用不上你们的网站。在服务器上上传和下载你们的托管模型又会受到vpn带宽的限制。更何况有一些人连vpn都没有。我写这个脚本也是为了更加方便一点，希望你能给我一个很好的解决方案，当然，只是在下载完成之后才使用我的vpn带宽调用一个api，这对我来说没有影响，但是我的脚本就没法分享给更多的人用了。

**Comment by Wauplin** [comment]
Thanks for the explanations @livegoplayer and very sorry for closing this issue too soon. With the help of @padeoe, I have been able to reproduce your issue and opened a patch that fixes the problem (https://github.com/huggingface/huggingface_hub/pull/2155). I'll let you know when it's reviewing, merged and released.

**Comment by livegoplayer** [comment]
我注意到这个bug修复了，我该怎么使用它，目前为止我使用的是pip intsall 来安装你们的包，是发布了新的版本吗，最好能给我一个安装命令

**Comment by livegoplayer** [comment]
> Thanks for the explanations @livegoplayer and very sorry for closing this issue too soon. With the help of @padeoe, I have been able to reproduce your issue and opened a patch that fixes the problem (#2155). I'll let you know when it's reviewing, merged and released.

我注意到这个bug修复了，我该怎么使用它，目前为止我使用的是pip intsall 来安装你们的包，是发布了新的版本吗，最好能给我一个安装命令

**Comment by Wauplin** [comment]
Hi @livegoplayer, a fix has indeed been merged to the `main` branch. I'll soon make a hot-fix release. In the meantime you can install `huggingface_hub` [from source](https://huggingface.co/docs/huggingface_hub/installation#install-from-source) to benefit from it:

```
pip install git+https://github.com/huggingface/huggingface_hub
```

**Comment by livegoplayer** [comment]
> Hi @livegoplayer, a fix has indeed been merged to the `main` branch. I'll soon make a hot-fix release. In the meantime you can install `huggingface_hub` [from source](https://huggingface.co/docs/huggingface_hub/installation#install-from-source) to benefit from it:
> 
> ```
> pip install git+https://github.com/huggingface/huggingface_hub
> ```
ok,  我不着急，如果你发布，请告诉我。另外我想知道你们是解决了HF_ENDPOINT=https://hf-mirror.com  设置之后的问题还是api = HfApi(endpoint=mirror_url, token=load_access_token()) 设置之后的问题，我用哪种方式可以正确的下载和上传？其实我感觉后者在程序中设置好一点，但是如果是前者我也可以接受。

**Comment by Wauplin** [comment]
Hi @livegoplayer actually I just realized only the HF_ENDPOINT solution was fixed. I pushed a new fix so now both setting `HF_ENDPOINT` environment variable or  `HfApi(endpoint=...)` should work! :)

**Comment by livegoplayer** [comment]
> Hi @livegoplayer actually I just realized only the HF_ENDPOINT solution was fixed. I pushed a new fix so now both setting `HF_ENDPOINT` environment variable or `HfApi(endpoint=...)` should work! :)

这个版本是对的吗
![image](https://github.com/huggingface/huggingface_hub/assets/31812698/aefc7be1-92c7-4951-93cb-ccba518a3b16)
我是用你的建议安装的
![image](https://github.com/huggingface/huggingface_hub/assets/31812698/cb0de23b-a9b0-4ecd-8741-ec130959ed38)
但是我运行我的测试代码之后
`import os

def test():
    os.environ["HTTP_PROXY"] = ""
    os.environ["HTTPS_PROXY"] = ""
    mirror_url = "https://hf-mirror.com"
    os.environ['HF_ENDPOINT'] = mirror_url

    from huggingface_hub import HfApi

    token = 'hf_***' #my token
    api = HfApi(endpoint=mirror_url, token=token) 
    repo_id = 'xxxx/xxxx'
    api.upload_file(repo_id=repo_id, path_or_fileobj='F:\p站下载\泛光.safetensors', path_in_repo="test/泛光.safetensors", commit_message="11", token=token)

if __name__ == "__main__":
    test()`

它依然是这个错误
![image](https://github.com/huggingface/huggingface_hub/assets/31812698/0ce7ae77-1325-45bf-816e-db51d6640f57)

我有地方搞错了吗，还是你提交出错了
