### ISSUE TITLE
autofill repo_url field when using ModelHubMixin to generate a model card

### ISSUE THREAD

**Issue by not-lain** [huggingface/huggingface_hub#2154]
automatically populate this field when generating modelcard

## useful resources
https://stackoverflow.com/questions/22081209/find-the-root-of-the-git-repository-where-the-file-lives
this can be used to get the remote url, here's an example i made up that can be used as a resource
```
pip install gitpython
```
```python
import git

# even local can work since we will extract the abs path and work our way backwards
path = os.path.abspath("path_to_file.py") 
path = os.path.split(path)[0] # drop filename
while (".git" not in os.listdir(path)) and (os.path.split(path)[0] != path):
  path = os.path.split(path)[0]
  if path == os.path.split(path)[0] : 
    # case we reached last parent directory and no .git was found
    path = None
    break

if path is not None : 
  g = git.Repo(path)
  url = next(g.remote().urls)
  print(url)
```

## Additional context**
![image](https://github.com/huggingface/huggingface_hub/assets/70411813/d66bba0b-bacf-4b80-abda-c15c89bc576c)

**Comment by not-lain** [comment]
this should with cases where repo has the architecture in there, a counter example of this is when this is not a repo but pypi library

**Comment by Wauplin** [comment]
Actually `repo_url` must be provided only once by the library author integrating `ModelHubMixin`, not for each individual user. Therefore I'd prefer not to "guess" the repo_url based on the current local directory -which can be very misleading-.
