### ISSUE TITLE
 No indication of virus/malware scanning for pytorch bins and safetensors. Only JSON files are scanned

### ISSUE THREAD

**Issue by swoldemichael** [huggingface/huggingface_hub#2160]
I notice there is no indication of scanning for pickle and safetensors. Only JSON files get scanned. It is not useful to see only some files are scanned and the rest skipped. Did the scans fail? There should be a response if they did.

I think it would be nice to add an app like the safetensors conversion tool to allow users to run scan and get response.

**Comment by swoldemichael** [comment]
![Screenshot 2024-03-26 at 10-23-02 solwol_my-awesome-adapter at main](https://github.com/huggingface/huggingface_hub/assets/37008415/bb5af334-b6fe-4b01-92b8-c0e2439bed2e)

**Comment by julien-c** [comment]
@McPatate

**Comment by McPatate** [comment]
Hi, sorry about the missing scan, we were having an issue in the backend. The issue is fixed and scans have restarted.

**Comment by swoldemichael** [comment]
Thanks @McPatate. I see the scans are performed on my repos. Thank you for the quick response.
