### ISSUE TITLE
Profiling info to model hub?

### ISSUE THREAD

**Issue by bayartsogt-ya** [huggingface/huggingface_hub#218]
Thank you for the great work.

I wonder if there is any way to include profiling information to model hub through `push_to_hub`?
So that we can see how much resource we are using during training, especially so helpful when using TPU.
I tried `pip install tensorboard_plugin_profile`, but only train/eval metrics uploaded to model hub.

**Comment by LysandreJik** [comment]
The `push_to_hub` method takes as input a `repo_path_or_name` which is the path to a local folder (which will be created if it doesn't exist). 

Any files you put in that folder will be uploaded to the hub - so if you're aware of a package that would create profiling information and save it as a file, you should be able to save those in this directory and see them uploaded to the hub. 

Here's a [document regarding TPU profiling](https://cloud.google.com/tpu/docs/pytorch-xla-performance-profiling-tpu-vm) for torch XLA - if it saves some files these could be uploaded to the hub. There's a tensorboard visualiser on the hub that should be helpful too, but I'm unaware of its ability to detect profiles from this tool.

**Comment by Wauplin** [comment]
I'm closing since quite old and seems to be solved.
