### ISSUE TITLE
How get the access of modifying past commit info for huggingface repos?

### ISSUE THREAD

**Issue by monet-joe** [huggingface/huggingface_hub#2187]
### Feature request

I tried to amend past commit info such as  GIT_COMMITTER_NAME , AIT_AUTHOR_NAME, etc., but failed to run git push -f to update them onto the cloud, please see the pic in Motivation part:

### Motivation

![Snipaste_2024-03-31_20-02-06](https://github.com/huggingface/datasets/assets/20459298/6d59ab3a-dfee-4ab0-98e1-27339e45b456)

### Your contribution

It seems that we have no access to unlock the protected branch of the hf repos, actually the settings of hf repos cannot let us edit any branch or do other branch operations. I wonder if we are able to achive batch modification of past commit info just like GitHub

**Comment by Wauplin** [comment]
Hi @monet-joe, it looks like the error is related to an LFS upload rather than the git commit amend. This can be the case if git LFS is not setup correctly for the local repo. 

cc @Pierrci just in case about updating existing commit metadata

**Comment by monet-joe** [comment]
> Hi @monet-joe, it looks like the error is related to an LFS upload rather than the git commit amend. This can be the case if git LFS is not setup correctly for the local repo.
> 
> cc @Pierrci just in case about updating existing commit metadata

thx 4 ur answer, it seems that u r right, cuz I tried another hf repo without LF, it succeeded!
![image](https://github.com/huggingface/huggingface_hub/assets/20459298/24929ba1-53cf-4d51-97cf-6fdea1ab0cc8)
