### ISSUE TITLE
Hugginface_CLI local_dir_use_symlink doesn't work.

### ISSUE THREAD

**Issue by Karesto** [huggingface/huggingface_hub#2203]
### Describe the bug

While trying to download a dataset with the command : 
`huggingface-cli download link_to_dataset --repo-type "dataset" --local-dir "." -- local_dir_use_symlink False, it doesn't work and the argument isn't recognized.`
Furthermore, when using the python function: 
`snapshot_download(repo_id="link_to_dataset", repo_type="dataset", allow_patterns=["dataset/*"], local_dir =".", local_dir_use_symlinks=False)` , there are symlinks at the output.

### System info

```shell
Copy-and-paste the text below in your GitHub issue.

- huggingface_hub version: 0.21.4
- Platform: Linux-5.10.0-27-amd64-x86_64-with-glibc2.31
- Python version: 3.9.2
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/achoukarah/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: UserAhc
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.2.1
- Jinja2: 3.1.3
- Graphviz: N/A
- Pydot: N/A
- Pillow: 10.2.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.26.4
- pydantic: N/A
- aiohttp: N/A
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /home/achoukarah/.cache/huggingface/hub
- HF_ASSETS_CACHE: /home/achoukarah/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/achoukarah/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment]
Hi @Karesto , I'm sorry for the inconvenience. Could you provide more details please? Could you provide a simple example that produce the undesired effect for this command:

```py
snapshot_download(repo_id="link_to_dataset", repo_type="dataset", allow_patterns=["dataset/*"], local_dir =".", local_dir_use_symlinks=False)
```

and also provide the resulting folder you're getting (by running `tree -alh .` for instance?

Without more information, it is hard to help. Disabling symlinks is supposed to work.

**Comment by Wauplin** [comment]
Weird. Does it still happen if you completely delete the current folder and try to re-download? It might be the case that the symlink exists from a previous download. Otherwise, I don't see how I could reproduce it myself :confused:

**Comment by Karesto** [comment]
I tried to delete both cache and current folder, but nothing seems to solve it. (I ended up downloading the files one by one through my browser).
