### ISSUE TITLE
ImportError: cannot import name 'is_jsonable' from 'huggingface_hub.utils' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/__init__.py)

### ISSUE THREAD

**Issue by 1MuhammadFarhanAslam** [huggingface/huggingface_hub#2231]
### Describe the bug

I want to push custom trained ml model to hugging face hub so I want to import huggingface_hub but it's showing me errror.

Error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-22-76d126dcf4a8> in <cell line: 1>()
----> 1 from huggingface_hub import from_pretrained_keras
      2 
      3 model = from_pretrained_keras("keras-io/mobile-vit-xxs")
      4 prediction = model.predict(image)
      5 prediction = tf.squeeze(tf.round(prediction))

5 frames
/usr/local/lib/python3.10/dist-packages/huggingface_hub/hub_mixin.py in <module>
     10 from .hf_api import HfApi
     11 from .repocard import ModelCard, ModelCardData
---> 12 from .utils import (
     13     EntryNotFoundError,
     14     HfHubHTTPError,

ImportError: cannot import name 'is_jsonable' from 'huggingface_hub.utils' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/__init__.py)

### Steps to reproduce the bug

```
%%capture
! pip install git+https://github.com/huggingface/huggingface_hub.git@main
! sudo apt -qq install git-lfs
! git config --global credential.helper store
```

`! huggingface-cli login`

```
from huggingface_hub import push_to_hub_keras
push_to_hub_keras(model, 'cancer_image_classifier')
```

### Expected behavior

![image](https://github.com/huggingface/datasets/assets/59208164/d1d0d59f-4cea-40c5-962a-23b07894c2ef)

### Environment info

I'm not using datasets library. I want to push my own custom trained keras dataset to huggingface to use in gradio spaces on Huggingface.

**Comment by Wauplin** [comment]
Hi @1MuhammadFarhanAslam, I'm sorry your facing this error. I think there is a problem with your installation. Could you try to uninstall huggingface_hub and then reinstall latest version? It should hopefully solve your problem.

**Comment by 1MuhammadFarhanAslam** [comment]
> Hi @1MuhammadFarhanAslam, I'm sorry your facing this error. I think there is a problem with your installation. Could you try to uninstall huggingface_hub and then reinstall latest version? It should hopefully solve your problem.

 Hi! @Wauplin,
 Great! It worked for me and resolved my issue. Thank You so much for helping me.

**Comment by Wauplin** [comment]
Glad your problem's solved!
