### ISSUE TITLE
[CLI] Command line to delete files on a repo

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#2235]
At the moment it's not possible to delete remote files from the command line except using the `huggingface-cli upload (...) --delete="*"` command. But this one requires to upload while deleting.

Other feature request: CLI command to move files inside a repo. 

We have everything needed in `HfApi`, it's just a matter of implementing the CLI. 

Requested by @ArthurZucker _"feature request for clumsy people"_ :smile:

**Comment by OlivierKessler01** [comment]
Hi @Wauplin :)

Is that something I could take as a first contribution ?

I see we have two related functions in the `HfApi`, namely `delete_file` and `delete_folder`. Should we rather have a single or two commands ? In the former, should we use a similar API to `upload --delete="*"` and use a glob-type parameter ?

**Comment by Wauplin** [comment]
Hi @OlivierKessler01, thanks for proposing your help on this issue :)

Agree with you it makes sense to create a single command. I would maybe call it `huggingface-cli commit delete` (and after that `huggingface-cli commit move`). Something like this:

```sh
# delete all
huggingface-cli commit delete *

# delete single file
huggingface-cli commit delete file.txt

# delete single folder
huggingface-cli commit delete folder/

# delete multiple
huggingface-cli commit delete file.txt folder/ file2.txt

# delete multiple patterns
huggingface-cli commit delete file.txt *.json folder/*.parquet

# delete from different revision / repo-type
huggingface-cli commit delete file.txt --revision=... --repo-type=dataset
```

What do you think?

**Comment by OlivierKessler01** [comment]
Hi @Wauplin  thank you for the thorough answer :)

I'll be working on this next week.

**Comment by Wauplin** [comment]
Thanks! Let me know if you have any question :hugs:

**Comment by OlivierKessler01** [comment]
Hi @Wauplin I don't know how you set-up your notifications, if mentionning the issue in a PR suffices or not, but check this out :) https://github.com/huggingface/huggingface_hub/pull/2280

**Comment by Wauplin** [comment]
Thanks for the PR @OlivierKessler01! I'm notified on every new PR/issue so it's fine. I took some time off, hence the delay to review it :) I just reviewed your PR, you can find my comments there.
