### ISSUE TITLE
Document question answering returns empty list without an error

### ISSUE THREAD

**Issue by aymeric-roucher** [huggingface/huggingface_hub#2247]
### Describe the bug

The document_question_answering method silently fails by returning an empty list. Same for visual_question_answering when set with a wrong model, like

```
  client = InferenceClient(
      model="impira/layoutlm-document-qa",
  )
```

### Reproduction

from huggingface_hub import InferenceClient

client = InferenceClient()

image = "data/gaia/validation/cca530fc-4052-43b2-b130-b30968d8aa44.png"
question = "On what number of row and column is the white king?"

client.document_question_answering(image=image, question=question)

> output: []

### System info

```shell
- huggingface_hub version: 0.22.2
- Platform: macOS-14.1-arm64-arm-64bit
- Python version: 3.11.6
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /Users/aymeric/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: m-ric
- Configured git credential helpers: osxkeychain
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.2.2
- Jinja2: 3.1.2
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 10.2.0
- hf_transfer: N/A
- gradio: 4.22.0
- tensorboard: N/A
- numpy: 1.26.3
- pydantic: 2.5.0
- aiohttp: 3.9.3
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /Users/aymeric/.cache/huggingface/hub
- HF_ASSETS_CACHE: /Users/aymeric/.cache/huggingface/assets
- HF_TOKEN_PATH: /Users/aymeric/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment]
Will look into it, thanks for reporting :+1:

**Comment by Wauplin** [comment]
Would it be possible to have more details on:
- what's your input? (a real image example)
- what would you expect from the client?

Thanks in advance!

**Comment by aymeric-roucher** [comment]
Hello @Wauplin!
The input is a real image.
I'd prefer the output to be either a completion, or an error. 

For instance if I use task `visual_question_answering`, as in:
```
from huggingface_hub import InferenceClient
client = InferenceClient()
image = "https://raw.githubusercontent.com/huggingface/text-generation-inference/main/integration-tests/images/chicken_on_money.png"
question = "What is on the image?"
client.visual_question_answering(image=image, question=question)
```

I get this completion, which is the desired behaviour for me:
```
[VisualQuestionAnsweringOutputElement(label=None, score=0.844512939453125, answer='rooster'),
 VisualQuestionAnsweringOutputElement(label=None, score=0.6880057454109192, answer='chicken'),
 VisualQuestionAnsweringOutputElement(label=None, score=0.043415617197752, answer='turkey'),
 VisualQuestionAnsweringOutputElement(label=None, score=0.026919541880488396, answer='yes'),
 VisualQuestionAnsweringOutputElement(label=None, score=0.0256495401263237, answer='bird')]
```

But with document_question_answering I get an empty list.

If `document_question_answering` does not support images it would be nice to get an informative error instead of an empty list.

**Comment by Wauplin** [comment]
Ok I understand better now.

So you provide an image without any text and expect `document_question_answering` to raise an error instead of returning an empty list? I don't find that returning an empty list is philosophically wrong TBH. If you ask a question, that the model is supposed to return a list of answers and that it didn't find any, then empty list makes sense.

In any case, this is not something that will be changed in `InferenceClient` and not even in Inference API. Those are simply forwarding inputs and outputs to / from transformers's pipeline. So I'll close this issue but feel free to open a new one in [`transformers`](https://github.com/huggingface/transformers/issues) if you feel strongly about it and think the document/visual question answering pipelines should be updated.

**Comment by aymeric-roucher** [comment]
Thank you for your detailed answer! 🤗
