### ISSUE TITLE
No package metadata was found for bitsandbytes

### ISSUE THREAD

**Issue by Lagstill** [huggingface/huggingface_hub#2249]
### Describe the bug

Used the following:

> quantization_config = BitsAndBytesConfig(load_in_4bit=True, 
>                                          bnb_4bit_use_double_quant=True,
>                                          bnb_4bit_compute_dtype=torch.bfloat16)
> 
> model = AutoModelForCausalLM.from_pretrained(model_id, 
>                                              device="cpu",
>                                              token=ACCESS_TOKEN)

and

`model.push_to_hub('Lagstill/Varsity_module2_bot')`, which was successful using the huggingface cli.
and similarly the tokensier was pushed.

But while loading in the model card, in HF Website I get _No package metadata was found for bitsandbytes_ in `Lagstill/Varsity_module2_bot`

### Logs

```shell
_No package metadata was found for bitsandbytes_
```

### System info

```shell
python-dotenv~=1.0.1
torch~=2.2.2
transformers~=4.38.2
bitsandbytes~=0.42.0; sys_platform == 'darwin'
bitsandbytes~=0.43.1; 'darwin' not in sys_platform 
accelerate~=0.28.0
pypdf~=4.1.0
tiktoken~=0.6.0
sentence-transformers~=2.5.1
faiss-cpu~=1.8.0
langchain~=0.1.16
streamlit~=1.29.0
```

**Comment by jeevanchaps** [comment]
i have the same issue. any solutions?

**Comment by Wauplin** [comment]
Same answer as what I mentioned above, I would need more context to help you investigate the issue. Also worth asking directly on `bitsandbytes` project :)

**Comment by jeevanchaps** [comment]
I was fine-tuning a LLM model and I installed all the required libraries including bits and bytes. After I completed the fine-tuning I pushed the model to the huggingface hub. Once pushed to the huggingface hub it should have been straightforward like other model cards but when using Inferene API on

<img width="1675" alt="Screenshot 2024-04-30 at 8 52 09 AM" src="https://github.com/huggingface/huggingface_hub/assets/10882985/aff65610-928a-43c8-bbde-00216528674b">
 the model that I pushed it says No package metadata was found for bitsandbytes. 

so like in the image above when you click compute the problem arises as the model has been already pushed into the hugging face hub,

**Comment by Wauplin** [comment]
Thanks for clarification @jeevanchaps. I reported it internally. I'm linking the PR that should fix it https://github.com/huggingface/api-inference/pull/1902/ (private repo). I'll let you know once it's deployed.

**Comment by Wauplin** [comment]
@jeevanchaps _No package metadata was found for bitsandbytes_ should now be solved in the Inference API. Can you let me know if you're still facing this issue? Otherwise we're good to merge this issue. If you have another issue than that, please open a separate issue.

**Comment by Wauplin** [comment]
Closing as the initial issue is not solved.
