### ISSUE TITLE
ValueError: Unable to retrieve user and repo ID from the passed HF ID: https://huggingface.co/MonolithFoundation/Bumblebee-Light

### ISSUE THREAD

**Issue by MonolithFoundation** [huggingface/huggingface_hub#2268]
I have loggined, the repo https://huggingface.co/MonolithFoundation/Bumblebee-Light exist.

Just can not push models, why?

**Comment by Wauplin** [comment]
> Just can not push models, why?

Can you explain more why you can't? Here is some docs that should help you:
- how to authenticate with the Python client: https://huggingface.co/docs/huggingface_hub/quick-start#authentication
- how to upload with the Python client: https://huggingface.co/docs/huggingface_hub/guides/upload
- how to upload with the web interface: https://huggingface.co/docs/hub/models-uploading

**Comment by MonolithFoundation** [comment]
I just keep getting error:

ValueError: Unable to retrieve user and repo ID from the passed HF ID: https://huggingface.co/MonolithFoundation/Bumblebee-Light

**Comment by Wauplin** [comment]
With a full stack trace it'll be easiest to point you toward to correct point. Anyway, when upload files or doing anything else on the Hub, you must pass a repo_id, not a URL. In your case the repo id is `MonolithFoundation/Bumblebee-Light`.

**Comment by MonolithFoundation** [comment]
Hi, am just exactly provide the id, otherwise the logging messages. concated would repeat the url prefix.

Can u tell me what could be the reason behind? Clearly it's not my repo id doesn't exist.



At 2024-05-03 18:43:53, "Lucain" ***@***.***> wrote:

With a full stack trace it'll be easiest to point you toward to correct point. Anyway, when upload files or doing anything else on the Hub, you must pass a repo_id, not a URL. In your case the repo id is MonolithFoundation/Bumblebee-Light.

**Comment by Wauplin** [comment]
Please provide: 
1. the Python script that is causing your error
2. the error with full traceback it produces

Won't be able to help further without those 2.

**Comment by Wauplin** [comment]
Looks like there is a double-dash in your command line MonolithFoundation/Bumblebee--Ligth, isn't it?

**Comment by MonolithFoundation** [comment]
Hi, thanksfor the reply, it is not

huggingface-cli upload MonolithFoundation/Bumblebee-Light ./ ./

I just copyed the id from my huggingace dashboard...

**Comment by Wauplin** [comment]
Could you try to run this in a separate python terminal?

```py
>>> from huggingface_hub import repo_type_and_id_from_hf_id
>>> repo_type_and_id_from_hf_id("MonolithFoundation/Bumblebee-Light")
(None, 'MonolithFoundation', 'Bumblebee-Light')
```

**Comment by MonolithFoundation** [comment]
@Wauplin Hi

<img width="475" alt="image" src="https://github.com/huggingface/huggingface_hub/assets/168061642/e19d9c8f-6219-4eb1-b08a-700fa4a3b103">

Any further steps?

**Comment by Wauplin** [comment]
Hi, not that I can think of no. It's very weird that you get this error while using the CLI but not if you run it manually in a snippet. Could you try uninstalling completely the package (and CLI) and reinstall it again?

To be honest this is not an expected error and it's appearing on a command that is very widely used and for which I've never seen this reported. That's why I'm a bit confused about what to do/how to explain it 😕

**Comment by MonolithFoundation** [comment]
Shit, I found the reason.

<img width="873" alt="image" src="https://github.com/huggingface/huggingface_hub/assets/168061642/460ef3c5-4e22-4845-a4a4-1113af8f3c81">


I would suggest your guys delete this package.


If it doesn't provided by huggingface, contact the author to delete it. thanks.
