### ISSUE TITLE
[Feature request] Set environment variable in inference endpoint (custom docker image)

### ISSUE THREAD

**Issue by datavistics** [huggingface/huggingface_hub#2301]
Save me @Wauplin, you are my only hope. 

`create_inference_endpoint` and `update_inference_endpoint` do not set the image the same way

I want to be able to update the env var in a deployed inference endpoint. Currently I can only delete and re-create.

**Comment by Wauplin** [comment]
Your hope is there: https://github.com/huggingface/huggingface_hub/pull/2306.

**Comment by Wauplin** [comment]
> Save me @Wauplin, you are my only hope.

@davanstrien Done.

**Comment by Wauplin** [comment]
> Save me @Wauplin

@davanstrien Done.
