### ISSUE TITLE
huggingface Error: t.at is not a function

### ISSUE THREAD

**Issue by Minami-su** [huggingface/huggingface_hub#2327]
![image](https://github.com/huggingface/huggingface_hub/assets/76865636/580c7d1a-0d24-4a74-afe3-4538e0171bdd)

**Comment by Wauplin** [comment]
Hi @Minami-su, has your issue been resolved? Mind sharing what went wrong and what did you do to solve it? It might be helpful for others in the community :hugs:

**Comment by Minami-su** [comment]
Replace browser.....
