### ISSUE TITLE
huggingface_hub release notes include unrelated changes

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#237]
The release notes of new releases of `huggingface_hub` include changes in widgets, documentation and `api-inference-community`. Ideally (specially for `api-inference-community`) we would have different release notes, tags and GitHub Actions workflows.

**Comment by adrinjalali** [comment]
We can probably manually edit the release notes for the next release, and the one after that should be clean. I think we can close this one.
