### ISSUE TITLE
Docs: Local Preview URL Discrepancy

### ISSUE THREAD

**Issue by lappemic** [huggingface/huggingface_hub#2381]
I built the documentation locally because I wanted to try some changes. After executing `doc-builder preview huggingface_hub docs/source/en`, the preview is displayed at `localhost:5173` instead of `localhost:3000` as mentioned in [`docs/README.md`](https://github.com/huggingface/huggingface_hub/tree/main/docs#previewing-the-documentation).

Is this just on my side, or should this be updated in the docs?

**Comment by julien-c** [comment]
cc: @mishig25

**Comment by Wauplin** [comment]
@lappemic it's opening on `http://localhost:5173/` as well for me so it's probably an outdated part of the docs. Would you like to open a PR to update it?
