### ISSUE TITLE
`token=False` doesn't work for `hf_hub_download`

### ISSUE THREAD

**Issue by ankushvangari** [huggingface/huggingface_hub#2385]
### Describe the bug

When `token=False` is passed in to `hf_hub_download` it still uses the `HF_TOKEN` set in the environment variable instead of ignoring it. This was working in `0.22.2` and now failing in `0.23.4`

### Reproduction

Same code with setting `HF_TOKEN` for both shows different behavior on `0.22.2` and `0.23.4`

![image (3)](https://github.com/huggingface/huggingface_hub/assets/32551394/54dd7479-ec94-4667-ae79-4fd8e85763ab)
![image (2)](https://github.com/huggingface/huggingface_hub/assets/32551394/138e15dd-3abc-4bd1-ae34-5b5e1efdb8c2)

### System info

```shell
- huggingface_hub version: 0.23.4
- Platform: macOS-14.5-arm64-arm-64bit
- Python version: 3.10.10
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /Users/ankushvangari/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: osxkeychain
- FastAI: 2.7.14
- Tensorflow: 2.16.2
- Torch: 2.3.1
- Jinja2: 3.1.4
- Graphviz: N/A
- keras: 3.4.1
- Pydot: N/A
- Pillow: 10.2.0
- hf_transfer: 0.1.4
- gradio: N/A
- tensorboard: N/A
- numpy: 1.26.4
- pydantic: 2.7.2
- aiohttp: 3.9.5
- ENDPOINT: http://localhost:8000
- HF_HUB_CACHE: /Users/ankushvangari/.cache/huggingface/hub
- HF_ASSETS_CACHE: /Users/ankushvangari/.cache/huggingface/assets
- HF_TOKEN_PATH: /Users/ankushvangari/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment]
Thanks for reporting @ankushvangari. This is indeed a bug. I'll shortly open a PR to fix it :)

**Comment by Wauplin** [comment]
PR opened: https://github.com/huggingface/huggingface_hub/pull/2386. Thanks again for the report!
