### ISSUE TITLE
v0.23 download method breaks on filesystems that don't have flock enabled

### ISSUE THREAD

**Issue by jeffliu-LL** [huggingface/huggingface_hub#2399]
### Describe the bug

The change in how downloads work in 0.23 breaks for file systems that don't have flock enabled. This is an issue for our HPC which uses lustre without flock for network storage. The previous approach allowed us to set the cache to a directory on the local filesystem, which has flock, and then it would be automatically copied over to the network location once the download is completed. The new approach requires the `local_dir` to be on a file system that has flock enabled.

It would be great to have some workaround that either doesn't require `local_dir` to have flock, or allow for the old behavior where it would get downloaded to cache then copied to the local directory.

### Reproduction

For a system where `local_dir` is on a network drive without `flock`, run

```
huggingface-cli download microsoft/Phi-3-mini-4k-instruct-gguf Phi-3-mini-4k-instruct-q4.gguf --local-dir=data/phi3
```

### Logs

```shell
Traceback (most recent call last):
  File "/path/to/env/lib/python3.12/site-packages/filelock/_unix.py", line 43, in _acquire
    fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
OSError: [Errno 38] Function not implemented

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/env/bin/huggingface-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/path/to/env/lib/python3.12/site-packages/huggingface_hub/commands/huggingface_cli.py", line 51, in main
    service.run()
  File "/path/to/env/lib/python3.12/site-packages/huggingface_hub/commands/download.py", line 146, in run
    print(self._download())  # Print path to downloaded files
          ^^^^^^^^^^^^^^^^
  File "/path/to/env/lib/python3.12/site-packages/huggingface_hub/commands/download.py", line 159, in _download
    return hf_hub_download(
           ^^^^^^^^^^^^^^^^
  File "/path/to/env/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/path/to/env/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1202, in hf_hub_download
    return _hf_hub_download_to_local_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/env/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1406, in _hf_hub_download_to_local_dir
    paths = get_local_download_paths(local_dir=local_dir, filename=filename)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/env/lib/python3.12/site-packages/huggingface_hub/_local_folder.py", line 138, in get_local_download_paths
    metadata_path = _huggingface_dir(local_dir) / "download" / f"{sanitized_filename}.metadata"
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/env/lib/python3.12/site-packages/huggingface_hub/_local_folder.py", line 223, in _huggingface_dir
    with WeakFileLock(gitignore_lock):
  File "/path/to/env/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/path/to/env/lib/python3.12/site-packages/huggingface_hub/utils/_fixes.py", line 84, in WeakFileLock
    lock.acquire()
  File "/path/to/env/lib/python3.12/site-packages/filelock/_api.py", line 255, in acquire
    self._acquire()
  File "/path/to/env/lib/python3.12/site-packages/filelock/_unix.py", line 48, in _acquire
    raise NotImplementedError(msg) from exception
NotImplementedError: FileSystem does not appear to support flock; user SoftFileLock instead
```

### System info

```shell
Copy-and-paste the text below in your GitHub issue.

- huggingface_hub version: 0.23.0
- Platform: Linux-5.10.218-llgrid-x86_64-with-glibc2.35
- Python version: 3.12.1
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /state/partition1/user/hf/token
- Has saved token ?: False
- Configured git credential helpers: store
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.2.0
- Jinja2: 3.1.3
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 10.2.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.26.4
- pydantic: N/A
- aiohttp: 3.9.1
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /state/partition1/user/hf/hub
- HF_ASSETS_CACHE: /state/partition1/user/hf/assets
- HF_TOKEN_PATH: /state/partition1/user/hf/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment]
Hi @jeffliu-LL, thanks for reporting and sorry for the inconvenience. To me it looks like having this working before v0.23 was more of a cool side effect rather than a well-thought feature :smile: Anyway, thanks for shedding light on this topic since it had to be fixed. I opened https://github.com/huggingface/huggingface_hub/pull/2402 to automatically default to a `SoftFileLock` in such a case, which is weaker but still enough in our case.

**Comment by jeffliu-LL** [comment]
Hi @Wauplin, thanks so much for the quick response and PR!

**Comment by jeffliu-LL** [comment]
@Wauplin, in using the version with SoftFileLock, it seems to hang indefinitely.

I get 
```bash
Fetching 5 files:   0%|                                                                              | 0/5 [01:45<?, ?it/s]
FileSystem does not appear to support flock. Falling back to SoftFileLock for /model_dir/.cache/huggingface/.gitignore.lock
FileSystem does not appear to support flock. Falling back to SoftFileLock for /model_dir/.cache/huggingface/.gitignore.lock
FileSystem does not appear to support flock. Falling back to SoftFileLock for /model_dir/.cache/huggingface/.gitignore.lock
FileSystem does not appear to support flock. Falling back to SoftFileLock for /model_dir/.cache/huggingface/.gitignore.lock
FileSystem does not appear to support flock. Falling back to SoftFileLock for /model_dir/.cache/huggingface/.gitignore.lock
```
repeated a bunch of times, with no progress even after several minutes. Using older versions of the hub library (<=0.22), it downloads fine.

When I keyboard interrupt, it seems to be waiting here:
```
Traceback (most recent call last):
  File "/proj_env/lib/python3.10/threading.py", line 1537, in _shutdown
    atexit_call()
  File "/proj_env/lib/python3.10/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/proj_env/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/proj_env/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt: 
```

Should I make a separate issue for this? Thanks!

**Comment by ZhuoruiLiu12** [comment]
> [@Wauplin](https://github.com/Wauplin), in using the version with SoftFileLock, it seems to hang indefinitely.
> 
> I get
> 
> Fetching 5 files:   0%|                                                                              | 0/5 [01:45<?, ?it/s]
> FileSystem does not appear to support flock. Falling back to SoftFileLock for /model_dir/.cache/huggingface/.gitignore.lock
> FileSystem does not appear to support flock. Falling back to SoftFileLock for /model_dir/.cache/huggingface/.gitignore.lock
> FileSystem does not appear to support flock. Falling back to SoftFileLock for /model_dir/.cache/huggingface/.gitignore.lock
> FileSystem does not appear to support flock. Falling back to SoftFileLock for /model_dir/.cache/huggingface/.gitignore.lock
> FileSystem does not appear to support flock. Falling back to SoftFileLock for /model_dir/.cache/huggingface/.gitignore.lock
> repeated a bunch of times, with no progress even after several minutes. Using older versions of the hub library (<=0.22), it downloads fine.
> 
> When I keyboard interrupt, it seems to be waiting here:
> 
> ```
> Traceback (most recent call last):
>   File "/proj_env/lib/python3.10/threading.py", line 1537, in _shutdown
>     atexit_call()
>   File "/proj_env/lib/python3.10/concurrent/futures/thread.py", line 31, in _python_exit
>     t.join()
>   File "/proj_env/lib/python3.10/threading.py", line 1096, in join
>     self._wait_for_tstate_lock()
>   File "/proj_env/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
>     if lock.acquire(block, timeout):
> KeyboardInterrupt: 
> ```
> 
> Should I make a separate issue for this? Thanks!

I have met the same problem when using huggingface-hub version of 0.27.1, in your description which version of hub could work well? Thanks

**Comment by Wauplin** [comment]
Hi @jeffliu-LL @ZhuoruiLiu12 sorry for the delay responding to this. I just opened this PR https://github.com/huggingface/huggingface_hub/pull/2751 which should definitely settle this issue.
