### ISSUE TITLE
ImportError: cannot import name 'DatasetFilter' from 'huggingface_hub' (/opt/conda/lib/python3.10/site-packages/huggingface_hub/init.py)

### ISSUE THREAD

**Issue by JayeetaP** [huggingface/huggingface_hub#2401]
### Describe the bug

Hi,

I have been using Setfit for the last month with no errors. This morning when I tried to rerun the same code, with no changes, looks 'DatasetFilter' import from huggingface_hub is failing.

The associated issue in setfit branch: https://github.com/huggingface/setfit/issues/544

### Reproduction

from setfit import SetFitModel, Trainer, TrainingArguments

### Logs

```shell
ImportError Traceback (most recent call last)
Cell In[15], line 8
6 from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, precision_score, recall_score, f1_score, classification_report
7 import matplotlib.pyplot as plt
----> 8 from setfit import SetFitModel, Trainer, TrainingArguments
9 from sentence_transformers.losses import CosineSimilarityLoss
10 from datasets import Dataset

File /opt/conda/lib/python3.10/site-packages/setfit/init.py:8
5 import warnings
7 from .data import get_templated_dataset, sample_dataset
----> 8 from .model_card import SetFitModelCardData
9 from .modeling import SetFitHead, SetFitModel
10 from .span import AbsaModel, AbsaTrainer, AspectExtractor, AspectModel, PolarityModel

File /opt/conda/lib/python3.10/site-packages/setfit/model_card.py:14
12 import transformers
13 from datasets import Dataset
---> 14 from huggingface_hub import CardData, DatasetFilter, ModelCard, dataset_info, list_datasets, model_info
15 from huggingface_hub.repocard_data import EvalResult, eval_results_to_model_index
16 from huggingface_hub.utils import yaml_dump

ImportError: cannot import name 'DatasetFilter' from 'huggingface_hub' (/opt/conda/lib/python3.10/site-packages/huggingface_hub/init.py)
```

### System info

```shell
Name: transformers
Version: 4.39.0
Name: setfit
Version: 1.0.3
Name: huggingface-hub
Version: 0.24.0
Python: 3.10
```

**Comment by Wauplin** [comment]
Hi @JayeetaP, sorry for the inconvenience this is caused by a recent breaking change introduce [in 0.24.0 release](https://github.com/huggingface/huggingface_hub/releases/tag/v0.24.0). The use of `DatasetFilter` has been deprecated for a few months already and reached its end of life. Could you update SetFit to its latest version and retry? If the problem persists, then could you downgrade your local `huggingface_hub` version and open an issue on [Setfit](https://github.com/huggingface/setfit) repository? Thanks!

**Comment by JayeetaP** [comment]
Thanks for the response.

I am on the latest version of `Setfit`: 1.0.3. Can you confirm if that's not the latest release?
I downgraded `huggingface_hub` version to 0.23.0 and it still didn't work. Any recommendation on which version I should use?
I already have an issue open in the Setfit repository: https://github.com/huggingface/setfit/issues/544

**Comment by chenmoneygithub** [comment]
+1, seeing the same issue.

**Comment by Wauplin** [comment]
I replied in https://github.com/huggingface/setfit/issues/544#issuecomment-2238645761 about the fuller context. 2 solutions while waiting for a proper fix: either downgrade `huggingface_hub` version or install `setfit` from source with the fix introduced in https://github.com/huggingface/setfit/pull/527. 

@JayeetaP I'm surprised installing `huggingface_hub==0.23.0` did not work. I just tried with 0.23.5 and it works for me. Maybe the installation did not go well? Sometimes it's better to uninstall and reinstall completely to be sure of the change (and restart the runtime)

**Comment by RubTalha** [comment]
https://stackoverflow.com/questions/78787623/cannot-import-name-datasetfilter-from-huggingface-hub/78787734#78787734

**Comment by JayeetaP** [comment]
like I mentioned in [github.com/huggingface/setfit/issues/544 (https://github.com/huggingface/setfit/issues/544#issuecomment-2238645761), I had to uninstall, re-install, and restart so now huggingface_hub version 0.23.5 works. I am unblocked for now! :)
