### ISSUE TITLE
Impacts of removing `modelId`

### ISSUE THREAD

**Issue by davidmezzetti** [huggingface/huggingface_hub#2408]
Did something change on the HF Hub server side related to this? https://github.com/huggingface/huggingface_hub/pull/2405

It appears that the `modelId` while deprecated was still returning a value even for the latest version (0.24.0) as of yesterday. But now it's throwing an exception for the same version of the library. 

Here are two examples of the impact.

- https://github.com/microsoft/DeepSpeed/pull/5789
- https://github.com/neuml/txtai/issues/750

And if we use the last version that supported the `modelId` attribute v0.18.0, it no longer throws an exception but it just returns `None`.

Overall, the impact is that this change is breaking code running in production as it's running, which makes it tricky to figure out why all of the sudden it stopped working. While it's an easy fix, it's definitely tough to force users to make an immediate upgrade with no temporary workaround such as reverting or pinning to a prior version.

I'm not sure if this was the intended impact but I just wanted to share this.

**Comment by julien-c** [comment]
Hi @davidmezzetti thanks for the report. We have reverted the change server-side for now.

We still hope to formally remove this deprecated field in the future.

We'll monitor other reports of breakage, if you see any, let us know!

**Comment by davidmezzetti** [comment]
Thank you. I appreciate the fix and response!

I made the change to any code I had that was affected. I'll share anything if I see anything.
