### ISSUE TITLE
Add sentence similarity for spaCy

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#241]
Computing similarity is simple with `spaCy` and there is an existing [template pipeline](https://github.com/huggingface/huggingface_hub/blob/main/api-inference-community/docker_images/common/app/pipelines/sentence_similarity.py) for sentence similarity at which can be modified for this. 

https://spacy.io/api/doc#similarity

**Comment by devpramod** [comment]
Hi! @osanseviero I would like to contribute

**Comment by osanseviero** [comment]
Hi @devpramod! Excellent! Contributions are always welcomed. I think this should be easier to introduce since there is already an existing template for this use case. Let me know if you have any questions

**Comment by devpramod** [comment]
Hi @osanseviero, very sorry about the delay. I've had a hectic month. I just added sentence similarity. Please let me know about any further changes.

**Comment by osanseviero** [comment]
Don't worry @devpramod! Your contribution is extremely appreciated :) I left a couple of comments in the PR
