### ISSUE TITLE
Support regex of filename in download

### ISSUE THREAD

**Issue by jazelly** [huggingface/huggingface_hub#2424]
**Is your feature request related to a problem? Please describe.**
When downloading some repo, I'd like to download some files by regex matching.

For example, in a GGUF collection, it's typical to have different quantization options. It's painful to specify them one by one, but with regex, I can do `^.*Q[4-8].*\.gguf$` to download all quantization versions from Q4 to Q8.
 
**Describe the solution you'd like**
Allow `filename` to take regex and download these files within the repo.

**Describe alternatives you've considered**
Right now, what I can do from userland is to use HF API to query the files under the repo and do self regex check. It would be great if this is integrated.

**Comment by Wauplin** [comment]
Hi @jazelly, it is possible to filter the files to download using the `allow_patterns` and `ignore_patterns` parameters from `snapshot_download`. Here is the guide explaining this: https://huggingface.co/docs/huggingface_hub/guides/download#filter-files-to-download.  Patterns are not regexes but Standard Wildcards (globbing patterns) as documented [here](https://tldp.org/LDP/GNU-Linux-Tools-Summary/html/x11655.htm). For you doing something like `*Q[4-8]*.gguf` should work:


```py
from huggingface_hub import snapshot_download


snapshot_download(
    repo_id="lmstudio-community/Meta-Llama-3.1-8B-Instruct-GGUF",
    allow_patterns="*Q[4-8]*.gguf",
)
```

Hope this answers your question. Feel free to close this issue if that's the case :)
