### ISSUE TITLE
hfapi.list_models() support list the top K trending models for TGI/TEI/Diffusion models

### ISSUE THREAD

**Issue by weigary** [huggingface/huggingface_hub#2427]
**Is your feature request related to a problem? Please describe.**
We are integrating with HF to get the top K TGI/TEI models and generate the deployment settings for these models. We need to have a way to get the top K trending models. Now it seems the only way is to use a crawler to crawl the page `https://huggingface.co/models-json?sort=trending&p=1&other=text-generation-inference`, which is not very reliable and inconvenient. 

**Describe the solution you'd like**
Can we add a `sort=trending` option in this API, so that we can list all the models sorted by trending?

**Describe alternatives you've considered**

**Additional context**

**Comment by Wauplin** [comment]
Hi @weigary, yes this is already possible. The `trending` section is based on the likes received over the last 7 days. You can request them like this:

```py
from huggingface_hub import HfApi

api = HfApi()

print("id, likes, downloads")
for model in api.list_models(filter="text-generation-inference", sort="likes7d", limit=5):
    print(model.id, model.likes, model.downloads)
```
which outputs:
```
id, likes, downloads
meta-llama/Meta-Llama-3.1-8B-Instruct 1129 338803
mistralai/Mistral-Large-Instruct-2407 556 5706
meta-llama/Meta-Llama-3.1-405B 528 48455
meta-llama/Meta-Llama-3.1-8B 368 96880
meta-llama/Meta-Llama-3.1-405B-Instruct 348 17717
```

Let me know if you have any further questions, otherwise feel free to close this issue :hugs:

**Comment by weigary** [comment]
Thanks @Wauplin ! So IIUC the trending models is sorted by "likes7d"? 

Thanks a lot!

**Comment by weigary** [comment]
Hi @Wauplin in the `list_models()` API, is there a way to filter out the models with `gated=false`? I see the `ModelFilter` was deprecated recently.

**Comment by weigary** [comment]
thanks @Wauplin. Is it possible to add the additional filter (`gated`) in the `list_models` API, as a feature request?

**Comment by Wauplin** [comment]
Hi @weigary, I opened an internal ticket to track your feature request. I will let you know if and when it's implemented server-side. In the meantime, you can rely on the client-side filtering :)

**Comment by Wauplin** [comment]
Hi @weigary, happy to let you know that it's not possible to filter by "gated" status :)
I opened a new PR to integrate this to `huggingface_hub` https://github.com/huggingface/huggingface_hub/pull/2448

- Top 5 gated models: https://huggingface.co/api/models?gated=true&limit=5&expand[]=gated&sort=likes7d
- Top 5 non-gated: https://huggingface.co/api/models?gated=false&limit=5&expand[]=gated&sort=likes7d
- Top 5 gated datasets: https://huggingface.co/api/datasets?gated=true&limit=5&expand[]=gated&sort=likes7d
- Top 5 non-gated datasets: https://huggingface.co/api/datasets?gated=false&limit=5&expand[]=gated&sort=likes7d
