### ISSUE TITLE
Is there any equivlent to text_generation special tokens in Hugginface-hub InterfaceClient

### ISSUE THREAD

**Issue by hariv0** [huggingface/huggingface_hub#2436]
---

In `text_generation`, while using the `generate_stream` method, there is an option to separate special tokens from the response. 

**Example:**

```python
async for response in self.client.generate_stream(prompt=input_prompt, max_new_tokens=max_new_tokens):
    if not response.token.special:
        text_response += response.token.text
```

Is there any alternative to this in the `InferenceClient.text_generation(prompt="Sample Prompt", stream=True)` method? 

If not, are there any plans to implement its equivalent for handling special tokens in `InferenceClient.text_generation`?

---

**Comment by Wauplin** [comment]
Hi @hariv0 , yes this is possible. You must pass `details=True` to get a iterable of [`TextGenerationStreamOutput`](https://huggingface.co/docs/huggingface_hub/v0.24.5/en/package_reference/inference_types#huggingface_hub.TextGenerationStreamOutput) items:

```py
from huggingface_hub import InferenceClient


client = InferenceClient()

text_response = ""
for response in client.text_generation(prompt="The capital of France is", max_new_tokens=10, stream=True, details=True):
    if not response.token.special:
        text_response += response.token.text

print(text_response)
# a city that is full of life, culture,
```

Hope this solves your problem :)

**Comment by hariv0** [comment]
@Wauplin Thanks for the reply 😄😄
