### ISSUE TITLE
SecurityStatus missing in  hf_api.model_info()

### ISSUE THREAD

**Issue by hopenbr** [huggingface/huggingface_hub#2438]
### Describe the bug

when requesting Model info from hub api, the securityStatus dict is not being returned. 

```python
hf_api = HfApi()
model = hf_api.model_info(repo_id='mcpotato/42-eicar-street', securityStatus=True, revision='9cb322a7c2b4ec7c9f18045f0fa05015b831f256')
if hasattr(model, 'securityStatus'):
  # security status found, verify it ...
else:
  # security status not found, ... 
```

mcpotato/42-eicar-street does have security issues, early last week I was getting back a status like

```json
{'repositoryId': 'models/mcpotato/42-eicar-street',
    'revision': '9cb322a7c2b4ec7c9f18045f0fa05015b831f256',
    'hasUnsafeFile': True,
    'clamAVInfectedFiles': ['eicar_test_file'],
    'dangerousPickles': ['danger.dat'],
    'scansDone': True}
```

For the last serval days ModelInfo has not included the `SecurityStatus` even with `securityStatus=True` 

I also noticed scan results are not in the UI either lately.  

Is there an issue with the Scan results?  Can `securityStatus` be relied upon to always be present?  

### Reproduction

run code like above, and you see that model object is missing `securityStatus` attr

### System info

```shell
- huggingface_hub version: 0.23.4
- Platform: Linux-6.6.31-linuxkit-x86_64-with-glibc2.36
- Python version: 3.11.8
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/vscode/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.3.1
- Jinja2: 3.1.4
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: N/A
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 2.0.0
- pydantic: N/A
- aiohttp: 3.9.5
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /home/vscode/.cache/huggingface/hub
- HF_ASSETS_CACHE: /home/vscode/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/vscode/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by julien-c** [comment]
ping'ing @McPatate

**Comment by hopenbr** [comment]
all,
I see the security Status is back up now both in API and UI, is this a common event or schedule outage?  It seemed to be offline for 3 or 4 days.  I could not find any message or outage report either about it. 

Reason being, I am looking to write some automation to reference the security status before a model is allowed to be used.

**Comment by McPatate** [comment]
Hi @hopenbr, thank you for pinging us about this. This was an outage, I have not configured alerting on the API which caused us to assume everything was ok, my mistake.

The system is back to a nominal state, sorry for the disruption. Feel free to write your automation, I'll be setting up alerting correctly first thing in the morning to catch these issues faster next time.
