### ISSUE TITLE
add support for a version command

### ISSUE THREAD

**Issue by remyleone** [huggingface/huggingface_hub#2441]
**Is your feature request related to a problem? Please describe.**

I would like to know the version of the CLI I use using only a version command.

**Describe the solution you'd like**

```
$ huggingface-cli version
huggingface_hub version: 0.17.3
```

Or 

```
$ huggingface-cli version
0.17.3
```

**Describe alternatives you've considered**

Using `$ huggingface-cli env` but it is not as clear and straightforward to think about the environment to fetch the version of the CLI.

**Additional context**

**Comment by Wauplin** [comment]
This is indeed not already there. Community PR is very welcome :) It would consists in printing the `huggingface_hub.__version__` value.

**Comment by remyleone** [comment]
Go for it 😊

**Comment by WizKnight** [comment]
@Wauplin Hey there! 👋 I'm new to this repository and excited to learn and contribute. Please let me know if there are any good starting points or tasks where I can be of assistance. And as I can see @010kim is already working on this issue.

**Comment by Wauplin** [comment]
Hi @WizKnight :hugs: Glad to hear that! Issues labelled as https://github.com/huggingface/huggingface_hub/labels/good%20first%20issue are usually a good start when starting to contribute to a repository. Before starting anything, we have a contributing guide with some guidance to help you getting started that we recommend to read: https://github.com/huggingface/huggingface_hub/blob/dfd73c05c7777804b14e9e3cec17e38b23c52ebe/CONTRIBUTING.md.

A good first issue could be https://github.com/huggingface/huggingface_hub/issues/1172. `@dankornas` mentioned they would work on it but given it has been a few months, I think you can take it over. You can start with a first PR to update constants in [`hf_api.py`](https://github.com/huggingface/huggingface_hub/blob/411e378861ae3389bfc0388ce2cd5818f7ffbe89/src/huggingface_hub/hf_api.py). Once reviewed and merged, you'll be able to do all the other modules the same way. 

Thanks! :hugs:

**Comment by WizKnight** [comment]
@Wauplin Alright, I'm on it!

Cheers! 🤗
