### ISSUE TITLE
add support for setting scaleToZeroTimeout with create_inference_endpoint/update_inference_endpoint

### ISSUE THREAD

**Issue by hommayushi3** [huggingface/huggingface_hub#2462]
**Is your feature request related to a problem? Please describe.**
I would like to be able to programmatically set the scaleToZeroTimeout parameter in HFApi.create_inference_endpoint and HFApi.update_inference_endpoint programmatically. The only ways to do this currently are through the HF inference endpoints UI or directly through the `/v2/endpoint/{namespace}` post request.

**Describe the solution you'd like**
```python
from huggingface_hub import HfApi
api = HfApi()
endpoint = api.create_inference_endpoint(
    "aws-zephyr-7b-beta-0486",
    repository="HuggingFaceH4/zephyr-7b-beta",
    framework="pytorch",
    task="text-generation",
    accelerator="gpu",
    vendor="aws",
    region="us-east-1",
    type="protected",
    instance_size="x1",
    instance_type="nvidia-a10g",
    min_replica=0,
    max_replica=1,
    scale_to_zero_timeout=30,  # in minutes ************ REQUESTED PARAMETER **********************
    custom_image={
        "health_route": "/health",
        "env": {
            "MAX_BATCH_PREFILL_TOKENS": "2048",
            "MAX_INPUT_LENGTH": "1024",
            "MAX_TOTAL_TOKENS": "1512",
            "MODEL_ID": "/repository"
        },
        "url": "ghcr.io/huggingface/text-generation-inference:1.1.0",
    },
)
```

**Describe alternatives you've considered**
- HF inference endpoints UI
- Direct post request to `/v2/endpoint/{namespace}` endpoint

**Additional context**
- [create_inference_endpoint documentation](https://huggingface.co/docs/huggingface_hub/en/package_reference/hf_api#huggingface_hub.HfApi.create_inference_endpoint)
- [Post request open-API specification that supports setting scaleToZeroTimeout](https://api.endpoints.huggingface.cloud/#post-/v2/endpoint/-namespace-)

**Comment by Wauplin** [comment]
Thanks for the suggestion and PR @hommayushi3! I just reviewed and merged it: https://github.com/huggingface/huggingface_hub/pull/2463. Clean, concise and documented like I like :heart:
