### ISSUE TITLE
To unify `text_generation()`'s `stop_sequences` and `TextGenerationInput`'s `stop` params

### ISSUE THREAD

**Issue by sadra-barikbin** [huggingface/huggingface_hub#2471]
Hi there! 🤗

It would be great if `text_generation()`'s `stop_sequences` and `TextGenerationInput`'s `stop` params are unified just like `chat_completion` and `ChatCompletionInput` to be able to feed the input dataclasses to the client methods directly:

```python
client.text_generation(prepared_request.inputs, **prepared_request.parameters) # currently raises `TypeError: text_generation() got an unexpected keyword argument 'stop'`
# or
client.chat_completion(**prepared_request)
```

https://github.com/huggingface/huggingface_hub/blob/359093fbe4fa049aadadf08ca60a2b0fa9a39c2d/src/huggingface_hub/inference/_client.py#L1658

**Comment by sadra-barikbin** [comment]
Currently I should do this as the alternative:
```python
from dataclasses import asdict

input_as_dict = asdict(input)
input_as_dict["parameters"]["stop_sequences"] = input_as_dict["parameters"]["stop"]
del input_as_dict["parameters"]["stop"]
client.text_generation(input.inputs, **input_as_dict["parameters"])
```

**Comment by Wauplin** [comment]
Hi @sadra-barikbin, yes I definitely agree this parameter should be unified. I opened a PR to fix it :) https://github.com/huggingface/huggingface_hub/pull/2473

**Comment by sadra-barikbin** [comment]
Thanks @Wauplin ! 👍

**Comment by sadra-barikbin** [comment]
There's also a discrepancy between `ChatCompletionInput`'s `stream` param which is optional defaulting to `None` and `chat_completion()`'s `stream` param which should be either `True` or `False`. Is this OK?

https://github.com/huggingface/huggingface_hub/blob/359093fbe4fa049aadadf08ca60a2b0fa9a39c2d/src/huggingface_hub/inference/_generated/types/chat_completion.py#L123
