### ISSUE TITLE
ImportError: cannot import name 'ModelFilter' from 'huggingface_hub'

### ISSUE THREAD

**Issue by phicha20224** [huggingface/huggingface_hub#2478]
### Describe the bug

C:\Users\Username>python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from huggingface_hub import HfApi, ModelFilter, ModelSearchArguments
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ModelFilter' from 'huggingface_hub' (D:\Program Files\Python\Python310\lib\site-packages\huggingface_hub\__init__.py)

### Reproduction

C:\Users\Username>pip install --no-cache-dir transformers huggingface-hub -U
Requirement already satisfied: transformers in d:\program files\python\python310\lib\site-packages (4.25.1)
Collecting transformers
  Downloading transformers-4.44.1-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: huggingface-hub in d:\program files\python\python310\lib\site-packages (0.20.3)
Collecting huggingface-hub
  Downloading huggingface_hub-0.24.6-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: filelock in d:\program files\python\python310\lib\site-packages (from transformers) (3.15.4)
Requirement already satisfied: numpy>=1.17 in d:\program files\python\python310\lib\site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in d:\program files\python\python310\lib\site-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in d:\program files\python\python310\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in d:\program files\python\python310\lib\site-packages (from transformers) (2024.5.15)
Requirement already satisfied: requests in d:\program files\python\python310\lib\site-packages (from transformers) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in d:\program files\python\python310\lib\site-packages (from transformers) (0.4.4)
Collecting tokenizers<0.20,>=0.19 (from transformers)
  Downloading tokenizers-0.19.1-cp310-none-win_amd64.whl.metadata (6.9 kB)
Requirement already satisfied: tqdm>=4.27 in d:\program files\python\python310\lib\site-packages (from transformers) (4.66.4)
Requirement already satisfied: fsspec>=2023.5.0 in d:\program files\python\python310\lib\site-packages (from huggingface-hub) (2024.6.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\program files\python\python310\lib\site-packages (from huggingface-hub) (4.12.2)
Requirement already satisfied: colorama in d:\program files\python\python310\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\program files\python\python310\lib\site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\program files\python\python310\lib\site-packages (from requests->transformers) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\program files\python\python310\lib\site-packages (from requests->transformers) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in d:\program files\python\python310\lib\site-packages (from requests->transformers) (2024.6.2)
Downloading transformers-4.44.1-py3-none-any.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 4.3 MB/s eta 0:00:00
Downloading huggingface_hub-0.24.6-py3-none-any.whl (417 kB)
Downloading tokenizers-0.19.1-cp310-none-win_amd64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 4.5 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, tokenizers, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.20.3
    Uninstalling huggingface-hub-0.20.3:
      Successfully uninstalled huggingface-hub-0.20.3
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.13.3
    Uninstalling tokenizers-0.13.3:
      Successfully uninstalled tokenizers-0.13.3
  Attempting uninstall: transformers
    Found existing installation: transformers 4.25.1
    Uninstalling transformers-4.25.1:
      Successfully uninstalled transformers-4.25.1
Successfully installed huggingface-hub-0.24.6 tokenizers-0.19.1 transformers-4.44.1

### System info

```shell
- huggingface_hub version: 0.24.6
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.10.11
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: C:\Users\Username\.cache\huggingface\token
- Has saved token ?: False
- Configured git credential helpers:
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.3.1+cu121
- Jinja2: 3.1.4
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 10.3.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.26.4
- pydantic: 2.7.4
- aiohttp: 3.9.5
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: C:\Users\Username\.cache\huggingface\hub
- HF_ASSETS_CACHE: C:\Users\Username\.cache\huggingface\assets
- HF_TOKEN_PATH: C:\Users\Username\.cache\huggingface\token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment]
Hi @phicha20224, `ModelFilter` has been deprecated in https://github.com/huggingface/huggingface_hub/pull/2028 and removed in the last version of `huggingface_hub` (0.24.x). What you should do is pass all arguments you were passing to `ModelFilter` directly to `list_models`. 

Example:

```diff
- from huggingface_hub import list_models, ModelFilter
+ from huggingface_hub import list_models

- for model in list_models(filter=ModelFilter(library="keras")):
+ for model in list_models(library="keras"):
    # do something
    ...
```

This should simplify should code by not relying on other classes

**Comment by sinazadeh** [comment]
> Hi [@phicha20224](https://github.com/phicha20224), `ModelFilter` has been deprecated in [#2028](https://github.com/huggingface/huggingface_hub/pull/2028) and removed in the last version of `huggingface_hub` (0.24.x). What you should do is pass all arguments you were passing to `ModelFilter` directly to `list_models`.
> 
> Example:
> 
> - from huggingface_hub import list_models, ModelFilter
> + from huggingface_hub import list_models
> 
> - for model in list_models(filter=ModelFilter(library="keras")):
> + for model in list_models(library="keras"):
>     # do something
>     ...
> 
> This should simplify should code by not relying on other classes

The library seems to be deprecated as of version 0.35.1. What is the best approach to apply the library filter?
`library : str or List, optional Deprecated. Pass a library name in filter to filter models by library.`

**Comment by Wauplin** [comment]
Hey @sinazadeh , the correct solution from now on is:
```py
for model in list_models(filter="keras"):
    ...
```
