### ISSUE TITLE
Passing Secrets to the create_inference_endpoint python client 

### ISSUE THREAD

**Issue by LuisBlanche** [huggingface/huggingface_hub#2485]
I am trying to host a **private** adpater model on an inference endpoint. 
I have managed to to it manually by setting the **HF_TOKEN** as a secret from the UI. 
Now I would like to do it from the python client but while I see that I can pass environment variables to a custom Text Generation Image, I don't see how I can pass a secret. I figure if I pass the token to the env variables it would work but that would also expose the token. 

I see from the Swagger that in the API there is an option to pass secrets  :

```json
{
  "compute": {
    "accelerator": "cpu",
    "id": "string",
    "instanceSize": "large",
    "instanceType": "c6i",
    "scaling": {
      "maxReplica": 8,
      "minReplica": 2,
      "scaleToZeroTimeout": 15
    }
  },
  "model": {
    "framework": "custom",
    "image": {
      "custom": {
        "credentials": {
          "password": "string",
          "username": "string"
        },
        "env": {},
        "health_route": "/health",
        "port": 8000,
        "url": "https://host/image:tag"
      }
    },
    "repository": "openai-community/gpt2",
    "revision": "6c0e6080953db56375760c0471a8c5f2929baf11",
    "secrets": {},
    "task": "custom"
  },
  "name": "my-endpoint",
  "privateService": {
    "accountId": "123456789",
    "shared": false
  },
  "provider": {
    "region": "#/components/schemas/Region",
    "vendor": "aws"
  },
  "type": "public"
}
```

**Describe the solution you'd like**
I think just adding the `secrets` argument in the signature and the payload would work : 

https://github.com/SBrandeis/huggingface_hub/blob/ef846d759f0aee9d586ecdffaa09c49ae0807e9c/src/huggingface_hub/hf_api.py#L6551C1-L6575C10
```python
def create_inference_endpoint(
        self,
        name: str,
        *,
        repository: str,
        framework: str,
        accelerator: str,
        instance_size: str,
        instance_type: str,
        region: str,
        vendor: str,
        account_id: Optional[str] = None,
        min_replica: int = 0,
        max_replica: int = 1,
        revision: Optional[str] = None,
        task: Optional[str] = None,
        custom_image: Optional[Dict] = None,
        secrets: Optional[Dict]=None,
        type: InferenceEndpointType = InferenceEndpointType.PROTECTED,
        namespace: Optional[str] = None,
        token: Union[bool, str, None] = None,
    ) -> InferenceEndpoint:
        namespace = namespace or self._get_namespace(token=token)

        image = {"custom": custom_image} if custom_image is not None else {"huggingface": {}}
        payload: Dict = {
            "accountId": account_id,
            "compute": {
                "accelerator": accelerator,
                "instanceSize": instance_size,
                "instanceType": instance_type,
                "scaling": {
                    "maxReplica": max_replica,
                    "minReplica": min_replica,
                },
            },
            "model": {
                "framework": framework,
                "repository": repository,
                "revision": revision,
                "task": task,
                "image": image,
                "secrets": secrets
            },
            "name": name,
            "provider": {
                "region": region,
                "vendor": vendor,
            },
            "type": type,
        }
      ...
```

**Describe alternatives you've considered**
The alternative for now is to call the API directly without using the client 

**Additional context**
Tested with `huggingface_hub=0.24.6`

**Comment by Wauplin** [comment]
Good point, thanks for opening this ticket @LuisBlanche :) The solution you suggest is correct and should be the way to go. Would you like to open a PR for that? The `secrets` parameter should be added in [create_inference_endpoint](https://github.com/huggingface/huggingface_hub/blob/73ee66433d01131cc79c9de5503f774d411adf74/src/huggingface_hub/hf_api.py#L7403), [update_inference_endpoint](https://github.com/huggingface/huggingface_hub/blob/73ee66433d01131cc79c9de5503f774d411adf74/src/huggingface_hub/hf_api.py#L7611) and also in [InferenceEndpoints.update](https://github.com/huggingface/huggingface_hub/blob/73ee66433d01131cc79c9de5503f774d411adf74/src/huggingface_hub/_inference_endpoints.py#L232).

**Comment by LuisBlanche** [comment]
Yes I can handle this PR

**Comment by LuisBlanche** [comment]
I @Wauplin  I think I detected a problem in the PR that was merged : 
the default value of `secrets` being None , the API will return a 422 if no secrets are passed , so we might need to modify the code for `create_inference_edpoint` for   something like InferEndpoints.update :  
```python

if secrets is not None:
            payload["model"]["secrets"] = secrets
```

**Comment by Wauplin** [comment]
Thanks for the quick fix @LuisBlanche! This is indeed the correct way to do it :)

**Comment by Wauplin** [comment]
Closing this issue as completed by https://github.com/huggingface/huggingface_hub/pull/2486 (and https://github.com/huggingface/huggingface_hub/pull/2490). Thank you!
