### ISSUE TITLE
Need to add the `max-workers` argument to the huggingface-cli command

### ISSUE THREAD

**Issue by devymex** [huggingface/huggingface_hub#2499]
My internet speed is not good, so I can only accept single-threading. The default 8 threads downloading simultaneously is too much, causing frequent interruptions and download failures.

Adding this feature is very simple, you just need to modify download.py.  I will submit a pull request containing the necessary improvements.

**Comment by Wauplin** [comment]
Makes total sense yes! Closed by https://github.com/huggingface/huggingface_hub/pull/2500, thanks again for the contribution :hugs:
