### ISSUE TITLE
TODO: remove this once https://github.com/huggingface/safetensors/pull/449 is merged.

### ISSUE THREAD

**Issue by yuxi-liu-wired** [huggingface/huggingface_hub#2516]
<https://github.com/huggingface/huggingface_hub/blob/23bab6a3fdb11bcdf3424f79fbe245ed4b9256ef/src/huggingface_hub/hub_mixin.py#L833C1-L834C1>

says

```
# TODO: remove this once https://github.com/huggingface/safetensors/pull/449 is merged.
```

<https://github.com/huggingface/safetensors/pull/449> has been merged.

**Comment by Wauplin** [comment]
Closed by https://github.com/huggingface/huggingface_hub/pull/2532
