### ISSUE TITLE
How can I rename folders in given repo? I need to rename folders 

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/huggingface_hub#2526]
### Describe the bug

I am try to rename like below but it fails :/

```
from huggingface_hub import HfApi
import os

# Initialize the Hugging Face API
api = HfApi()

# Set the repository name
repo_name = "MonsterMMORPG/3D-Cartoon-Style-FLUX"

# Define the folder renaming mappings
folder_renames = {
    "Training-Checkpoints-NO-Captions": "Training-Checkpoints-Inconsistent-DATASET-NO-Captions",
    "Training-Checkpoints-With-Captions": "Training-Checkpoints-Inconsistent-DATASET-With-Captions"
}

# Function to rename folders
def rename_folder(repo_name, old_name, new_name):
    try:
        api.move_folder(
            repo_id=repo_name,
            path_in_repo=old_name,
            new_path=new_name,
            commit_message=f"Rename folder '{old_name}' to '{new_name}'"
        )
        print(f"Successfully renamed '{old_name}' to '{new_name}'")
    except Exception as e:
        print(f"Error renaming '{old_name}' to '{new_name}': {str(e)}")

# Iterate through the folder renaming mappings and rename each folder
for old_name, new_name in folder_renames.items():
    rename_folder(repo_name, old_name, new_name)

print("Folder renaming process completed.")
```

### System info

```shell
latest
```

**Comment by hanouticelina** [comment]
Hi @FurkanGozukara, `rename_folder()` is not implemented in HfApi, instead, we recommend using copy + delete operations to move files from a folder to another. 
You can use : [`huggingface_hub.CommitOperationCopy`](https://huggingface.co/docs/huggingface_hub/package_reference/hf_api#huggingface_hub.CommitOperationCopy) and  [`huggingface_hub.CommitOperationDelete`](https://huggingface.co/docs/huggingface_hub/package_reference/hf_api#huggingface_hub.CommitOperationDelete)

**Comment by hanouticelina** [comment]
I'm closing this issue but feel free to comment if you have any other question related to this and I'll be glad to reopen

**Comment by FurkanGozukara** [comment]
> Hi @FurkanGozukara, `rename_folder()` is not implemented in HfApi, instead, we recommend using copy + delete operations to move files from a folder to another. You can use : [`huggingface_hub.CommitOperationCopy`](https://huggingface.co/docs/huggingface_hub/package_reference/hf_api#huggingface_hub.CommitOperationCopy) and [`huggingface_hub.CommitOperationDelete`](https://huggingface.co/docs/huggingface_hub/package_reference/hf_api#huggingface_hub.CommitOperationDelete)

thank you. on the browser interface i can rename files but no option for folders. do you think about it?

**Comment by Wauplin** [comment]
This is not necessarily something we want to do no. Renaming an entire folder cannot be done in a single commit if the folder is too big. So such a feature couldn't be atomic, making it difficult to implement in a generic way (also, what should we do if an error occurs while renaming a huge folder and we end up with a half-renamed folder?). So for simplicity we won't provide such a feature but provide tools for users to create it themselves.
