### ISSUE TITLE
Why uploading single part file doesn't take with header

### ISSUE THREAD

**Issue by koryyang** [huggingface/huggingface_hub#2533]
https://github.com/huggingface/huggingface_hub/blob/3395e637d4f1ba1dca665d3cf42e41e3637faa67/src/huggingface_hub/lfs.py#L248

I notice that while uploading lfs file to hub, if the chunk size is null, it means uploading single part, but it doesn't take with headers. If uploading multi part, it takes with header（line 246）. Why there is such a difference

**Comment by Wauplin** [comment]
Hi @koryyang, are you facing any problem regarding this or is it simply out of curiosity? For multipart upload, the headers are needed to retrieve the upload_url for each part (see [here](https://github.com/huggingface/huggingface_hub/blob/1462151a794b297cc43eebd35cd38bb902f42e3d/src/huggingface_hub/lfs.py#L328)).

**Comment by koryyang** [comment]
Hi. I am developing my private huggingface repository server, so I need to resolve how the client interact with server. I thought the previous response server send to client could include "Authorization" header . But when I debug this process, I found this issue that client doesn't carry the headers so failed to authenticate

**Comment by Wauplin** [comment]
This is because the urls to upload files are S3 signed URLs. This means we don't want to forward the HF `Authorization` headers since that would leak the HF tokens to AWS. The signed URLs are temporary S3 urls that are authenticated (given the url parameters).
