### ISSUE TITLE
Add `num_following` and `num_followers` to `User` returned by `get_user_overview`

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#2535]
Follow-up after server-side update (https://github.com/huggingface-internal/moon-landing/pull/11107, internal).

Route `/api/users/{username}/overview` now returns two news attributes `numFollowing` and `numFollowers`. It would be nice to support them officially client-side. It would avoid to have to iterate over all followers to count them (currently using `list_user_following`/`list_user_followers`).

In practice, it means updating `User` class + add a test.

**Comment by Amrit02102004** [comment]
I will try doing it 
Can I get assigned this issue

**Comment by Wauplin** [comment]
Hi @Amrit02102004, thanks for proposing yourself! I just assigned you the task. Let me know if you need anything :hugs:

**Comment by Amrit02102004** [comment]
![image](https://github.com/user-attachments/assets/6853f149-bfff-4e95-8e42-9558f8c3f670)
![image](https://github.com/user-attachments/assets/f5a00b59-4942-4c46-b8a1-44863744d35f)


Hey I have made the changes here is it okay or should I add something else?

Thanks

**Comment by Wauplin** [comment]
Hey @Amrit02102004, this is good yes. In addition to that, you'll need to update `User`'s `__init__` method to populate the 2 new fields + add them to the docstring. Apart from that, I think it should be good. Could you open a PR to make the proper review easier? :)

**Comment by Amrit02102004** [comment]
I have successfully opened a PR 
https://github.com/huggingface/huggingface_hub/pull/2536
