### ISSUE TITLE
Feature: switch visibility with `update_repo_settings`

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#2537]
Follow-up PR after https://github.com/huggingface/huggingface_hub/pull/2502.

Now that we have a generic `update_repo_settings`, we can add the option to switch visibility status of a repo. This would be a drop-in replacement for `update_repo_visibility`:

```diff
- update_repo_visibility(repo_id, private=True)
+ update_repo_settings(repo_id, private=True)
```

TODO:
- add a `private` attribute to `update_repo_settings`
- make both `gated` and `private` attributes optional (default to None)
- check `update_repo_settings` inputs => either `gated` is passed, or `private`, or both. If both gated and private are None, raise a ValueError.
- add `gated` and `private` to the request payload only if not None
- update `update_repo_settings` docstring
- update all references of `update_repo_visibility` in docs
- add `@_deprecate_method` decorator to `update_repo_visibility` (will be removed in 0.29.x)

**Comment by WizKnight** [comment]
Hey @Wauplin :), I'd be happy to take on this PR!😊
