### ISSUE TITLE
fs.exists(hub_model_id, refresh=True) does not work correctly after deleting a repository

### ISSUE THREAD

**Issue by MoritzLaurer** [huggingface/huggingface_hub#2552]
### Describe the bug

The following code outputs "True" twice, even though the repo is deleted. See this [ internal thread](https://huggingface.slack.com/archives/C02V5EA0A95/p1726667186598329) for details. 

### Reproduction

```py
from huggingface_hub import HfApi, HfFileSystem
import time

api = HfApi()
hfs = HfFileSystem()
hub_model_id = "MoritzLaurer/test-repo"

api.create_repo(hub_model_id, repo_type='model')
print(hfs.exists(hub_model_id, refresh=True))
time.sleep(5)
api.delete_repo(repo_id=hub_model_id, repo_type="model")
time.sleep(5)
print(hfs.exists(hub_model_id, refresh=True))
# output True, True
```

### System info

```shell
huggingfac_hub==0.25.0
```

**Comment by MoritzLaurer** [comment]
In case someone finds this issue later: the current recommended approach is using `api.repo_exists` instead of `hfs.exists`. `HfApi` is generally more used and better maintained than `HfFileSystem` so we recommend checking the docs for [HfApi](https://huggingface.co/docs/huggingface_hub/package_reference/hf_api) first. 

This works correctly: 
```py
from huggingface_hub import HfApi, HfFileSystem
import time

api = HfApi()
hfs = HfFileSystem()
hub_model_id = "MoritzLaurer/test-repo"

api.create_repo(hub_model_id, repo_type='model')
print(api.repo_exists(repo_id=hub_model_id))
time.sleep(5)
api.delete_repo(repo_id=hub_model_id, repo_type="model")
time.sleep(5)
print(api.repo_exists(repo_id=hub_model_id))
```

**Comment by Wauplin** [comment]
Thanks for reporting @MoritzLaurer. This is indeed a bug in `HfFileSystem` implementation (not correctly refreshing the cache in this case). 
@hanouticelina would you like to have a look when you have some time? (not urgent). It'll require to dive a bit in the fsspec internals.
