### ISSUE TITLE
Raise root error when tring to login and permission denied

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#2565]
in [_login.py](https://github.com/huggingface/huggingface_hub/blob/12ec449b2346cb115a23bd1628aeac4dae5014bd/src/huggingface_hub/_login.py#L305) we check if a new token provided by the user is valid. The logic is:

```py
    permission = get_token_permission(token)
    if permission is None:
        raise ValueError("Invalid token passed!")
```

with `get_token_permission` been:

```py
        try:
            return self.whoami(token=token)["auth"]["accessToken"]["role"]
        except (LocalTokenNotFoundError, HTTPError):
            return None
```

We should update this to something like 

```py
# disclaimer: untested
        try:
            permission = whoami(token=token)["auth"]["accessToken"]["role"]
        except HTTPError as e:
            raise ValueError("Invalid token passed!") from e
```

We should still keep `get_token_permission` used. This way when the token is invalid, the user might get more info from the server about the root cause.

**Comment by Wauplin** [comment]
(related to internal slack [thread](https://huggingface.slack.com/archives/C02EMARJ65P/p1727219898351269) -private- where we cannot investigate further a bug)

**Comment by WizKnight** [comment]
Hey @Wauplin :),
I'd love to take over this issue if that's okay with you!
Let me know if you'd like me to get started or if there's anything specific I should keep in mind.

Thanks!

**Comment by Wauplin** [comment]
Hi @WizKnight, thanks for proposing yourself again :) Please go ahead. I'm not sure there is anything else to think about except what I mentioned in the PR description. Let me know if you have any question

**Comment by Amrit02102004** [comment]
Can I handle this issue if its not fixed yet ?

**Comment by hanouticelina** [comment]
Hi @Amrit02102004, thanks for proposing your help! 🤗 Actually, @WizKnight is on it and a PR is already open #2575.

**Comment by Amrit02102004** [comment]
> Hi @Amrit02102004, thanks for proposing your help! 🤗 Actually, @WizKnight is on it and a PR is already open #2575.

Okay Thanks

**Comment by hanouticelina** [comment]
closing this issue as completed by #2549
