### ISSUE TITLE
defog/sqlcoder-70b-alpha autotokenizer error

### ISSUE THREAD

**Issue by KevinZhang0120** [huggingface/huggingface_hub#2568]
### Describe the bug

Running autotokenizer on defog/sqlcoder-70b-alpha getting error that never happened before (Llama model works fine):

- ReadTimeout: (ReadTimeoutError("HTTPSConnectionPool(host='cdn-lfs-us-1.hf.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 835293f3-08b9-4ec4-bbf1-4f9d8c1eaf61)')

### Reproduction

from transformers import AutoTokenizer

model_id = "defog/sqlcoder-70b-alpha"
model_id = "meta-llama/Llama-3.1-8B"

# Load the tokenizer for the specified model.
tokenizer = AutoTokenizer.from_pretrained(model_id, padding_side = "right")

### System info

```shell
- huggingface_hub version: 0.25.1
- Platform: Linux-5.15.0-1069-aws-x86_64-with-glibc2.35
- Python version: 3.10.12
- Running in iPython ?: Yes
- iPython shell: DatabricksShell
- Running in notebook ?: Yes
- Running in Google Colab ?: No
- Running in Google Colab Enterprise ?: No
- Token path ?: /root/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: kevinzhang120
- Configured git credential helpers: cache
- FastAI: N/A
- Tensorflow: 2.14.1
- Torch: 2.0.1+cu118
- Jinja2: 3.1.2
- Graphviz: N/A
- keras: 2.14.0
- Pydot: N/A
- Pillow: 9.4.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.23.5
- pydantic: 1.10.6
- aiohttp: 3.9.1
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /root/.cache/huggingface/hub
- HF_ASSETS_CACHE: /root/.cache/huggingface/assets
- HF_TOKEN_PATH: /root/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment]
Hi @KevinZhang0120, sorry for the inconvenience. It looks like your machine took more than 10s to connect to network. This is usually a transient error but if it happens again, you can set the `HF_HUB_ETAG_TIMEOUT` and `HF_HUB_DOWNLOAD_TIMEOUT` with higher values (default to 10s each). See [reference](https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfhubetagtimeout) for more details.
