### ISSUE TITLE
snapshot_download doesn't download files but also doesn't give any error message

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/huggingface_hub#2576]
### Describe the bug

This happened on one of my followers computer

I suspect that his antivirus / windows defender blocked files to be downloaded

However on CMD, there isn't any error and files are not downlaoded

Are there any way to force snapshot_download to download or display error message at least?

Here used code on latest huggingface_hub

local_dir  exists manually downloading into there from repo fixed the issue

Happened on Windows  11 python 3.10.11

```
import os
from huggingface_hub import snapshot_download

# Define the local directory where the snapshot will be downloaded
local_dir = "facefusion/venv/Lib/site-packages/onnxruntime/capi"

# Get the absolute path of the local directory
absolute_path = os.path.abspath(local_dir)

snapshot_download(repo_id="MonsterMMORPG/94_CUDA_Fix", local_dir=local_dir)
```

**Comment by FurkanGozukara** [comment]
@Wauplin any chance to force this? lets say file downloaded but antivirus deleted. can it redownload in that case? because i connected his pc and this wasnt the case

snapshot_download wasnt doing anything and was not displaying anything even though files were missing

can i force it to check files exists or not?

**Comment by Wauplin** [comment]
You can pass `force_download=True` to `snapshot_download` yes
