### ISSUE TITLE
What is the highest Python version currently supported?

### ISSUE THREAD

**Issue by tanbw** [huggingface/huggingface_hub#2578]
### Describe the bug

I utilized Hugging Face Spaces to construct my application, which was built using Gradio, zerogpuspace, and the link is: https://huggingface.co/spaces/tanbw/CosyVoice
In the readme.md, I specified the Python version as 3.8.9, but the version of Python that the application prints out is still 3.1. What is the highest Python version currently supported?
![image](https://github.com/user-attachments/assets/3a6e426c-2cef-485e-b1b7-8a6edab1cd65)

![image](https://github.com/user-attachments/assets/0afc1e2a-8014-4130-9426-1effeebbfbfa)

![image](https://github.com/user-attachments/assets/9731452b-5535-450e-9ece-32741216ca79)

### System info

```shell
- huggingface_hub version: 0.24.5
- Platform: Linux-5.10.223-211.872.amzn2.x86_64-x86_64-with-glibc2.36
- Python version: 3.10.13
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/user/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: store
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.0.1
- Jinja2: 3.1.4
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 10.4.0
- hf_transfer: 0.1.8
- gradio: 4.44.0
- tensorboard: N/A
- numpy: 1.26.4
- pydantic: 2.7.0
- aiohttp: 3.10.0
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /home/user/.cache/huggingface/hub
- HF_ASSETS_CACHE: /home/user/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/user/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: True
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment]
Hi @tanbw, the `huggingface_hub` is supported on Python 3.8, 3.9, 3.10 and 3.11 as mentioned in the README header: https://github.com/huggingface/huggingface_hub/blob/main/README.md.
