### ISSUE TITLE
429 when uploading many files

### ISSUE THREAD

**Issue by fakerybakery** [huggingface/huggingface_hub#2587]
### Describe the bug

Hi,
I'm using the experimental `upload-large-folder` feature. I'm trying to upload ~2000 files, but I'm running into a 429 error. Would it be possible to increase the rate limit when using the `upload-large-folder` feature?
Thanks!

### System info

```shell
- huggingface_hub version: 0.25.1
- Python version: 3.12.5
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Running in Google Colab Enterprise ?: No
- Has saved token ?: True
- Configured git credential helpers: store
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.4.1
- Jinja2: 3.1.4
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 10.4.0
- hf_transfer: 0.1.8
- gradio: N/A
- tensorboard: N/A
- numpy: 1.26.4
- pydantic: N/A
- aiohttp: 3.10.8
- ENDPOINT: https://huggingface.co
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by hanouticelina** [comment]
Hi @fakerybakery! sorry you ran into this issue. to help us better understand the problem, could you please provide the traceback of the error and the printed report of `upload_large_folder` as well to have more details about the number of files uploaded before hitting the 429 error, their sizes and the number of commits generated. thanks!

**Comment by fakerybakery** [comment]
Hi,
I'm getting this error:
```
Failed to commit: 429 Client Error: Too Many Requests for url: https://huggingface.co/api/datasets/username/repo/commit/main (Request ID: Root=...)

You have been rate-limited; you can retry this action in about 1 hour. If you're a new user, your limits will raise progressively over time. Get in touch with us at website@huggingface.co if you need access now.
```

**Comment by hanouticelina** [comment]
Hi @fakerybakery, we had an incident yesterday on our side that required temporarily reducing our rate limits. However, it has been fixed since then and rate limits have been restored to normal. 
I'm closing this issue but don't hesitate to comment if you're still encountering this problem 🙂

**Comment by fakerybakery** [comment]
Hi,
Thanks for the information. I've been getting this issue for a while, was this incident just yesterday or for the past couple weeks?
Thanks!

**Comment by fakerybakery** [comment]
Hi,
I was trying to upload a large folder (~150k files) again and got the same error.

**Comment by hanouticelina** [comment]
Hi @fakerybakery, you've hit the hard limit of numbers of files per repo. In the repo size recommendations,(https://huggingface.co/docs/hub/repositories-recommendations) we set the limit to 100k files per repo. 
What is the file format you're working with? It would help to know if you can group these files together to reduce the total count.
