### ISSUE TITLE
Revisions are not automatically created remotely with upload_large_folder

### ISSUE THREAD

**Issue by BramVanroy** [huggingface/huggingface_hub#2602]
### Describe the bug

It seems that when a revision is passed to upload_large_folder, a new branch is not constructed if that revision does not exist, leading to an error (see below). This seems different from `upload_folder`, as per the note in the [docs](https://huggingface.co/docs/datasets/main/en/share#upload-to-a-specific-revision):

> if revision does not exist and --create-pr is not set, a branch will be created automatically from the main branch.

### Reproduction

```python
from huggingface_hub import upload_large_folder

hf_repo = "Your/Repo"
local_path = "your/local/path/"
revision = "this-is-a-revision"

upload_large_folder(
    repo_id=hf_repo, folder_path=local_path, revision=revision, repo_type="dataset"
)
```

### Logs

```shell
Revision Not Found for url: https://huggingface.co/api/datasets/BramVanroy/[my-dataset]/preupload/mh_dedup.
Invalid rev id: mh_dedup
Failed to get upload mode: 404 Client Error. (Request ID: Root=1-670baeb2-07e18cac6ae4d42c56806cd8;0b138bad-fd8d-4dcb-ade6-6daf1bc0408d)
```

### System info

```shell
- huggingface_hub version: 0.25.2
- Platform: Linux-4.18.0-477.43.1.el8_8.x86_64-x86_64-with-glibc2.28
- Python version: 3.11.5
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Running in Google Colab Enterprise ?: No
- Token path ?: /dodrio/scratch/projects/2023_071/cache/huggingface/token
- Has saved token ?: True
- Who am I ?: BramVanroy
- Configured git credential helpers: store
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.4.1
- Jinja2: 3.1.4
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: N/A
- hf_transfer: 0.1.8
- gradio: N/A
- tensorboard: N/A
- numpy: 1.26.4
- pydantic: 2.9.2
- aiohttp: 3.10.10
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /dodrio/scratch/projects/2023_071/cache/huggingface/hub
- HF_ASSETS_CACHE: /dodrio/scratch/projects/2023_071/cache/huggingface/assets
- HF_TOKEN_PATH: /dodrio/scratch/projects/2023_071/cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: True
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by hanouticelina** [comment]
Hi @BramVanroy 👋 
`upload_large_folder` does not create a new `revision` when the specified revision does not exist, the method requires the target branch `revision` to exist beforehand. 
The method is mainly designed to upload **large** folders efficiently and is more limited than`upload_folder` feature-wise. If you need to upload to a new branch, you will have to create a PR first (from the UI or using `create_pull_request`) and then commit to it by passing `revision`.

**Comment by Wauplin** [comment]
Note: for "real" branches (not just PRs), you can use `create_branch` before uploading. 
(aligned on the fact that this is a more power user tool that has on purpose a more limited scope)

**Comment by BramVanroy** [comment]
Right, but would it not make sense to do that automatically, as with upload_folder?

**Comment by Wauplin** [comment]
Well, `upload_folder` doesn't create a branch by default either. 
The docs you referred to in the PR description comes from the `datasets` library and they refer only to the `huggingface-cli upload` CLI -which is slightly different from just calling `upload_folder`-.

We could add it but we would really prefer to make this command "upload-only". Since it creates several commits and we want it to be resumable, we preferred not to add features related to branches/PRs except been able to push to a `revision`. I don't say it's impossible to do, just that we prefer not to do it.
