### ISSUE TITLE
Option to get security status with `hf_api`

### ISSUE THREAD

**Issue by suzukimain** [huggingface/huggingface_hub#2649]
**Is your feature request related to a problem? Please describe.**
There is no option to get `securityStatus` in `list_models`

**Describe the solution you'd like**
I would like to request an option in `list_models` like `securityStatus` in `model_info`

**Describe alternatives you've considered**
After getting the repo id in `list_models`, I get it in `securityStatus` of `model_info`

**Additional context**
I am thinking of making a feature request to the [api-inference-community](https://github.com/huggingface/api-inference-community) as well, if necessary.

**Comment by Wauplin** [comment]
Hi @suzukimain, the `securityStatus` field has been removed in favor of `security_repo_status`. The change has been made server side so you won't be able to fetch it the old way. However you can already get the new format in `list_models` thanks to https://github.com/huggingface/huggingface_hub/pull/2639 (not released yet, you must [install from source](https://huggingface.co/docs/huggingface_hub/installation#install-from-source)).

**Comment by suzukimain** [comment]
> Hi @suzukimain, the `securityStatus` field has been removed in favor of `security_repo_status`. The change has been made server side so you won't be able to fetch it the old way. However you can already get the new format in `list_models` thanks to #2639. If you upgrade to `v0.26.2`, you'll get it. See [#2638 (comment)](https://github.com/huggingface/huggingface_hub/issues/2638#issuecomment-2441834659).

I'm sorry, my previous explanation was insufficient. The feature I want to request is an option to directly obtain `security_repo_status` from `list_models`, as shown in the following code. Currently, the default value None is returned, but I would like to have `security_repo_status` included and returned.


```python
from huggingface_hub import HfApi

hf_api = HfApi()
hf_info = list(hf_api.list_models(filter="google"))

model_info = hf_info[0].__dict__

security_repo_status = model_info["security_repo_status"]

print(f"security_repo_status: {security_repo_status}")
print(f"keys: {model_info.keys()}")

# security_repo_status: None
# keys: dict_keys(['id', 'author', 'sha', 'last_modified', 'created_at', 'private', 'gated', 'disabled', 'downloads', 'downloads_all_time', 'likes', 'library_name', 'gguf', 'inference', 'tags', 'pipeline_tag', 'mask_token', 'trending_score', 'card_data', 'widget_data', 'model_index', 'config', 'transformers_info', 'siblings', 'spaces', 'safetensors', 'security_repo_status', 'lastModified', 'cardData', 'transformersInfo', '_id', 'modelId'])
```

**Comment by Wauplin** [comment]
In https://github.com/huggingface/huggingface_hub/issues/2638#issuecomment-2441834659 @hanouticelina showed how to leverage the `securityStatus=True` parameter to ask the server to return the security info. Have you tried it?

**Comment by hanouticelina** [comment]
@Wauplin I think the issue pointed here is that the endpoint `/api/models` doesn't include the security status of the listed repos, the info is not included even with`?full=true`. However, the individual model endpoint info `/api/models/{model_id}` includes security status when requested with `?securityStatus=true`. i guess we should look into this on the server side.

@suzukimain For now, you can work around this by iterating through the list of models and call `HfApi().model_info("your_model_id",securityStatus=True)` for each model. While we know this is definitely not optimal, we've noted your feature request, thanks a lot! 🤗 we will get back to you as soon as we have a better solution.

**Comment by hanouticelina** [comment]
Hi @suzukimain, the backend team confirmed that including `security_repo_status` directly in the `/api/models` response isn’t feasible at this time, unfortunately. since this field is retrieved on-demand rather than stored in a database, adding it would significantly slow down the API and likely trigger rate limiting when requested in bulk.

The recommendation is to retrieve this information on a case-by-case basis by querying model info individually:
```python
from huggingface_hub import HfApi
api = HfApi()
api.model_info("your_model_id", securityStatus=True)
```

thanks a lot for your understanding! I will close this issue but don't hesitate to comment or open a new one if you have any other question or feature request 🤗
