### ISSUE TITLE
Suggest to use `upload_large_folder` when using `upload_folder` with folders containing many files

### ISSUE THREAD

**Issue by yoinked-h** [huggingface/huggingface_hub#2650]
**Is your feature request related to a problem? Please describe.**
I had an upload that took 40 min to fail (some windows driver messed up, not in scope for this issue); then, while reading the docs, saw the magical function `upload_large_folder`, with *restartability*, and even *multiple workers*! I thought "surely this just takes a bit faster" and swapped the original `upload_folder` function with it. In less than 30 minutes the entire 35GB folder had been uploaded onto HF, with no critical errors. This function is black magic (the good kind).

**Describe the solution you'd like**
If a folder is being uploaded that has over 100 files, or is onto a dataset, put a message/warning reading something alike `WARNING: upload_folder cannot be restarted without losing progress and has a single worker by default. Only use this for small amounts of data.`, actual message can be changed.

**Describe alternatives you've considered**
Modify the docs for `upload_folder` to *heavily* suggest the alternative function.

**Additional context**
N/A

**Comment by julien-c** [comment]
> This function is black magic (the good kind).

😁

**Comment by Wauplin** [comment]
Glad you liked this black magic! Hope we don't use it too much :grin: 

Regarding your suggestion, this is exactly what we did in https://github.com/huggingface/huggingface_hub/pull/2547. In theory it should be triggered on any upload_folder larger than 30 new files. The message is logged at the `INFO` level as we don't want to "warn" the user (there is nothing wrong in uploading 50 files with `upload_folder`). When you use `huggingface-cli upload`, the default log level is `INFO` so the users see the suggestion to use `huggingface-cli upload-large-folder`. However if you're using `upload_folder` in a script you'll most probably miss the suggestion. Was this your case? I think it's fine to keep it as it is now but feel free to let us know if you have another suggestion.

**Comment by yoinked-h** [comment]
> [...] However if you're using `upload_folder` in a script you'll most probably miss the suggestion. Was this your case? I think it's fine to keep it as it is now but feel free to let us know if you have another suggestion.

Yes, the original usage was in a notebook, and as for suggestion, maybe increase it from "info" to "warn" after 300 files, since as you pointed out, 50 files seems reasonable, but I feel like 300 should be enough to inform the user.
