### ISSUE TITLE
`max_tokens`'s default in docstring of `InferenceClient::chat_completion`'s  is 20 but that of TGI is 100

### ISSUE THREAD

**Issue by sadra-barikbin** [huggingface/huggingface_hub#2652]
Hi there!🤗

`InferenceClient::chat_completion`'s docstring states that `max_tokens`'s default value is `20` but it seems that of the TGI is `100`.

https://github.com/huggingface/huggingface_hub/blob/8a99deb4e1c2c70ed180d4429e9da48902cd39bf/src/huggingface_hub/inference/_client.py#L586-L587

https://github.com/huggingface/text-generation-inference/blob/6e3220529df5906ae586031873b7865e9923040b/router/src/lib.rs#L939

**Comment by hanouticelina** [comment]
Hello @sadra-barikbin , thanks a lot for reporting this! 🤗 I just opened a PR #2653 to fix the docstrings.
