### ISSUE TITLE
snapshot_download download speeds are not shown on Kaggle and on some other platforms

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/huggingface_hub#2662]
### Describe the bug

I download models like this e.g. case

`!export HF_HUB_ENABLE_HF_TRANSFER=1`

```
snapshot_download(
    repo_id="myrepo/repoid",
    allow_patterns=["flux_dev_fp8_scaled_diffusion_model.safetensors"],
    local_dir=f"{base_path}/Stable-Diffusion"
)
```

The outputs are like this, not only on Kaggle but also on some other platforms as well

Can this be fixed? zero info is displayed during the download

**The download works but we can't see speed or the progress - not even after fully downloaded** 

![image](https://github.com/user-attachments/assets/69e204b2-0526-4104-932a-885f3cccb528)

![image](https://github.com/user-attachments/assets/f41d27d3-123b-42f5-8ef4-b90f813cfc4d)

### System info

```shell
Copy-and-paste the text below in your GitHub issue.

- huggingface_hub version: 0.25.1
- Platform: Linux-5.15.154+-x86_64-with-glibc2.35
- Python version: 3.10.14
- Running in iPython ?: Yes
- iPython shell: ZMQInteractiveShell
- Running in notebook ?: Yes
- Running in Google Colab ?: No
- Running in Google Colab Enterprise ?: No
- Token path ?: /root/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: 
- FastAI: 2.7.17
- Tensorflow: 2.16.1
- Torch: 2.4.0
- Jinja2: 3.1.4
- Graphviz: 0.20.3
- keras: 3.3.3
- Pydot: 1.4.2
- Pillow: 10.4.0
- hf_transfer: 0.1.8
- gradio: N/A
- tensorboard: 2.6.2.2
- numpy: 1.26.4
- pydantic: 2.9.2
- aiohttp: 3.9.5
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /root/.cache/huggingface/hub
- HF_ASSETS_CACHE: /root/.cache/huggingface/assets
- HF_TOKEN_PATH: /root/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10


```

**Comment by Wauplin** [comment]
Hmm, thanks for reporting. That seems quite a specific issue :confused: As mentioned [in the docs](https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfhubenablehftransfer), hf_transfer is a power-user tool that is not necessarily well-polished to be user-friendly. Can't tell why specifically on Kaggle the progress bar doesn't work but not sure we will spent much time investigating it.
Progress bars are working locally, on Colab and in Spaces which are the main use cases for `huggingface_hub`+`hf_transfer`.
