### ISSUE TITLE
Enable branch to be specified in `Repository.push_to_hub`

### ISSUE THREAD

**Issue by lewtun** [huggingface/huggingface_hub#268]
As a user, I would like to be able to push my repo's files to a specific branch on the Hub, e.g.

```python
my_repo = Repository(...)

# create some local files, e.g. save a model

my_repo.push_to_hub(commit_message="I love Git!", branch="my-awesome-branch")
```

This would be quite useful for the evaluation / benchmarking projects where the current idea (due to @lhoestq) is to store the model predictions for task X in a separate branch on a single repo. (We store the predictions for reproducibility purposes)

I'm not sure if `Repository.push_to_hub` is the right entry point for this feature or whether it makes sense to have something like `Repository.git_checkout` 

cc @SBrandeis @thomwolf @abhishekkrthakur

**Comment by osanseviero** [comment]
(Not a direct solution, but `HfApi.upload_file` already allows for an optional `revision` param which can be a branch iirc).

cc @LysandreJik probably has some good ideas about this.

**Comment by LysandreJik** [comment]
Having a `revision` option on the `push_to_hub` method sounds good to me. Feel free to open a PR @lewtun, otherwise, I'll take a stab at it in a bit.

**Comment by osanseviero** [comment]
Do you think that the constructor should also support something like this (be it optional `revision` parameter or allowing to have the revision in the url of `clone_from`)? That way if your workflow is in a branch you can do this without much issues.

I'm also not sure `revision` should be the option for `push_to_hub`, no? I think it should be something like `branch`, but I'm not completely sure.

**Comment by LysandreJik** [comment]
cc @lvwerra with whom we have had a similar conversation

**Comment by LysandreJik** [comment]
> Do you think that the constructor should also support something like this (be it optional revision parameter or allowing to have the revision in the url of clone_from)? That way if your workflow is in a branch you can do this without much issues.

You mean something like the following:

```py
from huggingface_hub import Repository

repo = Repository("xxx", clone_from="xxx/yyy", revision="zzz")
# or
repo = Repository("xxx", clone_from="xxx/yyy@zzz")
```

This would essentially be a clone + checkout, or did you envision it a different way?

**Comment by osanseviero** [comment]
Yes, those two options are exactly what I meant (I would go with the second option to avoid having too many parameters and enabling this in downstream libraries). This would enable users that work just in a single, non-main branch. The `revision` param in `push_to_hub` will also be needed for those users that want to clone from a branch (normally main) but push to another.
 
I think it could be either clone+checkout and ensure this points to the right branch or `git clone --branch`.

**Comment by lewtun** [comment]
> Having a `revision` option on the `push_to_hub` method sounds good to me. Feel free to open a PR @lewtun, otherwise, I'll take a stab at it in a bit.

I’m on vacation for the next two weeks, but happy to pick this up when I’m back if you don’t beat me to it 😎

**Comment by LysandreJik** [comment]
I'm taking care of it in the [branch-push-to-hub](https://github.com/huggingface/huggingface_hub/tree/branch-push-to-hub) branch!

**Comment by LysandreJik** [comment]
Opened PR: https://github.com/huggingface/huggingface_hub/pull/276
