### ISSUE TITLE
Enormous repository storage overusage

### ISSUE THREAD

**Issue by umarbutler** [huggingface/huggingface_hub#2700]
### Describe the bug

My Hugging Face account reports that I'm using 405 GB of my 500 GB storage allowance.
![image](https://github.com/user-attachments/assets/6dc163ca-5971-4bc7-aa2a-d07f9030ad31)

I suspect this is because I manage the [Open Australian Legal Corpus](https://huggingface.co/datasets/umarbutler/open-australian-legal-corpus). It is only 10 GB but I think all the previous verisons of the Corpus are being stored and taking up space.

Respectfully, I'd like to understand why one should be required to pay a subscription in order to share my Corpus with the rest of Hugging Face, thereby driving traffic to your service (it is downloaded 785 times a month).

If it looks like maintaining my Corpus by releasing new versions is going to permanently increase my storage then I am incentivized to take down my Corpus from Hugging Face :(

### System info

```shell
N/A
```

**Comment by Wauplin** [comment]
Hi @umarbutler, sorry for the misunderstanding that topic lately. We'll share some updates soon but rest assured that we'll always encourage people to share models and datasets publicly for free on the Hub :hugs:

**Comment by umarbutler** [comment]
> Hi @umarbutler, sorry for the misunderstanding that topic lately. We'll share some updates shortly but rest assured that we'll always encourage people to share models and datasets publicly for free on the Hub 🤗

Thank you :) I cross-posted to the forum and discovered the limits are not actually enforced and that you'll be sharing updates shortly.

**Might I suggest,** you could impose limits only on private repositories and models. In doing so you, would you continue to incentivize your users to share as much as they want (I know its possible to request additional storage but making people make such requests is going to lock off a bunch of people who might be skeptical about it working / might not want to wait to upload and will just go look elsewhere), and at the same time, you would be able to manage overusage of your services.

**Comment by Wauplin** [comment]
> Might I suggest, you could impose limits only on private repositories and models.

This is indeed the direction we are moving towards.

**Comment by umarbutler** [comment]
@Wauplin Just noticed the new UI change, really glad to see that was the direction you guys picked!

**Comment by Wauplin** [comment]
And for more info, check out the official announcement + docs: https://huggingface.co/posts/julien-c/388331843225875
