### ISSUE TITLE
Script deleted LFS files using git filter-repo but space is still used

### ISSUE THREAD

**Issue by m-elagdar** [huggingface/huggingface_hub#2722]
**Is your feature request related to a problem? Please describe.**
I'm trying to save space by deleting lots of intermediate checkpoints using a script. But it seems like the files are deleted from git history but the CDN still has them and the repo still has the same size.

**Describe the solution you'd like**
There's an extra step I should add to the script but I'm not sure what is it.

**Describe alternatives you've considered**
The way that actually reduces the repo size is the menu in settings but it would take lots of effort to repeat the steps for each file.

**Additional context**
Here's the script
```bash
#!/usr/bin/env bash
# -*- coding: utf-8 -*-
set -eu -o pipefail
log() { echo "${@}" 1>&2; }; stt=$SECONDS; trap 'log $(basename $0): total duration: $(($SECONDS-$stt)) seconds' EXIT

# pip install git-filter-repo

repo_id=$1
pattern=$2
echo "Will clean '$pattern' from Repo ID: $repo_id"
read -p "Enter token: " -s hub_token
(! [ -z "$hub_token" ] || read -p "Enter token: " -s hub_token; GIT_LFS_SKIP_SMUDGE=1 git clone https://-:$hub_token@huggingface.co/$repo_id)
owd="$PWD"
repo_dir=$(basename $repo_id)
cd $repo_dir
git filter-repo --path-glob "$pattern" --invert-paths
(! [ -z "$hub_token" ] || read -p "Enter token: " -s hub_token; git remote add origin https://-:$hub_token@huggingface.co/$repo_id)
git push --set-upstream origin main -f
cd "$owd"
rm -rf "$repo_dir"
```

**Comment by hanouticelina** [comment]
Hi @m-elagdar, sorry you encountered this issue! I suggest using `huggingface-cli repo-files` directly Instead of git-filter-repo:

```bash
# Install huggingface-cli
pip install -U "huggingface_hub[cli]"

# Login
huggingface-cli login

# Delete files
huggingface-cli repo-files username/repo-name delete "pattern/*"
```

I'm closing this issue but please feel free to comment if you have any other related question!

**Comment by m-elagdar** [comment]
Thanks, I tried this command but it simply created a new commit with the files deleted which doesn't save space.

I also tried [HfApi.super_squash_history](https://huggingface.co/docs/huggingface_hub/main/en/package_reference/hf_api#huggingface_hub.HfApi.super_squash_history) but it's only useful to delete older versions of the same path. So to fully delete files, I'd have to guess all their names, replace them with 1byte files then run super_squash_history

So both super_squash_history and the "LFS files list" in settings do some extra step per file that I can't find because the source code just calls an internal API: [super-squash](https://github.com/huggingface/huggingface_hub/blob/3618a38f80ae3073b95ea0fba26f363d2ec4ece8/src/huggingface_hub/hf_api.py#L3388)

**Comment by m-elagdar** [comment]
Here's a workaround script that effectively replaces the matches with 1-byte files then reclaims the space using super-squash then removes the 1-byte lfs pointers

```bash
#!/usr/bin/env bash
# -*- coding: utf-8 -*-
set -eu -o pipefail
log() { echo "${@}" 1>&2; }; stt=$SECONDS; trap 'log $(basename $0): total duration: $(($SECONDS-$stt)) seconds' EXIT

repo_id=$1
pattern=$2
unseen_names=${3-}
echo "Will clean '$pattern' from Repo ID: $repo_id"
read -p "Enter token: " -s hub_token
(! [ -z "$hub_token" ] || read -p "Enter token: " -s hub_token; GIT_LFS_SKIP_SMUDGE=1 git clone https://-:$hub_token@huggingface.co/$repo_id)
owd="$PWD"
repo_dir=$(basename $repo_id)
cd $repo_dir

log -e "\n\nReducing matched file-sizes to 1-byte"
if [ ! -z "$pattern" ]; then find . -name "$pattern" | while read f; do printf "\0" > $f; done; fi
if [ ! -z "$unseen_names" ]; then unseen_temp=$(mktemp); cat "$unseen_names" | tee "$unseen_temp" | while read f; do printf "\0" > $f; done; fi
(git add -Av; git commit -m "replace files matching: "$pattern" with 1-byte files")
git push

log -e "\n\nMerging all commits (super-squash)"
python3 -c "import sys; from huggingface_hub import HfApi; api = HfApi(token=(\"$hub_token\")); api.super_squash_history(repo_id=sys.argv[1])" "$repo_id"

log -e "\n\nCleaning the 1-byte pointers in a new commit"
git fetch origin; GIT_LFS_SKIP_SMUDGE=1 git reset --hard origin/main
if [ ! -z "$pattern" ]; then find . -name "$pattern" -exec rm {} \; ; fi
if [ ! -z "${unseen_temp-}" ]; then cat "$unseen_temp" | while read f; do echo rm $f; rm $f; done; rm "$unseen_temp"; fi
(git add -Av; git commit -m "remove 1-byte LFS pointers")
git push
cd "$owd"
rm -rf "$repo_dir"
```

###### Usage
1. Option 1: Clean existing files
  `clean_hf_repo.sh repo_id "pattern*"`
2. Option 2: Clean non-existing files (Assuming their names are {checkpoint-100.pt, checkpoint-110.pt ... checkpoint-200.pt})
  `clean_hf_repo.sh repo_id "" <(printf "%s\n" checkpoint-{100..200..10}.pt)`

**Comment by julien-c** [comment]
(maybe cc @Kakulukian for viz^)

**Comment by Kakulukian** [comment]
Hello, to clean up storage space, you can refer to https://huggingface.co/docs/hub/storage-limits#how-can-i-free-up-storage-space-in-my-accountorganization

**Comment by m-elagdar** [comment]
Thanks, the issue is based on this doc page, which gives no solution to deleting files that have different names other than deleting them from the UI one-by-one (which requires at least 4 left/mid clicks per file)

**Comment by m-elagdar** [comment]
Hello again, please re-open the issue
1. The [super_squash_history](https://huggingface.co/docs/huggingface_hub/main/en/package_reference/hf_api#huggingface_hub.HfApi.super_squash_history) workaround above no longer reduces repo space.
2. Depth-1 clones followed by deletion and force push also doesn't workThe files remain in the repository used storage until manually inspected and deleted from the Settings page

**Comment by Wauplin** [comment]
@m-elagdar LFS files must be garbage collected once per day so the used storage should decrease worth case after 24 hours. Did you encounter a repo where it's not the case? If yes, can you provide more details so we can investigate on our side?

**Comment by Wauplin** [comment]
Opened a PR to programmatically force-delete LFS files: https://github.com/huggingface/huggingface_hub/pull/2954

**Comment by m-elagdar** [comment]
Much appreciated
I testest with main (0.30) and it works instantly

Also made a script out of your snippet to match the script above
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Clean files matching a pattern from a huggingface repo
"""
import sys, os
from getpass import getpass
from fnmatch import fnmatch

from huggingface_hub import HfApi

def main():
    if len(sys.argv)==1 or {"-h", "--help"} & set(sys.argv): log(main.__doc__, end=""); exit(1)
    args = (a for a in sys.argv[1:] if not (a[:1]=="-" and a[1:]))
    kwargs = {k: next(iter(v), True) for k, *v in (a.lstrip("-").split("=", 1) for a in sys.argv[1:] if (a[:1]=="-" and a[1:]))}
    run(*args, **kwargs)

def run(repo_id, pattern, repo_type="model", token=None, y=False):
    log(f"Will clean pattern: '{pattern}' from repo id: '{repo_id}'")
    if not token: token = getpass("Enter huggingface_hub token: ")
    # https://github.com/huggingface/huggingface_hub/pull/2954
    api = HfApi(token=token)
    lfs_files = api.list_lfs_files(repo_id, repo_type=repo_type)

    # Filter files files to delete based on a combination of `filename`, `pushed_at`, `ref` or `size`.
    lfs_files_to_delete = [lfs_file for lfs_file in lfs_files if fnmatch(lfs_file.filename, pattern)]

    if not y and input(f"File list:\n\t{[f.filename for f in lfs_files_to_delete]}\n\nContinue (y,N)? ").lower() != "y": log("Rejected confirmation"); exit(1) 

    # Permanently delete LFS files
    api.permanently_delete_lfs_files(repo_id, lfs_files_to_delete, repo_type=repo_type)
    log(f"Successfully deleted {len(lfs_files_to_delete)} file(s)")

def log(*args, file=sys.stderr, **kwargs): print(*args, file=file, flush=True, **kwargs)

if __name__ == "__main__": main()
```

Usage: `clean_hf_repo.py repo_id "pattern*"`
