### ISSUE TITLE
Space - Failed to process a Websocket message 

### ISSUE THREAD

**Issue by m3hrdadfi** [huggingface/huggingface_hub#275]
I launched a streamlit app a couple of weeks ago, and everything worked fine until yesterday when I checked the app encountered with this message!

![Screen Shot 2021-08-11 at 1 08 31 PM](https://user-images.githubusercontent.com/2601833/129019491-008323bc-acb4-4f52-9352-ec8b3bc9617b.png)

I checked the app locally, and it works like a charm.

Space: [m3hrdadfi/typo-detector](https://huggingface.co/spaces/m3hrdadfi/typo-detector)
Github: [Typo Detector Repo](https://github.com/m3hrdadfi/typo-detector)

**Comment by osanseviero** [comment]
I think both Spaces are working now :)

**Comment by cbensimon** [comment]
There was a maintenance operation on HF Spaces at the time !

Thanks for your feedback @m3hrdadfi :)
