### ISSUE TITLE
Splinter's Inference API doesn't work

### ISSUE THREAD

**Issue by oriram** [huggingface/huggingface_hub#289]
Hi :)
When running Splinter models in the models hub (for example `tau/splinter-base-qass`, the following error is shown:
```
We could not properly load your model with any of the classes [<class 'types.AutoModelForQuestionAnswering'>, <class 'types.TFAutoModelForQuestionAnswering'>], are you sure this model can be loaded with the specified task ?
```
Any idea what is the source of this behavior? 
Many thanks!
@patrickvonplaten

**Comment by osanseviero** [comment]
Hi @oriram! Thanks for your splinter contribution!

The [PR](https://github.com/huggingface/transformers/pull/12955) merge was 5 days ago, but the latest `transformers` release happened [13 days ago](https://github.com/huggingface/transformers/releases/tag/v4.9.2). This change needs to make it to a new release and then it should work in the Inference API. I hope this makes sense. 

Cheers!

**Comment by oriram** [comment]
Sure, it makes sense :)
Thanks @osanseviero!
