### ISSUE TITLE
`PyTorchModelHubMixin` cannot push local files to the Hub

### ISSUE THREAD

**Issue by lewtun** [huggingface/huggingface_hub#309]
I'm using `huggingface_hub` v0.0.16 and am trying to use `PyTorchModelHubMixin` to save my model's weights and push them to the Hub.  Unfortunately I am hitting a

> ValueError: If not specifying `clone_from`, you need to pass Repository a valid git clone. 

error which suggests my local directory needs to be initialised with something like `git init`.

Here is a minimal example:

```python
from huggingface_hub import PyTorchModelHubMixin
import torch.nn as nn
import torch.nn.functional as F

class Model(nn.Module, PyTorchModelHubMixin):
    def __init__(self):
        super(Model, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5)
        self.conv2 = nn.Conv2d(20, 20, 5)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        return F.relu(self.conv2(x))

model = Model()
model.save_pretrained("cnn-dummy")
model.push_to_hub("cnn-dummy")
```

And the full stack trace

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_1600/2114550461.py in <module>
      1 model = Model()
      2 model.save_pretrained("cnn-dummy")
----> 3 model.push_to_hub("cnn-dummy")

~/miniconda3/envs/satflow/lib/python3.9/site-packages/huggingface_hub/hub_mixin.py in push_to_hub(self, repo_path_or_name, repo_url, commit_message, organization, private, api_endpoint, use_auth_token, git_user, git_email, config)
    266             )
    267 
--> 268         repo = Repository(
    269             repo_path_or_name,
    270             clone_from=repo_url,

~/miniconda3/envs/satflow/lib/python3.9/site-packages/huggingface_hub/repository.py in __init__(self, local_dir, clone_from, repo_type, use_auth_token, git_user, git_email, revision)
    321                 logger.debug("[Repository] is a valid git repo")
    322             else:
--> 323                 raise ValueError(
    324                     "If not specifying `clone_from`, you need to pass Repository a valid git clone."
    325                 )

ValueError: If not specifying `clone_from`, you need to pass Repository a valid git clone.
```

cc @LysandreJik

**Comment by nateraw** [comment]
@lewtun A really quick fix for this would be to not call `save_pretrained` first, but to instead just call `push_to_hub`, as its calling `save_pretrained` for you in the background. 

By just removing your call to `save_pretrained`, your code works fine :smile:. Here's proof!

<a href="https://colab.research.google.com/gist/nateraw/7a87ba17114e29727fbeb557551c1b98/pytorch-push-to-hub.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Comment by lewtun** [comment]
Thanks for the tip @nateraw - it works! 

Nevertheless, I think it would be nice if one could still push to the Hub after calling `save_pretrained` as I gather this is a pretty common workflow (especially if you're working in notebooks) :)

**Comment by Wauplin** [comment]
Solved in https://github.com/huggingface/huggingface_hub/pull/847 as `push_to_hub` is not leveraging git-based methods anymore.
