### ISSUE TITLE
Feature Request: Be able to search the hub by substring and author

### ISSUE THREAD

**Issue by muellerzr** [huggingface/huggingface_hub#31]
Hi! Thank you so much for a wonderful API and Hub, I'm finding it super useful with the [AdaptNLP](https://github.com/novetta/adaptnlp) project! I do have one request though:

I wrote a wrapper API to make the search results a bit more easy to read and comprehend for users, such as seen below
![image](https://user-images.githubusercontent.com/7831895/114557818-aaed3380-9c2f-11eb-95b4-791ff2df6865.png)

One issue I've come to have though is if I want to search for a model by a substring of its name such as 
if I search "danish-large", "flair/ner-danish-large" isn't returned which would be a very nice quality of life with the search API. Similarly if I try and search for models created by a specific user, the API will simply return nothing. It would be excellent if these features were added!

My method in the meantime is just to download the entire list (ie `api.list_modes()`) and filter the results, but it's far from ideal and memory efficient.

Thank you for all your your hard work!

(IF there is a different API route and flag I should be using rather than what's used by default, that would be good to know too)

**Comment by julien-c** [comment]
This is indeed on our roadmap

**Comment by muellerzr** [comment]
Fantastic! Glad to hear @julien-c. Is also adjusting how the results are presented/shown in Jupyter part of the roadmap as well? (Ex something like the `__repr__` I've shown here so it's not just a list of `instance of ModelInfo`)

I can also submit a pr for that *if* it's something wanted. What I have there is extremely simplistic

**Comment by julien-c** [comment]
I'll defer to @LysandreJik for that part of your question

**Comment by LysandreJik** [comment]
Indeed, better readability for `ModelInfo` would be great. We would gladly welcome a PR on which we could discuss the best way to handle the information held in it.

**Comment by julien-c** [comment]
Check out #41 which should fit at least part of your use case!

**Comment by muellerzr** [comment]
Looks awesome! Thanks for the heads up @julien-c

**Comment by julien-c** [comment]
we'll add a `search` param too soon

**Comment by julien-c** [comment]
I think this one can mostly be closed now no?

**Comment by LysandreJik** [comment]
Yes, thanks to the addition of `filter` [here](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/hf_api.py#L346)

There's a WIP PR with finer selection available here: https://github.com/huggingface/huggingface_hub/pull/263

**Comment by muellerzr** [comment]
Thanks guys!
