### ISSUE TITLE
Add model card via the APIs

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [huggingface/huggingface_hub#33]
Hi guys,

First of all, great work! The hub is amazing. I would like to ask if there is an easy way to automatically add a model_card to the uploaded model.

Thank you.

Cheers,

Francesco

**Comment by julien-c** [comment]
Do you mean from Python? 

You would just save a .md file from Python into your `local_dir`, and then the git-wrapping utilities in https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/repository.py to git push.

Would that fit your use case? cc @LysandreJik

**Comment by FrancescoSaverioZuppichini** [comment]
You are amazing! Thank you very much!
