### ISSUE TITLE
Feature request: Check if repo / file exists

### ISSUE THREAD

**Issue by nreimers** [huggingface/huggingface_hub#36]
Hi,
not sure if these functions are already implement, but I was not able to find them. It would be nice to have the following two methods:

- a function that checks if a repository exists. I provide a name, it checks if huggingface.co/[model_name] exists. Returns True / False. 
- a function that checks if a specific file in a repository exists. For sentence-transformers, I check if there is a sentence-transformers specific file  (modules.json) in that repositoryand depending on it I execute different code. Currently I do this with ` cached_download(url_to_modules_json_file)`  and catching a 404 exception. But having a function that just checks if the file exists (without downloading) and return True / False would have been nice.

**Comment by LysandreJik** [comment]
Hi @nreimers, 

There is a method you might find useful, it's the `model_info` method on the `HfApi`:

```py
from huggingface_hub import HfApi

hf_api = HfApi()
model_info = hf_api.model_info("lysandre/dummy-hf-hub")

print("Model ID:", model_info.modelId)

for file in model_info.siblings:
    print("file:", file.rfilename)
```

It has access to all files on the repository, and handles revisions! You can specify the branch, tag or commit and it will work.

We do not have a method to check if a repo exists - but there is a method to list all models available on the hub: 

```py
from huggingface_hub import HfApi

hf_api = HfApi()
models = hf_api.list_models()
```

You could filter those to check if the model you're targeting exists:

```py
from huggingface_hub import HfApi

hf_api = HfApi()

model_exists = "lysandre/dummy-hf-hub" in [model.modelId for model in hf_api.list_models()]
# True

model_exists = "lysandre/dummy-hf-hub2" in [model.modelId for model in hf_api.list_models()]
# False
```

**Comment by julien-c** [comment]
yes, we return a 404 (cc @Pierrci)

**Comment by Wauplin** [comment]
Issue is 2-years old so here's an updated snippet that does the job:

```py
from huggingface_hub import model_info, get_hf_file_metadata, hf_hub_url
from huggingface_hub.utils import RepositoryNotFoundError, EntryNotFoundError, RevisionNotFoundError
from typing import Optional


def model_exists(repo_id: str, token: Optional[str] = None) -> bool:
    try:
        # can also use `dataset_info` and `space_info`
        model_info(repo_id, token=token)
        return True
    except RepositoryNotFoundError:
        return False


def file_exists(
    repo_id: str,
    filename: str,
    repo_type: Optional[str] = None,
    revision: Optional[str] = None,
    token: Optional[str] = None,
) -> bool:
    url = hf_hub_url(repo_id=repo_id, repo_type=repo_type, revision=revision, filename=filename)
    try:
        get_hf_file_metadata(url, token=token)
        return True
    except (RepositoryNotFoundError, EntryNotFoundError, RevisionNotFoundError):
        return False


assert model_exists("gpt2")
assert not model_exists("Wauplin/missing-repo")  # missing repo

assert file_exists("gpt2", "config.json")
assert not file_exists("Wauplin/missing-repo", "config.json")  # missing repo
assert not file_exists("gpt2", "missing_file")  # missing file
assert not file_exists("gpt2", "config.json", revision="missing_revision")  # missing revision
```

When accessing private repos, if the token is not provided the repo is considered "not found" (as if it doesn't exist at all).
I don't think we want to integrate officially these helpers in `huggingface_hub` as I think it's best if users have an hand on such code. Especially for `file_exists` the implementation here is simplistic and returns False no matter if the repo/revision/file is missing. For a real-world use case, it's often best to process those errors differently. 

We could reconsider in case of huge demand but otherwise I'll close the issue for now :)

**Comment by julien-c** [comment]
note that in https://github.com/huggingface/huggingface.js we did integrate those helpers into the library if i'm not mistaken (cc @coyotte508) so i wouldn't be opposed to integrating them here too if it improves the DX

**Comment by Wauplin** [comment]
Yep, let's reopen it. I've added the "Good First issue" label if anyone wants to take it :) I'd be happy to provide help or review a PR here :hugs:

**Comment by martinbrose** [comment]
@Wauplin / @julien-c, happy to take this if still available.

**Comment by Wauplin** [comment]
Yes go ahead. Thanks for your work @martinbrose :) I'll be glad to review a PR

**Comment by martinbrose** [comment]
New PR #1591 should take care of the basics.

I haven't looked into including tests for private repos yet.

**Comment by Wauplin** [comment]
Thanks for your PR @martinbrose ! I reviewed it and added comments directly on it :)

**Comment by Wauplin** [comment]
Great work @martinbrose ! :clap:  I just merged https://github.com/huggingface/huggingface_hub/pull/1591 which makes `repo_exists` and `file_exists` available to everyone!
