### ISSUE TITLE
Feature request: snapshot_download - add library_name and library_version

### ISSUE THREAD

**Issue by nreimers** [huggingface/huggingface_hub#37]
With cached_download() I can provide the library name & version, which is sent via http-agent.

For snapshot_download() I did not find such a function. For statistics reasons, it would be nice if you could also provide library_name and library_version. [And hopefully later get statistics which models are most frequently accessed from your library]

PS: Are the github issues the right place to propose wishes for features or should I put them somewhere else?

**Comment by LysandreJik** [comment]
Thanks, @nreimers, the GitHub issues are definitely the right place to proposes your feature requests. You're right that `library_name` and `library_version` are currently missing on `snapshot_download` and that they should be added.
