### ISSUE TITLE
Chat bot empty replies 

### ISSUE THREAD

**Issue by vexhor** [huggingface/huggingface_hub#465]
I've made my own chatbot in google colabs using this tutorial: https://youtu.be/UjDpW_SOrlw
I've made some changes like changing the gpt model as I wanted it to speak Russian so I picked up the well trained medium gpt3 model from sberbank.
I pushed it to huggingface https://huggingface.co/life4free96/DialogGPT-med-TeiaMoranta?
So the problem is i send a message, the bot replies to it and when I'm sending the 2nd message it replies with nothing.
![Screenshot_2021-11-11-10-03-49-924_com android chrome](https://user-images.githubusercontent.com/74937003/141260972-151be9d1-c2fb-41b4-b4e0-1c25656e8476.jpg)
And the json output log:
{
  "generated_text": "",
  "conversation": {
    "generated_responses": [
      "! Хочешь пойти на утреннюю пробежку вместе? Можно пообедать вместе с тобой",
      ""
    ],
    "past_user_inputs": [
      "Здравствуй",
      "Привет"
    ]
  },
  "warnings": [
    "Conversation input is to long (22), trimming it to (20 - 10)",
    "Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation."
  ]
}

**Comment by Narsil** [comment]
Is it possible that your model is just generating an EOS token here (or EOS + special tokens that get removed) ?

In order to debug this, you could use `pipeline(model="life4free96/DialogGPT-med-TeiaMoranta")` and play around with it.
```python
from transformers import pipeline
from transformers.pipelines.conversational import Conversation


pipe = pipeline(model="life4free96/DialogGPT-med-TeiaMoranta")
conv = Conversation("Привет")
out = pipe(conv)
print(out)
conv.add_user_input("Здравствуй")
out2 = pipe(conv)
print(out2)
```

**Comment by Narsil** [comment]
Go checkout what happens in the `generate` function you should get a better grasp of what's happening.

**Comment by vexhor** [comment]
> pipeline(model="life4free96/DialogGPT-med-TeiaMoranta")

How can I do it in google colab?

**Comment by Narsil** [comment]
Hi, actually, we should close this, and open a discussion here: https://discuss.huggingface.co/ if you don't mind.

We try to keep conversations in the forum so other users can search an learn from those, which is less convenient on discord (which is more for casual conversation).

I am closing this issue, but please comment with the thread on discuss once you have created it please.

Cheers.
