### ISSUE TITLE
Discussion: download and upload models have a somewhat inconsistent API 

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#47]
Hi all. Just a small-ish thing to discuss.

Methods that get information about/from repos take the full model id (e.g. `hf_api.model_info("osanseviero/my-model")` or `snapshot_download("osanseviero/my-model)`).

On the other hand, `create_repo` takes as two separate arguments the model name and the organization (if any). I wonder if this could lead to confusions in the future, and, if so, we should check if the name param has a `/` and determine if there's an org in there.

**Comment by nreimers** [comment]
I think this makes a lot of sense. Actually implemented it in the `save_to_hub` from sentence-transformers

Users are used to pull images like `{org}/{name}`, so it makes sense to have a `push_to_hub("{org}/{name}")`

**Comment by osanseviero** [comment]
@LysandreJik @sgugger @julien-c in case you have any suggestions/ideas :) 

We now have better error messages when this error happens, so it might not be such a big issue.

**Comment by LysandreJik** [comment]
I wouldn't mind having `org/name` be interpreted as `name, organization=org` if specified, I think it would be coherent with the downloading methods.

**Comment by julien-c** [comment]
Yes I'd be supportive of this as well

**Comment by severo** [comment]
Related: while working on the models' data in https://observablehq.com/@huggingface/kaggle-dataset-huggingface-modelhub, I have been surprised that some of the "modelId"s are not "user/model", but just "model" (I understand all of them are models provided by Hugging Face as the organization). eg: https://huggingface.co/bert-base-uncased

**Comment by LysandreJik** [comment]
Yes, this is for historic purposes. The first models had no organization and were therefore at the root.

Unfortunately, for backwards compatibility purposes, it is now complicated to change the behavior.
