### ISSUE TITLE
[Spaces: Feature Request] Add option to select `sdk: static` when creating new space

### ISSUE THREAD

**Issue by cakiki** [huggingface/huggingface_hub#476]
**Is your feature request related to a problem? Please describe.**
There is no option to create a raw HTML space from the space creation workflow. Current options are *strictly* either streamlit or gradio, even though `sdk: static` is described as an option in the docs.

**Describe the solution you'd like**
Either the option not to select an sdk and havet that default to static, or an explicit option to create a space with `sdk: static`.

**Describe alternatives you've considered**
The alternative is to choose an sdk at random and change it afterwards.

**Additional context**
N/A

**Comment by julien-c** [comment]
Yes this is on our internal tracker, we're going to make those better documented and integrated into the flow (as well as fix a few bugs)

BTW saw your awesome static space yesterday, thanks for experimenting! Any feedback that you have please let us know, this is super helpful

BTW we are also thinking about maybe introducing a `sdk: docker` at some point 🤯 

cc @cbensimon @osanseviero

**Comment by cakiki** [comment]
Thank you, I'm glad you liked the space! I will keep experimenting and providing feedback.

`sdk: docker` would be an amazing addition.

**Comment by cakiki** [comment]
@julien-c Just to double check before opening an issue for this: those bugs you mention, is one of them the fact that a space with `sdk: static` will throw an error if you don't add an empty line after the YAML header?

**Comment by julien-c** [comment]
Ok this was finally shipped! Yay!

https://twitter.com/julien_c/status/1480671645060956166
