### ISSUE TITLE
Enable snapshot_download for different repo types

### ISSUE THREAD

**Issue by nateraw** [huggingface/huggingface_hub#496]
**Is your feature request related to a problem? Please describe.**

Currently, `snapshot_download` only works for `model` repos. It would be nice to add `repo_type` kwarg here and pass it along to the underlying functions to enable snapshot downloads of dataset repos.

**Describe the solution you'd like**

```python
from huggingface_hub import snapshot_download

cached_repo_path = snapshot_download('nateraw/huggingpics-data-2', repo_type='dataset')
```

**Describe alternatives you've considered**

You can do this via `Repository`, but its more verbose. Also, a generic `download_file_or_path` function may be nice too...(Related to #460 )

```python
from huggingface_hub import download_file

path = download_file('nateraw/huggingpics-data-2', 'images/')
```

**Additional context**

I was playing around with `upload_to_hub` and `load_from_hub` functions for Hugging Pics' datasets when I ran into this. Just wanted to grab the entire repo and load images from there, but realized its not possible with `snapshot_download`.

**Comment by osanseviero** [comment]
I think your solution is fine and would be consistent with the other methods.

cc @LysandreJik @muellerzr

**Comment by LysandreJik** [comment]
Indeed, that would be a nice addition!

**Comment by Wauplin** [comment]
`repo_type` kwarg added in https://github.com/huggingface/huggingface_hub/pull/801.
