### ISSUE TITLE
Only expose toplevel imports, not "nested" ones

### ISSUE THREAD

**Issue by julien-c** [huggingface/huggingface_hub#5]
Python Packaging question: how do we achieve `from package_name import xxx` importing from the `__init__.py` and not from the nested files inside the package?

**Comment by Narsil** [comment]
if `__init__.py`  has:

```
xxx = "some value"
```

and hierarchy:
```
package_name/
   __init__,py
  myfunctions.py
```

Then `from package_name import xxx` should work as is.

**Comment by julien-c** [comment]
Sorry my question wasn't clear, see internal Slack discussion/question instead: https://huggingface.slack.com/archives/C014N4749J9/p1608808664326600

What you described is already the case (https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/__init__.py) and it works fine.

But IDEs for some reason auto-import from inside the package, whereas they import from the init.py in e.g. transformers.

**Comment by julien-c** [comment]
The reason for solving this is that I don't want all third party libraries to import methods in a slightly different way, which will complicate maintenance/evolution.

**Comment by julien-c** [comment]
Closing this as we never really found out why some IDEs (vscode) insist on importing from nested subdirs
