### ISSUE TITLE
Selecting a sample in audio widgets automatically plays the audio

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#508]
For example, open https://huggingface.co/facebook/wav2vec2-base-960h, and  click sample dropdown. When selecting one, the audio automatically plays

**Comment by mishig25** [comment]
It was a feature, not a bug 😊
Please let me know if I should disable it

**Comment by osanseviero** [comment]
Imo auto-play for audio is not great, it's a bit unexpected. For audio to audio it can get confusing as a user might now know if they are hearing the output audio or input audio.
