### ISSUE TITLE
List models by author from HfApi

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [huggingface/huggingface_hub#513]
**Is your feature request related to a problem? Please describe.**
I would like to search for a specific author using `HfApi`. I've tried to use the `filter` option as following but the list is empty

```python
from huggingface_hub import HfApi
from pprint import pprint

api = HfApi()
pprint(api.list_models(filter="glasses")) 
pprint(api.list_models(filter="organization:glasses"))
pprint(api.list_models(filter="author:glasses"))
```
[glasses](https://huggingface.co/glasses) is an organization with saved models on hugging face. 

**Describe the solution you'd like**
It appears is indeed possible to search by authors, 

![image](https://user-images.githubusercontent.com/15908060/144102573-30e54633-dc31-4acc-8c81-fcfcae06c6a3.png)

<del>I've tried to look online for the endpoint used by `Hfapi` (so` https://huggingface.co/api/models`) but I was not able to find them.</del>

[Edit], [here](https://huggingface.co/docs/hub/endpoints) they are

Something in the right direction can be archived by listing all the files inside an organization repo

```python
from huggingface_hub import HfApi, HfFolder
from pprint import pprint
import requests


api = HfApi()
headers = {"authorization": f"Bearer {HfFolder.get_token()}"}
params = {"organization": "glasses"}
res = requests.get(f"{api.endpoint}/api/repos/ls", headers=headers, params=params)

pprint(res.json())
```

[Edit] Also,  `.list_repos_objs` from `HfApi` can be used to list the files.

But probably there is a better way

Thanks!

Cheers,

Francesco

**Comment by julien-c** [comment]
This is not document nor implemented in the `huggingface_hub.HfApi` wrapper yet (cc @LysandreJik @muellerzr @osanseviero), but you can do https://huggingface.co/api/models?author=glasses to get models by author 

you can also do https://huggingface.co/api/models?search=glasses to get model names that contain the string "glasses"

There exist equivalent endpoints for datasets and spaces.

`list_models(filter=...)` applies on tags, i.e. the repo labels you see in the header of the model page on hf.co

**Comment by julien-c** [comment]
If you'd like to implement this in `huggingface_hub` feel free to give it a shot!

**Comment by FrancescoSaverioZuppichini** [comment]
Hi @julien-c , thank you for the highlights! I'll work on that ;)
