### ISSUE TITLE
Since 0.2.0, git push fails (on Colab)

### ISSUE THREAD

**Issue by tianjianjiang** [huggingface/huggingface_hub#520]
I'm not sure whether it is a Colab-specific issue.

`git push` works with 0.1.2 using username/password login, but it fails with 0.2.[01] using token.

```shell
!git config --global credential.helper store
!huggingface-cli login
...
!git push
```
remote: Invalid username or password.
fatal: Authentication failed for [repo URL here]

**Comment by osanseviero** [comment]
cc @LysandreJik (https://github.com/huggingface/huggingface_hub/pull/507)

**Comment by LysandreJik** [comment]
Thanks for reporting, taking a look

**Comment by LysandreJik** [comment]
Hmmm I can't seem to reproduce, could you share more information about the workflow? Was it a model that was previously cloned?

**Comment by tianjianjiang** [comment]
> Hmmm I can't seem to reproduce, could you share more information about the workflow? Was it a model that was previously cloned?

I've just shared a Colab notebook with you. It contains somewhat sensitive info, so I guess better not post it here.
But you may need those info to ensure 100% reproducibility.

**Comment by LysandreJik** [comment]
Thanks a lot for sharing! I don't have access to your token so I replaced all the content relative to your organization with one I have control over to replicate - with the tokens, [I confirm that using a token with `write` access allows me to push to the repository](https://huggingface.co/datasets/hf-internal-testing/test-dataset/tree/main). Using a token with `read` access, obviously, does not.

Could you let me know of the following:
- Does it work with user/pass? When in notebooks, we recommend using the `notebook_login` method (`from huggingface_hub import notebook_login; notebook_login()`, which allows you to login with user/pass.
- Could you try recreating a token with write access and trying once again?

Thank you for your patience!

**Comment by tianjianjiang** [comment]
> * Does it work with user/pass? When in notebooks, we recommend using the `notebook_login` method (`from huggingface_hub import notebook_login; notebook_login()`, which allows you to login with user/pass.

My user/pass works for both 0.1.2 and 0.2.1 with `notebook_login()`.

---

> [...] [I confirm that using a token with `write` access allows me to push to the repository](https://huggingface.co/datasets/hf-internal-testing/test-dataset/tree/main). Using a token with `read` access, obviously, does not.
> * Could you try recreating a token with write access and trying once again?

Oops, I just realize that I haven't read the token page carefully and missed this:
> Unlike user access tokens, an Organization API token can only be used to provide read access to repos, or for billing access to a compute resource.

So this is entirely a user error. My sincere apologies. 🙇‍♂️ 

---

> Thank you for your patience!

Thank you for your patience as well. Once again, I'm terribly sorry for wasting your time, much obliged! 🖖

**Comment by LysandreJik** [comment]
That's great news! Thanks a lot for reporting, this ended up being another stress test for our stack so it's all good.

Let us know if you have feedback regarding the new system!

**Comment by tianjianjiang** [comment]
> * Does it work with user/pass? When in notebooks, we recommend using the `notebook_login` method (`from huggingface_hub import notebook_login; notebook_login()`, which allows you to login with user/pass.

> Let us know if you have feedback regarding the new system!

@LysandreJik It's been a while. I just want to share the reason I sometimes use `!huggingface-cli login` before I forget. Nothing critical, so I didn't open a GitHub issue.
When using `notebook_login()`, that webpage isn't blocking. I think that is a feature, and yet sometimes I schedule a run of many cells after that, then a non-blocking `notebook_login()` will lead to a wrong state. In theory, I can even argue that any login is stateful and blocking.

**Comment by LysandreJik** [comment]
Ah that's quite interesting @tianjianjiang, thanks for pointing it out! cc @sgugger, what do you think about making the `notebook_login` blocking?

**Comment by sgugger** [comment]
I don't think there is any widget that allow blocking execution, but I may be wrong.

**Comment by tianjianjiang** [comment]
@LysandreJik @sgugger I also guess no widgets block execution. IMO, wandb has an interesting and non-widget implementation that focuses the caret to the password field, but it also has its own quirky behaviors such as CTRL-C not working for me: https://colab.research.google.com/github/wandb/examples/blob/master/colabs/intro/Intro_to_Weights_%26_Biases.ipynb#scrollTo=93ub0LzeYwUZ
