### ISSUE TITLE
Feature request: Change repo from private to public (or viceversa) programatically

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#53]
I think this use case might be common:

1. User A decided to use `huggingface_hub` to share their company models in their org.
2. User A decided to begin by creating private repos and see if everything works.
3. User A now wants to make their repos public. Unfortunately, they have over 50 repos and going through each of them might be painful.

**Comment by julien-c** [comment]
Not a prioritary feature IMO (we need to push the usage of private models and datasets first), but this should be already exposed from the hf.co API (so it would just be a matter of exposing the call here)

**Comment by julien-c** [comment]
feel free to take a shot at this @osanseviero :)
