### ISSUE TITLE
(Spaces) Unable to sync with github actions

### ISSUE THREAD

**Issue by pleonova** [huggingface/huggingface_hub#534]
I followed the instructions in the docs but have not been able to sync my spaces repo with GH actions (https://huggingface.co/docs/hub/spaces#manage-app-with-github-actions).

I was able to force sync everything for the first time, set up the HF_TOKEN in my environment secrets and allow all actions in the settings.

I copied the two yaml files to actions flow and modified the url. However, I keep getting errors, I even tried updating the url to include my username, but had not luck.

```Run git push ***huggingface.co/spaces/pleonova/multi-label-long-text main
remote: Invalid username or password.
fatal: Authentication failed for 'https://huggingface.co/spaces/pleonova/multi-label-long-text/'
Error: Process completed with exit code 128.
```

GH: https://github.com/pleonova/multi-label-long-text/actions
HF Spaces: https://huggingface.co/spaces/pleonova/multi-label-long-text (currently private, but I can make public to help with debugging)

**Comment by julien-c** [comment]
maybe @SBrandeis (or @cbensimon) will have an idea!

**Comment by SBrandeis** [comment]
@pleonova it looks like your GitHub action secret is not set properly

**Comment by pleonova** [comment]
Thank you @SBrandeis for you advice! I wasn't sure which of the steps I did wrong as I hadn't set up GH actions before, but your tip helped me debug, thank you!

In case this would be helpful to those who are new setting up a remote repo and github actions, I added some notes below:

Additional notes to the steps provided here: https://huggingface.co/docs/hub/spaces#manage-app-with-github-actions
**In order manually push changes from GH to Spaces each time:**
1. Set up token in the GH settings -> secretes -> **repository secrets** (the first time around I set this up as an environment variable)
2. In your GH repo, run the following `git remote add space https://huggingface.co/spaces/HF_USERNAME/FULL_SPACE_NAME` (I originally got confused that my full space name included my username since the next section explicitly mentioned the username)
3. Every time you want to update the repo on Spaces, use the following `git push --force space main` (you can skip setting up actions if you want to manually push changes each time)

**In order to sync push to GH to automatically update Spaces:**
4. Set up two Action Workflows, I named mine name.yml and file_size.yml and paste the provided code in the original instructions into each file
5. Update with the token name that matches what name you gave it in step #1 (replace HF_TOKEN)
6. Replace HF_USERNAME and  FULL_SPACE_NAME `run: git push https://HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/HF_USERNAME/FULL_SPACE_NAME main` (the first time around I did not include my username in the path)
7. Next time you push to your GH repo, you should now also see your changes in spaces
