### ISSUE TITLE
Feature Request: Have programatic way of adding metadata to a repo

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#54]
If a user creates dozens of repos programmatically, and then realized they forgot adding some tag or any other info for the metadata, they will have to either go through each of them manually, re-generate the README.md, or change the README.md content manually which can be error-prone.

**Comment by julien-c** [comment]
I think the way to do this is to provide helper to update one model card locally (for instance via exposing only updating the metadata), then use the regular git-wrapping upload methods to push.
