### ISSUE TITLE
Model template

### ISSUE THREAD

**Issue by zaccharieramzi** [huggingface/huggingface_hub#549]
**Is your feature request related to a problem? Please describe.**
I am starting to use the Hugging Face hub to store some of my models.
Some of them are very similar and are only different in some parameters.
Right now I will have to create a new model repository for each one of them (I understand this is the typical way to do it).

**Describe the solution you'd like**
It would be nice if I could have a template repository (like the GitHub ones) that I could just use for all the models I am going to upload.

**Describe alternatives you've considered**
Of course it's relatively easy for me to copy paste the different elements of the models repositories in the other ones, but it would be even more seamless with templates.

I could also have many different model weights in the same repository, but as I understand it, it is not the expected way.

**Comment by julien-c** [comment]
Replying not to the feature request itself, but to this last sentence

> I could also have many different model weights in the same repository, but as I understand it, it is not the expected way.

You are right, in most cases we advise to store different models (checkpoints) into different repos, so it's super easy to use them from libraries etc.

There are exceptions: for instance different checkpoints inside the same training run, or fp16 or other type variations, are best stored in the same model repo.

**Comment by zaccharieramzi** [comment]
I have worked a lot on a topic called MRI reconstruction, basically generating an MRI image but with undersampled measurements.

For a lot of models, I have different weights depending on the undersampling factor, or the organ to reconstruct.
I sometimes have a different model architecture altogether, but still the model card is pretty similar (same paper, same way to report evaluation etc): this is why I felt that having a template would have been nice.
For a better view you can have a look at [my models](https://huggingface.co/zaccharieramzi), but don't hesitate to ask me for more info.

**Comment by julien-c** [comment]
yes in that case I would indeed keep separate model repos (cc @osanseviero) but build some scripts to help you sync them together etc

we'll keep this use case in mind for the future but probably not on the short-term roadmap!

PS/ oh you're from the awesome Parietal team! That's great!

**Comment by zaccharieramzi** [comment]
Haha yes I leaving very soon (end of the PhD) but it is indeed an awesome team !

One more question before I close this issue : do you by any chance have an example of the type of scripts you are talking about ?

**Comment by julien-c** [comment]
no it's really custom scripts in shell/Python/whatever you prefer :)

**Comment by zaccharieramzi** [comment]
Makes sense thanks!
