### ISSUE TITLE
website error

### ISSUE THREAD

**Issue by zz2995** [huggingface/huggingface_hub#550]
https://huggingface.co/docs/transformers/main_classes/deepspeed
This is just a small error. Hope it can be fixed.  The correct name is deepspeed
![image](https://user-images.githubusercontent.com/90665153/146657284-53cf8745-990e-4a44-afb7-f756435da7ad.png)

**Comment by julien-c** [comment]
gentle ping to @stas00

**Comment by stas00** [comment]
Thank you for letting us know about the typo, @zz2995! Should be fixed on the next doc rebuild.
