### ISSUE TITLE
Creating a repo does not allow using model as repo_type

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#557]
Using `create_repo` does not accept `repo_type="model"` right now. This is counter intuitive, specially as the params docstring says 

> repo_type: Set to "dataset" or "space" if creating a dataset or space, default is model

But in reality only `dataset` and `space` are [allowed](https://github.com/huggingface/huggingface_hub/blob/7b7b6e18ad6b770ca7cce3187512e91dc22a4dee/src/huggingface_hub/constants.py#L36).

Here is an example painful usage in which I need to have conditionals to handle spaces/datasets vs models https://huggingface.co/spaces/osanseviero/fork_a_repo/blob/main/app.py#L14-L20

cc @LysandreJik @muellerzr

**Comment by LysandreJik** [comment]
Indeed, there's a bit of a discrepancy as initially there were only model repositories. I think it's fine if the backend remains the same (using `None`), but the frontend should probably allow `"model"` as a valid `repo_type`.

**Comment by julien-c** [comment]
agree with @LysandreJik solution
