### ISSUE TITLE
Allow changing remote origin with Repository

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#558]
This is a bit of a power-user case, so actually I'm not sure we want this in `huggingface_hub`. I used this to be able to fork repos, but apart from that there might not be too much usage, so wanted to bring it up and see what you think.

We already have a [getter method](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/repository.py#L692) for the remote origin url.

cc @LysandreJik @muellerzr

**Comment by LysandreJik** [comment]
I think a broader solution to this would be to add a very configurable git method  that would take as commands any git command. For example, something alongside:

```
repo.git_command("clone https://..")
```

As long as this is launched with the `shell=False` parameter of `subprocess` it should be somewhat security friendly, and would enable complex use-cases like you describe without needing to interact with the command line directly.

**Comment by Wauplin** [comment]
(closing as "wontfix" as Repository usage is deprecated anyway)
