### ISSUE TITLE
Make it possible to skip large files when doing push_to_hub

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/huggingface_hub#591]
**Is your feature request related to a problem? Please describe.**

Suppose you have a repo on the hub with some large model files (>1 GB). Suppose that you want to upload some very small tokenizer files to that repo (this was my use case).

Currently when doing

```
tokenizer.push_to_hub(repo_url="...")
```

, it will first clone the entire repository (this takes a while!), downloading the big model.pt file, before I'm able to upload my tiny files to the repo. 

**Describe the solution you'd like**

We recently added a kwarg to a Repository called `skip_lfs_files`, to skip LFS files when cloning a repo (see #472). It would be great to pass this argument when pushing to the hub, something like:

```
tokenizer.push_to_hub(repo_url="...", skip_lfs_files=True)
```

Or skip those files by default?

**Comment by osanseviero** [comment]
WDYT @muellerzr?

cc @LysandreJik

**Comment by LysandreJik** [comment]
As discussed offline this is very linked to #321, which I believe Zach wants to work on next week.

**Comment by muellerzr** [comment]
Correct! Will make sure to touch on this.

**Comment by NielsRogge** [comment]
Gently pinging @muellerzr here, as `push_to_hub` just downloaded a > 1GB to just upload a tiny JSON to the hub 😅

**Comment by LysandreJik** [comment]
Opened https://github.com/huggingface/huggingface_hub/pull/847 which should help with that.

**Comment by Wauplin** [comment]
Closing this one since PR https://github.com/huggingface/huggingface_hub/pull/847 offers a non-git version of `push_to_hub` and is now merged. Should solve this issue as nothing is downloaded before pushing.
