### ISSUE TITLE
Use all parameters of the `keras.models.save_model`

### ISSUE THREAD

**Issue by ariG23498** [huggingface/huggingface_hub#598]
With the current implementation of saving a keras model we are missing out on a number of different parameters as mentioned in the [official docs of `tf.keras.models.save_model`](https://www.tensorflow.org/api_docs/python/tf/keras/models/save_model)
```python
tf.keras.models.save_model(
    model, filepath, overwrite=True, include_optimizer=True, save_format=None,
    signatures=None, options=None, save_traces=True
)
```

From the `push_to_hub_keras` code:
https://github.com/huggingface/huggingface_hub/blob/aa4994cf98db77cd709ea7a107a83b39c0d8f91b/src/huggingface_hub/keras_mixin.py#L53

I would love to see more control on the `push_to_hub_keras` API.

**Comment by merveenoyan** [comment]
@gante @osanseviero @ariG23498 we could introduce `include_optimizer` as an optional parameter that is set to default as False. For other parameters you indicated here we could maybe include signatures which would allow users willing to use their model on TF lite. I don't see a need to change the rest. WDYT?

**Comment by merveenoyan** [comment]
Answered it in the previous issue but my 2 cents:
```
@gante @ariG23498 @osanseviero
save_traces registers every custom layer to SavedModel by default and we don't need to register custom objects, it's my bad. I thought the error @ariG23498 got was related to that because the error message indicated this.
Now, we only need to change include_optimizer and maybe we could change signatures for TF Lite users, related to #598.
```

**Comment by merveenoyan** [comment]
Hello 👋  I'm currently on it. Will inform you when I open the PR 🤗
