### ISSUE TITLE
Text2text task link redirects to text2text

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/huggingface_hub#612]
I don't know if it should be hub that I'm opening the issue here, but basically we have only one task for both text generation and text2text generation (because they're pretty much the same) but the widget link redirects to non-existent text2text  task page. (You can see below) (The task name is "Text Generation" and it covers text2text as well)
@osanseviero @beurkinger 

<img width="1027" alt="Ekran Resmi 2022-01-20 18 41 28" src="https://user-images.githubusercontent.com/53175384/150371898-b07bafb7-a7ac-409d-ab76-d3ddde7399df.png">
a

**Comment by beurkinger** [comment]
Good point, I think I implemented this link a bit too hastily.

Before doing anything I need to know:
- what are the tasks share the same task page ?
- what are the tasks that don't have a task page ?

@merveenoyan @osanseviero

**Comment by merveenoyan** [comment]
@beurkinger it's only this one, that "Text Generation" task page is shared by Text-Generation and Text-2-text generation.
I tested the rest and there's no problem.

**Comment by beurkinger** [comment]
Hmmm this will need new code logic both on the hf_hub and moon-landing side I think 🤔
