### ISSUE TITLE
`unknown error` in TTS Model Loading

### ISSUE THREAD

**Issue by bayartsogt-ya** [huggingface/huggingface_hub#624]
**Is your feature request related to a problem? Please describe.**
I am trying out text-to-speech pipeline and I pushed files to hub based similar to [this one](https://huggingface.co/facebook/tts_transformer-ru-cv7_css10/tree/main) except I am not using hifigan as vocoder, but using the default griffin-lim.

When I try to load in interface, I am getting following error:
![Screenshot from 2022-01-24 23-52-01](https://user-images.githubusercontent.com/43239645/150919074-88d95607-71c5-4432-8a0d-5327abd24cd4.png)

Here is how my fs look like:
```
.
├── config.yaml
├── gcmvn_stats.npz
├── model.pt
├── README.md
├── speakers.txt
├── spm_char.model
├── spm_char.txt
└── spm_char.vocab
```

**Describe alternatives you've considered**
I tried to replicate how @kahne created the config and added a `hub` key to config.yml and it did not help:
```
...
hub:
  lang: mn
  speaker: 0
```
I wonder if you guys have any idea why it would throw `index out of range in self`?

**Comment by osanseviero** [comment]
Hey there! I was able to replicate using the Inference API code

```python
!pip install git+git://github.com/pytorch/fairseq.git@1d5da6d5b954ba01fc3df12d25d63df27437e20e
!pip install sentencepiece huggingface_hub

from fairseq.checkpoint_utils import load_model_ensemble_and_task_from_hf_hub
from fairseq.models.text_to_speech.hub_interface import TTSHubInterface

model, cfg, task = load_model_ensemble_and_task_from_hf_hub(
    "bayartsogt/tts_transformer-mn-mbspeech",
    arg_overrides={"vocoder": "griffin_lim", "fp16": False},
)

model_2 = model[0].cpu()
model_2.eval()
cfg["task"].cpu = True

TTSHubInterface.update_cfg_with_data_cfg(cfg, task.data_cfg)
generator = task.build_generator(model, cfg)

# Inference
inputs = "this is a test"
sample = TTSHubInterface.get_model_input(task, inputs)
wav, sr = TTSHubInterface.get_prediction(
            task, model_2, generator, sample
        )
```

In the last step I get a index out of range, so there seems to be some issue with Fairseq here.

**Comment by osanseviero** [comment]
Maybe @patrickvonplaten or @kahne have some ideas on this one

**Comment by patrickvonplaten** [comment]
Sadly I don't really know what's going on etiher here - @kahne should we move this issue to https://github.com/pytorch/fairseq/tree/main/fairseq ?

**Comment by Narsil** [comment]
It's an embedding error where the `src_tokens` exceed the vocab_size of `TTSTransformerEncoder`.

```python
src_tokens = tensor([[ 4, 44,  2]], dtype=torch.int32)
self.embed_tokens = Embedding(44, 512, padding_idx=1)
# id 44 is crashing.
```


```
  File "/home/nicolas/src/huggingface_hub/api-inference-community/.venv/lib/python3.9/site-packages/fairseq/models/text_to_speech/hub_interface.py", line 130, in get_prediction
    prediction = generator.generate(model, sample)
  File "/home/nicolas/src/huggingface_hub/api-inference-community/.venv/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/nicolas/src/huggingface_hub/api-inference-community/.venv/lib/python3.9/site-packages/fairseq/speech_generator.py", line 61, in generate
    encoder_out = model.forward_encoder(
  File "/home/nicolas/src/huggingface_hub/api-inference-community/.venv/lib/python3.9/site-packages/fairseq/models/text_to_speech/tts_transformer.py", line 403, in forward_encoder
    return self.encoder(
  File "/home/nicolas/src/huggingface_hub/api-inference-community/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nicolas/src/huggingface_hub/api-inference-community/.venv/lib/python3.9/site-packages/fairseq/models/text_to_speech/tts_transformer.py", line 90, in forward
    x = self.embed_tokens(src_tokens)
  File "/home/nicolas/src/huggingface_hub/api-inference-community/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nicolas/src/huggingface_hub/api-inference-community/.venv/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/home/nicolas/src/huggingface_hub/api-inference-community/.venv/lib/python3.9/site-packages/torch/nn/functional.py", line 2043, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
```

**Comment by bayartsogt-ya** [comment]
Thank you so much @osanseviero @Narsil @patrickvonplaten 

I just found that when I use only characters that are present in `spm_char.txt`, then it is working fine. In my case, I just needed to lowercase :sweat_smile: 

I also could have specified the uncased or cased scenario in sentencepiece training.

I guess the root cause was [sentencepiece encoding](https://github.com/pytorch/fairseq/blob/5fd38e3d5b1e5163aeace2a43d4a481fbbf1d83e/fairseq/models/text_to_speech/hub_interface.py#L116) (`src_dict.encode_line(tokenized)`) which caused embedding index out of range issue. I automatically assumed that sentencepiece model would do the out of vocab handling (falling back to `<unk>` token), but obviously it does not.

Anyways, thank you again for figuring this out!

**Comment by Narsil** [comment]
Still think it's something the pipeline should handle then IMO, no ?

**Comment by kahne** [comment]
Hi all, thanks very much for the discussions here! `src_dict.encode_line()` adds OOV tokens to the dictionary by default instead of replacing them with the UNK token (needs to set `add_if_not_exist=False`). I will update fairseq with this fallback to UNK.

**Comment by bayartsogt-ya** [comment]
I definitely agree with @Narsil and thank you so much @kahne for making that change.

Thanks to you guys! It was easier than ever to train and add TTS model and hifi-gan in a new language.
https://huggingface.co/bayartsogt/tts_transformer-mn-mbspeech

Also for future hifi-gan references:
in [original implementation](https://github.com/jik876/hifi-gan/blob/master/utils.py#L46) by default, checkpoints saved during the training (if you are using cuda) will be in cuda, so when you load it in the hub (on cpu) it will throw device mismatching error.

So you have to load that model with 
```
checkpoint_dict = torch.load(filepath, map_location="cpu")
torch.save(checkpoint_dict, filepath)
```
