### ISSUE TITLE
Automatically upload tensorboard traces if available with keras push to hub

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#627]
Something that would be interesting to explore is if `push_to_hub_keras` could automatically detect if tensorboard traces are available and upload them if yes.

Related internal discussion: https://huggingface.slack.com/archives/C025RSDHH54/p1643223960265000 cc @nateraw

**Comment by merveenoyan** [comment]
This is a great idea, sorry I missed it in Slack. I'll look into it once I merge couple of fixes.

**Comment by merveenoyan** [comment]
https://github.com/pulls This PR solves this issue.
