### ISSUE TITLE
TTS models response header is sent as application/json

### ISSUE THREAD

**Issue by julien-c** [huggingface/huggingface_hub#64]
causing widgets to fail: https://hf.co/julien-c/kan-bayashi_csmsc_tacotron2

Evidenced by:

```bash
curl 'https://api-inference.huggingface.co/models/julien-c/kan-bayashi_csmsc_tacotron2' \
  -H 'content-type: application/json' \
  -H 'Accept: */*' \
  --data-raw '{"inputs":"请您说得慢些好吗"}' \
  --compressed -vv
```

returns a 
```
content-type: application/json
```

**Comment by Narsil** [comment]
Old cache, issue was solved sometime ago (but modifying the code did not trigger cache flushing). 

Purging in progress.

Are there other tts models ? (I checked https://huggingface.co/models?pipeline_tag=text-to-speech but could only find incomplete models or disabled ones)

**Comment by julien-c** [comment]
yes, this one: https://huggingface.co/julien-c/ljspeech_tts_train_tacotron2_raw_phn_tacotron_g2p_en_no_space_train

only those two

**Comment by Narsil** [comment]
Done for this one too.

**Comment by julien-c** [comment]
Thank you! closing this
