### ISSUE TITLE
Allow `handle_impossible_answer=True` in Inference API 

### ISSUE THREAD

**Issue by pierrerappolt** [huggingface/huggingface_hub#640]
Does a new task need to be created to do this? Feels like should be an option allowed on the Question Answering task.

**Comment by Narsil** [comment]
As you might have noticed, it is supported (as in it works).

Which is the default for the API (most arguments flow directly to the pipeline).

We do not document it however, as we don't necessarily want to support every parameter/parameter combination in the future + we don't want to make the documentation arbitrarily long (the `generate_kwargs` for instance).
We won't cut parameters for the sake of it, but we might restrict the range of some, or some combination when it's putting unnecessary strain on the API and/or want to support different workflows when it makes sense (Live automatic speech recognition for instance)
