### ISSUE TITLE
DOC Clarification on non-text examples

### ISSUE THREAD

**Issue by adrinjalali** [huggingface/huggingface_hub#643]
At the moment the documentation in `model-repos` [says](https://huggingface.co/docs/hub/model-repos):

> Moreover, you can specify non-text example inputs in the model card metadata. Refer [here](https://github.com/huggingface/huggingface_hub/blob/main/docs/hub/input-examples.md) for a complete list of example input formats for all widget types. For vision & audio widget types, provide example inputs with `src` rather than `text`. 
> 
> For example, allow users to choose from two sample audio files for automatic speech recognition tasks by:
> 
> ```yaml
> widget:
> - src: https://cdn-media.huggingface.co/speech_samples/sample1.flac
>   example_title: Librispeech sample 1
> - src: https://cdn-media.huggingface.co/speech_samples/sample2.flac
>   example_title: Librispeech sample 2
> ```

It's not clear to me whether users can upload their own non-text examples, or if there's an interface where they can go through existing examples. If this is clarified somewhere in the documentation, I think it's not clear to the reader by the point they get to reading this part of the docs.

**Comment by osanseviero** [comment]
Good point. 

Users can just upload an audio file to the HF repo and link to it in the source. 
https://huggingface.co/facebook/xm_transformer_600m-es_en-multi_domain/blob/main/README.md#L17

**Comment by julien-c** [comment]
might be better to replace those (existing URLs) in the doc by example URLs like `https://example.org/somewhere/speech_samples/sample1.flac `, no?
