### ISSUE TITLE
Render Jupyter Notebooks as web pages

### ISSUE THREAD

**Issue by cakiki** [huggingface/huggingface_hub#644]
Jupyter notebooks are a very common medium for experimentation and result communication.

**Is your feature request related to a problem? Please describe.**
Jupyter notebooks are currently displayed as json 

**Describe the solution you'd like**
It would be nice to have an [nbviewer](https://github.com/jupyter/nbviewer) server that renders notebooks to html

**Describe alternatives you've considered**
N/A

**Additional context**
unrendered example from the hub: https://huggingface.co/keras-io/deep-neural-decision-forests/blob/main/deep-neural-decision-forests.ipynb
rendered example from github: https://github.com/barbagroup/AeroPython/blob/master/lessons/01_Lesson01_sourceSink.ipynb

**Comment by adrinjalali** [comment]
This is very valuable feedback @cakiki , but I think the forum (https://discuss.huggingface.co/c/site-feedback/2) is a much better place to discuss this than here (especially since we're restructuring the repo a little bit)
