### ISSUE TITLE
`api.set_access_token` seems to fail silently

### ISSUE THREAD

**Issue by yjernite** [huggingface/huggingface_hub#661]
I tried the following code to create a private repository using the Python API, and got a 403 permission error:
```
from huggingface_hub import HfApi
_AUTH_TOKEN = "{newly created token with write permissions}"
api = HfApi()
api.set_access_token(_AUTH_TOKEN)
api.create_repo(
    "bigscience-catalogue-lm-data/lm_vi_pseudocrawl_vnexpress",
    private=True,
    repo_type="dataset",
)
```

I am using version `0.4.0.dev0`, and can create a repository with the same token by passing it to the `create_repo` method:
```
from huggingface_hub import HfApi
_AUTH_TOKEN = "{newly created token with write permissions}"
api = HfApi()

api.create_repo(
    "bigscience-catalogue-lm-data/lm_vi_pseudocrawl_vnexpress",
    private=True,
    repo_type="dataset",
    token=_AUTH_TOKEN,
)
```

`set_access_token` did not return any output or show any logs by default, let me know if I can re-run the command with additional args to get more info

cc @SBrandeis @coyotte508

**Comment by LysandreJik** [comment]
Hey! As Zach mentioned, `set_access_token` sets the token for the git side of things, but it doesn't save it to the folder. This seems to be a common error so maybe we could move the token saving to the `set_access_token` method, cc @osanseviero who mentioned something similar a few months back.

In the meantime this should do what you want @yjernite:

```diff
  from huggingface_hub import HfApi, HfFolder
  _AUTH_TOKEN = "{newly created token with write permissions}"

  api = HfApi()
  api.set_access_token(_AUTH_TOKEN)
+ HfFolder.save_token(_AUTH_TOKEN)
```
