### ISSUE TITLE
Document server-side locks for `HfApi.upload_file`

### ISSUE THREAD

**Issue by SBrandeis** [huggingface/huggingface_hub#683]
`HfApi.upload_file` can only upload one file per repo at a time, due to a server-side locking logic

This specificity is not mentioned in the docstring of the method

cc @lhoestq since this method is used in datasets

**Comment by lhoestq** [comment]
Thanks ! At one point it would be awesome to find a way to upload several files in parallel though, to speed up `push_to_hub`

**Comment by SBrandeis** [comment]
Closing since `upload_file` now uses the `/commit` API
