### ISSUE TITLE
Time-ago issue on 'Files and versions' / repo view

### ISSUE THREAD

**Issue by mapmeld** [huggingface/huggingface_hub#685]
**Is your feature request related to a problem? Please describe.**

When I was looking at [this model repo](https://huggingface.co/aubmindlab/bert-large-arabertv2/tree/main), I noticed that some files were commited "in 9 months" (to me this means in the future).

<img width="226" alt="Screen Shot 2022-02-12 at 8 15 04 PM" src="https://user-images.githubusercontent.com/643918/153738402-af9228cf-5be1-4b1f-827b-d41374e222ea.png">

**Describe the solution you'd like**

It should read "9 months ago". Other timestamps seem correct (e.g. "last year")

**Comment by julien-c** [comment]
thanks for reporting! this is tracked internally and should be fixed soon

**Comment by Pierrci** [comment]
We deployed the fix (thanks @coyotte508), so I'm closing this - feel free to reopen @mapmeld if you still encounter the problem
