### ISSUE TITLE
Support canonical dataset endpoints in `HfApi.upload_file`

### ISSUE THREAD

**Issue by mariosasko** [huggingface/huggingface_hub#686]
Upload to the endpoints of canonical datasets currently doesn't work, even though I have a valid token.

#### Code to reproduce

```python
import huggingface_hub

huggingface_hub.upload_file(
    "./redcaps_v1.0_annotations.zip?dl=1",
    "data/redcaps_v1_0_annotations.zip",
    repo_id="red_caps",
    repo_type="dataset",
    token=******,
)
```
ERROR: `HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/datasets/red_caps/upload/main/data/redcaps_v1_0_annotations.zip`

CC: @SBrandeis, @lhoestq

**Comment by SBrandeis** [comment]
That's intended, as long as GitHub is the source of truth for canonical datasets

For now, any updates to canonical datasets should go through the datasets repo on GH

**Comment by lhoestq** [comment]
Note that you can still clone the repository locally and push your changes to the `data` folder if you want
