### ISSUE TITLE
[🐞Bug?] Canonical datasets on Hub link to github file instead of dir

### ISSUE THREAD

**Issue by cakiki** [huggingface/huggingface_hub#713]
**Is your feature request related to a problem? Please describe.**
Current "Update on github" link on canonical dataset pages links to the README.md file of a given dataset.
e.g.: https://huggingface.co/datasets/super_glue links to https://github.com/huggingface/datasets/blob/master/datasets/super_glue/README.md

**Describe the solution you'd like**
Have the button link one level higher, to the root of the dataset entry, i.e. here: https://github.com/huggingface/datasets/tree/master/datasets/super_glue

**Describe alternatives you've considered**
N/A

**Additional context**
The README would still render the same; but one would have direct access to the loading script and other relevant files without having to navigate one level higher. I personally always navigate to github for the loading script, never for the metadata which I can already access from the hub.

**Comment by julien-c** [comment]
i think your proposed change makes sense! will post to internal tracker and report here with outcome

**Comment by julien-c** [comment]
this has been changed and will be in the next production version, please re-open if that's not the case.

Thanks for your suggestion!
