### ISSUE TITLE
Inference API documentation detailed parameters missing "do_sample"

### ISSUE THREAD

**Issue by kagglesintracking** [huggingface/huggingface_hub#722]
Doc: https://api-inference.huggingface.co/docs/python/html/detailed_parameters.html

There should be a `do_sample` parameter in all the generation tasks otherwise parameters like `temperature`, `top_k`, `top_p` won't work.

**Comment by merveenoyan** [comment]
Hello, thanks a lot for noting this and creating this issue! 🤗 we'll fix it.

**Comment by adrinjalali** [comment]
Closing as the fix is merged.
