### ISSUE TITLE
[🐞 BUG?] Empty README.md with YAML header gets overwritten for datasets

### ISSUE THREAD

**Issue by cakiki** [huggingface/huggingface_hub#725]
**Is your feature request related to a problem? Please describe.**
When I have a README.md with a YAML header and no text content, I get the `No dataset card yet New: Create and edit your dataset card directly on the website! Create Dataset Card` which, if clicked, will create a new empty README.md and overwrite the committed one with header info (and therefore remove all tags).

e.g. For a private repo in one of my orgs, this button links to **`https://huggingface.co/datasets/ORG/DATASET/new/main/?filename=README.md`** even though the file already exists.

**Describe the solution you'd like**
Have the button check if there is a README.md file and open that for editing instead of overwriting with an empty one.

**Describe alternatives you've considered**
N/A

**Additional context**
This happened with a private repo; not sure this detail matters.

**Comment by osanseviero** [comment]
Thanks for reporting!

**Comment by Pierrci** [comment]
Closing this since we deployed a fix server-side, thanks @cakiki! Feel free to reopen if needed.

**Comment by cakiki** [comment]
Thank you for the fix! 
I think there is now a new bug, as I now see "README.md exists but content is empty. You can click on Edit dataset card to edit." on datasets without a README.md file.

cc @Pierrci @osanseviero

**Comment by julien-c** [comment]
can you post an example dataset where this happens?

**Comment by cakiki** [comment]
@julien-c https://huggingface.co/datasets/bigscience-catalogue-lm-data/lm_fr_wikisource_filtered

**Comment by julien-c** [comment]
(i think i broke this, btw 😅)
