### ISSUE TITLE
How to correctly upload 160 RL models?

### ISSUE THREAD

**Issue by simoninithomas** [huggingface/huggingface_hub#769]
Hi! For people who upload a lot of models on the Hub, I'm working on the upload of about 160 RL models ([rl-trained-agents](https://github.com/DLR-RM/rl-trained-agents/tree/72feeb8c2e8985e5382ee61f3542ee023ec81922)) :fire: so **I will not do it by hand :sweat_smile:**

The github repository containing all the models is like this:
```
rl-trained-agents
   /a2c/Acrobot-v1_1
   /a2c/CartPole-v1_1
   ...
   /ppo/CartPOle-v1_1
```

Each model is like this (for instance `/ppo/SpaceInvadersNoFrameskip-v4`:
```
├── SpaceInvadersNoFrameskip-v4_1/
│   ├── SpaceInvadersNoFrameskip-v4.zip
│   ├── monitor.csv
│   ├── evaluations.npz        
│   ├── SpaceInvadersNoFrameskip-v4/
│     ├── args.yml
│     ├── config.yml
│     ├── vecnormalize.pkl
```

The process I'm defining is this way (pseudocode) for each {algo}/{env_id}:
```
# Step 1: Create Repo on the Hub using Repository
sb3/{algo}-{env_id}: for instance `sb3/ppo-CartPole-v1`

# Step 2: Clone the Repo to a folder

# Step 3: Move the corresponding rl-trained-agents/algo/env to Repo

# Step 4: Go to the Repo and generate the model card

# Step 5: Generate the video (using a script)

# Step 6: Push to Hub the repo

```
**Do you think it's a good process or you have some better solutions?** Thanks for your feedback

**Comment by simoninithomas** [comment]
@osanseviero : "Then the approach sounds good. One suggestion to avoid having to do this twice, is that I would unzip the files. Having them within a zip is not great I feel, specially since you have 0 idea what is in there without download+unzipping (similar to how we discussed spaCy works atm)"

**So the described process is only for SB team models**. 

The idea is:
- When people run the script enjoy.py (from rl-baselines-zoo) that test a model. They define if it's an official trained model **and if they don't have on their local machine, it will be automatically retrieved from the hub.**
```python
if not found then:
  local_dir = f"rl-trained-agents/{algo}/{env_id}_1"
  clone_from = f"sb3/{algo}-{env_id}"
  repo = Repository(local_dir, clone_from)
```
- I'm agree with the security pb and we can have **a custom process for RL-Zoo custom trained models** (not official ones but ones trained by users), because we will have a two step process in this case:
```
# I want to get my custom ppo-CartPole v-1
# This download the model and put it in logs/ppo/CartPole-v1_1
!python utils/load_from_hf.py --algo ppo --env CartPole-v1 --model-id="ThomasSimonini/ppo-Cartpole-v1"

# I try the environment
!python enjoy.py --algo ppo --env CartPole-v1 --no-render
```
But for these official saved models, we just modify one line of code of enjoy.py (if the folder is not found and the model searched is from rl-trained-agents then download it from the hub) that's why we can put it directly on rl-baselines-zoo without having an external repo like sb3

**Comment by julien-c** [comment]
i agree that you should store the uncompressed files whenever possible (to get git history etc)

**Comment by adrinjalali** [comment]
Is this issue resolved? Can we close this?

**Comment by osanseviero** [comment]
Yes, this is more of a discussion on good practices rather than an issue with the core library. This info will be useful for the new docs as well cc @NimaBoscarino
