### ISSUE TITLE
[Feature request] linking docs

### ISSUE THREAD

**Issue by flozi00** [huggingface/huggingface_hub#77]
While transformers are growing pretty fast and there are new models it would be cool if the docs are linked.
For example I saw Luke on the hub and had absolutely no idea how to use, until I found it in transformers docs

**Comment by julien-c** [comment]
linked to https://github.com/huggingface/huggingface_hub/issues/532 and can probably be addressed at the same time

we can display link to the doc inside the "How to use" modal like this:

<img width="823" alt="Screenshot 2021-12-23 at 14 12 46" src="https://user-images.githubusercontent.com/326577/147245706-7607f1d3-be8b-4f78-95c0-71ef9982349d.png">

Thoughts?
