### ISSUE TITLE
`/api/repos/move` now completes in a synchronous way

### ISSUE THREAD

**Issue by Pierrci** [huggingface/huggingface_hub#775]
No more 202 HTTP response code or email sent, all the errors are returned directly if any (simple 200 if everything went well). See https://github.com/huggingface/moon-landing/pull/2354 for more details.

The related method(s) in `hf_api` need to be updated accordingly cc @coyotte508 @osanseviero

**Comment by adrinjalali** [comment]
@Pierrci could you please specify what the change exactly is? What was the response sent on the endpoint before, and what is it going to be now, and what are the possible response codes/error messages in each possible case? Is there a doc page where I could find the info?

**Comment by coyotte508** [comment]
- If the move went well: 200 HTTP code
- If the move went wrong - a JSON with "error" field is sent - the error message is in the "error" field.

If you want to add a "move went wrong" case, you can for example rename a repo to one you already own.
