### ISSUE TITLE
Reviewer assing task fails on PRs from forks

### ISSUE THREAD

**Issue by adrinjalali** [huggingface/huggingface_hub#791]
The task fails with this error:

```
 Fetching configuration file from the source branch
Fetching changed files in the pull request
Identifying reviewers based on the changed files
Identifying reviewers based on the author
"per_author" is not set; returning no reviewers for the author.
Adding other group membres to reviewers if group assignment feature is on
Group assignment feature is disabled
Randomly picking reviewers if the number of reviewers is set
Requesting review to LysandreJik, osanseviero
Error: HttpError: Resource not accessible by integration
```

Example run: https://github.com/huggingface/huggingface_hub/runs/5659079126?check_suite_focus=true

ping @muellerzr

**Comment by osanseviero** [comment]
In any case with the simplification of the repo I was thinking the auto reviewer might not be very necessary anymore. WDYT @muellerzr @LysandreJik?

**Comment by muellerzr** [comment]
I actually completely agree with you Omar. Before it was good because we had essentially 3 different libs at once, so it was needed for delegation. Now that we no longer have that it can be removed. Feel free to assign it to me and I can get this in today!
