### ISSUE TITLE
PyYAML parses `no` as `False`

### ISSUE THREAD

**Issue by anton-l** [huggingface/huggingface_hub#797]
In model cards related to the Norwegian languages (e.g. https://huggingface.co/NbAiLab/wav2vec2-large-voxrex-npsc-nynorsk/blob/main/README.md) some metadata values can be parsed as `False` instead of `no` for the Norwegian language code.

To reproduce:
```python
from huggingface_hub.repocard import metadata_load

readme_path = hf_hub_download("NbAiLab/wav2vec2-large-voxrex-npsc-nynorsk", filename="README.md")
print(metadata_load(readme_path)["tags"])
```
Returns:
```python
['generated_from_trainer', 'automatic-speech-recognition', 'NbAiLab/NPSC', 'robust-speech-event', False, 'nn-NO']
```
Expected:
```python
['generated_from_trainer', 'automatic-speech-recognition', 'NbAiLab/NPSC', 'robust-speech-event', 'no', 'nn-NO']
```

**Comment by julien-c** [comment]
yes that conforms to the YAML spec. It's the model card that should be updated to quote "no"
