### ISSUE TITLE
Is it possible to make `HF_ENDPOINT` endpoint overridable in environment variable ?

### ISSUE THREAD

**Issue by Narsil** [huggingface/huggingface_hub#798]
**Is your feature request related to a problem? Please describe.**

 We want to update the endpoint for this library (actually for `datasets`) for hub reasons.
AFAIK, it's actually also necessary for China.

**Describe the solution you'd like**

Something like in `transformers` : https://github.com/huggingface/transformers/blob/main/src/transformers/utils/hub.py#L110
Having the same defaults, just make it overridable with an env variable (other mecanisms are fine, just seems env variable are consistent and easy)

Also `ENDPOINT` and `HUGGINGFACE_CO_URL_HOME` seem to be duplicate names.

**Describe alternatives you've considered**

Current fix, is by monkey patching the relevant variables from external code, which is not ideal for maintenance reasons.

@LysandreJik @osanseviero  ? 

This could be a good opportunity to use the same variables across HF libraries in datasets, I rechecked and it's using `HF_ENDPOINT` actually.

**Comment by julien-c** [comment]
this library does honor `HF_ENDPOINT` as far as i know

**Comment by julien-c** [comment]
#703

**Comment by Narsil** [comment]
I think this call is wrong then, no ? https://github.com/huggingface/huggingface_hub/blob/df4c6d929a6357379ae20558edc609d12876a294/src/huggingface_hub/file_download.py#L174

Defined here: https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/constants.py#L32

**Comment by Narsil** [comment]
Ahh it's not in the released version either ! That's also part of why I was confused it wasn't working.

Maybe the call site I found was not the culprit for the behavior I was observing.

```
pip install -U huggingface_hub
HF_ENDPOINT=http://example.com python -c "from huggingface_hub import HfApi; print(HfApi().endpoint)" #  https://huggingface.co
```

**Comment by LysandreJik** [comment]
Version v0.5.0 should drop in the coming days, hopefully by next Wednesday.

**Comment by adrinjalali** [comment]
From what I understand this seems to be fixed in upstream. Closing. Please comment if the fixes in upstream don't satisfy the requirements.

**Comment by Narsil** [comment]
I think this part was not fixed: https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/constants.py#L32

This function is used in `pyctcdecode` *https://github.com/kensho-technologies/pyctcdecode/blob/09eadf4c3670c94ffc1d84a415c2685e16645b65/pyctcdecode/decoder.py#L764)  for instance which we use in `transformers` for instance (https://github.com/huggingface/transformers/blob/main/src/transformers/pipelines/__init__.py#L640)

Also, the current code doesn't use `HF_ENDPOINT` for these constants afaik which seems to have been updated in all other libraries.

Happy to prepare the PR !

**Comment by LysandreJik** [comment]
Makes sense to me to align the variable names, indeed.
