### ISSUE TITLE
Allow specifying multiple tags with the Keras mixin

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#800]
As a user, I might want to not just specify the task name, but also other tags. Since tags with a task name are automatically identified as a task, we can simply accept a list of tags .

For example 
```
save_pretrained_keras(..., tags=["huggan", "gan", "text-to-image"])
```

cc @merveenoyan @NielsRogge @nateraw

**Comment by merveenoyan** [comment]
I'm currently off, will implement this tomorrow.
