### ISSUE TITLE
`HfApi.endpoint` should be configurable in `Repository`

### ISSUE THREAD

**Issue by SBrandeis** [huggingface/huggingface_hub#808]
https://github.com/huggingface/huggingface_hub/blob/c2ffc48cd4d9c0271c0cc68d17a11e1088d3fa1a/src/huggingface_hub/repository.py#L434

We should be able to pass arguments to `HfApi()` from `Repository`

**Comment by adrinjalali** [comment]
@SBrandeis could you please explain further what the usecase is, and share a bit of code which would use the arguments? It helps with designing the API.

**Comment by SBrandeis** [comment]
I'm using `huggingface_hub` in AutoTrain to handle repo creation / cloning

My local version of AutoTrain uses a local version of the HF Hub to store and manipulate repos. The URL of the local HF Hub is not `https://huggingface.co` but rather `http://localhost:PORT` 

Currently `huggingface_hub` assumes the URL to the HF Hub is `https://huggingface.co`, and I have to implement ugly hacks as the one following to make it work:
```python
import os
import huggingface_hub

# I have to override ENDPOINT
HF_HUB_URL = "http://localhost:PORT"
huggingface_hub.constants.ENDPOINT = HF_HUB_URL
huggingface_hub.hf_api.ENDPOINT = HF_HUB_URL
huggingface_hub.repository.ENDPOINT = HF_HUB_URL

# Even worse:
clone_url = f"http://user:{hf_token}@{HF_HUB_URL[len('http://'):]}/datasets/user/dataset_name"
repo = huggingface_hub.Repository(local_dir=".", clone_from=clone_url, use_auth_token=hf_token)
```

I would like to be able to configure the URL of the HF Hub when using `huggingface_hub`

**Comment by SBrandeis** [comment]
I'm happy to open a PR if it makes sens to add this change to the library

**Comment by LysandreJik** [comment]
It's a reasonable asumption which would also unblock on-prem efforts as seen in https://github.com/huggingface/huggingface_hub/issues/650 and  https://github.com/huggingface/transformers/issues/15514
