### ISSUE TITLE
push_to_hub_keras rejected because it contains binary files

### ISSUE THREAD

**Issue by nateraw** [huggingface/huggingface_hub#825]
I noticed I can't push the LFS files associated with Keras models anymore. What's interesting is that I'm experiencing the same issue on older versions of `huggingface_hub` (0.4.0) as well as new versions (0.5.1). 

Here is a minimal example to recreate the issue:

```python
import tensorflow as tf
from tensorflow.keras import layers, Sequential

from huggingface_hub import push_to_hub_keras

model = Sequential(
    [
        layers.Dense(1000, activation="relu", name="layer1"),
        layers.Dense(1000, activation="relu", name="layer2"),
        layers.Dense(1000, name="layer3"),
    ]
)
model.build((None, 2))

push_to_hub_keras(model, 'test-save-keras-sequential')
```

You can also try it yourself in Colab: [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/gist/nateraw/dcb52b7b9846a41006000709d8c40159/keras-push-to-hub-rejected.ipynb)

When you run the above, you get this...I redacted my token which was being printed here.

```
remote: -------------------------------------------------------------------------        
remote: Your push was rejected because it contains binary files.        
remote: Please use https://git-lfs.github.com/ to store binary files.        
remote: See also: https://hf.co/docs/hub/adding-a-model#uploading-your-files        
remote: -------------------------------------------------------------------------        
remote: Offending files:        
remote:  - variables/variables.data-00000-of-00001 (ref: refs/heads/main)        
To https://huggingface.co/nateraw/test-save-keras-sequential
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://user:<REDACTED TOKEN>@huggingface.co/nateraw/test-save-keras-sequential'
```

**Comment by LysandreJik** [comment]
Linked to https://github.com/huggingface/huggingface_hub/issues/687

**Comment by merveenoyan** [comment]
The issue linked by @LysandreJik is for git lfs not tracking small files, what Dimitre pushed was a GAN model and I doubt that's a small file.

**Comment by LysandreJik** [comment]
The issue linked above is due to binary files not being automatically tracked by git-lfs; in this instance, the push was rejected because it contains binary file. I believe having automatic tracking via git-lfs for binary files would solve the issue shown by @nateraw's code sample above.

**Comment by LysandreJik** [comment]
@nateraw could you try by checking out this branch to see if it solves your problem? https://github.com/huggingface/huggingface_hub/pull/828

**Comment by nateraw** [comment]
Solved ✅ thank you!!
