### ISSUE TITLE
`/api/repos/ls` has been removed

### ISSUE THREAD

**Issue by Pierrci** [huggingface/huggingface_hub#826]
Since March 1, the endpoint `/api/repos/ls` doesn't exist anymore (see https://github.com/huggingface/moon-landing/pull/2215, cc @coyotte508). The `hfApi.list_repos_objs` method should be removed too as a result - sorry for the (very) late notice!

(FYI, there were 21 calls to this endpoint in the last 30 days)

**Comment by julien-c** [comment]
unless I'm missing something, this was removed in February in #702

**Comment by Pierrci** [comment]
wtf - I probably wasn't looking on `main`, my bad 💩💩💩
