### ISSUE TITLE
Rename `allow_regex` and `ignore_regex` in `snapshot_download` to be consistent with `fnmatch`

### ISSUE THREAD

**Issue by willfrey** [huggingface/huggingface_hub#836]
https://github.com/huggingface/huggingface_hub/blob/3e72bc876d72855445a3c204f483eb761eb91da5/src/huggingface_hub/snapshot_download.py#L214-L223

In the above, `fnmatch` is being used to filter files against `allow_regex` and `ignore_regex`. Acknowledging that I might be being overly pedantic here, [the official docs for fnmatch](https://docs.python.org/3/library/fnmatch.html) include the following disclaimer at the top:

> This module provides support for Unix shell-style wildcards, which a[re](https://docs.python.org/3/library/re.html#module-re) not the same as regular expressions (which are documented in the re module).

One place where this inconsistency might cause an issue is if someone is downloading a snapshot of a model with large weights and only wants weights for one particular framework. If they created regular expression strings for `ignore_regex`, they'd be unpleasantly surprised with the function downloading everything anyway.

I can open a PR changing the names of the parameters if you're open to making this change and let me know what you'd prefer them be changed to. Perhaps `allow_patterns` and `ignore_patterns`, respectively?

Thanks!

**Comment by adrinjalali** [comment]
I think we can fix this as a bugfix, i.e. no deprecation. I agree with your analysis. I'd be happy to review a PR if you'd like to send one :)

**Comment by LysandreJik** [comment]
cc @patrickvonplaten who implemented it originally

**Comment by patrickvonplaten** [comment]
Ok for me to rename the function arguments. I'd prefer to go over a deprecation cycle though that would still allow `allow_regex` and `ignore_regex` to be passed, but would throw a warning to instead use `allow_patterns`. 

We should then also update the naming here: 
- https://github.com/huggingface/transformers/blob/9a2995ee394b8f45fa3a5c12187e06886b77691a/src/transformers/models/wav2vec2_with_lm/processing_wav2vec2_with_lm.py#L157
- https://github.com/huggingface/transformers/blob/9a2995ee394b8f45fa3a5c12187e06886b77691a/src/transformers/pipelines/__init__.py#L640

**Comment by willfrey** [comment]
I won't be able to dig into this until next week at the earliest. If someone else wants to make the changes, that's more than OK with me 😄 I'd have to do some digging for examples of how all like to handle warning messages for deprecating APIs/changing callable signatures.

**Comment by Wauplin** [comment]
Closed by https://github.com/huggingface/huggingface_hub/pull/994.
