### ISSUE TITLE
History and Config in Keras repositories

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/huggingface_hub#843]
This is a feature request and discussion between @ariG23498 and me :') Wanted to carry this here for opinions.

Aritra thinks it would be cool to have history in repository directly, currently we only write `model.history.history` in model card. 
Also if the config dictionary is not provided by the user, we can load the config with `get_config` (see [here](https://www.tensorflow.org/guide/keras/save_and_serialize#how_savedmodel_handles_custom_objects) for more reference) and host it on the repository. If user provides config as argument, it can be overridden (which I think is not used that much atm). 

From what I see in API reference of Keras, this makes models more lightweight and reduces serialization time, so
1. User setting `save_traces = False` yet saving `config` in the repository
2. Loading `config` and passing it in custom objects for loading the model
should suffice and would be a nice option for users. (correct me if I'm wrong, @ariG23498)

These are both super nice to have, I'll be releasing my blog without these and later add them. One consideration is we don't want to add any argument because mixin takes `**model_save_kwargs` or deprecate `config`, allow user to override instead. 
Pinging @nateraw and @gante because I want to know what they think (it's optional, feel free to pass 🤗)
Also, Aritra accepted to co-author this PR with me which I'm super happy of 🥺

**Comment by ariG23498** [comment]
On top of what @merveenoyan documented brilliantly I also think we should compare the the pytorch auto-filling of cards with that of Keras. If we can align the expectation it would be a more controlled effort in building this API better.

WDYT?

**Comment by gante** [comment]
In general sounds good! 

But let me play the devil's advocate for a bit :D The `config` in Keras seems to have a similar role to our (Hugging Face) `config`. Having two `config`, especially with similar names, might be confusing -- what do you think? Also -- do you think we could convert back and forth between these two configs? We might be able to create a way to use our HF `config` (which we have for all models) with Keras 🤔

**Comment by ariG23498** [comment]
Hey @gante 

Just to clear things in my head:
- By HF `config` we are referring to [config](https://huggingface.co/docs/transformers/main_classes/configuration)?
- With the `push_to_hub` Keras API currently, we cannot populate the `config`. Do you think there is a better way to do it so that there is no clash of variable names?  https://github.com/huggingface/huggingface_hub/blob/18e6e87af82ee18f1fd5a3fc744ec2c401dbab02/src/huggingface_hub/hub_mixin.py#L211

**Comment by merveenoyan** [comment]
@gante currently `push_to_hub_keras` already takes an arg called `config`(which is a dict) that is later saved into a `config.json` file, so it's already there. We're talking about automating the process and not receiving it by user (and if user decides to override config, let them do it). 
@ariG23498 the card comparison sounds really good! My code is a bit too dirty on that side.

**Comment by gante** [comment]
Yes yes, I agree with what you're proposing @merveenoyan @ariG23498  :D What you're proposing should have clear benefits for the user.

I realized now that I was concerned about a case that shouldn't happen: the case where we have a Keras model that is defined by an architecture in HF transformers, where the user calls `push_to_hub_keras`. In that case, the user should call instead `save_pretrained` (which pushes to the hub with the HF config file, as @ariG23498 linked). Disregard my previous comment :D

**Comment by merveenoyan** [comment]
@gante I think `push_to_hub_keras` is not meant for transformers and we have different functions for that, I wonder if `tf.keras.models.save_model` which is used for Keras mixin would be able to save a transformers model anyway. The callbacks and other stuff save other things that model needs to be loaded with `from_pretrained`, if user tries to save a transformers Keras model they will not be able to do it, no? So I don't think it should be a concern. Users do it sometimes, I help them out in discord and tell them to save with `save_pretrained` and load with `from_pretrained` and maybe we should somehow block them to do so, I wonder if there would be something that we can put as a warning. It might be overkill though.

**Comment by gante** [comment]
> if user tries to save a transformers Keras model they will not be able to do it, no? 

It is doable, and required for some use cases (e.g. TF Lite). It kinda works, but has severe limitations (e.g. with variable-length inputs). If there was a way to quickly determine whether the model is a `transformers` model, then we might avoid some user struggle :D In any case, it is a non-urgent topic that's not directly related to the original proposal, sorry for disrupting 🙏

**Comment by merveenoyan** [comment]
@gante can you open an issue and ping me there?

**Comment by merveenoyan** [comment]
I want to wrap the config part out today given we will do another sprint :')

**Comment by merveenoyan** [comment]
Assuming you have a custom model like below:
```
class CustomModel(keras.Model):
    def __init__(self, hidden_units):
        super(CustomModel, self).__init__()
        self.hidden_units = hidden_units
        self.dense_layers = [keras.layers.Dense(u) for u in hidden_units]

    def call(self, inputs):
        x = inputs
        for layer in self.dense_layers:
            x = layer(x)
        return x

    def get_config(self):
        return {"hidden_units": self.hidden_units}

    @classmethod
    def from_config(cls, config):
        return cls(**config)

```

You have two choices for loading. One is to pass config inside the custom objects, you can also choose not to do that.
```
model = CustomModel([16, 16, 10])
# Build the model by calling it
input_arr = tf.random.uniform((1, 5))
outputs = model(input_arr)
model.save("my_model")

# Option 1: Load with the custom_object argument.
loaded_1 = keras.models.load_model(
    "my_model", custom_objects={"CustomModel": CustomModel}
)

# Option 2: Load without the CustomModel class.

# Delete the custom-defined model class to ensure that the loader does not have
# access to it.
del CustomModel

loaded_2 = keras.models.load_model("my_model")
np.testing.assert_allclose(loaded_1(input_arr), outputs)
np.testing.assert_allclose(loaded_2(input_arr), outputs)

print("Original model:", model)
print("Model Loaded with custom objects:", loaded_1)
print("Model loaded without the custom object class:", loaded_2)
```
This is the output you'll get:
```
INFO:tensorflow:Assets written to: my_model/assets
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
Original model: <__main__.CustomModel object at 0x7fdda067f450>
Model Loaded with custom objects: <__main__.CustomModel object at 0x7fdda05f8f10>
Model loaded without the custom object class: <keras.saving.saved_model.load.CustomModel object at 0x7fdda050fb50>
```
Currently mixin doesn't pass config to loading function properly. What I'm doing:
1. If user passes config, get the config and override config.json file such that user can load and pass it later.
2. If they don't, still get the config through `get_config()` (when you load above model with no custom object passed, you can still call `get_config()` so I hope there's no edge case whatsoever to this, pinging @gante)
3. If there's a config.json, pass it to `from_pretrained_keras()` when loading.
I'm almost done, writing a couple of test cases.

**Comment by merveenoyan** [comment]
@nateraw does above align with your findings?

**Comment by nateraw** [comment]
So IIRC when we made the original implementation, we intentionally avoided loading config this way because it seemed quite complicated. 😅 I definitely think you're right in that we could do something a bit better.

Right now, you just get the `model.config` attribute added to your model instance if config is found:

https://github.com/huggingface/huggingface_hub/blob/7042df38a9839ac41efd60cf7f985d473c49d426/src/huggingface_hub/keras_mixin.py#L525

How are we going to validate that the config that's found is going to be valid for something like `from_config` for a given model? Couldn't this potentially start breaking previously uploaded models somehow? (sorry if I'm missing something here 😅)

Also, if folks already aren't really using:
1. The custom model feature too much
2. The config when it comes to Keras,

Do we expect users to use it for `get_config`/`from_config` in custom models? 

---

As for history, which is a separate issue, I think that sounds great to include it as some dictionary file `history.json`. 🤗

**Comment by osanseviero** [comment]
Agree with Nate :smile: I would avoid adding complexity, but instead focus efforts in increasing the usage of what already exists.

**Comment by merveenoyan** [comment]
Do you think I should close this issue given we merged History feature?

**Comment by nateraw** [comment]
@merveenoyan I think the discussion here is 95% about `get_config`/`from_config`, but if we're not planning on doing that now, you can close if you like. Or leave it open for other folks to come join the discussion here if related problems arise. 😄

**Comment by merveenoyan** [comment]
Closing since we decided not to have the changes.
