### ISSUE TITLE
Deprecation of pushing arguments for cleaner DX in Keras mixin

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/huggingface_hub#846]
Currently push_to_hub_keras looks like this:
```
def push_to_hub_keras(
    model,
    repo_path_or_name: Optional[str] = None,
    repo_url: Optional[str] = None,
    commit_message: Optional[str] = "Add model",
    organization: Optional[str] = None,
    private: Optional[bool] = None,
    api_endpoint: Optional[str] = None,
    use_auth_token: Optional[Union[bool, str]] = True,
    git_user: Optional[str] = None,
    git_email: Optional[str] = None,
    config: Optional[dict] = None,
    include_optimizer: Optional[bool] = False,
    **model_save_kwargs,
):
```
But it's not intuitive and clean. Would be better if we'd do
```
def push_to_hub_keras(
    model,
    repo_id: str,
    commit_message: Optional[str] = "Add model",
    private: Optional[bool] = None,
    use_auth_token: Optional[Union[bool, str]] = True,
    config: Optional[dict] = None,
    include_optimizer: Optional[bool] = False,
    **model_save_kwargs,
):
```
As put by @osanseviero [here](https://github.com/huggingface/huggingface_hub/issues/652#issuecomment-1030039263). 
We need to deprecate a couple of arguments and put `FutureWarnings` if provided and then remove completely.
Pinging @ariG23498 for discussion 🤗

**Comment by LysandreJik** [comment]
Nice proposal, I agree that what you propose here is much cleaner! It is similar to what is proposed in https://github.com/huggingface/huggingface_hub/pull/847, with some additional arguments stripped away. I'd be very eager to hearing your feedback and proposals on that PR!

**Comment by Wauplin** [comment]
Since #847 is merged, previous signature is deprecated and will change in v0.12 to something very similar to what is proposed here (see [comment here](https://github.com/huggingface/huggingface_hub/blob/e28646c977fc9304a4c3576ce61ff07f9778950b/src/huggingface_hub/keras_mixin.py#L326)).

Therefore I'm closing this issue :)
