### ISSUE TITLE
Private GitLab

### ISSUE THREAD

**Issue by INF800** [huggingface/huggingface_hub#862]
Hi, can I use `https://github.com/huggingface/huggingface_hub` with my private gitlab

**Comment by INF800** [comment]
And have model search and dataset search available

**Comment by adrinjalali** [comment]
Most of the methods in `huggingface_hub` call REST endpoint of the HuggingFace Hub, so you won't be able to use it against a private gitlab. Closing as it's not in the scope of this library.
