### ISSUE TITLE
Allow boolean values for force_filename in hf_hub_download

### ISSUE THREAD

**Issue by nateraw** [huggingface/huggingface_hub#863]
**Is your feature request related to a problem? Please describe.**
If you want to force the filename of a given download with `hf_hub_download`, right now you have to specify the filename in two places. First, when you name the file you wish to download, and then again as you have to pass a string to the `force_filename` kwarg. It would be really nice if you could just say `force_filename=True` to use the same name as the one you already referenced.

**Describe the solution you'd like**

When I do:

```python
from huggingface_hub import hf_hub_download

filepath = hf_hub_download('nateraw/rare-puppers', 'config.json', force_filename=True)
```

The filepath should be `'<cache_dir>/config.json'`. 

If you set it to False, it should behave the same way it does for the default `None`, and use the hashed filename.

I can do this if this seems like a reasonable feature to add 😄

**Comment by osanseviero** [comment]
WDYT @julien-c @adrinjalali @LysandreJik? I personally like this idea :+1:

**Comment by julien-c** [comment]
i feel like this might be rendered a bit moot by #801 as all downloaded files will have their "correct" filename out of the box

I invite everyone to start reviewing #801 BTW when you have a change (still a bit WIP but nearing the "ready for review" status)

**Comment by Wauplin** [comment]
I'm closing this issue as https://github.com/huggingface/huggingface_hub/issues/801 is closed and git-aware cache is now the default way to download files from the hub (and keeping correct filename).
