### ISSUE TITLE
Remove history from Keras model card

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/huggingface_hub#869]
This is a minor change, I would like to get rid of history in model card before next sprint (which I’m planning to have on first week of june) given we save it as a JSON now (see #861 ) , because for models with more epochs it will look bad on the card as it will log every epoch, and we already have tensorboard traces and history JSON, wanted to be transparent before I move on with the decision. 
Pinging @nateraw @osanseviero

**Comment by merveenoyan** [comment]
@LysandreJik I'd love to get this in next release :)

**Comment by LysandreJik** [comment]
Sounds good, adding it to the milestone!
