### ISSUE TITLE
wrong link for the paper of facebook/blenderbot-400M-distill

### ISSUE THREAD

**Issue by Ruihua-Fang** [huggingface/huggingface_hub#873]
### Describe the bug

when click on the link on  Papers: Recipes for building an open-domain chatbot on the following page: https://huggingface.co/facebook/blenderbot-400M-distill, it open the following link, https://arxiv.org/abs/1907.06616, which is not the right paper.  The correct link for the above paper is the following: https://arxiv.org/abs/2004.13637

### Reproduction

see above to reproduce the problem
![873_blenderbot-400M-distill](https://user-images.githubusercontent.com/4677340/168411869-5ab1bb80-fe2a-4979-8604-7143ef295058.png)

### Logs

```shell
None
```

### System Info

```shell
v0.6.0, ubuntu 20.04
```

**Comment by julien-c** [comment]
maybe for @patrickvonplaten

**Comment by patrickvonplaten** [comment]
Thanks for the issue @Ruihua-Fang !

Corrected it here: https://huggingface.co/facebook/blenderbot-400M-distill/commit/a2084cb58dd4810f45302724dd07c68051fe9ed3
