### ISSUE TITLE
Add list_spaces

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#881]
**Is your feature request related to a problem? Please describe.**
Allow users listing spaces similar to how they can list models and datasets

We can use something like this for example

```
HF_LIST_ENDPOINT = HF_ENDPOINT + "/api/spaces?filter={type}"
r = requests.get(HF_LIST_ENDPOINT.format(type=type))
r.raise_for_status()
d = r.json()
```

cc @lvwerra

**Comment by LysandreJik** [comment]
Indeed, should be simple to add! I've added some labels, happy to review a PR! :)

**Comment by cakiki** [comment]
I'd like to work on this!

**Comment by osanseviero** [comment]
Sounds good! Feel free to open a PR for this and let us know if you have any questions :fire:
