### ISSUE TITLE
Create ability to push tf.Module inside Keras Mixin

### ISSUE THREAD

**Issue by merveenoyan** [huggingface/huggingface_hub#887]
We should be able to push models made with `tf.Module` without writing a mixin from scratch by adding capabilities to understand if a model is `tf.Module` or not and saving them with `model.save()` instead of existing saving mechanism.
Pinging @ariG23498 and @nateraw here :) 
See this [model](https://huggingface.co/pyimagesearch/nmt-bahdanau-attention) as an example.

**Comment by ariG23498** [comment]
I have tried hosting a `tf.Module` on the hub. These were the steps:
- Build the `tf.Module`
- Create a hub repo
- Move the serialized and saved `tf.Module` into the hub repo
- Push the changes with a commit message to the hub

@merveenoyan what according to you would be a better approach to take?

**Comment by merveenoyan** [comment]
A better approach would be to pass `tf.Module` to `push_to_hub_keras()` to push it instead of above steps 🙂 @ariG23498

**Comment by ariG23498** [comment]
I am thinking of the following:
- Have a boolean flag in the `save_pretrained_keras` model named `is_tf_module` which by default is `False`
- If the `is_tf_module` is `True` we switch the behaviour from

```diff
-tf.keras.models.save_model(
-    model, save_directory, include_optimizer=include_optimizer, **model_save_kwargs
- )

+if is_tf_module:
+    tf.saved_model.save(
+	    obj=model,
+	    export_dir="<model_dir>",
+    )
+else:
+    tf.keras.models.save_model(
+        model, save_directory, include_optimizer=include_optimizer, **model_save_kwargs
+    )
```

Let me know what you think? What are the possible pitfalls you think we can run into?

**Comment by merveenoyan** [comment]
@ariG23498 I think instead of `else` we can just check if it's a Keras model in general. I'd like to ping other folks for discussion as well @nateraw @osanseviero

**Comment by merveenoyan** [comment]
@nateraw they're loaded like this: 
`model = tf.saved_model.load(model_path)`
So the answer is no 😅 because it's not a Keras model.

**Comment by nateraw** [comment]
Oh, interesting. Would this cause issues, say, in [our pipeline here](https://github.com/huggingface/api-inference-community/blob/main/docker_images/keras/app/pipelines/image_classification.py) as well (assuming it loads from hub correctly + its an image classification module)?

We'll want to be very clear on all the differences if we are to add this. I'm not too famililar 😅

**Comment by Wauplin** [comment]
@merveenoyan @nateraw not sure to exactly understand the issue here. Is there something we can do/want to do ?

**Comment by nateraw** [comment]
I don't see huge need for it, but will let others chime in, as I've been a bit separated from the Keras work as of late. ❤️

**Comment by Wauplin** [comment]
Given this comment https://github.com/huggingface/huggingface_hub/issues/887#issuecomment-1265681248 and the lack of additional input, I'll close this issue. Anyone landing on this issue, feel free to chime in so we can reopen.
