### ISSUE TITLE
missing "view the api" on new spaces

### ISSUE THREAD

**Issue by summerstay** [huggingface/huggingface_hub#896]
### Describe the bug

Previously, when a new space was created, instructions for accessing the model via API were generated, and a link to this page called "view the API" appeared at the bottom of the app page. This doesn't seem to be the case currently.
According to this post https://discuss.huggingface.co/t/gradio-iframe-embedding/13021/12?u=summerstay the SDK version needs to be pinned to 2.9.4 for this to show up. I don't know how to do that on my space.

### Reproduction

create a minimal new gradio space with this app.py

`import gradio as gr
from sentence_transformers import SentenceTransformer

model_Q = SentenceTransformer('flax-sentence-embeddings/multi-QA_v1-mpnet-asymmetric-Q')

def getVectors(sentences):
            vectors = []
            splitSentences = sentences.split('/*/')
            for sentence in sentences:
                        vectors.append(model_Q.encode(sentence))
            return vectors
            
interface = gr.Interface(fn = getVectors,
inputs = "text",
outputs = ['text'],
title = 'get vectors',
description = 'get vectors for search')

interface.launch(inline = False)
`

### System Info

```shell
Using the https://huggingface.co/spaces/ website from Chrome on Windows.
```

**Comment by summerstay** [comment]
But the API still seems to work properly when I follow analogous instructions from another page.

**Comment by osanseviero** [comment]
Hey there! This is an issue with Gradio 3.0, so what you might see are Spaces using older and newer versions. I would suggest you to follow-up in Gradio since this is unrelated to the `huggingface_hub` library. See https://github.com/gradio-app/gradio/issues/1390
