### ISSUE TITLE
create_repo does not work unless you set private argument

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#897]
### Describe the bug

create_repo does not work if `private` is not set. In https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/hf_api.py#L1458 we should likely set a boolean. 

Internal discussion https://huggingface.slack.com/archives/C02V5EA0A95/p1654783848296429

### Reproduction

I just tried 

```python
create_repo("osanseviero/test_copy", token="TOKEN")
```

### Logs

```shell
HTTPError: 400 Client Error: Bad Request for url: https://huggingface.co/api/repos/create - "private" must be a boolean
```

### System Info

```shell
huggingface-hub-0.7.0, Colab and Space
```

**Comment by julien-c** [comment]
this was solved server-side, ok to close?

**Comment by julien-c** [comment]
(we'll keep supporting server-side otherwise old versions of `huggingface_hub` won't work anymore)

**Comment by julien-c** [comment]
(cc @coyotte508)

**Comment by osanseviero** [comment]
@coyotte508 was suggesting that it would be nice to still send a boolean to the backend, but I agree this still needs to be supported server, so ok with closing :)

**Comment by coyotte508** [comment]
I'd rather have it fixed anyway here, it should be a one line change like using `not not private`

**Comment by julien-c** [comment]
yes what i meant is that we won't be able to drop the server fix anyways, but ok to update the behavior here
