### ISSUE TITLE
Add simple class to ease saving loading from HF hub

### ISSUE THREAD

**Issue by vasudevgupta7** [huggingface/huggingface_hub#9]
Would like to have a class from which model class can be inherited to add support of Huggingface hub. It will look something like this :

```
from huggingface_hub import SavingUtils

class MyModel(nn.Module, SavingUtils):

   def __init__(self):
      self.layer1 = ....

   def forward(self, ...):
      return ...

model = MyModel()
model.save_pretrained("model_id")

# loading model
model = MyModel.from_pretrained("model_id")
```

I can make a PR for adding this simple feature if you approve it.

**Comment by julien-c** [comment]
Sounds like a great feature! 

Not sure about calling `.save_pretrained()` to `git push` though – might be confusing vs. saving to a local directory.

Maybe `.upload_to_hub()` or `.git_push()` or `.upload_pretrained()` if we wanted to maintain the symmetry with other methods?

Finally, not sure about implementing as a mixin vs. subclassing `nn.Module`. I think I like the mixin but I'd like to get more feedback, maybe from @sgugger @thomwolf @patrickvonplaten and others.

**Comment by patrickvonplaten** [comment]
I'm fine with adding a `.upload_to_hub()` method in `PreTrainedModel(....)` next to `save_pretrained(...)` and `from_pretrained(...)` - I don't think we really need a new Mixin class for that

**Comment by julien-c** [comment]
@patrickvonplaten this is `huggingface_hub` not `transformers` so we do not have a `PreTrainedModel` here. (It is meant to be used from any library)

**Comment by patrickvonplaten** [comment]
My bad! Then I think it's a good idea to have a `ModelHubMixin` class

**Comment by vasudevgupta7** [comment]
Okay. I will start PR then.

**Comment by sgugger** [comment]
I agree with @julien-c and @patrickvonplaten on the fact it should be a mixin. Seems like a useful feature, so thanks for tackling this @vasudevgupta7 !
