### ISSUE TITLE
`hub-ci` returning error 500 when trying to create a Space

### ISSUE THREAD

**Issue by LysandreJik** [huggingface/huggingface_hub#907]
> @SBrandeis, @XciD, would you have why we're getting errors 500 on the `test_init_clone_from` test? It seems like creating a space using `create_repo` doesn't work and throws an error 500. Reproducible code example:
> 
> ```python
> temp_repo_url = create_repo(
>     repo_id=f"temp",
>     token=token,
>     repo_type="space",
>     space_sdk="streamlit"
> )
> ```
> 
> I tried with both `streamlit`, `gradio`. However, `static` seems to work just fine!

from https://github.com/huggingface/huggingface_hub/pull/900

and

> This one fails `HfApiEndpointsTest.test_create_update_and_delete_space_repo` with 500 like it was failing for my PR, see below where the error comes from (due to picking other SDKs for others)
> 
> ```
> for sdk in SPACES_SDK_TYPES:
>             SPACE_REPO_NAME = space_repo_name(sdk)
>             self._api.create_repo(
>                 repo_id=SPACE_REPO_NAME,
>                 token=self._token,
>                 repo_type=REPO_TYPE_SPACE,
>                 space_sdk=sdk,
>             )
>             res = self._api.update_repo_visibility(
>                 repo_id=SPACE_REPO_NAME,
>                 token=self._token,
>                 private=True,
>                 repo_type=REPO_TYPE_SPACE,
>             )
>             self.assertTrue(res["private"])
>             res = self._api.update_repo_visibility(
>                 repo_id=SPACE_REPO_NAME,
>                 token=self._token,
>                 private=False,
>                 repo_type=REPO_TYPE_SPACE,
>             )
> ```
> 
> _Originally posted by @merveenoyan in https://github.com/huggingface/huggingface_hub/issues/900#issuecomment-1155463193_

**Comment by julien-c** [comment]
To clarify, this is happening on the new CI server, `hub-ci`? not on the old one `moon-staging`?

I think I remember that Space creation on the backend (ie spaces-app-manager) needs to be disabled through an env var. @cbensimon @XciD @christophe-rannou happy to take a deeper look if it's needed

**Comment by XciD** [comment]
We found the bug: https://github.com/huggingface/moon-landing/commit/f2e8068348e225ba1f07c5d27a38843253e23dcb

Related to new infra of spaces.
