### ISSUE TITLE
hf_hub_url not giving appropriate URL

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/huggingface_hub#915]
### Describe the bug

I uploaded a video stored as a NumPy array to the hub: https://huggingface.co/datasets/hf-internal-testing/spaghetti-video.

However, when using `hf_hub_url` to give me the appropriate URL as follows:

```
from huggingface_hub import hf_hub_url

hf_hub_url("hf-internal-testing/spaghetti-video", filename="eating_spaghetti.npy")
```

I doesn't give me the appropriate URL: https://huggingface.co/hf-internal-testing/spaghetti-video/resolve/main/eating_spaghetti.npy. When clicking on this link, one gets a "Repository not found" error.

It seems that the appropriate URL is https://huggingface.co/datasets/hf-internal-testing/spaghetti-video/resolve/main/eating_spaghetti.npy

### Reproduction

```
from huggingface_hub import hf_hub_url

hf_hub_url("hf-internal-testing/spaghetti-video", filename="eating_spaghetti.npy")
```

### Logs

```shell
/
```

### System Info
Using huggingface_hub v0.7.0 in Google Colab

**Comment by osanseviero** [comment]
`hf_hub_url` by default expects a model repo. You can add `repo_type="dataset"` when using a dataset repo, and then you would get the right url.

**Comment by NielsRogge** [comment]
My bad, indeed, just discovered I had to use `datasets/hf-internal-testing/spaghetti-video` as the repo name.

Maybe this could be added to the docs?

**Comment by osanseviero** [comment]
Yes, I think that's a good idea! Would you like to open a small PR for it?
