### ISSUE TITLE
Add to pipeline "feature-extration": "sentence-transformers / paraphrase-multilingual-MiniLM-L12-v2" model

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [huggingface/huggingface_hub#92]
Hello,

I would like to serve a custom model on accelerated inference API based on this original model: https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2

However, pipeline is not defined for this model so I can't use it. Could you add this model to the `feature-extraction` pipeline?

Thanks!

**Comment by LysandreJik** [comment]
cc @nreimers, @osanseviero

**Comment by osanseviero** [comment]
Hi @Matthieu-Tinycoaching,

I just added the model card with the metadata for the `feature-extraction` pipeline to work.

```yaml
---
tags:
 - sentence-transformers
 - feature-extraction
---
```

Please note that with incoming Sentence Transformers v2 release, the repos of the organization will be updated to have:
1. The proper tags
2. Some additional layers so that the API works just as using `sentence-transformers` right now (such as mean pooling, but also some models might have an additional dense layer)

**Comment by Matthieu-Tinycoaching** [comment]
Hi @osanseviero,

Thanks for adding appropriate metadata for this model. I have take into account the news about the future Sentence Transformers v2 release and wait for it!

I have customized `sentence-transformers / paraphrase-multilingual-MiniLM-L12-v2` model to integrate within the model the mean pooling layer: https://huggingface.co/Matthieu/paraphrase-multilingual-MiniLM-L12-v2-custom

Could you please add this custom model on the inference API in order to enable me to do some tests?

Thanks!

**Comment by osanseviero** [comment]
Hey @Matthieu-Tinycoaching!

There are a couple of things.

1. When a repo is added, it should work in the Inference API out of the box. No need for us to enable it :)

2. Loading your model fails in `SentenceTransformers` v2. We fail to give a more useful error message (we need to work on that). Here is a [colab](https://colab.research.google.com/drive/1Yz7P6WSywgFyOwlgchh-SoOf9aP7TRHC?usp=sharing) you can use to reproduce the error. The specific error message is:
> OSError: Unable to load vocabulary from file. Please check that the provided vocabulary is accessible and not corrupted.

3. But even if you fix the error, I'm not sure than what you're doing is needed at all. `SentenceTransformers` will already add a mean pooling layer by default: https://github.com/UKPLab/sentence-transformers/blob/v2_dev/sentence_transformers/SentenceTransformer.py#L100, so using `sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2` should do what you were intending.

Let me know if you have any other questions!
Omar

**Comment by nreimers** [comment]
Hi @osanseviero @Matthieu-Tinycoaching 
The multilingual MiniLM models uses a bit strange combination: It is a BERT architecture, but it uses the XLM-Roberta tokenizer. 

I saw in your model repository that the sentence-piece model file is missing.

When you add this file:
https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/blob/main/sentencepiece.bpe.model

To your custom model git repo, it should hopefully work.

**Comment by Matthieu-Tinycoaching** [comment]
Hi @osanseviero thanks for your feedback!

Please find my comments below.

> 1. When a repo is added, it should work in the Inference API out of the box. No need for us to enable it :)

That's great but since I have tried with my public custom repository which failed loading model that could explain why I couldn't get prediction. However, sometimes behavior of the inference API is strange and can't load when switching predictions from custom repository to community repository or when swichting between no API token to personal/org API token.

> 2. Loading your model fails in SentenceTransformers v2. We fail to give a more useful error message (we need to work on that). 

Things seem to be linked to what @nreimers depicted: sentence-piece model file is missing in my model repository, however I use exactly the same Python environment and script file to `.save_pretrained` both model and tokenizer as I have done for `Matthieu/stsb-xlm-r-multilingual-custom` model. So, I don't understand why for this model sentence-piece model file was not generated?

> 3. But even if you fix the error, I'm not sure than what you're doing is needed at all. SentenceTransformers will already add a mean pooling layer by default: https://github.com/UKPLab/sentence-transformers/blob/v2_dev/sentence_transformers/SentenceTransformer.py#L100, so using sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2 should do what you were intending.

Great news! But this is new to v2 models since I had to add a mean pooling layer for the `sentence-transformers/stsb-xlm-r-multilingual` model?

**Comment by osanseviero** [comment]
Closing this issue as it's stale :smile:
