### ISSUE TITLE
hf_hub_download and cached_download should read the token by default

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#926]
### Describe the bug

Right now, `hf_hub_download` does not work for private repos unless you set `use_auth_token=True`. This is inconsistent with other methods in which the token is automatically retrieved if not specified. I think we should change https://github.com/huggingface/huggingface_hub/blob/7e80140bc5ea0a3991418d2cb6a6ecda90c4f38f/src/huggingface_hub/file_download.py#L577-L586 to always get the token if it's not explicitly passed.

WDYT @LysandreJik @julien-c?

### System Info

```shell
-
```

**Comment by julien-c** [comment]
we've discussed it in the past and decided against it for privacy protection reasons (especially in the case when it's used from third party libraries – the hf.co server will "know" what models user A is downloading without explicitly opting-in)

But maybe it does make sense to revisit this

**Comment by julien-c** [comment]
> not sure why the download should be different 

Upload methods aren't expected by the user to even work w/o authentication, but download methods are (for public repos anyways)

I will try to find the past discussions of this and link them here, for completeness. 

But note that I'm not opposed to changing this behavior, just need to be aware of privacy implications

**Comment by julien-c** [comment]
one example of [internal convo](https://huggingface.slack.com/archives/C014N4749J9/p1645023949365789) but earlier discussions were probably more interesting

**Comment by julien-c** [comment]
@sgugger pointed me to this PR description https://github.com/huggingface/transformers/pull/9141
