### ISSUE TITLE
API Implementation Error: (intermediate value).filter is not a function 

### ISSUE THREAD

**Issue by sergeyf** [huggingface/huggingface_hub#932]
### Describe the bug

This model doesn't seem to load on the HUB: https://huggingface.co/guidecare/feelings_and_issues_large?text=I+like+you.+I+love+you

It throws the error in the title: 
![image](https://user-images.githubusercontent.com/1874668/176099884-acbecead-0805-4035-8cfb-5a394af79304.png)

This issue looked different a few days ago, for which I opened a ticket: https://github.com/huggingface/transformers/issues/17876

Probably in the wrong place...

### Reproduction

Just go to the URL

### System Info

```shell
Same on every browser
```

**Comment by osanseviero** [comment]
Cc @mishig25

**Comment by LysandreJik** [comment]
cc @Narsil

**Comment by Narsil** [comment]
Thanks for pinging me !

I think this is related to this  https://github.com/huggingface/transformers/pull/17906

**Comment by Narsil** [comment]
Should be sorted out right, now.

You might still see the issue if you are hitting cache with some requests, they should go away soon.

Thanks for the report !

**Comment by sergeyf** [comment]
Yes, it is fixed now thanks!

Any idea if this is related to the Space still not working? https://huggingface.co/spaces/guidecare/feelings_and_issues_demo

**Comment by Narsil** [comment]
I have no idea, can't see any logs nor UI in the space.
