### ISSUE TITLE
High level feedback on docs

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#938]
From @NielsRogge https://huggingface.slack.com/archives/C02V5EA0A95/p1656934663589609

1. [here](https://huggingface.co/docs/huggingface_hub/v0.8.1/en/how-to-upstream#pushtohub), Repository is imported from the library without being used. Also, the repo variable is just casually used without being instantiated
2. [here](https://huggingface.co/docs/huggingface_hub/v0.8.1/en/package_reference/hf_api#huggingface_hub.HfApi.upload_file): I'm not sure how to import upload_file in the code snippets below. Is it just from huggingface_hub import upload_file?
3. [here](https://huggingface.co/docs/huggingface_hub/v0.8.1/en/how-to-upstream#commit-context-manager), I'm reading the docs on "how to upload a file to the hub", but the first example it shows pulls an existing repo from the hub and modifies an existing file. That's not why users came to this page, I want to just upload a new file to the hub rather than modifying an existing one. The second example is also not useful for me as I already have a file.
4. [here](https://huggingface.co/docs/huggingface_hub/v0.8.1/en/how-to-downstream), an image is not displayed correctly
5. [here](https://huggingface.co/docs/huggingface_hub/v0.8.1/en/how-to-upstream#managing-files-in-a-repo-without-git-with-the-createcommit-api), this code snippet doesn't work out-of-the-box, you also need to provide the commit_message argument

**Comment by osanseviero** [comment]
Note that 4 is already fixed in main

**Comment by LysandreJik** [comment]
Maybe of interest to @stevhliu

**Comment by stevhliu** [comment]
Thanks for the feedback, I'll take a look and open a PR to address it!

**Comment by Wauplin** [comment]
Seems to be solved in https://github.com/huggingface/huggingface_hub/pull/944 so I'm closing.
