### ISSUE TITLE
Path for saving authentication token should be configureable.

### ISSUE THREAD

**Issue by mrkkollo** [huggingface/huggingface_hub#942]
**Is your feature request related to a problem? Please describe.**
At the moment, when downloading models through the transformers Python package, we get a permission denied error since in our current set-up we have very limited file-system access on where we can read-write but the path for saving the token in the HfFolder class is essentially hard-coded through the path_token class variable.

**Describe the solution you'd like**
Would be good if you could change the path through an environment variable instead of it being essentially hard-coded to the home directory.

**Describe alternatives you've considered**
There really isn't an alternative to this problem in cases you can't just write to the home directory other than overwriting the HOME environment variable which is a rather far-fetched solution.

**Comment by julien-c** [comment]
i think this is reasonable given that the file cache can be controlled by an env var, the token cache should be too.

Would you want to open a PR to make this change, @mrkkollo?

You can name the env var something like `HUGGINGFACE_TOKEN_CACHE`

**Comment by Wauplin** [comment]
This value now exists as `HUGGING_FACE_HUB_TOKEN` (or `HF_HOME` is general). See [reference](https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#huggingfacehubtoken).
