### ISSUE TITLE
Support any git method

### ISSUE THREAD

**Issue by LysandreJik** [huggingface/huggingface_hub#955]
The `huggingface_hub` package abstracts most of the difficulty related to git management of repositories, by providing utility methods tailored to large file/binary file management and helper methods abstracting the methods underneath.

However, for rare cases where something goes wrong or where the API doesn't meet the requirements of a given workflow, we're currently in need of leaving the python runtime, and opening the console to run `git` commands.

Adding a feature that would enable running power-user git commands so that users do not have to leave the python runtime to run them would enable these workflows better.

*This was mentioned somewhere by @julien-c but I cannot find the original thread*

**Comment by LysandreJik** [comment]
Related: https://github.com/huggingface/huggingface_hub/issues/954

**Comment by LysandreJik** [comment]
Related: https://github.com/huggingface/huggingface_hub/issues/953

**Comment by Wauplin** [comment]
(closing as "wontfix" as `Repository` usage is deprecated anyway)
