### ISSUE TITLE
Add `flake8-bugbear` to the code quality checks

### ISSUE THREAD

**Issue by SBrandeis** [huggingface/huggingface_hub#966]
Good catch since this can really create unexpected behaviours.

I would really suggest that we start tracking these errors automatically using [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear). It is a plugin for flake8 that finds "bad patterns" in code. In particular `B006 ` checks for mutable default values. Since [we already check for flake8 issues](https://github.com/huggingface/huggingface_hub/blob/main/.github/workflows/python-quality.yml#L32) in our CI, it will integrate seamlessly with current workflow. To use it, we would need to:
- add `flake8-bugbear` as dependency in `setup.py [quality]`
- adapt existing codebase to remove new "errors" raised by flake8-bugbear. I already checked and the number of changes is quite low and very easy to adapt.

Any opinion about it ? If no-one sees a problem here I can create a PR to enable it.
The only catch I see is that it can "slow down" the dev process but I would argue that it's for the best (+we can always ignore a given error if it's really annoying).

_Originally posted by @Wauplin in https://github.com/huggingface/huggingface_hub/pull/959#issuecomment-1206145019_

**Comment by Wauplin** [comment]
Addressed in https://github.com/huggingface/huggingface_hub/pull/967.
