### ISSUE TITLE
ArchLinux cant push models ! atleast on keras

### ISSUE THREAD

**Issue by sneedgers** [huggingface/huggingface_hub#968]
### Describe the bug

push_to_hub_keras(model,"stufuf333")

and the error I get 
Traceback (most recent call last):
  File "/run/aistuff/ai_thing2.py", line 215, in <module>
    push_to_hub_keras(model,"sneedger")
  File "/home/ori/.local/lib/python3.10/site-packages/huggingface_hub/keras_mixin.py", line 373, in push_to_hub_keras
    repo = Repository(
  File "/home/ori/.local/lib/python3.10/site-packages/huggingface_hub/repository.py", line 504, in __init__
    raise ValueError(
ValueError: If not specifying `clone_from`, you need to pass Repository a valid git clone.

git lfs has issues??

### System Info

```shell
Archlinux
python 3.10
```

**Comment by osanseviero** [comment]
Hi there! Thanks for reporting!

Do you have a reproducible example? I just tried this in a Colab and it worked well https://colab.research.google.com/drive/1D46OEKDmvMwAieCVcShO1kKdqZsF4JeE?usp=sharing

**Comment by osanseviero** [comment]
(cc @merveenoyan )

**Comment by LysandreJik** [comment]
Hey @sneedgers, thanks for opening an issue! As @osanseviero was mentioning, we'll need a reproducible code example in order to help you out. Please provide the version of your tools, especially the version of `huggingface_hub` as this is what's important. Thanks.

**Comment by sneedgers** [comment]
> Hi there! Thanks for reporting!
> 
> Do you have a reproducible example? I just tried this in a Colab and it worked well https://colab.research.google.com/drive/1D46OEKDmvMwAieCVcShO1kKdqZsF4JeE?usp=sharing

dev version from github.

**Comment by merveenoyan** [comment]
hey @sneedgers, can you please post the code snippet you used to push your model so we can test and see what doesn't work?

**Comment by merveenoyan** [comment]
@sneedgers Hello there! Can you please put a code snippet here for us to reproduce your problem?

**Comment by sneedgers** [comment]
> 

Push a model. Read again my issue

**Comment by Wauplin** [comment]
@sneedgers sorry if we didn't solve your issue here but we are really missing a part. Did you try the colab from @osanseviero's comment https://github.com/huggingface/huggingface_hub/issues/968#issuecomment-1207747180 ? If the colab is also working for you then we would need more context (e.g. a real code snippet) to see what could cause the error.
In general it's good to isolate the problem in a short example if you don't want to share your full code.

Otherwise, I will just close this issue as unresolved.
