### ISSUE TITLE
Make `path_in_repo` optional in `upload_folder`

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#971]
At the moment, `path_in_repo` argument is required in `upload_folder` method. This makes it weird when a user wants to upload a folder to the root of the repo.

Example:
```py
api.upload_folder(
    repo_id=repo_id,
    repo_type="model",
    path_in_repo=""
)
```
By default, we could assess `path_in_repo` to be set to `""`.
Would also be good to remove all occurrences of `path_in_repo=""` from `huggingface_hub`.

Highlighted in https://github.com/huggingface/huggingface_hub/pull/847#discussion_r941255882,

**Comment by LysandreJik** [comment]
Indeed, that would be a better default.

**Comment by Wauplin** [comment]
Closed by https://github.com/huggingface/huggingface_hub/pull/988.
