### ISSUE TITLE
Add a utility to list cached things

### ISSUE THREAD

**Issue by sgugger** [huggingface/huggingface_hub#972]
In Transformers, we have [this function](https://github.com/huggingface/transformers/blob/ab2006e3d6db88654526a4169e65d4bfc52da2e3/src/transformers/utils/hub.py#L119) that returns the list of cached models. It would be nice to rely on an util in this repository instead (not limited to models) that would list:
- cached repos
- revisions cached for each repos (replacing commit hashes with refs when they exist)
- files cached for a given repo and revision

**Comment by LysandreJik** [comment]
This would be a nice exercise to dive into the way the cache is structured and understand it thoroughly. @Wauplin, would you like to try your hand at it?

**Comment by Wauplin** [comment]
@LysandreJik Thanks for pinging me on this one. It's a great idea, I'll assign the issue to myself and get back to you when I'm starting to work on it.

**Comment by sgugger** [comment]
`cached_file` is just a wrapper around `hf_hub_download` which is in `huggingface_hub`. I'll actually make a PR to move `try_to_load_from_cache` to `huggingface_hub` later today/tomorrow as it should live there IMO.

You should rely on the new cache structure (so as created by `hf_hub_downlaod` for instance) I think, but I'll let others correct me if I'm wrong.

**Comment by Wauplin** [comment]
Ok thanks for the info ! This precision definitely helps as caching in `huggingface_hub` is still a bit blurry for me 🙄

**Comment by mariosasko** [comment]
Great proposal! I guess this is somewhat related to https://github.com/huggingface/datasets/pull/2631, in which we discussed how great it would be to have a CLI tool for easy inspection/deletion of the `datasets` cache.

**Comment by julien-c** [comment]
NB: for shared terminology, when we talk about "new cache structure" (aka. "cache file layout"), it's = what we shipped in https://github.com/huggingface/huggingface_hub/pull/801 i.e. where do we store cached files on local disk

**Comment by Wauplin** [comment]
Closed by https://github.com/huggingface/huggingface_hub/pull/990.
See doc and usage here: https://huggingface.co/docs/huggingface_hub/main/en/how-to-cache#scan-your-cache

**Comment by julien-c** [comment]
feel free to publicize/announce this =)
