### ISSUE TITLE
HTTP-based `push_to_hub` for fastai integration

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#996]
Helper functions `push_to_hub` for keras integration and `ModelHubMixin` mixin now uses an HTTP approach instead of a git-based one. This work as been discussed in https://github.com/huggingface/huggingface_hub/pull/321 and done in https://github.com/huggingface/huggingface_hub/pull/847. The main advantage is that the all repo doesn't have to be cloned locally before uploading the model weights.

However, `fastai` integration is still git-based (see implementation [here](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/fastai_utils.py#L352)). It would be good to update `push_to_hub_fastai` to use the new http-based approach.

**Comment by nandwalritik** [comment]
Hi @Wauplin I would like to take this up.

**Comment by Wauplin** [comment]
Hi @nandwalritik, thanks for offering your support on this !

Do you see more or less what needs to be done ? An example of http-based `push_to_hub` can be found [here](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/hub_mixin.py#L251). The idea is to still support both git-based and http-based version but deprecate arguments used for the git-based approach (see decorator `@_deprecate_positional_args` and `@_deprecate_arguments`). In the docstring, we only document the arguments for the new http-based approach.

I think that's it if you want to start working on it. I remain available if you have any questions.

**Comment by osanseviero** [comment]
cc @omarespejel on this since afaik he was planning to work on this as he implemented the mixin. (it's totally fine if @nandwalritik wants to take this one, I'm just making sure work is not duplicated)
