### ISSUE TITLE
[Spaces] Can't install from private git

### ISSUE THREAD

**Issue by lukasfolle** [huggingface/huggingface_hub#997]
### Describe the bug

Hi,

I cannot get installing python packages from private repos to work (tried gitlab and hf).
When using the access tokens, the part where the requirements.txt are installed still fails.

On any remote machine I tried, this works perfectly.
The error is attached below.

To reproduce create a private repo with a setup.py and a folder named "test" (as attached).
Then in your public space add this to the requirements.txt: `pip install git+https://${USERNAME}:${SECRET}@${YOUR_REPO}`.

### Logs

```shell
--> RUN pip install -r requirements.txt
Defaulting to user instal
[test.zip](https://github.com/huggingface/huggingface_hub/files/9371797/test.zip)
lation because normal site-packages is not writeable
Collecting git+https://lfolle:****@huggingface.co/lfolle/handkimodel (from -r requirements.txt (line 3))
  Cloning https://lfolle:****@huggingface.co/lfolle/handkimodel to /tmp/pip-req-build-8eb7e8uv
  Running command git clone --filter=blob:none --quiet 'https://lfolle:****@huggingface.co/lfolle/handkimodel' /tmp/pip-req-build-8eb7e8uv
  fatal: Authentication failed for 'https://lfolle:${HANDKIMODEL}@huggingface.co/lfolle/handkimodel/'
  error: subprocess-exited-with-error
```

### System Info

```shell
The code is running on Spaces, so should be up-to-date an linux.
```

**Comment by Wauplin** [comment]
@lukasfolle Thanks for reporting this. If I understand correctly you want to host your code on a HF Space repo (private) and then install it as a package as you would do from github/gitlab, right ? 

Ping @Pierrci @LysandreJik is this a behaviour we should support/we want to support ?

**Comment by lukasfolle** [comment]
Yes, actually I uploaded the code as a private model and want to use this model in a public Space.
But this model can also be uploaded to e.g. gitlab.

**Comment by Wauplin** [comment]
Oh ok, so you want to make a model private but still usable publicly in a Space. Not sure if that's something HF will support. I prefer to let others confirm that and maybe advice you on a workaround.

**Comment by lukasfolle** [comment]
Exactly, the model weights can actually already be loaded from a private model:
```
file_path = hf_hub_download("lfolle/DeepNAPSIModel", "dummy_model.pth",
                              use_auth_token=os.environ['DeepNAPSIModel'])
```
Installing private repos is possible, but seems to be broken currently.

**Comment by osanseviero** [comment]
If this is for a Space, you could do something like

```python
file_path = hf_hub_download("lfolle/DeepNAPSIModel", "dummy_model.pth",
                              use_auth_token=os.environ['DeepNAPSIModel'])
````

And you can add the environment variable as a secret in the Settings tab as documented [here](https://huggingface.co/docs/hub/spaces-overview#managing-secrets). There is no need to have it in the requirements file.

**Comment by lukasfolle** [comment]
Yes that works, but I would like to install a package from a private git repo.

**Comment by osanseviero** [comment]
I don't think this use case is supported. If I understand correctly, you have a model repository which is also a Python package? And you want to do `pip install` from it, which works unless the repository is private. In this case, I would suggest to do a git clone + pip install from the clone.

**Comment by lukasfolle** [comment]
Thank you for your help @osanseviero & @Wauplin!
How would I clone a git repository inside spaces? I couldn't find anything in the docs.

**Comment by osanseviero** [comment]
If you're doing it in runtime, although it would be slower, you can do `subprocess.run` to run `git clone` + `cd` + `pip install .`

**Comment by lukasfolle** [comment]
Perfect, thank you!
